[4 - 9단계 - 방탈출 예약 관리] 상돌(이상진) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #103
Opened 2024-04-22 06:20 UTC by pricelees

안돌 안녕하세요! 6기 상돌(이상진) 입니다.😄 

경험이 없는 상태에서 혼자 진행하다보니 이번 단계에선 많이 헤맸던것 같습니다.

이후 단계를 감안해서 구현을 했다면 조금 더 빨리 끝나긴 했겠지만, 안돌께서 슬랙에서 해주셨던 말씀이 많이 공감이 되기도 했고, 헤메는 과정에서 배울 것이 있다는 생각에 단계별 요구사항만을 생각하려고 노력했습니다.

예외 처리와 원시값 포장 등 추가적으로 생각할 여지는 있지만, 이러한 부분들은 시간이 남으면 고민해보려고 합니다.

감사합니다. 즐거운 한 주 보내세요!

2024-04-22 11:37 UTC, andole98 requested changes
잘 구현해 주셨네요~

코멘트 남겼으니 살펴보세요

추가)
admin template에서 reservation / time 으로 링크하는 기능이 있어요. 지금은 링크 url이 제대로 동작하지 않는것 같네요 (저번 스텝에서 이야기하려다 미룸)
`a 태그` 로 검색후 잘 작동되게 해주세요

2024-04-22 11:37 UTC, andole98 commented on src/main/java/roomescape/service/ReservationService.java
> +                reservation.getId(),
db에는 실제로 timeId만 들어가는데도 `time` 을 db에서 조회해야 하네요.

생성할때는 꼭 domain 객체여야만 할까요? 이런 객체를 활용해보면 어떤가요?

```java
class ReservationRegisterDetail {
    // id 없이 필드만
    // reservationTime id만
}
```

2024-04-22 11:37 UTC, andole98 commented on src/main/resources/application.properties
> +spring.h2.console.enabled=true
스프링 설정은 .properties , .yaml , .yml 로 구성할 수 있어요. 각각을 알아보고 맘에 드는걸로 구성해보시면 좋을것 같아요.

2024-04-22 11:37 UTC, andole98 commented on src/test/java/roomescape/controller/ReservationApiControllerTest.java
> +    }
api 실행 결과로 db 상태를 검증하고 있네요.

controller는 db에 직접 access하고 있나요? controller는 무슨 책임을 갖고 있나요?

db table 이름이 바뀌면(reservation_time -> book_time) 어느 코드를 수정해야 하나요? 이 테스트도 수정되어야 하나요?

2024-04-23 04:07 UTC, pricelees commented on src/main/java/roomescape/mapper/ReservationMapper.java
> +public class ReservationMapper {
> (궁금) dto <> domain 매핑을 담당하는건 어떤 장점이 있나요?

9단계에서 계층화 리팩터링을 진행하면서 자연스레 의문이 들었던 부분이 `DTO 를 어디서 처리하는게 좋을까?` 였습니다!
느낌상 Dao에서 하는 것은 아닌 것 같고.. 그래서 구글링을 해보니 다음의 두 선택지가 있더라구요.

1. 컨트롤러에서 DTO를 엔티티로 매핑한 뒤 서비스 계층으로 넘긴다.
2. 서비스에서 DTO를 처리한다.

명확한 선택지가 있으면 좋았겠지만.. 수많은 자료를 찾아봐도 '딱 이게 정답이다' 라고 하는 것이 없더라구요. 
저는 서비스 레이어는 비즈니스 로직이 있기에 가급적 수정할 여지를 만들면 안되고, DTO는 API 명세에 따라 계속 변화할 여지가 있는 것이라고 생각했기에 서비스 레이어에서 DTO를 처리한다는 의견보단 컨트롤러에서 엔티티로 매핑한뒤 넘기는 것이 조금 더 합리적으로 느껴졌던 것 같습니다.

그래서 처음에는 컨트롤러에서 직접 매핑하도록 구현을 했었는데, 컨트롤러 코드가 깔끔하게 느껴지지 않아서 별도의 객체로 분리하게 되었습니다.

참고한 자료는 https://www.baeldung.com/java-dto-pattern 입니다!

2024-04-23 04:13 UTC, pricelees commented on src/main/java/roomescape/mapper/ReservationMapper.java
> +public class ReservationMapper {
> ReservationTime도 `Reservation`Mapper가 처리하고 있군요

만약 Mapper를 계속 사용해야 한다면 분리하는게 맞겠네요 ㅠㅠ 아직 이런저런 정답을 내리기 힘든 상태라 이전 커멘트에 대해 의견 주시면 다시 생각해보겠습니다..!!

2024-04-23 04:27 UTC, andole98 commented on src/main/java/roomescape/mapper/ReservationMapper.java
> +public class ReservationMapper {
잘 찾아보신것 같네요.

Dto자체에서 domain을 매핑하는 방법으로 많이들 구현합니다. `new xxDto(domain)` 이렇게요.

domain 이 dto가 필요로 하는 모든 정보가 있다면 간편하고 좋은 편입니다.

dto가 domain외에 context가 있는 경우, 상돌처럼 전담하는 component를 만들기도 합니다.

2024-04-23 04:32 UTC, andole98 commented on src/main/java/roomescape/mapper/ReservationMapper.java
> +public class ReservationMapper {
덧붙여서, 정답을 찾으려는 노력은 지양하는게 좋을것 같습니다.

상돌은 정답을 찾고 있나요? 그렇다면 지금의 교육코스나.. 진로를 잘못 잡으신것 같아요. 대학원으로 가셔야 합니다.

기술을 잘 이해하고 니즈에 맞게 잘 응용하는게 개발자의 능력입니다. 정답이 존재한다면 개발자가 왜 필요할까요? 수학자가 정답으로 다 풀면 되겠죠.

알아보신 내용도 이야기한것처럼 의견이 분분합니다. 생각이 다른 사람들이 많이 있고, 다 장단점이 있을거에요. 다들 처한 상황이나 니즈가 다르기 때문일거에요. 상돌은 어떤 상황인가요? 어떤 니즈가 있나요?

상돌은 어떤것을 얻고 어떤것을 버릴지 선택하는 "중재자"이자 "창조자"입니다. 

기술 자체를 잘 몰라서 판단이 어렵다면 하나하나 직접 따라해보고 스스로 평가해보는게 도움될거에요.

2024-04-23 04:33 UTC, andole98 commented on src/main/java/roomescape/controller/ReservationApiController.java
> +    public void deleteReservation(@PathVariable Long id) {
여기는 delete인데, `delete reservation by id(null)` 이 가능한가요?

2024-04-23 04:33 UTC, andole98 commented on src/main/java/roomescape/controller/ReservationApiController.java
> +    public void deleteReservation(@PathVariable Long id) {
`delete reservations by null` 은 서버가 어떻게 처리해야 하나요?

2024-04-24 04:46 UTC, pricelees commented on src/main/java/roomescape/mapper/ReservationMapper.java
> +public class ReservationMapper {
> 잘 찾아보신것 같네요.
> 
> Dto자체에서 domain을 매핑하는 방법으로 많이들 구현합니다. `new xxDto(domain)` 이렇게요.
> 
> domain 이 dto가 필요로 하는 모든 정보가 있다면 간편하고 좋은 편입니다.
> 
> dto가 domain외에 context가 있는 경우, 상돌처럼 전담하는 component를 만들기도 합니다.

감사합니다! DTO 자체에서 매핑하는 방법으로 한번 수정해 보겠습니다.😄

2024-04-25 06:48 UTC, pricelees commented on src/main/java/roomescape/mapper/ReservationMapper.java
> +public class ReservationMapper {
> 덧붙여서, 정답을 찾으려는 노력은 지양하는게 좋을것 같습니다.
> 
> 상돌은 정답을 찾고 있나요? 그렇다면 지금의 교육코스나.. 진로를 잘못 잡으신것 같아요. 대학원으로 가셔야 합니다.
> 
> 기술을 잘 이해하고 니즈에 맞게 잘 응용하는게 개발자의 능력입니다. 정답이 존재한다면 개발자가 왜 필요할까요? 수학자가 정답으로 다 풀면 되겠죠.
> 
> 알아보신 내용도 이야기한것처럼 의견이 분분합니다. 생각이 다른 사람들이 많이 있고, 다 장단점이 있을거에요. 다들 처한 상황이나 니즈가 다르기 때문일거에요. 상돌은 어떤 상황인가요? 어떤 니즈가 있나요?
> 
> 상돌은 어떤것을 얻고 어떤것을 버릴지 선택하는 "중재자"이자 "창조자"입니다.
> 
> 기술 자체를 잘 몰라서 판단이 어렵다면 하나하나 직접 따라해보고 스스로 평가해보는게 도움될거에요.

좋은 조언 감사드립니다. 하지만 저는 제가 했던 과정이 잘못되었다고 생각하지는 않습니다.

2024-04-25 10:26 UTC, pricelees commented on src/main/java/roomescape/mapper/ReservationMapper.java
> +public class ReservationMapper {
> 덧붙여서, 정답을 찾으려는 노력은 지양하는게 좋을것 같습니다.
> 
> 상돌은 정답을 찾고 있나요? 그렇다면 지금의 교육코스나.. 진로를 잘못 잡으신것 같아요. 대학원으로 가셔야 합니다.
> 
> 기술을 잘 이해하고 니즈에 맞게 잘 응용하는게 개발자의 능력입니다. 정답이 존재한다면 개발자가 왜 필요할까요? 수학자가 정답으로 다 풀면 되겠죠.
> 
> 알아보신 내용도 이야기한것처럼 의견이 분분합니다. 생각이 다른 사람들이 많이 있고, 다 장단점이 있을거에요. 다들 처한 상황이나 니즈가 다르기 때문일거에요. 상돌은 어떤 상황인가요? 어떤 니즈가 있나요?
> 
> 상돌은 어떤것을 얻고 어떤것을 버릴지 선택하는 "중재자"이자 "창조자"입니다.
> 
> 기술 자체를 잘 몰라서 판단이 어렵다면 하나하나 직접 따라해보고 스스로 평가해보는게 도움될거에요.

좋은 조언 감사드립니다. 지난 학습 과정을 많이 돌아볼 수 있었습니다. 

하지만 정답을 찾고자 하는 것은 초심자이기에 어쩔 수 없다는 생각입니다. 초심자 입장에서는 여러 의견이 있다는 것을 알았을 때, 바로 이것들의 장단점을 판단하고 직접 써보는 것 보단 정보를 더 찾아보고 원하는 답이 나오지 않았을 때 장단점을 판단하고 사용하는 것이 자연스럽습니다. 

항상 정답을 찾으려고 하는 것이 아닙니다. 단지 지금 단계에서는 여러 정보를 보고 직접 사용해볼 생각이 들 정도의 지식과 경험이 없었기 때문입니다. 수학을 공부할때도 다르지 않습니다. 처음엔 답을 생각하고 솔루션을 찾지만, 지식이 쌓여갈수록 문제 해결과 더불어 그 과정에 대해 생각합니다.  

저도 안돌의 말씀이 지당하다고 생각합니다. 그리고 리뷰를 받을 때는 생각이 다르다고 해도 일단 리뷰어의 의견을 수용해보는 것이 맞다고 생각합니다. 하지만 진로에 대한 언급은 이 시점에선 적절하지 않다는 생각입니다. 좋은 의도일 것이라고 생각해도 기분 좋게 수용할 수가 없었습니다. 

안돌께서 제가 처음 스프링을 사용하는 것을 감안하고 리뷰를 해주시는 것과, 슬랙방을 통해 중간중간 생각해볼 정보를 공유해 주시는 것도 감사하게 생각하고 있습니다. 정말 도움이 많이 되고 있습니다. 그래서 남겨주신 커멘트 하나하나 가볍게 생각하지 않고 몇 시간동안 고민하고 답변하고 있습니다. 이번 답변도 마찬가지로 정말 많은 고민끝에 남기는 것임을 이해해주시면 감사하겠습니다.

2024-04-25 10:26 UTC, pricelees commented on src/main/java/roomescape/controller/ReservationApiController.java
> +    public void deleteReservation(@PathVariable Long id) {
> 생성할때는 db의 generated id를 사용하니까 그럴것 같네요. 대신 명시적인 id == null이 아닌, id가 필요 없는것 아닌가요?

컨트롤러에서 엔티티로 변환해서 서비스에 전달했기에, 값을 채워야 하는 상황이었습니다. 안돌의 말씀처럼 null을 지정하는 것이 부자연스럽게 느껴졌고, Dto를 서비스에서 받아 매핑하는 방법으로 id를 제외했습니다! 말씀하신 의견을 보고 고민을 해보니 Dto의 매핑을 컨트롤러에서 하는 것과 서비스에서 하는 것이 어떤 차이가 있는지 느낄 수 있었습니다. 감사합니다!

> 또 여기는 delete인데, `delete reservation by id(null)` 이 가능한가요?

지금 구조에선 null을 넣는 것이 불가능하다고 생각합니다. 그래서 구조를 바꾸는 과정에서 id에 null을 지정할 필요가 없어졌기에 id의 타입을 다시 long으로 수정하였습니다!

2024-04-25 10:26 UTC, pricelees commented on src/main/java/roomescape/repository/ReservationDao.java
> +    private RowMapper<Reservation> reservationRowMapper() {
> 객체로 분리된다면 테스트가 가능하겠네요

객체 분리는 비교적 간단하나, 테스트를 작성하는데 많은 시간이 걸렸습니다. jdbcTemplate을 이용하여 커넥션을 얻는 방법 등 여러 방법을 시도해봤고, 안돌께서 슬랙에 올려주신 SimpleResultSet 도 확인하였습니다.

SimpleResultSet을 사용하려면 의존성을 추가해야 하더라구요. 그래서 더 생각해봤는데, 안돌께서 의도하신 것은 분리한 RowMapper 객체를 이용한 데이터베이스 테이블과 객체 간의 매핑을 확인하는 것이고, 이는 분리한 객체를 JdbcTemplate의 메서드에 넣는 방법으로 확인할 수 있다고 생각했습니다.

```java
String query = ...
RowMapper<Reservation> rowMapper = new ReservationRowMapper();
Reservation reservation = jdbcTemplate.queryForObject(query, rowMapper);

// 이후 Assertions 테스트
```

그래서 위와 같은 방법으로 일단 테스트를 작성하였습니다.

2024-04-25 10:26 UTC, pricelees commented on src/main/java/roomescape/service/ReservationService.java
> +                reservation.getId(),
> db에는 실제로 timeId만 들어가는데도 `time` 을 db에서 조회해야 하네요.
예약을 추가하면 응답에 시간을 넣어줘야 하고, 시간은 time 테이블에서 조회하여 넣을 수 밖에 없었습니다. 정말 많이 고민했는데 테이블에서 값을 조회하지 않고 해결할 방법이 지금 단계에선 떠오르지 않았습니다 ㅠ

> 생성할때는 꼭 domain 객체여야만 할까요? 이런 객체를 활용해보면 어떤가요?
좋은 방법인 것 같습니다. 해당 부분 참고하여 구조를 다음과 같이 수정하였습니다.

1. 컨트롤러에선 Request를 받아 Service에 전달한다.
- 즉, 이전에 했던 컨트롤러에서 엔티티로 매핑한 뒤 서비스에 전달하는 것이 아닌, 서비스에 바로 DTO를 전달하는 방법으로 수정하였습니다.

2. Service에선 Request를 받아 RegisterDetail 객체로 매핑한 뒤 Repository로 전달한다.

3. Repository에선 RegisterDetail을 입력받아 id를 채운 뒤 Reservation 엔티티를 반환한다.

이 방법이 안돌께서 의도하셨던 생각인지 궁금합니다!

2024-04-25 10:28 UTC, pricelees commented on src/main/resources/application.properties
> +spring.h2.console.enabled=true
> 스프링 설정은 .properties , .yaml , .yml 로 구성할 수 있어요. 각각을 알아보고 맘에 드는걸로 구성해보시면 좋을것 같아요.

지금 단계에선 값이 많이 없기에 크게 체감되는 것은 없으나, 데이터가 많아졌을 때 계층화를 통해 깔끔하게 볼 수 있다는 장점이 있다는 것을 확인했고, yml로 수정하였습니다!

2024-04-25 10:28 UTC, pricelees commented on src/test/java/roomescape/controller/ReservationApiControllerTest.java
> +    }
> api 실행 결과로 db 상태를 검증하고 있네요.
> 
> controller는 db에 직접 access하고 있나요? controller는 무슨 책임을 갖고 있나요?

이번 단계에선 테스트를 고려하지 않다보니, 미션에서 주어진 테스트를 API 별로 분리만 했었습니다.

말씀하신대로, 컨트롤러의 역할에 대해 생각해보니 DB의 값이 아니라, HTTP 응답에 있는 값으로 검증하는게 맞다는 생각이 들었고 컨트롤러에서 DB와 관련된 코드를 제거하는 방법으로 수정하였습니다. 

> db table 이름이 바뀌면(reservation_time -> book_time) 어느 코드를 수정해야 하나요? 이 테스트도 수정되어야 하나요?

테이블 변경이 컨트롤러에 영향을 끼치면 안 된다고 생각합니다. 제가 의도를 잘 이해한건지는 모르겠으나, 그래서 Repository와 Service 테스트를 별도로 만들었습니다. Repository는 RegisterDetail 객체를 이용하고, Service는 Request 객체를 이용하여 테스트하도록 구성하였습니다.

2024-04-25 10:30 UTC, pricelees commented
안돌 안녕하세요! 6기 상돌(이상진) 입니다.

남겨주신 커멘트들에 대해 많은 생각을 해보게 되어 예상보다 제출이 늦어졌습니다.
그래도 덕분에 많은 고민을 할 수 있었고, 조금씩 생각이 잡혀간다고 생각하고 있습니다.

감사합니다. 남은 한 주도 즐겁게 보내세요!

2024-04-29 01:06 UTC, andole98 approved these changes
수고하셨습니다

2024-04-29 01:06 UTC, andole98 commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +class ReservationServiceTest {
`webEnvironment`, `@DirtiesContext`는 없어도 되겠네요.

```suggestion
@SpringBootTest
```

2024-04-29 01:06 UTC, merged