[4 - 9단계 - 방탈출 예약 관리] 테니(나아연) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #104
Opened 2024-04-22 06:48 UTC by ay-eonii

안녕하세요 호돌! 
1-3 단계 리뷰 감사했습니다 ☺️ 이번에도 잘 부탁드립니다!

2024-04-23 00:34 UTC, kimhodol requested changes
안녕하세요 테니 :)

요구사항 구현 잘 해주셨네요!

코멘트 확인 부탁드릴게요~

2024-04-23 00:34 UTC, kimhodol commented on src/main/java/roomescape/domain/Reservation.java
> +    public long getReservationTimeId() {
질문) 프로젝트 전반적으로 어떤 곳은 primitive long을 사용하고 어떤 곳은 object Long을 사용하고 계시는데, 테니만의 기준이 있을까요?

2024-04-23 00:34 UTC, kimhodol commented on src/main/java/roomescape/repository/ReservationDao.java
> +    }
의견) Multiline string을 사용하면 가독성을 개선할 수 있을 것 같아요.

2024-04-23 00:34 UTC, kimhodol commented on src/main/java/roomescape/service/ReservationService.java
> +    private final ReservationMapper reservationMapper = new ReservationMapper();
의견) Mapper 객체도 스프링 빈 등록을 해서 의존성 주입을 해주면 어떨까요?

2024-04-23 00:34 UTC, kimhodol commented on src/main/java/roomescape/service/ReservationService.java
> +    private final ReservationDao reservationDao;
의견) 생성자 주입 시에는 `@Autowired` 어노테이션이 불필요합니다.

2024-04-23 00:34 UTC, kimhodol commented on src/main/java/roomescape/repository/TimeDao.java
> +        return new ArrayList<>(reservationTimes);
질문) new ArrayList로 한 번 더 감싸는 이유가 있나요?

2024-04-23 00:34 UTC, kimhodol commented on src/test/java/roomescape/MissionStepTest.java
>  @SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
의견) 테스트가 돌아가는 장치에서 DEFINED PORT가 이미 사용되고 있다면 테스트가 실패할 수 있겠네요.

2024-04-23 00:34 UTC, kimhodol commented on src/main/java/roomescape/service/ReservationService.java
> +        ReservationTime time = reservationTimeService.findTimeById(request.timeId());
질문) findTimeById가 null을 반환하면 어떻게 처리하나요?

2024-04-23 00:34 UTC, kimhodol commented on src/main/java/roomescape/service/ReservationTimeService.java
> +        timeDao.deleteById(id);
질문) time이 삭제되면 이를 참조하는 reservation은 어떻게 되나요?

2024-04-24 05:30 UTC, ay-eonii commented on src/test/java/roomescape/MissionStepTest.java
>  @SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
webEnvironment 옵션을 RANDOM_PORT 로 변경하고 런타임 시 할당된 포트번호를 `@LocalServerPort`로 받아 RestAssured.port로 사용하도록 변경했습니다!

2024-04-24 05:35 UTC, ay-eonii commented
@kimhodol 
리뷰 감사합니다 호돌!

답변과 몇가지 질문 확인해 주시면 감사하겠습니다!😊
추가적으로 질문이 하나 더 있습니다! DB에서 발생한 예외의 경우 DAO에서 처리할지 Service에서 처리할지 고민하다 Service에서 처리하도록 했습니다. 예외 메시지나 예외 처리방식이 정책 또는 기획에 따라 변경될 가능성이 있다고 생각해 DAO보다는 Service단에서 처리하는 게 좋을 것 같다고 생각했기 때문입니다! 
호돌의 경우 이런 예외를 어디에서 처리하는지 궁금합니다 ㅎㅎ

감사합니다!☺️

2024-04-24 12:03 UTC, kimhodol requested changes
안녕하세요 테니 :)

피드백 반영 잘 해주셨네요!

간단한 코멘트 남겼으니 확인 부탁드릴게요~

2024-04-24 12:03 UTC, kimhodol commented on src/main/java/roomescape/service/ReservationService.java
> +    private final ReservationMapper reservationMapper = new ReservationMapper();
듣고 보니 테니 말이 맞는 것 같네요 ㅋㅋ 뭔가 제가 all args constructor을 사용하는 것을 선호하다 보니 저런 의견을 드린 것 같은데, 생각해보니 불필요하게 스프링 빈으로 등록할 필요가 없겠군요..?

2024-04-25 02:02 UTC, ay-eonii commented on src/main/java/roomescape/controller/ReservationController.java
> +    }
호돌 의견대로 템플릿을 반환하는 컨트롤러와 ResponseEntity를 반환하는 컨트롤러를 분리하니 더 역할이 더 분명해진 것 같아요! 좋은 의견 감사합니다:)

2024-04-25 02:35 UTC, ay-eonii commented on src/main/java/roomescape/exception/ExceptionControllerAdvice.java
> +    }
네! 처리하지 않은 예외들에 대해 500 응답을 반환하도록 추가했습니다 👍 

추가로 존재하지 않는 예약시간 조회 요청 시 기존에 반환하던 400 대신 404를 반환하도록 변경하였습니다. 참조된 예약 시간 삭제 요청 시에는 NoSuchElementException보다 IllegalArgumentException이 더 적절한 예외라 판단해 변경했습니다 !

2024-04-25 02:41 UTC, ay-eonii commented
@kimhodol

안녕하세요 호돌! 피드백 반영하여 다시 리뷰 요청 드립니다:)

> 그런데 하나 궁금한 점이 있습니다! DAO클래스에서 findAll 을 호출한다면 그 값을 변경할 거라고 (저는) 기대하지 않습니다. 오히려 요소를 add 하거나 remove 하는 것이 위험하지 않나 라는 생각도 듭니다. 그래서 reservationTimes를 unmodifiable 하도록 반환하려 합니다.
>
> 혹시 DB 에서 꺼낸 값이 unmodifiable 하다면 유연성이 너무 떨어지는지 호돌의 의견이 궁금합니다!


이전 리뷰 중 `TimeDao.java`에서 드린 질문을 놓치신 것 같아 다시 질문 드립니다! 
위 코멘트에 대해서도 답변 주시면 감사하겠습니다 🥺

2024-04-26 02:49 UTC, kimhodol commented on src/main/java/roomescape/repository/TimeDao.java
> +        return new ArrayList<>(reservationTimes);
저도 테니 말에 동의합니다! findAll을 해서 변경을 할 여지는 없으니 unmodifiable한 값을 가져오는 것은 예상치 못한 액션을 막을 수 있을 것이라 생각해요.

2024-04-26 02:53 UTC, kimhodol commented on src/main/java/roomescape/repository/TimeDao.java
> +        return new ArrayList<>(reservationTimes);
아 지금도 Collections.unmodifiableList를 사용하는군요? 굿굿입니다!

2024-04-26 02:59 UTC, kimhodol commented on src/main/java/roomescape/exception/ExceptionControllerAdvice.java
> +    }
안녕하세요 테니 :)

피드백 반영 잘 해주셨네요.
이번 미션은 여기서 마무리 하도록 할게요.

고생하셨습니다!

2024-04-26 02:59 UTC, kimhodol approved these changes
안녕하세요 테니 :)

피드백 반영 잘 해주셨네요.
이번 미션은 여기서 마무리 하도록 할게요.

고생하셨습니다!

---

저 위에 질문에 대한 답변도 못 드린것 같아서 늦게서야 남깁니다!

> DB에서 발생한 예외의 경우 DAO에서 처리할지 Service에서 처리할지 고민하다 Service에서 처리하도록 했습니다. 예외 메시지나 예외 처리방식이 정책 또는 기획에 따라 변경될 가능성이 있다고 생각해 DAO보다는 Service단에서 처리하는 게 좋을 것 같다고 생각했기 때문입니다! 호돌의 경우 이런 예외를 어디에서 처리하는지 궁금합니다 ㅎㅎ

저는 예외가 발생하는 곳에서 throw를 한다는 생각인데요, 이 예외는 에러가 아닌 개발자가 인지하고 있는 오류라는 가정입니다. 테니가 작성해주신대로 TimeDao의 findById에서 DataAccessException을 catch해서 Optional.empty()를 반환하고 있는 것이 좋은 예시라고 생각해요. 값을 못찾으면 에러는 나지만 이건 실제로 예외는 아니잖아요? 그래서 그 값을 Optional.empty()로 적절하게 반환만 하고 값이 없어서 생기는 논리적 오류는 Service Layer에서 처리하게 만드셨는데 저도 이렇게 작성했을 것 같아요!

2024-04-26 03:00 UTC, merged