[4 - 9단계 방탈출 예약 관리] 트레(이충렬) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #105
Opened 2024-04-22 07:28 UTC by takoyakimchi

2024-04-22 10:32 UTC, JunHoPark93 requested changes
안녕하세요 트레~
미션 구현하느라 고생많으셨습니다.
몇 가지 코멘트 남겼는데 확인해보시고 의견 및 반영부탁드려요!

2024-04-23 02:26 UTC, takoyakimchi commented on src/test/java/roomescape/controller/ReservationTimeControllerTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)
해냈습니다...😭
```java
    @AfterEach
    void deleteAllData() {
        jdbcTemplate.execute("SET REFERENTIAL_INTEGRITY FALSE");
        jdbcTemplate.execute("TRUNCATE TABLE reservation");
        jdbcTemplate.execute("ALTER TABLE reservation ALTER COLUMN id RESTART WITH 1");
        jdbcTemplate.execute("TRUNCATE TABLE reservation_time");
        jdbcTemplate.execute("ALTER TABLE reservation_time ALTER COLUMN id RESTART WITH 1");
        jdbcTemplate.execute("SET REFERENTIAL_INTEGRITY TRUE");
    }
```

2024-04-23 04:34 UTC, takoyakimchi commented on src/main/resources/schema.sql
> +    time_id BIGINT,
있어야 합니다! `NOT NULL` 추가하도록 하겠습니다.

2024-04-23 08:03 UTC, takoyakimchi commented on src/main/java/roomescape/controller/ReservationController.java
> +            .header("Location", String.format("/reservations/%d", savedReservation.getId()))
201 Created를 응답할 때는 Location 헤더를 추가해서 응답하는군요.

200 OK를 주고 있기 때문에 헤더 관련 부분은 제거하겠습니다!

2024-04-23 08:16 UTC, takoyakimchi commented on src/main/java/roomescape/repository/ReservationTimeRepository.java
> +        Long id = keyHolder.getKey().longValue();
long으로 바꿔도 문제 없을 것 같습니다.

2024-04-23 08:18 UTC, takoyakimchi commented on src/main/java/roomescape/controller/ReservationTimeController.java
> +    public void delete(@PathVariable Long id) {
long으로 수정하겠습니다!

2024-04-23 08:19 UTC, takoyakimchi commented on src/main/java/roomescape/dto/CreateReservationRequest.java
> +public record CreateReservationRequest(String date, String name, Long timeId) {
서비스 계층에서 도메인 객체를 만들어서 전달하는 방식으로 수정하였습니다

2024-04-23 08:45 UTC, takoyakimchi commented on src/main/java/roomescape/repository/ReservationRepository.java
> +                inner join reservation_time as t
inner join은 양쪽 테이블에서 공통적으로 존재하는 값만 결과로 추출되며(교집합),
그냥 join을 쓰면 디폴트로 inner join으로 됩니다.

left join은 테이블 A의 모든 레코드와, 테이블 B에서 일치하는 값을 가진 레코드를 추출하며
따라서 일부 값이 null이 될 수 있습니다.

right join은 마찬가지로, 테이블 B의 모든 레코드와, 테이블 A에서 일치하는 값을 가진 레코드를 추출합니다.

이렇게만 찾아보면 inner join 외에는 잘 사용되지 않을 것만 같은데,
현업에서 outer join을 쓰는 경우가 많이 있나요?

2024-04-23 10:46 UTC, takoyakimchi commented on src/main/java/roomescape/controller/ReservationTimeController.java
> +public class ReservationTimeController {
Controller: 유저의 요청과 응답을 관리한다
Service: 컨트롤러로 받아온 요청을 토대로 데이터를 가공(비즈니스 로직을 처리)한다
Repository: DB에 접근한다

이렇게 알고 있습니다!

2024-04-23 10:47 UTC, takoyakimchi commented on src/main/resources/schema.sql
> +    date    VARCHAR(255) NOT NULL,
DATE, TIME 사용해 보겠습니다!

2024-04-23 11:59 UTC, takoyakimchi commented
안녕하세요 제이!
리뷰 주신 내용 바탕으로 몇 가지 개선해 보았습니다.

## 변경 사항
- 모든 요청, 응답에 DTO 사용하였습니다.
- `LocalTime`, `LocalDate` 적용하였습니다.
  - 시간이 초 단위까지 표시되어 API 명세가 맞지 않는 문제가 발생하였고, `@JsonFormat(pattern = "HH:mm")` 어노테이션으로 이를 해결하였습니다.
- INSERT 쿼리에서 `SimpleJdbcInsert`를 적용시켜 코드 가독성을 개선해 보았습니다.
- 내비게이션 바에 있는 a태그(Reservation, Time)가 정상 작동하도록 수정하였습니다.

## 질문
### 1. 응답으로 List를 반환할 때, List도 별도로 감싸는 게 바람직할까요?
예를 들면 현재 `ReservationController`의 `findAll()` 메소드는 `List<FindReservationResponse>`를 반환하고 있습니다.
DTO로 묶어서 반환하는 방식으로도 코드를 작성해 보았지만, 과제의 API 명세에도 맞지 않고, 테스트 용이성 때문에 일단은 롤백하게 되었습니다.
제이는 이것도 별도의 DTO로 묶어서 응답하시나요?

### 2. Response DTO를 Service 레이어에서 채워주어도 될까요?
예를 들면 `ReservationController.save()` 메소드의 내부 구현을 `return service.save( ... );`와 같이 한 줄로 줄이고, 응답 DTO를 채우는 로직을 서비스 레이어로 분리하면 어떨까 하는 생각이 들었습니다. 아직까지 DTO와 레이어 간 흐름이 감이 잡히지 않네요 😭 어떤 방식이 일반적으로 선호되는지 알려주시면 감사하겠습니다...!

2024-04-24 00:31 UTC, JunHoPark93 commented on src/main/java/roomescape/controller/ReservationTimeController.java
> +public class ReservationTimeController {
음 제가 언급드린 의도는 역할정리뿐만아니라 (조금 더 자세했으면 좋겠어요) 현재 모습이 알고계신 구조에 부합하는지 확인해보면 좋겠다는 의도였어요.

2024-04-24 00:36 UTC, JunHoPark93 commented on src/main/java/roomescape/repository/ReservationRepository.java
> +                inner join reservation_time as t
넵 예를들어, (범위에맞는) 모든 고객을 조회하면서 그들이 주문한 내역이 있다면 함께 조회한다든지 등 여러 상황이 있을수있습니다.

2024-04-24 00:37 UTC, JunHoPark93 commented on src/main/java/roomescape/service/ReservationService.java
> +        return repository.findAll();
넵 좋습니다! 추후 프로젝트하실때 구현하실 기회가 있으실거같아요.

2024-04-24 00:37 UTC, JunHoPark93 commented on src/main/resources/schema.sql
> +    date    VARCHAR(255) NOT NULL,
넵 자료형에 대해서 한번 정리해보셔도 좋을거같아요~

2024-04-24 00:52 UTC, JunHoPark93 approved these changes
안녕하세요 트레~
리뷰 반영 고생많으셨습니다.
질문주신 부분 코멘트 남겨두었는데 더 궁금하신점 있으시면 dm주세요~
다음 미션도 화이팅입니다!

2024-04-24 00:52 UTC, JunHoPark93 commented on src/main/resources/templates/admin/index.html
> +        <a class="nav-link" href="/admin/reservation">Reservation</a>
이거는 추후미션들에서 붙는줄알았는데 잘 개선해주셨네요!

2024-04-24 00:52 UTC, JunHoPark93 commented on src/main/java/roomescape/controller/ReservationTimeController.java
> +    public List<FindReservationTimeResponse> findAll() {
> 예를 들면 현재 ReservationController의 findAll() 메소드는 List<FindReservationResponse>를 반환하고 있습니다.
> DTO로 묶어서 반환하는 방식으로도 코드를 작성해 보았지만, 과제의 API 명세에도 맞지 않고, 테스트 용이성 때문에 일단은 롤백하게 되었습니다.
> 제이는 이것도 별도의 DTO로 묶어서 응답하시나요?

list를 한번더 감싸서 보내는 방식을 말씀하신거죠? 
장단점이 있는거같아요. 현재 구조가 더 간결하고 명확하지만 추후에 다른 응답값들이 포함되는 요구사항이 생긴다면 무중단으로 배포하기 힘들수도있습니다.

상황에 맞게 선택하면 될거같아요. 개인적으로 현재 구조가 간단하기 때문에 충분한거같습니다.

2024-04-24 00:52 UTC, JunHoPark93 commented on src/main/java/roomescape/service/ReservationService.java
> +public class ReservationService {
> 2. Response DTO를 Service 레이어에서 채워주어도 될까요?
> 예를 들면 ReservationController.save() 메소드의 내부 구현을 return service.save( ... );와 같이 한 줄로 줄이고, 응답 DTO를 채우는 로직을 서비스 레이어로 분리하면 어떨까 하는 생각이 들었습니다. 아직까지 DTO와 레이어 간 흐름이 감이 잡히지 않네요 😭 어떤 방식이 일반적으로 선호되는지 알려주시면 감사하겠습니다...!

정해진 방식이 있다기보다 제가 경험했던 구조들을 말씀드리면,
C: controller
S: service

* C (dto 변환) -> S -> ...
* C -> S (dto 변환) -> ...
* C -> S1(dto변환) -> S2 -> ...

세번째꺼는 구조가 훨씬복잡할때 서비스 계층을 나눈 구조입니다.

2024-04-24 00:52 UTC, JunHoPark93 commented on src/main/java/roomescape/service/ReservationService.java
> +public class ReservationService {
이것도 상황에 맞게 선택하시면 될거같습니다. 중요한점은 프로젝트내 일관성이며 모두가 동의를 하는구조가 되면 더 좋겠죠.

참고로 이론에 충실하게 하다보면 효율성이 떨어지는경우가 많은데 지금은 이론에 충실하게, 힘들게 개발해보는것을 추천드립니다.

2024-04-24 00:52 UTC, merged

2024-04-25 02:19 UTC, takoyakimchi commented on src/main/java/roomescape/controller/ReservationTimeController.java
> +public class ReservationTimeController {
프로젝트 규모가 작아서 아직까지는 차이가 잘 안 와닿네요... 😭😭

2024-04-25 02:20 UTC, takoyakimchi commented on src/main/java/roomescape/repository/ReservationRepository.java
> +                inner join reservation_time as t
그렇군요! 답변 감사합니다!!!

2024-04-25 02:24 UTC, takoyakimchi commented on src/main/java/roomescape/service/ReservationService.java
> +public class ReservationService {
팀/회사에 따라 정해진 방식이 다를 수도 있겠군요!
답변 감사합니다!!!