[4 - 9단계 - 방탈출 예약 관리] 초롱(정회성) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #107
Opened 2024-04-22 08:26 UTC by HoeSeong123

안녕하세요 영이!
이번에는 늦지 않게 찾아왔습니다😅

확실히 스프링이 처음이라 그런지 작은 기능 하나를 구현하는 것도 정말 오래 걸리네요..
그래도 오래 걸린 만큼 더 많이 배워가고 있는 것 같습니다.

미션을 진행하면서 궁금했던 점에 대해 질문드리겠습니다!!

# 궁금한 점
## Jackson의 자바 객체 변환
현재 도메인 객체들은 Jackson을 이용하여 JSON 데이터를 JAVA 객체로 만들기 위해 기본 생성자를 구현해두었습니다.
기본 생성자가 없으니 인스턴스 생성을 못한다고 하더군요..
그런데 노트북에서 진행할 때는 기본 생성자가 없으면 실행이 안되는데 동일한 코드로 데스크탑에서 실행시켜보니 기본 생성자가 없어도 정상적으로 동작하는 것을 확인하였습니다.

아무리 찾아봐도 둘의 차이점을 찾을 수가 없어서 질문 드려봅니다..
혹시 Jackson의 새로운 버전에서는 기본 생성자가 없어도 인스턴스 생성이 가능해진 것인가요??

## 한 Service에서 여러 Repository 연결
```java
@Service
public class ReservationService {
    @Autowired
    private ReservationDao reservationDao;
    @Autowired
    private ReservationTimeDao reservationTimeDao;

    public Reservation save(ReservationDto reservationDto) {
        ReservationTime reservationTime = reservationTimeDao.findById(reservationDto.timeId());
        Long id = reservationDao.save(reservationDto);
        return new Reservation.Builder()
                .id(id)
                .name(reservationDto.name())
                .date(reservationDto.date())
                .time(reservationTime)
                .build();
    }
}
```
위 코드는 `ReservationService`에서 reservation을 저장할 때 사용되는 코드입니다.
저장하고 `Reservation`을 반환하기 위해 `ReservationTimeDao`에서 reservationTime을 가져와야 합니다.
따라서 어쩔 수 없이 `ReservationDao`와 `ReservationTimeDao` 2가지의 repository를 연결하게 되었습니다.

이러한 구조가 일반적인 방법인지 궁금합니다.
만약 아니라면 `ReservationService`에서 `ReservationTimeService`를 연결해서 사용해야 하는 것인가요?

## spring에서의 tdd
이번 미션은 구현을 어떻게 해야할 지 아예 감이 잡히지 않아 주어진 테스트 코드만을 활용하여 tdd를 진행하였습니다.
그래도 이번 미션을 진행하면서 어떤 식으로 구현해야 하는 지 조금은 알게 되었습니다.

그래서 드는 의문인데 spring mvc에서도 레벨 1 때 했던 것과 동일하게 모든 클래스, 모든 메서드에 대한 테스트를 작성해야 하는 것인가요?

이상으로 질문은 마치고 이번 리뷰도 잘 부탁드립니다!!!

2024-04-22 15:28 UTC, choijy1705 requested changes
안녕하세요 초롱!
질문에 대한 답변과 몇가지 코멘트들 남겼습니다!
고민해보시고 피드백 반영 부탁드려요🙏

2024-04-24 05:31 UTC, HoeSeong123 commented on src/main/java/roomescape/controller/ReservationController.java
> +    private ReservationService reservationService;
처음에는 필드 주입과 생성자 주입의 차이가 없다고 생각하여 단순히 코드가 더 간결해지는 것 같아 필드 주입을 선택하였습니다.

영이의 피드백을 받고 둘의 차이에 대해 찾아보았는데 생성자를 통한 주입이 더욱 권장된다는 것을 알게 되었습니다.
권장되는 이유에 대해 정리해보면 다음과 같습니다.
- 순환 참조를 방지할 수 있다.
  - 생성자 주입의 경우 순환 참조가 발생하면 컴파일 에러가 발생한다.
- 테스트 코드 작성이 편리하다.
- 조금 더 품질 좋은 코드를 만들 수 있다.
  - 생성자 주입을 사용하게 되면 생성자의 인자가 많아짐에 따라 복잡한 코드가 됨을 쉽게 알 수 있다.
- 불변성
  - 필드 주입은 해당 필드를 final로 선언할 수 없다.

아래의 이유로 필드 주입보다는 생성자 주입이 조금 더 권장된다는 것을 알게 되었고 코드도 수정하였습니다😁

2024-04-24 05:55 UTC, HoeSeong123 commented on src/main/java/roomescape/controller/ReservationController.java
> +                .build();
```javascript
function requestDelete(id) {
  const requestOptions = {
    method: 'DELETE',
  };

  return fetch(`${RESERVATION_API_ENDPOINT}/${id}`, requestOptions)
      .then(response => {
        if (response.status !== 200) throw new Error('Delete failed');
      });
}
```
자바 스크립트 코드에 다음과 같이 작성되어 있어서 전부 200 코드를 응답하도록 코드를 작성하였습니다.
이런 경우에는 자바 스크립트의 코드를 수정하고 적절한 응답 코드를 보내도록 하는 것이 더 적절한 방법인가요?

2024-04-24 06:08 UTC, HoeSeong123 commented on src/main/java/roomescape/controller/ReservationController.java
>      @GetMapping("/reservations")
찾아보니 requestMapping으로 한 번에 관리할 수 있었네요!!

2024-04-24 07:59 UTC, HoeSeong123 commented on src/main/java/roomescape/dao/ReservationDao.java
> +    public Long save(ReservationDto reservationDto) {
해당 피드백을 반영하던 중에 궁금한 점이 생겼습니다.
우선 첫 번째로는 dto를 entity로 변환하는 코드를 어디에서 구현해야 하나요?
우선은 dto 클래스에서 `toEntity()`라는 메서드를 가지고 있게 하여 entity로 변환을 하도록 했습니다.
그런데 dto 클래스는 getter/setter 외에 다른 로직을 가지고 있으면 안된다는 얘기가 있어서 이정도의 변환 로직은 가지고 있어도 괜찮은지 궁금합니다.

두 번째로는 dto는 id를 가지고 있지 않아서 entity로 변환하는 과정에서 id가 null이 되게 되는데 이 부분을 어떻게 해결해야 할 지 감이 잘 오지 않습니다😢

2024-04-24 10:34 UTC, HoeSeong123 commented on src/main/java/roomescape/dao/ReservationTimeDao.java
> +    public ReservationTime findById(Long timeId) {
처음에는 질문의 의도를 파악하지 못해서 한참을 헤맸네요..😅
우선 null일 가능성에 대한 고려는 하지 않았었습니다.
애초에 `Long`과 `long`의 차이에 대해서도 명확하게 파악하지 못하고 있었던 것 같습니다..

그럼 혹시 id와 같이 절대 null이면 안되는 값들은 래퍼 클래스가 아닌 원시타입을 사용하여야 하나요?

2024-04-24 11:00 UTC, HoeSeong123 commented on src/main/java/roomescape/service/ReservationService.java
> +                .build();
다수(4개 이상)의 매개변수가 존재하는 경우 파라미터의 값을 잘못 입력하는 경우가 발생할 수 있다고 생각합니다. 다라서 Builder를 사용하여 이를 방지하고 메서드를 가독성 있게 호출할 수 있다고 생각하여 Builder를 사용했었습니다.

조금은 과도한 코딩일까요?

2024-04-24 15:34 UTC, HoeSeong123 commented on src/main/java/roomescape/service/ReservationTimeService.java
> +        reservationTimeDao.delete(id);
이에 대해 생각해보았는데 두 가지의 방법이 있을 것 같습니다.
1. reservationTime으로 생성된 reservation을 함께 삭제한다.
2. 예외처리를 진행한다.

1번의 경우는 cascade 타입을 `CascadeType.REMOVE`로 설정하여 해결할 수 있을 것 같지만 현재 미션에서는 적용할 수 없을 것으로 보입니다.
2번의 경우가 적절할 것으로 보이는데 위의 `queryForObject`에 대한 피드백에 대한 것과 동일한 질문이 있습니다.

예외 처리를 해야한다는 것은 알겠지만 어떤 방식으로 처리를 해야 하는 지 잘 모르겠습니다.
레벨 1에서는 예외가 발생하면 `IllegalArgumentException`을 발생시키고 Console 창에 에러 메세지를 띄운 후, 프로그램을 종료 또는 재입력을 받는 식으로 예외처리를 했었습니다.

스프링에서는 웹을 사용하는만큼 이전 방식처럼 콘솔 창에 띄우는 것은 적절한 해결책이 아니라고 생각됩니다. 다만 이를 어떻게 처리를 해야 하는 지 감이 잘 오지 않습니다..😭

보통은 어떤 식으로 예외처리를 진행하나요..

2024-04-24 15:35 UTC, HoeSeong123 commented on src/main/java/roomescape/dao/ReservationTimeDao.java
> +                }, timeId);
`EmptyResultDataAccessException`에 대한 예외처리를 진행하면 될 것 같습니다.
다만 이를 처리하는 방식에 대한 질문이 있는데 [아래 피드백](https://github.com/woowacourse/spring-roomescape-admin/pull/107#discussion_r1578097947) 에서 같이 질문드리겠습니다.

2024-04-24 15:38 UTC, HoeSeong123 commented on src/test/java/roomescape/MissionStepTest.java
>  @SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
아직 저는 말하는 감자에 불과한데 벌써 레벨 2가 되어버렸네요..
영이의 말을 듣고 보니 테스트 코드는 반드시 필요하다고 생각되네요..ㅎㅎ
하지만 영이의 말대로 언제까지나 요구사항과 피드백에만 의존할 수는 없다고 생각됩니다.
만약 테스트 코드에 대한 개인적인 궁금증이 생기면 리뷰 요청을 하면서 같이 질문 드려도 될까요?😅

2024-04-24 15:43 UTC, HoeSeong123 commented on src/main/java/roomescape/domain/Reservation.java
> +    }
앗 생각해보니 그렇네요😅
view에는 reservation이 아닌 reservationDto를 넘겨주니 해당 코드는 불필요한 코드가 되어버렸네요

2024-04-24 15:53 UTC, HoeSeong123 commented on src/main/resources/schema.sql
> +    time_id BIGINT,
주어진 sql문을 그대로 사용하여서 의문을 가져본 적이 없었는데 생각해보니 nullable하면 안 될 것 같습니다.
하지만 foreign key는 nullable하기 때문에 추가로 설정해줘야 할 것 같습니다.

만약 그렇게 수정하려면 아래와 같이 수정하면 되나요?
```sql
CREATE TABLE reservation
(
    id      BIGINT       NOT NULL AUTO_INCREMENT,
    name    VARCHAR(255) NOT NULL,
    date    VARCHAR(255) NOT NULL,
    time_id BIGINT       NOT NULL,    -- NOT NULL 제약 조건 추가
    PRIMARY KEY (id),
    FOREIGN KEY (time_id) REFERENCES reservation_time (id)
);
```

2024-04-25 01:18 UTC, choijy1705 requested changes
초롱 
질문 답변들과 추가 코멘트들 남겼습니다
확인 해보시고 반영부탁드려요🙏

2024-04-25 01:18 UTC, choijy1705 commented on src/main/java/roomescape/service/ReservationService.java
> +                .build();
builder 는 아마 직접 구현하실일은 없을것 같아요(롬복을 쓰면 되어서요)
또한 파라미터의 값을 잘못 입력할 가능성을 막을 수는 있지만 파라미터를 빼먹고 생성할 수 있는 문제가 있을것 같아요!

2024-04-25 01:18 UTC, choijy1705 commented on src/main/java/roomescape/service/ReservationTimeService.java
> +        reservationTimeDao.delete(id);
에러를 컨트롤하는 것은 다음 미션에서 다뤄보는걸로 알고 있습니다
지금은 적절한 에러를 throw 하는 정도까지만 해보면 좋을것 같아요!
cascade 는 웬만하면 잘 사용하지 않는것 같아요 예상치 못한 결과를 초래할 수 있기 때문에요!

2024-04-25 01:18 UTC, choijy1705 commented on src/main/resources/schema.sql
> +    time_id BIGINT,
넵 제약조건 추가해주면 될것 같습니다👍

2024-04-25 01:18 UTC, choijy1705 commented on src/test/java/roomescape/MissionStepTest.java
>  @SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
넵
추가적으로 질문을 남겨주실때 pr 에다가 남겨주시는것보다
코드에 코멘트로 질문주시는게 놓칠 가능성도 줄이고
좀 더 상황에 적절한 답변을 드릴 수 있을것 같아요🙏

2024-04-25 01:18 UTC, choijy1705 commented on src/main/java/roomescape/domain/Reservation.java
> +    private long id;
id 는 db에 저장되기 전까지는 null이어야 할것 같은데
primitive 타입에 빌더 까지 사용하고 있어
실제로 db 저장전 만들어진 객체의 id는 0일 것 같은데요🤔

2024-04-25 01:18 UTC, choijy1705 commented on src/main/java/roomescape/domain/Reservation.java
>          this.date = date;
도메인 생성시 name, date, time이 null이면 문제가 되지 않을까요?
적절한 validation이 필요해보입니다!

2024-04-25 01:18 UTC, choijy1705 commented on src/main/java/roomescape/domain/ReservationTime.java
> +    public ReservationTime(long id, LocalTime startAt) {
여기도 마찬가지로 validation이 필요하지 않을지 고민해봐주세요!

2024-04-25 01:18 UTC, choijy1705 commented on src/main/java/roomescape/dao/ReservationDao.java
> +    };
필드로 rowMapper를 관리하는 경우 static 으로 보통 관리할것 같습니다!

2024-04-25 01:18 UTC, choijy1705 commented on src/main/java/roomescape/dao/ReservationDao.java
> +        return jdbcTemplate.queryForObject(sql, rowMapper, id);
queryForObject는 없다면 조회한 값이 없거나 여러개라면 에러를 발생시킬것 같아요

2024-04-25 01:18 UTC, choijy1705 commented on src/main/java/roomescape/service/ReservationService.java
> +    public Long save(ReservationDto reservationDto) {
save를 했다면 반환되는 값은 Long이 아닌 Reservation이 반환되도록 하면 좋을것 같네요!

2024-04-25 01:18 UTC, choijy1705 commented on src/main/java/roomescape/controller/ReservationController.java
> +        return ResponseEntity.ok(reservationService.findById(saveId));
service에서 save한 reservation이 반환된다면 굳이 다시한번 조회할 필요 없을것 같습니다!

2024-04-25 01:18 UTC, choijy1705 commented on src/main/java/roomescape/controller/ReservationController.java
> +    public ResponseEntity<List<Reservation>> reservations() {
response로 도메인을 그대로 넘겨버리면 어떤 문제가 있을지 학습해보면 좋을것 같습니다!

2024-04-25 01:18 UTC, choijy1705 commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:database
yaml 로 관리해보면 좋을것 같네요!

2024-04-25 01:18 UTC, choijy1705 commented on src/main/java/roomescape/controller/ReservationController.java
> +                .build();
delete 때는 보통 204를 많이 내려줍니다!
참고 정도만 하셔도 될것 같고 바꿔보셔도 좋을것 같아요!

2024-04-25 01:18 UTC, choijy1705 commented on src/main/java/roomescape/dao/ReservationTimeDao.java
> +    public ReservationTime findById(Long timeId) {
다른 곳에도 남겼는데 원시타입으로 하고 빌더로 사용하면 더 큰 문제가 발생할것 같아요 id가 0인...
도메인의 id의 경우는 DB에 들어가기 전까지는 nullable하기 때문에 보통 래퍼 클래스를 사용합니다!

2024-04-26 04:34 UTC, HoeSeong123 commented on src/main/java/roomescape/domain/Reservation.java
> +    private long id;
id가 0인 것보다 null인 경우가 더 큰 문제인 건가요?
뭔가 이전에는 null이라는 것이 많은 문제를 일으키는 정말 사용하면 안 되는 것이라는 인식이 있어서 어색하게 느껴지네요😅
거기다 크루들도 다들 의견이 다른 것 같아서 궁금합니다!!

2024-04-26 05:25 UTC, HoeSeong123 commented on src/main/java/roomescape/domain/Reservation.java
>          this.date = date;
일단 검증 코드를 추가하기는 했는데 제가 영이의 의도를 제대로 파악하고 코드를 수정한 것이 맞는지 잘 모르겠네요..😭

여기서 한 가지 의문점이 들었습니다.
영이의 말대로 도메인 생성시 name, date, time이 null이면 문제가 될 것 같습니다.
다만 이는 dto에서도 마찬가지로 문제가 될 것 같습니다.
그렇다면 검증은 도메인이 아니라 dto에서 진행해줘야 하는 것인가요?

2024-04-26 05:49 UTC, HoeSeong123 commented on src/main/java/roomescape/controller/ReservationController.java
> +        return ResponseEntity.ok(reservationService.findById(saveId));
위 피드백을 반영하면서 `ReservationDao`의 `save` 메서드를 아래와 같이 수정하였습니다.
```java
public Reservation save(Reservation reservation) {
    String name = reservation.getName();
    LocalDate date = reservation.getDate();
    Long timeId = reservation.getTimeId();
    String sql = "insert into reservation (name, date, time_id) values (?, ?, ?)";
    KeyHolder keyHolder = new GeneratedKeyHolder();

    jdbcTemplate.update(connection -> {
        PreparedStatement ps = connection.prepareStatement(
                sql,
                new String[]{"id"});
        ps.setString(1, name);
        ps.setDate(2, Date.valueOf(date));
        ps.setLong(3, timeId);
        return ps;
    }, keyHolder);

    long saveId =  keyHolder.getKey().longValue();

    return findById(saveId);
}
```
그런데 굳이 다시 한 번 조회할 필요가 없다고 하시니 궁금증이 생겨서 질문드립니다😅

이런 방식으로 id를 구해서 다시 조회하는 방식보다 전달받은 reservation의 정보에 id 값만을 추가해서 return 시키는 것이 낫나요?
코드는 아래와 같을 것 같습니다.
```java
public Reservation save(Reservation reservation) {
    String name = reservation.getName();
    LocalDate date = reservation.getDate();
    Long timeId = reservation.getTimeId();
    
    // 생략

    long saveId =  keyHolder.getKey().longValue();

    return new Reservation(saveId, name, date, timdId);
}
```
뭔가 이렇게 하면 여기서 return된 reservation 객체가 db에 저장된 reservation과 정확하게 동일한 것이라고 확신할 수 있나? 라는 의문이 들어서 id만을 구하고 db에서 조회해서 가져오는 방식을 사용해보았습니다!!

2024-04-26 06:24 UTC, HoeSeong123 commented on src/main/java/roomescape/controller/ReservationController.java
> +    public ResponseEntity<List<Reservation>> reservations() {
이에 대해 크루들과 얘기도 나눠보고 다른 자료들도 찾아보았습니다.
제가 내린 결론은 다음과 같습니다.

- 현재는 Reservation의 모든 정보를 필요로 하기 때문에 Reservation을 그대로 넘겨버려도 문제는 없다.
- 만약 확장 가능성을 고려하면 다음과 같은 문제가 발생할 수 있다.
  - api 명세에서 전달 받고 싶은 정보가 달라지면 수정사항이 많아진다.
  - 만약 정보의 깊이가 더 깊어지면(reservation이 reservationTime 정보를 갖고 있고 reservationTime이 더 추가적인 정보를 가지고 있는 경우 등) 필요 이상의 정보들이 넘겨지게 된다.

따라서 responseDto를 만들어서 넘겨주는 것이 좋을 것 같다고 생각합니다.

2024-04-26 06:33 UTC, HoeSeong123 commented
안녕하세요 영이!
어느덧 네 번째 리뷰 요청입니다ㅎㅎ
공부할만한 부분들을 많이 알려주셔서 감사합니다😄

이번 피드백에 관한 질문도 몇 가지 코멘트로 남겨놨습니다.
추가적으로 저번 리뷰 요청 때 같이 드렸던 [질문](https://github.com/woowacourse/spring-roomescape-admin/pull/107#discussion_r1577456150)이 있었는데 하나 놓치신 것 같아서 확인 한 번 부탁드립니다!!

이번 리뷰 요청도 잘 부탁드립니다😆

2024-04-26 07:16 UTC, choijy1705 commented on src/main/java/roomescape/dao/ReservationDao.java
> +    public Long save(ReservationDto reservationDto) {
1. dto 에서 toEntity를 사용하는 경우도 있지만
지금과 같이 필드가 많지 않다면 service에서 객체를 생성자로 생성하면 될것 같네요!

2. id가 null인 객체를 만들어야할것 같습니다. 지금은 객체 저장전에 아무런 로직이 없어서 dto를 운좋게 바로 저장할 수 있지만 일반적으로 로직들을 수행하고 난뒤 객체를 저장하는 흐름일것 같네요!

2024-04-26 07:17 UTC, choijy1705 commented on src/main/java/roomescape/dao/ReservationDao.java
> +    public Long save(ReservationDto reservationDto) {
1. dto 에서 toEntity를 사용하는 경우도 있지만
지금과 같이 필드가 많지 않다면 service에서 객체를 생성자로 생성하면 될것 같네요!

2. id가 null인 객체를 만들어야할것 같습니다. 지금은 객체 저장전에 아무런 로직이 없어서 dto를 운좋게 바로 저장할 수 있지만 일반적으로 로직들을 수행하고 난뒤 객체를 저장하는 흐름일것 같네요!

2024-04-26 07:18 UTC, choijy1705 commented on src/main/java/roomescape/domain/Reservation.java
> +    private long id;
id가 0인 경우는 큰일이죠
값이 null인 경우는 있을 수 있지만 잘못된 정보가 객체로 잠시라도 존재하는것은 큰 오류를 낼 수 있을 것 같네요!

2024-04-26 07:20 UTC, choijy1705 commented on src/main/java/roomescape/controller/ReservationController.java
> +        return ResponseEntity.ok(reservationService.findById(saveId));
이전 로직처럼 dto를 db에 저장하면 신뢰할 수 없을 수 있지만
도메인을 만들고 db에 저장한다면 의심할 이유가 없을것 같네요...
이걸 의심하면 jdbcTemplate을 의심하는거나 마찬가지일것 같습니다 ㅎㅎ

2024-04-26 07:26 UTC, choijy1705 requested changes
초롱 
이전 리뷰들 중 반영이 안된 부분들이 있는것 같습니다!
다시한번 확인해보시고 리뷰 요청 부탁드려요!🙏

2024-04-26 07:26 UTC, choijy1705 commented on src/main/java/roomescape/dao/ReservationDao.java
> +        return jdbcTemplate.queryForObject(sql, ROW_MAPPER, id);
없는 값으로 조회했을때 에러에 대한 처리가 필요해보입니다!

2024-04-26 07:26 UTC, choijy1705 commented on src/main/java/roomescape/dao/ReservationDao.java
> +        return findById(saveId);
질문에 대한 답변을 드렸는데요!
지금 방법은 어차피 한번더 조회하는거라 이전 리뷰드린것과 큰 차이가 없을것 같습니다😭

2024-04-26 07:26 UTC, choijy1705 commented on src/main/java/roomescape/dao/ReservationTimeDao.java
> +                }, timeId);
여기도 남겼었네요!
에러처리 고민해봐주세요!

2024-04-26 07:26 UTC, choijy1705 commented on src/main/java/roomescape/dao/ReservationTimeDao.java
> +        return new ReservationTime(id, startAt);
여기는 객체를 만들어서 반환해주셨네요 ㅎㅎ

2024-04-26 07:26 UTC, choijy1705 commented on src/main/java/roomescape/service/ReservationTimeService.java
> +        reservationTimeDao.delete(id);
이거 처리가 안되어 있는것 같습니다!

2024-04-27 03:48 UTC, HoeSeong123 commented on src/main/java/roomescape/controller/ReservationController.java
> +        return ResponseEntity.ok(reservationService.findById(saveId));
생각해보니 그렇네요..괜한 생각이었던 것 같습니다😅

2024-04-27 06:28 UTC, HoeSeong123 commented
안녕하세요 영이!
리뷰를 꼼꼼하게 반영하지 않아서 정말 죄송합니다😭

그런데 이번 리뷰를 반영하던 중에 궁금한 부분이 생겨서 질문드립니다.

저번 리뷰 요청 때 에러를 처리하는 것에 대한 질문을 드렸었는데 영이가 이런 [답변](https://github.com/woowacourse/spring-roomescape-admin/pull/107#discussion_r1578679074)을 주셨었습니다.
그래서 `delete`나 `queryForObject` 등에서 발생할만한 에러를 throw 까지만 하고 별도의 처리는 진행하지 않았습니다.
혹시 에러에 대한 처리를 진행해야 하는 건가요?
또한 저번에도 질문드렸지만 만약 처리해야 한다면 어떤 식으로 처리해야 하나요..?😥

2024-04-27 09:30 UTC, choijy1705 requested changes
초롱 반영잘해주셨습니다👍
에러 처리에 관한 부분은 제가 생각한 방향과 조금 다른것 같아서 추가적인 피드백 남겼어요!
한번 확인해보시고 고민해보시면 좋을것 같습니다!

2024-04-27 09:30 UTC, choijy1705 commented on src/main/java/roomescape/service/ReservationTimeService.java
> +                .map(reservationTime -> reservationTime.toDto())
```suggestion
                .map(ReservationTime::toDto)
```
람다 활용해주세요!

2024-04-27 09:30 UTC, choijy1705 commented on src/main/java/roomescape/service/ReservationTimeService.java
> +        reservationTimeDao.delete(id);
제가 설명이 모호했군요!
우선 DataIntegrityViolationException 은 runtimeException을 상속하고 있는 uncheckedException입니다
명시적으로 throws 를 표시할 필요가 없는 에러라서 지금 이렇게 처리하여도 기존과 별차이가 없을것 같아요!

제가 기대했던거는 DB에서의 에러가 아닌 애플리케이션 레벨에서의 에러처리를 기대한 것입니다!
DB에서 터지는 에러는 어떤 에러가 날지 쉽게 예측할 수 없고 의도치 않은 에러가 발생할 수도 있습니다.
따라서 애플리케이션 레벨에서 에러를 내도록 처리하고 어떤 경우에 에러가 나는지를 명확하게 보여줄 수 있도록 처리하는 것을 기대하였습니다🙏
```suggestion
    public void delete(long id) {
        List<Reservation> reservations = reservationService.findByTimeId();
        
        if (!reservations.isEmpty()) { // reservationTime으로 reservation 조회시 있는지 체크
            throw new IllegalArgumentException("에러 메세지 설명");
        }
        
        reservationTimeDao.delete(id);
    }
```
예시코드를 보시고 지금 방식과 어떤 차이가 있을지 생각해보면 좋고 반영해보면 좋을것 같아요!

2024-04-27 09:30 UTC, choijy1705 commented on src/main/java/roomescape/dao/ReservationDao.java
> +    public void delete(Long id) throws DataIntegrityViolationException {
```suggestion
    public void delete(Long id) {
```
runtimeException이기 때문에 굳이 이렇게 처리할 필요 없을것 같아요
checked와 unchecked exception에 대해 학습해보는것도 좋을것 같네요!

2024-04-27 09:30 UTC, choijy1705 commented on src/main/java/roomescape/service/ReservationService.java
> +                .map(reservation -> reservation.toDto())
여기도 람다 이용을 해보면 좋을것 같습니다

2024-04-27 09:30 UTC, choijy1705 commented on src/main/java/roomescape/dao/ReservationDao.java
> +        return findById(saveId);
이전에 controller에서 save후 find 하는 로직에 대한 부분이 이전 리뷰를 의미했습니다!
지금은 반영된것 같네요!👍

2024-04-27 09:30 UTC, choijy1705 commented on src/main/java/roomescape/dao/ReservationTimeDao.java
> +                }, timeId);
```java
    public ReservationTime findById(Long timeId) {
        try {
            String sql = "select id, start_at from reservation_time where id = ?";
            return jdbcTemplate.queryForObject(
                sql,
                (resultSet, rowNum) -> {
                    ReservationTime reservationTime = new ReservationTime(
                        resultSet.getLong("id"),
                        resultSet.getTime("start_at")
                            .toLocalTime());
                    return reservationTime;
                }, timeId);
        } catch (DataAccessException e) {
            throw new RuntimeException("에러 메세지");
        }
    }
```
이런 부분도 메서드 명 옆에 throws를 남기는 걸 기대한것이 아니라
catch하여 어떤 에러인지 알 수 있도록 변환해주는 과정을 기대한것입니다!
원하는 에러로 바꿀 수 있어야 다음 단계에서 에러 핸들링 과정을 학습하시면서 좀 더 쉽게 처리할 수 있을것 같네요🙏

2024-04-28 01:08 UTC, HoeSeong123 commented
안녕하세요 영이!
전부 레벨 1 때 배웠던 내용들인데 제가 스프링은 뭔가 다를 거라고 생각해서 계속 핀트를 놓쳤던 것 같네요
많이 부끄럽습니다😂😂
다시 한 번 자세하게 설명해주셔서 감사합니다!!

2024-04-28 01:19 UTC, choijy1705 approved these changes
초롱 마지막까지 리뷰 반영 고생하셨습니다👍
이번 미션은 여기서 머지할께요!

2024-04-28 01:19 UTC, choijy1705 commented on src/main/java/roomescape/domain/Reservation.java
> +            throw new NullPointerException();
에러 메세지를 통해서 나중에 어디서 에러 났을지 디버깅 하기 좋게 에러를 내면 좋겠네요!

2024-04-28 01:20 UTC, merged