[4 - 9단계 - 방탈출 예약 관리] 비토(오상훈) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #115
Opened 2024-04-22 13:18 UTC by jhon3242

안녕하세요 제이미~~🙋‍♂️
타칸입니다!! 😁

4~9 단계 미션을 구현해서 리뷰 요청드립니다!!
이번에도 잘 부탁드립니다~🙇‍♂️

## DTO를 사용
이번에 미션을 진행하면서 도메인 객체는 비즈니스 로직을 활용하는 부분에서만 가지고 있는게 맞다고 생각이 들었어요 그래서 DTO 를 활용했었습니다!
<img width="937" alt="image" src="https://github.com/woowacourse/spring-roomescape-admin/assets/78288539/2becb60d-3f6b-4622-bdaf-44afba3d90d0">

클라이언트와 컨트롤러 사이에서도 DTO 를 활용했었고, Controller 와 Repository 사이에서도 DTO 를 활용했었어요!
클라이언트와 컨트롤러 사이의 DTO 는 ResponseXXX, RequestXXX 와 같은 네이밍을 사용해준 반면에,
Controller 와 Repository 사이에서도 DTO 는 XXXDto 와 같은 네이밍을 사용해주어서 둘을 구분해주려는 의도를 조금 담아봤습니다~😅

맨 처음에는 요청을 받는 DTO, 요청에 응답하는 DTO 단 두가지의 DTO 만을 정의해두고 모든 요청 흐름에서 사용했었어요
(RequestDto 를 `클라이언트 -> 컨트롤러 -> Repository` 사이에서 사용)
그런데 이러면 Dto 의 의존성이 올라가게 되는 것 같았어요. 그래서 각 계층 사이에 별도의 DTO 를 사용하도록 해주었습니다!

2024-04-22 13:25 UTC, jhon3242 commented on src/test/java/roomescape/reservations/ApiTest.java
> +public class ApiTest {
DirtiesContext 를 사용하고 BEFORE_EACH_TEST_METHOD 옵션을 사용하게 되면 테스트 실행 전에 DB 가 초기화 되더라고요~
반대로 말하면 테스트가 실행된 이후의 작업은 여전히 DB에 반영이 되는 문제가 있었어요! (물론 실행 전에 DB가 초기화되긴 하지만요)
그래서 테스트 이후에 DB 가 초기화되도록 AFTER_EACH_TEST_METHOD 옵션을 사용했습니다!😁

2024-04-22 16:07 UTC, jamie9504 requested changes
안녕하세요, 타칸 😄 리뷰어 제이미입니다.

간단한 코멘트 조금 남겼습니다.

오늘도 즐거운 하루 보내세요!

2024-04-22 16:07 UTC, jamie9504 commented on README.md
>  ## step3
> 이번에 미션을 진행하면서 도메인 객체는 비즈니스 로직을 활용하는 부분에서만 가지고 있는게 맞다고 생각이 들었어요 그래서 DTO 를 활용했었습니다!
>
> 클라이언트와 컨트롤러 사이에서도 DTO 를 활용했었고, Controller 와 Repository 사이에서도 DTO 를 활용했었어요!
> 클라이언트와 컨트롤러 사이의 DTO 는 ResponseXXX, RequestXXX 와 같은 네이밍을 사용해준 반면에,
> Controller 와 Repository 사이에서도 DTO 는 XXXDto 와 같은 네이밍을 사용해주어서 둘을 구분해주려는 의도를 조금 담아봤습니다~😅
> 
> 맨 처음에는 요청을 받는 DTO, 요청에 응답하는 DTO 단 두가지의 DTO 만을 정의해두고 모든 요청 흐름에서 사용했었어요
> (RequestDto 를 클라이언트 -> 컨트롤러 -> Repository 사이에서 사용)
> 그런데 이러면 Dto 의 의존성이 올라가게 되는 것 같았어요. 그래서 각 계층 사이에 별도의 DTO 를 사용하도록 해주었습니다!

네이밍은 Prefix와 Postfix가 섞여있네요 😃 
(이번 미션에선 중요하지 않지만요.)

도메인 객체가 비즈니스 로직을 활용하는 부분 외에 존재한다면 어떤 위험성이 있나요?
현재 1개의 도메인 객체에 몇 개의 DTO가 생성되었나요?

DTO를 사용하지 않는 것, 사용하는 것, 어느 부분에만 사용하는 것 모두 장/단점을 고려해보면 좋겠네요!

2024-04-23 11:55 UTC, jhon3242 reviewed
안녕하세요 제이미~~ 타칸입니다!😁

질문해주신 부분에 대해서 고민을 해보고 저만의 결론을 내려봤어요!
제 결론의 오류가 있거나 첨언해주실 수 있는 부분에 대해서 말씀해주시면 정말 감사하겠습니다!🙇‍♂️

2024-04-23 11:55 UTC, jhon3242 commented on src/main/java/roomescape/reservations/ReservationRepository.java
> +        jdbcTemplate.update(SQL, id);
의도한 것은 아니였습니다..😅
하지만 리뷰요청을 보낸 이후에 이 부분에 대해서 이미 크루들과 토론을 해왔었고 결론적으로 200을 반환하는게 맞다고 판단되었습니다!

크게 200와 404 응답 코드 중에서 어떤 응답 코드를 반환할지에 대해서 고민해왔어요.

저는 상황에 따라서 다르게 선택할 것 같아요. 
만약 유저가 의도해서 잘못된 삭제 요청을 보낼 수 있는 경우(특정 id와 함께 삭제 요청을 보낼 수 있는 상황 등)에는 404를 반환할 것 같아요.

반면에 유저가 의도하지 않고 잘못된 삭제 요청을 보낼 수 있는 경우(이미 삭제 버튼을 눌렀는데 모르고 두번 누른 경우)에는 200를 반환할 것 같아요.

지금 상황에서는 의도하지 않고 잘못된 삭제 요청을 보낼 가능성이 더 높은 상황인 것 같아요. 클라이언트가 postman 등을 사용하여 의도적으로 잘못된 삭제 요청을 보낼 경우보다, 삭제 요청이 처리되기 전에 삭제 버튼을 여러번 누르는 상황이 더 많이 일어날 것이라고 판단되었습니다! 그래서 200을 반환하는게 맞다고 판단되었습니다!

실제 실무에서는 상황에 맞게 그리고 팀 컨벤션에 맞게 어떤 코드를 반환할지 결정해서 사용하면 될 것 같아요!😁

2024-04-23 11:55 UTC, jhon3242 commented on src/main/java/roomescape/reservations/ReservationsController.java
> +    @ResponseBody
`@ResetController` 는 `@ResponseBody` 와 `@Controller` 가 합쳐진 애노테이션으로 모든 reqeust handling 메서드에 `@ResponseBody` 를 써주는 작업을 생략할 수 있어요! 따라서 RESTful Controller 를 간단하게 선언해줄 수 있죠! ([참고한 링크](https://www.baeldung.com/spring-controller-vs-restcontroller))
(이 외의 추가적인 기능을 하는지는 제가 찾아본 선에서는 보이지 않았어요)

결국 핵심은 `@ResponseBody` 와 `@Controller` 인데 `@Controller`는 지금 학습하기엔 조금 이르다는 판단이 되어서 시간이 되면 찾아보겠습니다!

`@ResponseBody` 는 ResponseEntity 와 무엇이 다른지에 대해서 크루들과 정말 많이 토론을 해왔었어요🫠
여러가지 차이점이 있겠지만 결국 핵심은 **헤더를 조작해줄 수 있는지**의 차이인 것 같아요.

`@ResponseBody` 만 사용했을 때는 응답코드가 200으로 고정되고(물론 `@ResponseStatus` 를 사용해서 바꿔줄 수 있습니다) 반환하는 값을 HTTP 응답 메시지 바디에 넣어줍니다!

반면에 ResponseEntity 는 바디에 원하는 데이터를 넣어줄 수 있는 것은 물론이고 추가적인 헤더에 대해서 유연하게 응답해 줄 수 있다는 차이점이 있는 것 같아요! 헤더에 응답 코드뿐만 아니라 URL도 넣어줄 수 있고 Content-Type 등도 설정해줄 수 있죠.

### 그래서 어떤 방식을 사용할까??
제 스스로 내린 결론은 기본적으로 `@ResponseBody` 나 `@RestControler` 와 함께 `@ReseponseStatus` 를 사용하고, 추가적인 헤더의 조작이 필요한 경우에만 `ResponseEntity` 를 반환하자고 결론을 내렸습니다.
이러면 ResponseEntity 를 사용하는 사용하는 부분을 보면 "_아 무언가 헤더를 의도적으로 조작하고 있구나_" 라는 의도를 전달할 수 있기 때문에 이 같은 결론을 내렸습니다! 😊

물론 하나의 방식을 사용해서 통일성을 지키는 것도 좋은 것 같아요! 그런데 아직까지는 저한테는 의도를 전달하는 것이 더 중요하게 느껴지는 것 같습니다!

2024-04-23 11:55 UTC, jhon3242 commented on src/main/java/roomescape/reservations/ReservationsController.java
> +    }
네! 아직까지는 Service 계층의 필요성이 크게 느껴지지 않았어요😅 (비즈니스 로직이 있다고 느껴지지 않았어요)
컨트롤러에서 직접적으로 비즈니스 로직을 사용해야하는 경우가 발생되면 그때 Service 계층을 만들어주면서 컨트롤러가 도메인을 모르도록 구현해주겠습니다! 😁

2024-04-24 16:35 UTC, jamie9504 commented on README.md
> +
// todo

2024-04-24 16:35 UTC, jamie9504 commented on src/main/java/roomescape/domain/Reservation.java
> +package roomescape.domain;
// todo

2024-04-24 16:36 UTC, jamie9504 commented on src/main/java/roomescape/domain/Reservation.java
> +package roomescape.domain;
// todo

2024-04-24 16:58 UTC, jamie9504 requested changes
안녕하세요, 타칸 😄 리뷰어 제이미입니다.

리뷰가 조금 늦어진 부분 죄송합니다 😢 

코멘트 반영해주시면서 10단계 같이 반영해주시면 될 것 같습니다. 😉 
오늘도 좋은 하루 보내세요!

2024-04-24 16:58 UTC, jamie9504 commented on src/main/java/roomescape/domain/Reservation.java
> +package roomescape.domain;
패키지가 익숙하지 않다면 폴더(디렉터리) 개념으로 사용해봐도 좋습니다.

바탕화면에 타칸이 폴더를 정리해놨다고 가정할 때, 일정한 기준으로 폴더를 정리해놓는 것이 구분이 편할지
이런 저런 기준대로 폴더를 정리해놓는 것이 구분이 편할지 고민해보면 좋겠네요 😃 

결국 타칸이 정리한 폴더를 다른 사람들도 보고 폴더 내에 뭐가 위치할지 짐작을 해봐야 하는 것이니까요!

2024-04-24 16:58 UTC, jamie9504 commented on src/main/java/roomescape/reservations/ReservationRepository.java
> +        jdbcTemplate.update(SQL, id);
이러한 코멘트를 남긴 부분이 있었는데요!
> HttpStatus 200번대에 대해 알아보세요!

실제로 (ID가 존재할 때) DELETE할 때는 취향에 따라 200번대의 코드 중 어떤 것을 내려줄지에 대한 의견이 분분합니다.
400번대와 고민하지 말고, 200번대끼리 고민해보는 것도 좋겠네요 😄

2024-04-24 16:58 UTC, jamie9504 commented on src/main/java/roomescape/reservations/ReservationsController.java
> +    @ResponseBody
의도를 전달하는 방식으로 기준을 잡고 프로그래밍 한다면, 그 역시 일관성을 가져갈 수 있다고 생각합니다 😃

2024-04-24 16:58 UTC, jamie9504 commented on README.md
>  ## step3
이 부분도 개인의 취향에 따라 달라질 수 있고, 협업 컨벤션에 따라 달라질 수 있지만
타칸이 위에 적어주었던 부분을 고려할 수도 있구요.
-> 도메인 혹은 DTO가 해당 레이어에 위치했을 때 영향을 줄 수 있는가 / 영향을 주었을 때 문제가 되는가

아니면 변경 가능성에 대한 부분을 고려할 수도 있겠죠!
-> 도메인은 변경되지 않는데 전달해야 하는 데이터가 계속 바뀔 수 있는가 / 이는 도메인에 영향을 줘도 되는가

또는 도메인의 정보를 전체 공개하는게 문제가 되는가도 고민해볼 수 있겠네요.
-> 데이터를 다 내려주는 것은 과연 비싼 리소스일까? (일부 필드를 제외하는 것) / 비싼 리소스가 아니라고 가정할 때는 필요하지 않은 필드를 모두 내려줘도 되는가?

그리고 Layer에 대한 고민을 해보는 것도 좋을 것 같네요.
Controller는 어떠한 역할을 하는 Layer인가? (마찬가지로 Service, Repository, ... etc)

위 부분을 고민해보고도 타칸의 의견이 동일하다면 그대로 가시면 된다고 생각합니다 😃 
이런 저런 부분을 고민하고 결정한다면, 만일 협업 컨벤션이 이와 다르더라도 설득을 해볼 수도 있고 그 컨벤션을 따를 수도 있게 된다고 생각하거든요 😆

2024-04-24 16:58 UTC, jamie9504 commented on src/main/java/roomescape/controller/ReservationsController.java
> +    @Autowired
`@Autowired`와 생성자 주입에 대해 알아보세요!

2024-04-24 16:58 UTC, jamie9504 commented on src/main/java/roomescape/controller/ReservationsController.java
> +    public int deleteReservation(@PathVariable Long id) {
오 이 친구는 ResponseBody를 사용하지 않은 이유가 있나요 ?!

DELETE Http Method로 요청시 200을 응답하는 경우, 바디에 보통 어떤 것을 담아주는지 알아봐도 좋을 것 같아요~!

2024-04-24 16:58 UTC, jamie9504 commented on src/main/java/roomescape/controller/TimesController.java
> +    @ResponseBody
> 제 스스로 내린 결론은 기본적으로 @ResponseBody 나 @RestControler 와 함께 @ReseponseStatus 를 사용하고, 추가적인 헤더의 조작이 필요한 경우에만 ResponseEntity 를 반환하자고 결론을 내렸습니다.

이 컨트롤러 같은 경우 `@ResponseBody`가 전체 메서드에 사용되고 있죠!
이런 경우엔 `@RestController`를 사용해보는 것도 좋겠네요.

2024-04-24 16:58 UTC, jamie9504 commented on src/main/java/roomescape/repository/ReservationRepository.java
> +        );
람다식은 계속 동일한 친구겠죠? 이 친구는 반복해서 생성할 필요는 없을 것 같네요 😃

2024-04-25 08:14 UTC, jhon3242 reviewed
10단계 구현 후 리뷰요청하겠습니다!😁

2024-04-25 08:14 UTC, jhon3242 commented on src/main/java/roomescape/reservations/ReservationRepository.java
> +        jdbcTemplate.update(SQL, id);
200번과 204번 사이에도 크루들과 토론을 했었습니다!(ㅎㅎ 이 부분에 대한 설명을 빠트렸네요!😅)

200을 반환해야 한다는 입장은 서버에 삭제 요청을 보내서 처리된 삭제 행의 개수(삭제된 데이터의 개수) 를 반환하는 것이 유저 친화적으로 더 좋을 것이고 프론트 입장에서도 처리하기 더 편할 것이기 때문에 200을 반환해야한다. 라는 의견입니다!

반면에 204를 반환해야한다는 입장에서는 서버에서는 단지 요청을 받고 처리하면 된다. 서버는 잘못된 ID 를 보내도 어쨌든 쿼리문을 수행할 것 이기에 응답 결과는 항상 성공일 것이다. 따라서 프론트에서 받을 데이터의 차이가 없기 때문에 응답으로 Body로 넘겨줄 것이 없다. 라는 의견입니다.

저의 의견은 200쪽에 더 가까운 것 같아요! 그래서 200을 반환하고 Body안에 삭제된 행의 개수를 넣어주었습니다!.
하지만 단지 저의 의견일 뿐, 팀 컨벤션과 상황에 따라서 선택할 것 같아요!

제이미는 200 과 204 사이에서 어떤 선택을 하실지 궁금하네요 ㅎㅎ

2024-04-29 03:53 UTC, jamie9504 requested changes
안녕하세요, 타칸 😄 리뷰어 제이미입니다.

코멘트 조금 더 남겨두었습니다 😉 

다음번엔 이슈가 없다면, Approve & Merge 예정입니다.
오늘도 좋은 하루 보내세요!

2024-04-29 03:53 UTC, jamie9504 commented on src/main/java/roomescape/ConsoleRoomescapeApplication.java
> +        ConsoleMainController controller = new ConsoleMainController(new InputView(), new OutputView(), new RoomescapeService(new MemoryReservationRepository(), new MemoryReservationTimeRepository())
모든 의존성을 Application에서 주입하고 있는데요!
전부 다 주입해주는 방식이 좋은 방식일까요?

2024-04-29 03:53 UTC, jamie9504 commented on src/main/java/roomescape/controller/ConsoleMainController.java
> +public class ConsoleMainController {
view쪽의 패키지와 클래스명, 그리고 controller쪽의 패키지와 클래스명의 일관성이 조금 없네요!

2024-04-29 03:53 UTC, jamie9504 commented on src/main/java/roomescape/controller/ConsoleMainController.java
> +    public void run() {
StackTrace를 사용자에게 노출하는 것이 좋은 방식일까요?

<img width="860" alt="image" src="https://github.com/woowacourse/spring-roomescape-admin/assets/59511689/af200fbd-5ce4-4580-924a-2fde4e1881e4">

---

시간은 이렇게 저장되어도 되는걸까요?

<img width="221" alt="image" src="https://github.com/woowacourse/spring-roomescape-admin/assets/59511689/f14ed0ac-04ba-4293-a094-b8aa08c10c0e">

2024-04-29 03:53 UTC, jamie9504 commented on src/main/java/roomescape/controller/ReservationsController.java
> +    @ResponseStatus(HttpStatus.OK)
`@ResponseStatus(HttpStatus.OK)`를 생략하면 어떤 응답이 나가게 될까요?

2024-04-29 03:53 UTC, jamie9504 commented on src/main/java/roomescape/dto/ReservationTimeDto.java
> +public record ReservationTimeDto(Long id, String startAt) {
이 친구는 `Repository`라는 이름이 들어가지 않은 이유가 있나요?

2024-04-29 03:53 UTC, jamie9504 commented on src/main/java/roomescape/repository/entity/ReservationEntity.java
> +package roomescape.repository.entity;
Entity와 Domain은 어떤 차이가 있나요?
나누어주었을 때 어떤 장/단점이 있었을까요?

2024-04-29 03:53 UTC, jamie9504 commented on README.md
>  - [X] : 예약 취소 API 구현한다.
> 리뷰요청이 조금 많이 늦었습니다. 죄송해요!😅
> 이번 주에 정보처리기사 시험이 있어서 시험 끝나고 10단계를 구현하느라 조금 오래걸렸네요..

시험 고생 많으셨네요!
리뷰요청은 마감기간 이내라면, 언제하셔도 상관없으니 죄송할 일이 아닙니다 😃 

> 처음부터 확장 가능하게 설계했다면 더 빠르게 구현할 수 있었겠지만, 저는 "필요성이 느껴지기 전까지는 하지 말자 생각을 가지고 있어요. 아직 제 생각이 잘못되었다는 생각은 들지 않기 때문에 유지해 보면서 나가보겠습니다!

좋습니다. 2레벨을 진행하다보면, 어디까지가 처음부터 확장을 고려하고 짜도 무관하고, 어디부터는 추후 필요하면 만드는 것이 나을지 타칸만의 기준이 생길 것 같네요! 😉

2024-04-29 08:54 UTC, jhon3242 reviewed
안녕하세요 제이미~ 타칸입니다! 😁
피드백 주신 부분에 대해서 반영했습니다!
좋은 저녁 보내세요~~😊

2024-04-29 08:54 UTC, jhon3242 commented on src/main/java/roomescape/repository/entity/ReservationEntity.java
> +package roomescape.repository.entity;
Entity 는 비즈니스 로직을 가지고 있지 않지만 Domain 은 비즈니스 로직을 가질 가능성이 높다는 차이점이 있을 것 같아요!
따라서 도메인의 사용 범위를 서비스 계층으로 한정시켜주어서 Repository 에서는 비즈니스 로직을 실행시킬 가능성을 배제할 수 있어요!  또한 Entity의 경우 ID 필드값을 가지고 있기만, Domain 은 ID 필드값을 가지고 있을 필요성이 없죠.

반면의 단점으로 별도의 객체가 생기고 변환을 해주는 로직이 추가되면서 코드의 복잡성이 올라갈 수 있겠죠. 따라서 필요성이 느껴지지 않는다면 굳이 Entity 를 사용할 필요성은 없는 것 같아요!

2024-04-30 07:09 UTC, jamie9504 approved these changes
안녕하세요, 타칸 😄 리뷰어 제이미입니다.

이번 PR 별다른 이슈 보이지 않아 Approve & Merge 합니다.
코멘트는 조금 남겨두었으니 가볍게 읽어보세요!

다음 미션도 즐겁게 진행하시길 바랍니다 😄

2024-04-30 07:09 UTC, jamie9504 commented on src/main/java/roomescape/controller/ReservationsController.java
> +    public int deleteReservation(@PathVariable Long id) {
좋습니다! 👍
DB의 경우엔 의존은 하고 있을 수 밖에 없지만, DB의 구조가 달라질 때마다 행의 개수를 수정한다던가의 행위는 번거롭기도 하고, 놓치기도 쉬운 포인트가 됩니다.
이런 부분에 대해서는 주의 깊게 고민해보면 좋습니다 😉

2024-04-30 07:09 UTC, jamie9504 commented on src/main/java/roomescape/ConsoleRoomescapeApplication.java
> +        ConsoleMainController controller = new ConsoleMainController(new InputView(), new OutputView(), new RoomescapeService(new MemoryReservationRepository(), new MemoryReservationTimeRepository())
알아도 상관은 없겠지만, Application이 알아야하는 부분, Controller가 알아야하는 부분 ... etc에 대한 구분을 해보는 것도 좋고
의존성을 관리해주는 객체를 생성해보는 것도 좋죠

모두 틀린 방식이 아닌 다른 방식임을 유념하며 장/단점을 비교해서 좋은 방향을 선택하도록 해요 😉

2024-04-30 07:09 UTC, jamie9504 commented on src/main/java/roomescape/repository/entity/ReservationEntity.java
> +package roomescape.repository.entity;
맞습니다. 나눈다면 어떤 기준으로 나누는 것이 좋을지 (얼마나 객체가 커진다던가, ... etc)
나누지 않는다면 Domain이라고 불러야 할지 Entity라고 불러야 할지 등에 대한 고민도 해보면 재밌겠네요 😃

2024-04-30 07:09 UTC, jamie9504 commented on src/main/java/roomescape/console/view/ConsoleInputView.java
> +package roomescape.console.view;
view가 console 패키지 안에 들어있어야 할까요? 패키지를 나누는 기준을 조금 더 일관성있게 가져가봅시다!

2024-04-30 07:09 UTC, jamie9504 commented on src/main/java/roomescape/ConsoleRoomescapeApplication.java
> +        ConsoleController controller = ConsoleAppConfig.consoleMainController();
Console의 경우 Memory에 저장하는 부분이다보니, 잘못 입력했을 때 프로그램을 종료해버린다면 데이터가 다 날아가겠죠? 😃

2024-04-30 07:09 UTC, merged