[4 - 9단계 - 방탈출 예약 관리] 리브(김민주) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #116
Opened 2024-04-22 15:40 UTC by Minjoo522

안녕하세요, 피케이!
리브입니다. 😊

4 - 9 단계 구현 완료하여 PR 보냅니다!
처음 접하는 스프링 프레임워크에 익숙해지는 것이 이번 미션의 가장 중요한 목표라고 생각하여 요구사항을 벗어나지 않는 범위 내에서 구현하려고 노력하였습니다!
리뷰 잘 부탁드립니다. 😆

---

이전 PR에서 코멘트 주신 부분에 대한 생각은 아래 작성하였습니다!

> @SpringBootTest 에는 DEFINED_PORT 와 RANDOM_PORT 말고도 옵션이 더 있는 것으로 알고 있는데 이들은 고려사항에 없었나요?

![스크린샷 2024-04-23 오전 12 23 09](https://github.com/woowacourse/spring-roomescape-admin/assets/131349867/a6fc4f20-50a3-4719-8bad-07ff5444328c)

`WebEnvironment` 옵션에는 위와 같이 네 종류가 있는데, `MOCK`과 `NONE`은 실제 톰캣을 구동시키지 않기 때문에 통합 테스트 성격을 가진 `RestAssured`와 맞지 않는다고 생각하여 고려하지 않았습니다.

2024-04-23 18:18 UTC, pkeugine requested changes
안녕하세요 리브!
미션 잘 진행해주셨네요.
몇 가지 질문 남겼으니 한 번 확인해주세요.
어떤 질문은 조금 추상적으로 남기기도 했는데요,
이해가 안간다 싶으면 언제든지 DM 보내주세요 :)
파이팅입니다!!

2024-04-23 18:18 UTC, pkeugine commented on src/main/java/roomescape/repository/JdbcTemplateReservationTimeRepository.java
> +    }
repository 에서 예외를 던진 뒤에 service 에서 이를 이용하여 true / false 판단을 하는데요,
예외를 이용하여 로직을 처리하는 이유가 궁금해요.

2024-04-23 18:18 UTC, pkeugine commented on src/main/java/roomescape/repository/JdbcTemplateReservationTimeRepository.java
> +    }
save 를 하고 난 뒤, 저장된 정보를 return 하는 방식이 `Reservation` 과 `ReservationTime` 이 서로 다른 이유가 궁금합니다!

2024-04-23 18:18 UTC, pkeugine commented on src/main/java/roomescape/controller/ReservationController.java
> +        return ResponseEntity.notFound().build();
그냥 재미삼아 생각해볼 거리를 던져볼게요.
Reservation 을 삭제하는 api 는 삭제하고자 하는 Reservation 이 없을 때 그 사실을 요청한 사람에게 알려줘야할까요?
없다면 이미 삭제된 것이나 마찬가지이기 때문에 그냥 성공했다고 알려줄수도 있으니까요 🤔

2024-04-23 18:18 UTC, pkeugine commented on src/main/java/roomescape/repository/JdbcTemplateReservationRepository.java
> +                """
multi line string 👍

2024-04-23 18:18 UTC, pkeugine commented on src/main/java/roomescape/repository/JdbcTemplateReservationRepository.java
> +                            t.start_at as time_value
AS 도 다른 키워드처럼 대문자로 바꿔볼까요? :)

2024-04-23 18:18 UTC, pkeugine commented on src/main/java/roomescape/dto/ReservationDto.java
> +public record ReservationDto(Long id, String name, LocalDate date, ReservationTimeDto time) {
DTO 이름을 짓는 방식을 통일시켜보면 어떨까요?
`ReservationRequest` 도 결국 DTO 인데, DTO 라는 명칭이 어떤 클래스에만 있다보니 누군가는 헷갈려 할 수도 있거든요.

2024-04-23 18:18 UTC, pkeugine commented on README.md
> +
> MOCK과 NONE은 실제 톰캣을 구동시키지 않기 때문에 통합 테스트 성격을 가진 RestAssured와 맞지 않는다고 생각하여 고려하지 않았습니다.

👍 👍

2024-04-24 05:27 UTC, Minjoo522 commented on src/main/java/roomescape/repository/JdbcTemplateReservationTimeRepository.java
> +    }
처음에는 동일했다가 나중에 DB 스키마가 변경되고 `Reservation`을 만들 때 `ReservationTime`도 찾아야 했기 때문에 `ReservationRepository`에 `findById` 메서드를 만들게 되었습니다.
그리고 `ReservationTime`도 동일하게 변경해야겠다는 생각을 못했습니다. 😅
두 repository가 다른 방식으로 정보를 return하면 다른 개발자로하여금 의문을 불러올 수 있다고 생각하여 통일해주었습니다!

2024-04-24 05:29 UTC, Minjoo522 commented on src/main/java/roomescape/repository/JdbcTemplateReservationRepository.java
> +                            t.start_at as time_value
변경하였습니다! 😆

2024-04-24 05:29 UTC, Minjoo522 commented on src/main/java/roomescape/dto/ReservationDto.java
> +public record ReservationDto(Long id, String name, LocalDate date, ReservationTimeDto time) {
`ReservationDto` ➡️ `ReservationResponse`
`ReservationTimeDto` ➡️ `ReservationTimeResponse`로 변경하였습니다! 😊

2024-04-24 05:30 UTC, Minjoo522 commented on src/main/java/roomescape/controller/ReservationTimeController.java
> +    public ResponseEntity<Void> deleteReservationTime(@PathVariable(value = "id") Long id) {
감사합니다! ☺️

2024-04-24 05:31 UTC, Minjoo522 commented on src/main/java/roomescape/domain/time/ReservationTime.java
> +    }
캠퍼스 내에서 "빌드 툴에 따라 기본 생성자 필요 여부가 다르다"는 것에 대한 크루들의 논의가 있었습니다.
그래서 저도 테스트해보다가 지우는 걸 잊고 말았습니다... 😅

2024-04-24 05:34 UTC, Minjoo522 commented on src/main/java/roomescape/dto/ReservationTimeDto.java
> +                reservationTime.getStartAt().format(DATE_TIME_FORMATTER));
피케이가 추측하신 게 정확히 맞습니다! 😅
줄의 길이를 유지하는 방식으로 줄바꿈을 하고 있었지만 피케이가 말씀 주신 서로 다른 요소를 분리하는 방식으로 해보니 훨씬 가독성이 좋아져서 반영해보았습니다!
감사합니다. 😆

2024-04-25 00:50 UTC, Minjoo522 commented on src/main/java/roomescape/domain/time/ReservationTime.java
> +package roomescape.domain.time;
LMS 미션 순서를 위에서부터 따라가면서 `Reservation`과 크게 관련 없는 도메인이 생기는줄 착각하고 분리 했었습니다. 😅
다시 변경하면서 패키지를 이동해야겠다는 생각을 못했던 것 같아요.
`Reservation`과 `ReservationTime` 같은 패키지로 옮겼습니다!

2024-04-25 00:51 UTC, Minjoo522 commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +class ReservationControllerTest {
컨트롤러 테스트라기보다는 통합테스트에 가깝다고 생각해 `ReservationFlowTest`로 변경하였습니다.

2024-04-25 01:01 UTC, Minjoo522 commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +    }
사실 이 테스트 코드는 LMS에서 주어진 테스트 코드입니다!
저는 데이터 베이스에 `reservation` 테이블이 생성되는지 확인하는 테스트 코드가 굳이 필요하지 않다고 생각합니다.
데이터 베이스 테이블을 한 번 만들고나면 변경되는 일이 많지 않기 때문에 굳이 테스트 코드를 작성해서 확인해야한다고 생각하지 않기 때문입니다.
하지만 스프링이 처음이기 때문에 우선 미션에 주어진 것을 충실하게 따라보겠다는 것을 목표로 진행을 했습니다.

피케이의 리뷰를 보며 이번 미션에 너무 수동적으로 임하지는 않았나 반성하기도 했습니다.😅
그래서 LMS에 있더라도 필요 없다고 생각하는 코드는 과감하게 삭제하거나 변경해야겠다고 생각했고 이 테스트 코드도 삭제했습니다!

2024-04-25 01:43 UTC, Minjoo522 commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +        }
사실 이 테스트 코드도 LMS에 있었던 테스트 코드입니다...😅
이 테스트 코드도 굳이 필요 없다고 생각해서 삭제했습니다!

2024-04-25 01:48 UTC, Minjoo522 commented on src/main/java/roomescape/controller/ReservationController.java
> +        return ResponseEntity.notFound().build();
이 부분은 클라이언트의 요구사항에 따라 다를 것 같다고 생각합니다.
이번 미션에서 관련하여 구체적인 요구사항까지는 명시되지 않아서 제 나름대로 해보았습니다. 😅
여러 사이트들을 이용해 봤을 때 `삭제` 버튼을 여러번 클릭하는 경우 삭제 되었다고 명확히 알려주는 것이 더 편리하다고 느껴서 삭제하고자하는 `Reservation`이 없을 때 알려주도록 설계했습니다.

2024-04-25 01:57 UTC, Minjoo522 commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +                dynamicTest("예약을 생성한다.", () -> {
예약 생성 시 생성한 데이터를 삭제 테스트 코드에서 재사용할 수 있어서 편리했고, 생성 ➡️ 삭제 서비스 흐름을 테스트 할 수 있어서 `dynamicTest`를 사용했습니다.

피케이의 리뷰를 보고 다시 테스트 코드를 보니 아예 예측되는 사용자 API 이용 순서에 맞게 다이나믹 테스트를 구성하는 게 좋을 것 같다고 생각하여 `생성 ➡️ 조회 ➡️ 삭제 ➡️ 재 삭제 시도`와 같이 변경해보았습니다. 😊

2024-04-25 02:02 UTC, Minjoo522 commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +                "INSERT INTO reservation (name, date, time_id) VALUES (?, ?, ?)", "브라운", "2023-08-05", 1);
이 상황에서는 초기 데이터를 넣는 부분을 최소화하여 변경사항이 있을 때 테스트 코드 변경을 최소화 할 수 있도록 하는 것이 제일 적합할 것 같습니다. `@BeforeEach`와 같은 어노테이션을 사용할 수 있을 것 같습니다.

저는 현재 `dynamicTest`를 사용하고 있고 다른 테스트 코드들도 다이나믹 테스트 내부로 포함하여 테스트 할 수 있기 때문에 통합하고 다이나믹 테스트 상단에서 초기 데이터를 생성하도록 변경해했습니다. 😊

2024-04-25 02:07 UTC, Minjoo522 commented on src/main/java/roomescape/repository/JdbcTemplateReservationTimeRepository.java
> +    }
이미 삭제된 데이터에 대해 또 다시 삭제 시도를 하는 상황이 예외 상황이라고 판단하여 예외를 던지도록 구현했습니다.

`jdbcTemplate`의 `update` 메서드는 SQL 문에 영향을 받은 행의 수를 반환합니다.
하지만 이 반환 값 자체가 명확한 의미를 가지지 않는다고 생각하여, 예외 메시지를 통해 상황을 명확히 전달하는게 좋겠다고 판단했습니다. 😊

2024-04-25 02:09 UTC, Minjoo522 commented on src/test/java/roomescape/controller/ReservationReservationTimeControllerTest.java
> +    }
피케이의 리뷰를 보고 저도 고민해보니 굳이 마지막 절차가 필요하지 않을 것 같다는 생각이 들어 지웠습니다!

2024-04-25 02:18 UTC, Minjoo522 commented
안녕하세요 피케이 😆
리뷰 감사합니다!

처음 배우는 지식을 담는 것에 집중하느라 레벨 1의 기억을 잊고 있는 기분입니다...😅
그래서 어쩌면 이번 미션에 굉장히 수동적으로 임하고 있었던 것 같아 반성하게 됐습니다.😆

리뷰 잘 부탁 드립니다. ☺️

2024-04-26 01:20 UTC, pkeugine commented on src/main/java/roomescape/domain/time/ReservationTime.java
> +    }
그렇군요!
그 때 시도해보고 배운걸 알려주시겠어요? 🙂

2024-04-26 08:47 UTC, pkeugine approved these changes
고생하셨어요 리브!
이번 미션은 이정도면 충분히 잘 진행하셨습니다.
하지만 아직 시간이 좀 남아있으니 리뷰도 더 해볼겸 10단계 같이 진행해보도록 하죠!
추가로 남긴 리뷰는 10단계 진행하면서 적용해주세요.
남은 시간동안 파이팅해봅시다 💪 💪 💪

2024-04-26 08:47 UTC, merged