[4 - 9단계 - 방탈출 예약 관리] 테바(김성겸) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #117
Opened 2024-04-22 16:41 UTC by ksk0605

Hello 조앤! 
4-9 단계 구현이 완료되어 리뷰요청드려요 👍

한가지 간단한 질문이 있는데요!

### Controller의 이름은 뭘 기준으로?
```java
@RequestMapping("/times")
public class TimeController 
```
저는 관습적으로 Controller 이름을 요청을 처리할 baseUrl 을 기준으로 지었는데
```java
@GetMapping
public ResponseEntity<List<ReservationTime>> readTimes() {
    List<ReservationTime> reservationTimes = timeService.readAll();
    return ResponseEntity.ok(reservationTimes);
}
```
정작 도메인 네임은  ReservationTime 이라 ReservationTimeController 로 지어야하나 고민이되네요..?
조앤의 취향은 어떤가요? 현업에서 더 자주 차용하는 쪽이 있을까요?

2024-04-23 10:52 UTC, seovalue commented
Controller의 이름은 뭘 기준으로?
@RequestMapping("/times")
public class TimeController 
저는 관습적으로 Controller 이름을 요청을 처리할 baseUrl 을 기준으로 지었는데

@GetMapping
public ResponseEntity<List<ReservationTime>> readTimes() {
    List<ReservationTime> reservationTimes = timeService.readAll();
    return ResponseEntity.ok(reservationTimes);
}
정작 도메인 네임은 ReservationTime 이라 ReservationTimeController 로 지어야하나 고민이되네요..?
조앤의 취향은 어떤가요? 현업에서 더 자주 차용하는 쪽이 있을까요?


---

예를 들어 예약시간 조회 API를 코드에서 찾아야한다고 했을 때, 직관적으로 떠오르는 이름으로 짓는 것 같아요? 그게 endpoint랑도 연결되는 것 같고요?ㅎㅎ 개인적으로는 endpoint가 time보다는 reservation-time이 더 나아보이긴 해요

2024-04-23 11:27 UTC, seovalue requested changes
안녕하세요, 테바!
4-9단계 미션 잘 수행해주셨네요ㅎㅎ
코멘트 남겼는데 확인 후 다시 리뷰 요청 주세요~!~!

2024-04-23 11:27 UTC, seovalue commented on src/main/java/roomescape/service/TimeService.java
> +        reservationTimeDao.delete(id);
이미 예약이 등록된 시간에 대해서 시간 삭제를 원할 때, 이미 그 시간으로 등록된 예약이 있는지 먼저 확인해보는 것은 어떨까요?

2024-04-23 11:27 UTC, seovalue commented on src/main/java/roomescape/controller/ReservationController.java
> +    public ResponseEntity<Integer> deleteReservation(@PathVariable int id) {
Integer를 반환하는 이유는 뭐예요?

2024-04-23 11:27 UTC, seovalue commented on src/main/java/roomescape/controller/TimeController.java
> +    private final TimeService timeService;
질문주신 내용이랑도 비슷한데 범용적인 TimeService 보다는 ReservationTimeService와 같이 지어보는 건 어때요?

2024-04-23 11:27 UTC, seovalue commented on src/main/java/roomescape/controller/dto/CreateReservationResponse.java
> +    public static CreateReservationResponse from(Reservation reservation) {
Response에서 도메인을 알고 있는 것에 대해서 어떻게 생각해요?

2024-04-23 11:27 UTC, seovalue commented on src/main/java/roomescape/dao/ReservationDao.java
> +        return jdbcTemplate.update("insert into reservation (name, date, time_id) values (?, ?, ?)",
SimpleJdbcInsert, KeyHolder도 학습해보셨나요?

2024-04-23 11:27 UTC, seovalue commented on src/main/java/roomescape/dao/ReservationDao.java
> +    public Reservation read(int id) {
getReservationById 이런식으로 네이밍해보는 건 어때요?

2024-04-23 11:27 UTC, seovalue commented on src/main/java/roomescape/dao/ReservationDao.java
> +    private RowMapper<Reservation> getReservationRowMapper() {
👍

2024-04-23 11:27 UTC, seovalue commented on src/main/java/roomescape/dao/ReservationTimeDao.java
> +    public int create(CreateReservationTimeRequest request) {
create의 결과로 int가 반환됐을 때, 호출부에서 그 int가 무슨 값인지 바로 알 수 있을까요?

2024-04-23 11:27 UTC, seovalue commented on src/main/resources/schema.sql
> +
이 테이블은 제시된 구조였는데, 혹시 변경하고 싶은 부분도 있으셨나요?

2024-04-23 11:27 UTC, seovalue commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +    @Test
DisplayName 대신 메서드명을 한글로 해주신 이유가 있나요?

2024-04-23 11:27 UTC, seovalue commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +                .when().delete("/times/1")
id를 1로 고정해두지 않고 update 한 결과값의 id를 넣는건 어때요?

2024-04-23 12:10 UTC, seovalue commented on src/main/java/roomescape/dao/ReservationDao.java
> +        return jdbcTemplate.update("insert into reservation (name, date, time_id) values (?, ?, ?)",
lms 단계별로 보면 아래에 키워드 라는 섹션이 있더라고요.
요구사항과 별개로 그 키워드라는 섹션에 대해서도 따로 공부하고, 기록해두면, 언젠간 쓸모가 있을 것 같아요?ㅎㅎ

2024-04-25 06:15 UTC, ksk0605 commented on .gitignore
> +application.properties
앗 그렇군요..ㅎㅎ 수정했습니다

2024-04-25 06:31 UTC, ksk0605 commented on src/test/java/roomescape/dao/ReservationDaoTest.java
> +    void 데이터베이스에_예약_테이블이_존재하는지_확인한다() {
단계별 테스트를 습관적 복붙의 폐해네요..ㅠ
불필요한 테스트라는 생각이 들어서 삭제하였고 DAO 의 기능 테스트를 별도로 생성해주었습니다.

2024-04-25 07:13 UTC, ksk0605 commented on src/main/java/roomescape/service/TimeService.java
> +        reservationTimeDao.delete(id);
좋은 조언 감사합니다! 
확실히 이미 예약이 등록된 예약시간은 비즈니스적 관점에서 함부로 삭제해서는 안되겠다는 생각이 들었어요. 

```java
reservationDao.findAnyByTimeId(timeId)
        .ifPresentOrElse(
                reservation -> {
                    throw new DeleteReservationTimeException(HttpStatus.BAD_REQUEST, "해당 예약시간에 예약이 등록되어 있습니다.");
                },
                () -> reservationTimeDao.delete(timeId)
        );
```
그래서 등록된 예약이 있는 예약시간을 삭제하려고 할 때에는 예외를 발생하도록 해보았습니다.
저는 위처럼 Optional 을 사용하여 구현하는 것이 가독성이 더 좋다고 생각하는데 조앤의 의견이 궁금해요!

2024-04-25 07:15 UTC, ksk0605 commented on src/main/java/roomescape/controller/ReservationController.java
> +    public ResponseEntity<Integer> deleteReservation(@PathVariable int id) {
원래는 정상적으로 삭제작업이 완료되었다는 의미로 리소스의 id를 반환해주려고 했습니다. 
그런데 생각해보니까 no Content로 충분히 의미가 전달되는 것 같더라구요! 그래서 반환하지 않는 것으로 변경하였습니다.

2024-04-25 07:16 UTC, ksk0605 commented on src/main/java/roomescape/controller/TimeController.java
> +    private final TimeService timeService;
변경해보았습니다 👍

2024-04-25 07:20 UTC, ksk0605 commented on src/main/java/roomescape/controller/dto/CreateReservationResponse.java
> +    public static CreateReservationResponse from(Reservation reservation) {
처음에는 큰 문제가 없다고 생각했어요 🥲
질문을 주셔서 DTO가 domain 을 알고 있는 것에 대해서 고민해보았습니다! 
알지 않는 쪽이 유지보수 측면에서 더 좋다는 결론을 내리게 되었습니다.

Response 의 형태는 개발 스펙 변경에 의해 언제든지 변경이 될 가능성이 높고 
상대적으로 가장 변경으로 부터 안전해야할 도메인까지 영향을 미칠 수 있다고 생각합니다. 

관리의 리소스는 좀 더 들지만 보다  안전하게 유지보수 할 수 있는 방향이라고 생각하는
Mapper 클래스를 구현하여 Response 와 domain 클래스를 분리했습니다.

2024-04-25 07:23 UTC, ksk0605 commented on src/main/java/roomescape/dao/ReservationDao.java
> +        return jdbcTemplate.update("insert into reservation (name, date, time_id) values (?, ?, ?)",
아무도 그렇게 알려주지 않았는데 update() 의 반환 값이 변경된 데이터의 id라고 생각했어요..! 😢

말씀해주신 두가지 키워드를 공부해보고 두 개 중에서는 SimpleJdbcInsert 가 더 가독성이 좋다고 생각하여 개선해보았습니다. 
좋은 조언 감사해요 👍

2024-04-25 07:24 UTC, ksk0605 commented on src/main/java/roomescape/dao/ReservationDao.java
> +    public Reservation read(int id) {
findBy~ 의 형태로 조회 기능 메서드명을 통일 시켜보았습니다!

2024-04-25 07:35 UTC, ksk0605 commented on src/main/java/roomescape/dao/ReservationTimeDao.java
> +    public int create(CreateReservationTimeRequest request) {
쉽지 않겠군요..🥲 타입만으로는 의도가 전달되지 않을 것 같아서 개선을 하다보니 고민되는 지점을 만났는데요.

```java
// ReservationTimeDao
public ReservationTime create(ReservationTime reservationTime) {
    SqlParameterSource params = new BeanPropertySqlParameterSource(reservationTime);
    long id = jdbcInsert.executeAndReturnKey(params).longValue();
    return new ReservationTime(id, reservationTime.getStartAt());
}

// ReservationDao 
public long create(Reservation reservation) {
    SqlParameterSource params = new MapSqlParameterSource()
            .addValue("name", reservation.getName())
            .addValue("date", reservation.getDate())
            .addValue("time_id", reservation.getTime().getId());
    return jdbcInsert.executeAndReturnKey(params).longValue();
}
```

메서드 시그니처를 개선해보기 위해 생성된 객체 자체를 반환해보려고 했는데 
단일 테이블을 참조하는 ReservationTimeDao 에서는 가능했지만 
**ReservationTime 객체와의 연관성을 가지고 있는 Reservation은 ReservationDao 자체로는 객체를 반환할 수 없는
문제**가 있었어요. 

```java
public CreateReservationResponse createReservation(CreateReservationRequest request) {
    Reservation requestedReservation = reservationMapper.toReservation(request);
    long createdId = reservationDao.create(requestedReservation);
    Reservation createdReservation = reservationDao.findById(createdId);
    return reservationMapper.toCreateReservationResponse(createdReservation);
}
```
결국은 서비스 쪽에서 Reservation 을 찾는 과정을 추가해야만 했습니다. 
고민되는 지점은 **서로 다른 Dao 의 create 메서드의 시그니쳐, 즉 동작 결과가 다름으로 인해 
읽는 개발자에게 혼란을 줄 수 있겠다는 점**이었습니다. 
위에서 지적해주신 것처럼 **int 만으로는 어떤 결과가 반환되는지 쉽게 알 수도 어렵구요**. 

떠오른 방안은 두가지가 있었습니다. 
1. 둘 모두 int 를 반환하도록 통일한다. 
2. 둘 모두 void 로 통일한다. 

제 생각이 맞다면 조앤은 어느 쪽이 더 합리적인 방향이라고 생각하시나요?

2024-04-25 07:41 UTC, ksk0605 commented on src/main/resources/schema.sql
> +
reservation 테이블의 time_id 의 null을 허용하면 안되겠군요..! NOT NULL 키워드를 추가했습니다. 
또 DB의 검증에 의존하는 것은 좋은 어플리케이션이 아니란 생각이 들어서 각각의 도메인에도 검증 로직을 추가했습니다. 

이때 **클라이언트의 요청에 비어있는 값이 있는 검증하는 책임이 누구의 것인가?** 가 고민이 되었는데요..!

저는 일단 Domain 에 관련된 정보는 Domain 스스로 검증하는 것이 맞다고 생각하여 각 Domain 에게 주었지만 
'올바른 요청' 에 대한 검증의 관점에서 본다면 Service 에서 수행하는 것도 괜찮겠다는 생각이 들었어요..!

조앤은 어떻게 생각하시나요?

2024-04-25 07:42 UTC, ksk0605 commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +    @Test
에디터에 따라 한글 메소드 명을 읽지 못하는 경우가 있다고 알고 있습니다만 저는 한글로 쓰는 것이 더 편하다고 생각하여 이번에 한번 시도해봤습니다. 현업에서 더 선호하는 방향이 있을까요?

2024-04-25 07:42 UTC, ksk0605 commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +                .when().delete("/times/1")
미쳐 생각지 못했네요..! 수정했습니다 👍

2024-04-25 07:50 UTC, ksk0605 commented
# 추가질문
```java
private Reservation(String name, LocalDate date, ReservationTime time) {
    this(-1, name, date, time);
}
```
코드를 개선하던 중에 검증로직을 추가하며 주,부 생성자를 만들게 되었고 모든 생성자에서 검증을 수행할 필요는 없기에 
모든 파라미터를 가지는 주생성자에만 검증로직을 추가해주었습니다. 
이때 주 생성자를 사용하기 위해서는 필히 모든 파라미터를 주입해주어야 해서 
위와 같이 의미 없는 쓰레기 값을 넣어주어야만 하는 문제가 있었어요. 
좋은 방향은 아니라는 생각이 드는데 이것이 혹시 도메인에게 억지로 검증 책임을 넘겨주었기 때문인지도 궁금합니다 🧐

2024-04-25 12:46 UTC, seovalue commented on README.md
> +### 시간 추가 API
👍

2024-04-25 12:47 UTC, seovalue commented on src/test/java/roomescape/dao/ReservationTimeDaoTest.java
> +class ReservationTimeDaoTest {
혹시 테스트 한꺼번에 돌려보셨을까요?
한꺼번에 돌리면 몇가지씩 번갈아가며 서로다른 테스트가 깨지는데, 왜 그럴까요?ㅎㅎ
한번 확인해봐주세요~

2024-04-25 12:49 UTC, seovalue commented on src/main/java/roomescape/controller/dto/CreateReservationResponse.java
> +    public static CreateReservationResponse from(Reservation reservation) {
오오오

> Response 의 형태는 개발 스펙 변경에 의해 언제든지 변경이 될 가능성이 높고
> 상대적으로 가장 변경으로 부터 안전해야할 도메인까지 영향을 미칠 수 있다고 생각합니다.

Response는 단지 도메인을 전달받을 뿐인데 왜 도메인에까지 영향을 미칠 수 있다고 생각했어요?

2024-04-25 12:50 UTC, seovalue commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +    @Test
저도 예전에는 한글로 썼는데 요즘엔 영어로 쓰는 걸 연습해보고 있어요!

2024-04-25 12:53 UTC, seovalue commented on src/main/java/roomescape/dao/ReservationTimeDao.java
> +    public int create(CreateReservationTimeRequest request) {
이런 건 어때요?

```java
public record ReservationId(long id){}
```

ReservationDao에서는 ReservationId에 감싸서 반환한다면, 외부에서도 이게 ReservationId를 나타내는 값이구나, 알 수 있지 않을까요?

2024-04-25 12:55 UTC, seovalue commented on src/main/resources/schema.sql
> +
오호! 이건 사람마다 의견이 꽤 다른 부분이긴 한데요,
가장 빡세게 해본다면

요청에 대한 검증은 Request Dto에서 수행하고, (좀 벗어난 범위이긴 한데 필요하시다면 한번 봐보셔도 좋을 것 같아요(cf. [@Valid로 Request 검증하기](https://jyami.tistory.com/55)))
그걸 받는 도메인에서도 도메인별 검증을 수행하는 방법이 있을 것 같아요.

2024-04-25 12:57 UTC, seovalue commented on src/main/java/roomescape/core/exception/GlobalExceptionHandler.java
> +@ControllerAdvice
헉! 예외처리까지 해주셨군요! 👍 
참고로 ControllerAdvice도 있고 RestControllerAdvice도 있어요.
컨트롤러 어드바이스 쓰는 방법 말고 예외 처리를 할 수 있는 방법엔 또 뭐가 있을까요~를 다음단계에 고민해보셔도 좋을 것 같아요ㅎㅎ
(물론 시간이 되신다면 지금 해보셔도 좋아요~)

2024-04-25 12:57 UTC, seovalue commented on src/main/java/roomescape/dao/ReservationDao.java
> +    private final SimpleJdbcInsert jdbcInsert;
👍

2024-04-25 12:58 UTC, seovalue commented on src/main/java/roomescape/dao/ReservationDao.java
> +    public Optional<Reservation> findAnyByTimeId(long timeId) {
findReservationByTimeId 가 아닌 Any를 선택해주신 이유가 뭐예요?

2024-04-25 12:58 UTC, seovalue commented on src/main/java/roomescape/domain/Reservation.java
> +    private void validateNotNull(String name, LocalDate date) {
👍 
하지만 도메인이 HttpStatus까지 알고 있는게 불필요한 관심이라는 생각이 들긴 해요~

2024-04-25 12:59 UTC, seovalue commented on src/main/java/roomescape/service/ReservationTimeService.java
> +                            throw new DeleteReservationTimeException(HttpStatus.BAD_REQUEST, "해당 예약시간에 예약이 등록되어 있습니다.");
여기도 마찬가지로 서비스가 HttpStatus를 알 필요가 있을까요?

2024-04-26 01:56 UTC, seovalue commented
> private Reservation(String name, LocalDate date, ReservationTime time) {
>     this(-1, name, date, time);
> }
> 코드를 개선하던 중에 검증로직을 추가하며 주,부 생성자를 만들게 되었고 모든 생성자에서 검증을 수행할 필요는 없기에
> 모든 파라미터를 가지는 주생성자에만 검증로직을 추가해주었습니다.
> 
> 이때 주 생성자를 사용하기 위해서는 필히 모든 파라미터를 주입해주어야 해서
> 위와 같이 의미 없는 쓰레기 값을 넣어주어야만 하는 문제가 있었어요.
> 
> 좋은 방향은 아니라는 생각이 드는데 이것이 혹시 도메인에게 억지로 검증 책임을 넘겨주었기 때문인지도 궁금합니다 🧐

검증 메서드를 분리하고 부생성자에서도 검증을 수행하도록 하는 방법도 있을 것 같은데, 위와 같은 방식으로 진행해주신 이유가 궁금해요!

2024-04-26 05:05 UTC, ksk0605 commented on src/main/java/roomescape/controller/dto/CreateReservationResponse.java
> +    public static CreateReservationResponse from(Reservation reservation) {
```
HTTP/1.1 200
Content-Type: application/json

{
    "id": 1,
    "user": { // 스펙 변경
        "name" : "브라운",
        "phoneNumber" : "010-1234-5678"
    "date": "2023-08-05",
    "time" : {
        "id": 1,
        "startAt" : "10:00"
    }
}
```
(API 스펙 변경은 아니지만) 예를 들어 데이터베이스에 user 라는 테이블이 추가되고 User 도메인 클래스를 만들고 Reservation 과 관계를 맺게 되면 변경된 도메인의 스펙에 따라 위와같이 응답 형태가 변하게 될거에요. 

이 때 클라이언트에서 별도의 대응없이 기존의 응답 형태처럼 "name" 으로 파싱을 진행하게 되면 정상적으로 작동이 되지 않을거에요!

안정적이고 변화에 유연한 프로그램을 만들기 위해서는 객체 간 연관성을 줄이는 것이 좋은 방향이라고 생각합니다 👍

2024-04-26 07:12 UTC, ksk0605 commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +    @Test
영어가 너무 싫...어서 반항을 한번 해봤습니다 ㅋㅋ 저도 연습해볼게요!

2024-04-26 07:31 UTC, ksk0605 commented on src/main/java/roomescape/dao/ReservationDao.java
> +    public Optional<Reservation> findAnyByTimeId(long timeId) {
동일한 timeId 를 사용하는 Reservation 이 여러 개 존재할 때 모든 예약을 모두 불러오는 행위가 불필요하다고 생각했어요!
그래서 limit 를 1로 두어 '한가지라도 존재한다면' 이라는 의미를 주려고 했습니다 😀

2024-04-27 03:21 UTC, ksk0605 commented on src/main/resources/schema.sql
> +
'요청'에 대한 검증을 Dto 에서 수행하도록 하는 방법도 있군요..!
여러 단계에서 검증을 수행할 수도 있고 도메인에서 믿고 사용할 수도 있고..다양한 방법이 있네요. 
현재 상황에 가장 적절한 검증이 무엇이지 고민해볼 수 있는 기회가 되었습니다.

감사합니다!

2024-04-27 03:23 UTC, ksk0605 commented on src/main/java/roomescape/dao/ReservationTimeDao.java
> +    public int create(CreateReservationTimeRequest request) {
좋은 방법인 것 같습니다! 추상화 단계를 맞추는 방법에 대한 인사이트를 얻을 수 있었어요 👍
다만 ReservationId 를 만들고 관리하는 것 또한 리소스일텐데 
조앤이 VO를 생성하는 기준이 있다면 듣고 싶어요!

2024-04-27 03:37 UTC, ksk0605 commented on src/test/java/roomescape/dao/ReservationTimeDaoTest.java
> +class ReservationTimeDaoTest {
클래스 전체테스트를 돌리면 성공하고, 한개씩 돌리게 되면 실패하는 것.. 사실 알고 있었습니다 🥲

이유는 JdbcTest 의 Transactional 기능 때문이라고 알고 있는데요! 
JdbcTest하나의 테스트가 끝나면 롤백을 수행하여 실제 DB 에 적용이 되지 않도록 해주는 것으로 알고있어요 

그런데 이미 데이터베이스의 auto increment 가 작동하며 이전에 증가한 id가 영향을 주게 되는 것 같아요.
기존에는 테스트별 격리가 안되어있어서 ContextCaching 때문에 전체와 각각 돌렸을 때 다른 결과가 나타나고 있었네요 

```java
@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)
```
해당 문제는 `DirtiesContext` 를 사용해서 테스트별 Context를 분리하여 해결해보았어요!

2024-04-27 03:44 UTC, ksk0605 commented on src/main/java/roomescape/domain/Reservation.java
> +    private void validateNotNull(String name, LocalDate date) {
다시보니 도메인의 관심사와는 상관없는 객체인 것 같네요..! 
커스텀 예외를 분리한 장점을 사용하지 못하고 있던 것 같아요. 

```java
public class NonEmptyNameException extends CustomException {

    public NonEmptyNameException() {
        super(HttpStatus.BAD_REQUEST, "이름은 비어있을 수 없습니다");
    }
}
```

그래서 위와 같이 수정해보았어요! 
예외의 원인은 예외명 만으로도 알 수 있도록 좀 더 구체적인 예외 이름으로 변경하고
각 예외가 리턴해야하는 HttpStatus 와 메시지를 스스로 결정할 수 있도록 해보았습니다!

2024-04-27 03:44 UTC, ksk0605 commented on src/main/java/roomescape/service/ReservationTimeService.java
> +                            throw new DeleteReservationTimeException(HttpStatus.BAD_REQUEST, "해당 예약시간에 예약이 등록되어 있습니다.");
마찬가지로 위와 같이 수정해보았어요!

2024-04-27 03:48 UTC, ksk0605 commented
> 검증 메서드를 분리하고 부생성자에서도 검증을 수행하도록 하는 방법도 있을 것 같은데, 위와 같은 방식으로 진행해주신 이유가 궁금해요!

동일한 코드의 중복을 줄이는 것이 목적이었어요..! 
사실상 같은 기능을 하는 validationXXX() 코드가 이곳 저곳 산재하는 것 보다는
한 곳에서 관리하도록하는 것이 유지보수 측면에서 더 낫겠다는 생각이었네요. 
각 파라매터 마다 검증해야하는 개수가 달라지는 것도 문제이구요..

지금은 요청에 대한 검증은 별도의 클래스에게 위임하고, 
도메인은 도메인 로직에 집중하는 것이 더 좋겠다는 생각으로 기울고 있어요!

2024-04-27 04:00 UTC, seovalue commented on src/main/java/roomescape/dao/ReservationTimeDao.java
> +    public int create(CreateReservationTimeRequest request) {
저도 사실 빠르게 개발할 땐 원시값을 거의 사용하는데요ㅎㅎ
뭔가 이  값이 어떤 값인지를 꼭 알려주고 싶을 때 VO를 사용하곤 하는 것 같아요! 
예를 들어  Map<Integer, Integer>을 반환하는 메서드가 있을 때, 가끔 헷갈리곤 하더라고요..ㅎㅎ 
그래서 일단은 메서드명이나 변수명을 최대한 가독성있게 짓고, 그 다음에도 헷갈린다면 VO를 쓰곤 해요!

2024-04-27 04:00 UTC, seovalue commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +    @Test
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 저도 그랬는데 영어가 뭔가 무기중에 하나인 느낌이 들어서..

2024-04-27 04:01 UTC, seovalue commented on src/test/java/roomescape/dao/ReservationTimeDaoTest.java
> +class ReservationTimeDaoTest {
오 넵넵!ㅎㅎ 어쩌다보니 선행학습까지 해보셨군요 💯

2024-04-27 04:01 UTC, seovalue commented on src/test/java/roomescape/dao/ReservationTimeDaoTest.java
> +class ReservationTimeDaoTest {
DirtiesContext 외에도 여러 방법이 있을 텐데 시간나실 때, 혹은 다음 미션하면서? 한번 확인해보셔도 좋을 것 같아요~!

2024-04-27 04:08 UTC, seovalue approved these changes
안녕하세요, 테바!ㅎㅎ
리팩터링 잘 해주셨네요. 
테스트 부분이랑 몇가지 코멘트 추가로 남겼는데, 확인 꼭 부탁드릴게요~👍

2024-04-27 04:08 UTC, seovalue commented on src/test/java/roomescape/domain/ReservationTest.java
> +                .isInstanceOf(NonEmptyNameException.class)
이 테스트, 실제로는 해당 메시지를 안던져서 깨져요! 확인해주세요~

2024-04-27 04:08 UTC, seovalue commented on src/test/java/roomescape/dao/ReservationTimeDaoTest.java
> +        reservationTimeDao.delete(1);
```suggestion
                var createdReservationTime = reservationTimeDao.create(reservationTime);

        reservationTimeDao.delete(createdReservationTime.getId());
```

id는 항상 직접 작성하는 것이 아닌 만들어진 객체에서 가져오는 습관을 들이면 유지보수에 편리해요!

2024-04-27 04:08 UTC, seovalue commented on src/main/java/roomescape/exception/NonEmptyDateException.java
> +        super(HttpStatus.BAD_REQUEST, "예약날짜는 비어있을 수 없습니다");
👍

2024-04-27 04:08 UTC, seovalue commented on src/main/java/roomescape/domain/Reservation.java
>      private void validateNotNull(String name, LocalDate date) {
> 동일한 코드의 중복을 줄이는 것이 목적이었어요..!
> 사실상 같은 기능을 하는 validationXXX() 코드가 이곳 저곳 산재하는 것 보다는
> 한 곳에서 관리하도록하는 것이 유지보수 측면에서 더 낫겠다는 생각이었네요.
> 각 파라매터 마다 검증해야하는 개수가 달라지는 것도 문제이구요..
> 
> 지금은 요청에 대한 검증은 별도의 클래스에게 위임하고,
> 도메인은 도메인 로직에 집중하는 것이 더 좋겠다는 생각으로 기울고 있어요!

오호! Validator와 같은 객체를 말씀해주시는 걸까요?
저는 우선 개인적으로는 id와 같은 곳은 db에 persist 되기 전에는 생기지 않는 값이기 때문에, default인 0이나 null로 두고 주 생성자를 호출한 뒤 주생성자 안에서 검증하는 것도 좋은 방법이라고 생각하긴 해요~!

2024-04-27 04:09 UTC, merged