[4 - 9단계 - 방탈출 예약 관리] 클로버(이은정) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #125
Opened 2024-04-23 06:33 UTC by eunjungL

안녕하세요, 범블비! 클로버입니다.
1-3단계에서 좋은 리뷰 남겨주셔서 감사했습니다. 

### 궁금한 점
1. 현재는 패키지 구조가 계층을 토대로 나누어져 있습니다. 하지만 `controller.dto`의 request들은 service에서도 함께 사용되고 있는데 `controller` 패키지 내부에만 존재하는 것이 맞는가에 대한 의문이 들었고, 도메인 단위(현재 프로젝트에서는 `admin`, `reservation`)로 나눈 후 dto는 도메인 내부에 `controller`, `service`에도 속하지 않게 두는 것이 더 좋은 방법인가에 대한 고민이 생겼습니다. 범블비는 dto를 어느 패키지에 주로 두시나요? 의견이 궁금합니다!
2. 패키지 분리에 대한 기준도 궁금점이 생겼습니다. 도메인 단위으로 나눈 후 내부에 계층으로 나누는 것이 나은지(Ex. `reservation.controller`, `reservation.service`) 계층으로 나눈 후 내부에 도메인으로 패키지를 분리하는 것이 더 나은지(Ex. `controller.reservation`)에 대한 범블비의 의견도 궁금합니다. 
현재 패키지에 대한 기준을 잡기 위해 level 1부터 노력하는 중이라 범블비는 어떤 기준을 가지고 패키지를 분리하는지 의견을 듣고 싶습니다!

### Spring 사용 경험
- 총 3번의 프로젝트를 통해 Spring boot를 사용해본 경험이 있습니다.
- 현재 Spring boot를 사용한 사이드 프로젝트를 진행 중입니다.
- Spring과 관련된 강의를 듣거나 책을 본적은 없으며 공식 문서와 공식 문서의 튜토리얼을 통해 Spring boot를 공부했습니다.

남은 4 - 9단계도 잘 부탁드립니다. 감사합니다. 🙇

2024-04-23 09:43 UTC, ddaaac requested changes
안녕하세요 클로버 👋 

이번 단계도 구현 잘 해주셨네요.

몇 가지 코멘트를 남겼으니 확인해주세요.

2024-04-23 09:43 UTC, ddaaac commented on src/main/java/roomescape/controller/ReservationController.java
> +    }
[docs](https://docs.spring.io/spring-framework/reference/core/beans/annotation-config/autowired.html)를 확인해볼까요?

> As of Spring Framework 4.3, an @Autowired annotation on such a constructor is no longer necessary if the target bean defines only one constructor to begin with. However, if several constructors are available and there is no primary/default constructor, at least one of the constructors must be annotated with @Autowired in order to instruct the container which one to use. See the discussion on [constructor resolution](https://docs.spring.io/spring-framework/reference/core/beans/annotation-config/autowired.html#beans-autowired-annotation-constructor-resolution) for details.

2024-04-23 09:43 UTC, ddaaac commented on src/main/java/roomescape/controller/ReservationController.java
[docs](https://docs.spring.io/spring-framework/reference/core/beans/annotation-config/autowired.html)를 확인해볼까요?

> As of Spring Framework 4.3, an `@Autowired` annotation on such a constructor is no longer necessary if the target bean defines only one constructor to begin with. However, if several constructors are available and there is no primary/default constructor, at least one of the constructors must be annotated with `@Autowired` in order to instruct the container which one to use. See the discussion on [constructor resolution](https://docs.spring.io/spring-framework/reference/core/beans/annotation-config/autowired.html#beans-autowired-annotation-constructor-resolution) for details.

2024-04-23 09:43 UTC, ddaaac commented on src/main/java/roomescape/controller/dto/ReservationTimeCreateRequest.java
> +public record ReservationTimeCreateRequest(String startAt) {
올바르지 않은 포맷의 시간이라면 어떤 일이 발생할까요?

2024-04-23 09:43 UTC, ddaaac commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
> +        return ResponseEntity.badRequest().body(data);
표준예외는 어플리케이션 코드 내에서 발생시킬 수도 있지만, 라이브러리에서 발생시키기도 합니다.
의도한 메세지가 아닌 라이브러리에서 발생시키는 메세지가 클라이언트에 노출되면 보안 상 문제가 있을 수 있겠네요.

2024-04-23 09:43 UTC, ddaaac commented on src/main/java/roomescape/controller/ReservationController.java
> +    }
알고 계실 수 있겠지만 [생성자 주입](https://tecoble.techcourse.co.kr/post/2020-07-18-di-constuctor-injection/)에 대한 글을 읽어봐도 좋을 것 같네요.

2024-04-23 09:43 UTC, ddaaac commented on src/main/java/roomescape/repository/reservation/ReservationRepository.java
> +public interface ReservationRepository {
Repository를 인터페이스로 분리해서 얻은 장점이 있나요?

2024-04-23 09:43 UTC, ddaaac commented on src/main/java/roomescape/service/ReservationService.java
> +    public Reservation createReservation(ReservationCreateRequest request) {
질문을 조금 나눠서 얘기해봐야될 것 같네요. 일단은 서비스 레이어가 dto를 알아도 될까?에 대해서 생각해보면 좋을 것 같아요.

https://github.com/woowacourse/spring-roomescape-admin/pull/108#discussion_r1575496115 비슷한 고민을 한 많은 분들이 있어서 이 코멘트를 참고하면 좋을 것 같네요.

2024-04-23 09:43 UTC, ddaaac commented on src/main/java/roomescape/controller/dto/ReservationCreateRequest.java
> +import roomescape.domain.ReservationTime;
다음으로는 dto 패키지의 위치에 대해서 얘기해볼 수 있을 것 같아요.

만약 컨트롤러/서비스 레이어가 모두 dto를 알고 있다면, 둘 어디에도 속하지 않는 패키지에 있는 편이 적당할 것 같고
컨트롤러만 dto를 알고 있다면 컨트롤러 패키지 안에 들어와도 괜찮겠죠.

2024-04-23 09:43 UTC, ddaaac commented on src/main/java/roomescape/controller/ReservationTimeController.java
> +package roomescape.controller;
> 도메인 단위으로 나눈 후 내부에 계층으로 나누는 것이 나은지(Ex. reservation.controller, reservation.service) 계층으로 나눈 후 내부에 도메인으로 패키지를 분리하는 것이 더 나은지(Ex. controller.reservation)에 대한 범블비의 의견도 궁금합니다

이 것도 정해진 정답은 없습니다. 이 부분은 프로젝트 규모에 따라 좀 달라지는 것 같네요. 나중에 도메인이 엄청 많아지면 어떤 패키지가 적당할지 생각해보시고, 지금 규모에서 지금 클로버가 분리해주신 패키지가 적당한지 모두 생각해보시면 좋을 것 같아요.

2024-04-23 09:43 UTC, ddaaac commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +import static org.junit.jupiter.api.Assertions.assertAll;
개인적으로는 assertj나 jupiter의 Assertion은 하나로 통일하는 편입니다.
동일한 기능이 여러 라이브러리에 의존하고 있을 때 발생하는 문제를 생각해보셔도 좋을 것 같아요.

2024-04-24 07:46 UTC, eunjungL reviewed
안녕하세요, 범블비! 클로버입니다.
좋은 리뷰 남겨주셔서 감사합니다. 덕분에 놓치고 있던 부분을 많이 학습했습니다.

남겨주신 리뷰에 대해 반영 완료했고 추가적으로 언급해주신 리뷰도 확인했습니다.

남은 기간 잘 부탁드립니다. 감사합니다! 🙇

2024-04-24 07:46 UTC, eunjungL commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +import static org.junit.jupiter.api.Assertions.assertAll;
`SoftAssertions`를 사용해 통일 완료했습니다! 동일한 기능이 여러 라이브러리에 의존하고 있을 때, 라이브러리간의 의존성 충돌이  발생할 수 있을 것 같습니다. 그 외에도 발생할 문제점에 대해서 더 알아보겠습니다. 좋은 인사이트 감사합니다, 범블비! 👍

2024-04-25 03:59 UTC, ddaaac requested changes
안녕하세요 클로버 👋 

리뷰 반영 잘 해주셨습니다

추가 코멘트 남겼으니 확인해주세요.

2024-04-25 09:39 UTC, eunjungL reviewed
안녕하세요, 범블비! 클로버입니다.
이번에도 좋은 리뷰 많이 남겨주셔서 감사합니다! 덕분에 많이 학습할 수 있었습니다. 👍 

## 궁금한 점
1. 리뷰 남겨주신 것 중 `Dao vs Repository`에 대해 궁금한 점이 생겨 해당 리뷰에 답글로 질문을 남겼습니다! 시간 되실 때 확인 부탁드립니다.
2. service는 다른 도메인의 객체가 필요할 때 service와 repository 중 어느 것을 의존해야 하는지에 대한 의문입니다.
현재 구조는 `Reservation`을 저장하기 위해서는 `time_id`를 통해 `ReservationTime` 객체를 찾아온 후 저장을 해야하는 구조인데요, 이를 위해서 기존에는 `ReservationService`가 `ReservationTimeService`를 통해 `ReservationTime` 객체를 얻어왔습니다. 하지만 각 service가 도메인이 아닌 ResponseDto를 반환하면서 위와 같은 구조를 유지하기 어려워졌고 `ReservationService`가 `ReservationTimeRepository`를 통해 객체를 얻어오게 코드를 변경했습니다.
이때 `ReservationTime` 객체를 얻어오는 과정에서 필요한 예외처리 과정이 `ReservationTimeService.readReservationTime()`와 완전히 동일한데 두 service에서 각자 중복된 코드를 가지게 되는 것이 아닌가라는 의문이 들었습니다. 하지만 이를 위해 service가 도메인을 반환하고 controller에게 도메인을 ResponseDto로 바꾸게 하는 것은 도메인이 표현 계층에 노출되는 것이라 계층을 나눈 의미가 퇴색되지 않나 싶어 어떻게 해결할 수 있을지 고민입니다. 
범블비는 위와 같은 상황에서 어떤 방법을 선택하시는지 의견을 듣고 싶습니다!

남은 기간 동안도 잘 부탁드립나다! 좋은 리뷰 항상 감사합니다 🙇

2024-04-25 09:39 UTC, eunjungL commented on src/test/java/roomescape/repository/ReservationTimeFakeDao.java
> +public class ReservationTimeFakeDao implements ReservationTimeRepository {
Mockito를 적용해보고 싶어 공부하고 적용을 시도해봤는데, 공부할 양이 많아 시간이 좀 걸릴 것 같습니다. 😢 
일단 현재까지 해둔 것에 대한 리뷰를 받고 싶어 리뷰 요청을 먼저 드립니다! mockito에 대해서도 꼭 학습하고 적용해보도록 하겠습니다. 🙇

2024-04-26 05:32 UTC, ddaaac requested changes
안녕하세요 클로버 👋 

리뷰 반영 잘 해주셨어요. 몇 가지 코멘트 남겼으니 확인해주세요.

2024-04-26 05:32 UTC, ddaaac commented on src/main/java/roomescape/controller/ReservationController.java
> +        return ResponseEntity.ok(data);
어차피 스프링 내부에서 이래저래 변환하는 과정을 생각하면 객체 생성의 비용은 생각 안하셔도 됩니다.
가독성에 집중해서 생각해보시면 좋을 것 같아요!

2024-04-26 05:32 UTC, ddaaac commented on src/main/java/roomescape/repository/reservation/ReservationDao.java
> +public class ReservationDao implements ReservationRepository {
> Indicates that an annotated class is a "Repository", originally defined by Domain-Driven Design (Evans, 2003) as "a mechanism for encapsulating storage, retrieval, and search behavior which emulates a collection of objects".
Teams implementing traditional Jakarta EE patterns such as "Data Access Object" may also apply this stereotype to DAO classes, though care should be taken to understand the distinction between Data Access Object and DDD-style repositories before doing so. This annotation is a general-purpose stereotype and individual teams may narrow their semantics and use as appropriate.


`@Repository` 어노테이션의 주석에 달린 내용입니다. 정확한 차이를 아는 건 이번 미션 주제에서 벗어나기도 하고 지금은 잘 와닿지 않을 수도 있어서 클로버가 이해한 정도로 넘어가시면 좋을 것 같아요.

여튼 `apply this stereotype to DAO classes`란 말에 집중해보면 클로버가 만든 Dao 클래스에 이 어노테이션을 붙여도 전혀 문제가 되지 않는다는 걸 알 수 있겠죠.

이 부분은 추후에 공부해보시길 바랍니다. 

+) DDD란 용어에 너무 매몰되지 않았으면 좋겠어요. 어느 정도 공부를 할 수는 있겠지만 개인적으로는 우테코 미션 기간동안은 건드리지 않았으면 하는 키워드입니다.

2024-04-26 05:32 UTC, ddaaac commented on src/test/java/roomescape/repository/reservation/ReservationDaoTest.java
> +    public ReservationDaoTest(JdbcTemplate jdbcTemplate, DataSource dataSource) {
ReservationRepository를 직접 주입받을 수는 없을까요?

2024-04-26 05:32 UTC, ddaaac commented on src/test/java/roomescape/repository/ReservationTimeFakeDao.java
> +public class ReservationTimeFakeDao implements ReservationTimeRepository {
코드를 보니 적용이 된 것 같은데 추후에 커밋하신걸까요?
여튼 잘 적용해주셨고, 기존에 FakeDao를 통해 한 테스트와 mockito를 통해 만든 테스트의 차이에 대해 생각해보시면 좋을 것 같습니다 👍

2024-04-26 05:32 UTC, ddaaac commented on src/main/java/roomescape/service/ReservationService.java
> +    private final ReservationTimeRepository reservationTimeRepository;
> service는 다른 도메인의 객체가 필요할 때 service와 repository 중 어느 것을 의존해야 하는지에 대한 의문입니다.

좋은 질문이네요. 생각하신 내용들도 읽어봤는데 크게 두 가지로 나눠서 얘기해봐야될 것 같아요.
우선 질문을 하나 드리고 싶은데요, service와 repository가 하는 일은 각각 어떤 일일까요? 이를 잘 생각해보면 어떤 경우에 서비스를 의존해야하는지, 어떤 경우에 레포에 의존해야하는지 떠오를 수 있을 것 같아요.

2024-04-26 05:32 UTC, ddaaac commented on src/main/java/roomescape/service/ReservationService.java
> +    private final ReservationTimeRepository reservationTimeRepository;
> 하지만 이를 위해 service가 도메인을 반환하고 controller에게 도메인을 ResponseDto로 바꾸게 하는 것은 도메인이 표현 계층에 노출되는 것이라 계층을 나눈 의미가 퇴색되지 않나 싶어 어떻게 해결할 수 있을지 고민입니다.

도메인이 컨트롤러에 노출되어도 되나?에 대한 얘기네요. 제가 우테코 크루였을 때 아마도 구구에게 이 설명을 들은 적이 있던 것 같아요(그 때는 코치가 아니셨던 걸로 기억하네요). 밴다이어그램을 그려주시면서 왜 모델이 컨트롤러에 노출되어도 되는지 설명을 해주셨었는데 아직도 그 설명이 인상깊게 남아있습니다. 한 번 구구와 이 부분에 대해서 얘기 나눠보시면 좋은 인사이트를 얻을 수 있지 않을까 싶습니다. (구구가 아니었다면 다시 저한테 와주세요...)

2024-04-26 08:34 UTC, eunjungL reviewed
안녕하세요, 범블비! 클로버입니다.

좋은 리뷰 많이 남겨주셔서 감사합니다. 특히 service와 repo 중 어느 것에 의존해야 하는지에 대해 인사이트를 얻을 수 있어서 한번 더 학습하는 기회였습니다. 🙇 

남은 미션 기간도 잘 부탁드립니다!

2024-04-26 08:34 UTC, eunjungL commented on src/test/java/roomescape/repository/reservation/ReservationDaoTest.java
> +    public ReservationDaoTest(JdbcTemplate jdbcTemplate, DataSource dataSource) {
`@JdbcTest`를 사용했을 때는 빈을 자동으로 주입받는 방법이 없는 줄 알았는데요, 크루한테 `@Import`에 대해 듣고나서 생성자 주입을 받을 수 있게끔 변경 완료했습니다. 좋은 인사이트 감사합니다! 👍

2024-04-27 03:43 UTC, ddaaac approved these changes
안녕하세요 클로버 👋 

리뷰 반영 너무 잘 해주셔서 여기서 머지해도 될 것 같아요.

다음 단계는 옵션이니 도전해보고 싶으시다면 도전해보시면 좋을 것 같습니다.

고생 많으셨어요!

2024-04-27 03:43 UTC, ddaaac commented on src/main/java/roomescape/service/ReservationService.java
> +    private final ReservationTimeRepository reservationTimeRepository;
생각 너무 잘 해주셨어요 👍 

앞으로도 비슷한 고민이 떠오르면 이 생각을 바탕으로 고민을 해결해나가시면 될 것 같습니다.

2024-04-27 03:43 UTC, ddaaac commented on src/main/java/roomescape/service/ReservationService.java
> +    private final ReservationTimeRepository reservationTimeRepository;
음.. 아니었군요. 좀 된 일이라 저도 가물가물하네요. 죄송합니다 🥲

말로 정리하려니 쉽지 않아서 혹시나 궁금하시다면 나중에 게더나 밋에서 잠깐 얘기하면 좋을 것 같네요.

2024-04-27 03:43 UTC, ddaaac commented on src/test/java/roomescape/repository/ReservationTimeFakeDao.java
> +public class ReservationTimeFakeDao implements ReservationTimeRepository {
생각이랑 정리를 되게 잘 해주시네요 👍

2024-04-27 03:43 UTC, merged

2024-04-28 06:21 UTC, eunjungL reviewed
안녕하세요, 범블비! 클로버입니다.

남은 기간은 스프링에 대해 새롭게 알게된 지식을 공부하기 위해 사용할 예정이라 10단계는 진행하지 않을 것 같습니다.

방탈출 예약 관리 미션 기간동안 좋은 리뷰 너무 감사했습니다! 🙇

2025-01-11 03:41 UTC, kingle1024 commented
댓글 통해 잘 배웠습니다.