[방탈출 예약 관리 4-9단계] 리니(이예린) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #132
Opened 2024-04-23 09:10 UTC by linirini

안녕하세요, 웨지🖐️
1-3단계에서 남겨주신 의견 확인했습니다! 남겨주신 코멘트까지 반영해서 4-9단계를 구현해봤는데요.! 구현 방향이랑 질문 함께 남깁니다.!

1. 컨트롤러 테스트
Dao가 Controller에 노출되는 것과 웨지가 말씀해주셨던 BeforeEach과정에서 구체적인 초기화 로직에 의존하게 된다는 단점에서 api 콜로 beforeEach를 수행하도록 유지했습니다.

2. 계층화
Controller에서는 요청과 응답만 관리하도록 Service 계층을 분리하여 Service 계층 내부에서 Repository를 활용하여 비즈니스 로직을 처리할 수 있도록 계층 분리를 했습니다.

3. Service 계층의 테스트
**Service 단위 테스트는 Repository 테스트와 분리해주기 위해 기존에 만들었었던 FakeRepository를 활용하여 테스트를 진행**했습니다. 
의도한 바는 Service 단위 테스트의 검증 대상을 Service 내 비즈니스 로직으로 분명하게 하고자 함이었습니다.
 하지만 이렇게 했을 때 서비스가 커진다면 매번 FakeRepository를 만드는 것도 비용 소모일 것이며, 그 로직이 복잡해졌을 때 FakeRepository를 신뢰하기 위해서는 이를 위한 테스트도 추가로 필요해지는 상황이 발생할 수도 있다는 단점이 존재한다고 생각합니다.

만약, 테스트 더블이 아닌 db를 사용한다면 위의 단점은 해결할 수 있겠지만, 테스트가 실패했을 때 원인이 2가지(데이터 로직과 비즈니스 로직)가 존재한다는 점에서 아쉬움이 남아 저는 FakeRepository를 사용하는 것을 선택했는데, 이에 대한 웨지의 의견이 궁금합니다.

4. Repository 테스트 제거
Repository 단위 테스트를 제거하고 싶은데, 그 근거는 다음과 같습니다.
결국 (문법적인 오류가 없다면) **sql문이 잘 실행되는가**를 테스트 할 뿐이라고 생각합니다. 
그리고, 문법적인 오류는 다른 계층의 단위 테스트가 잘 분리되어 있고, 던져지는 예외를 통해 충분히 추적 가능하다고 생각합니다.
그리고 **외부 요인으로 인해 우리 서비스의 테스트 성공률이 달라질 수 있다는 문제점**을 가집니다.
이러한 근거로 지금 존재하는 JdbcRepository 테스트는 제거하는 것이 옳다고 생각합니다. 
일단 테스트를 남겨놓긴 했는데, 웨지는 이에 대해 어떻게 생각하시는지 의견이 궁금합니다.

이번에도 리뷰 잘 부탁드립니다.🙇‍♀️

2024-04-24 13:57 UTC, sihyung92 requested changes
안녕하세요 리니! 리뷰어 웨지입니다.
잘 구현해주셔서 패키지 변경이나 RowMapper 추출 등 간단한 리뷰만 있습니다!
질문 중 답변이 필요한 것은 리뷰 중에 남겨두었습니다.
반영 후 리뷰 요청 주세요 :)

2024-04-25 06:30 UTC, linirini commented on src/test/java/roomescape/dao/ReservationTimeJDBCRepositoryTest.java
> +@JdbcTest
웨지 코멘트대로 지금은 쿼리가 간단하기 때문에 repository 테스트의 필요성에 고민한 것 같습니다.

2024-04-26 07:53 UTC, linirini commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +class ReservationServiceTest {
> 주요한 작업이 DB 접근인 경우가 많아서, DB 접근을 모킹하고 나면 응답객체 맵핑 정도만 테스트 하게 되는 코드가 만들어지는데, 이게 의미가 있는 작업일지 의문이 있습니다.

의미있는 테스트로 만들어주기 위해서는 DB 접근을 실제로 해야겠네요!!
또 한번 내가 무엇을 테스트하고 있는지 잘 인지하면서 해야겠다는 생각이 듭니다😅

실제 DB를 주입 받아서 사용할 수 있도록 통합 테스트 형태로 리팩토링 했습니다!

2024-04-27 02:41 UTC, sihyung92 commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +class ReservationServiceTest {
넵 제 주위에도 service 슬라이스 테스트를 선호하는 개발자가 많습니다 ㅎ 저는 소수의견인 편입니다
리니도 많이 토론해보시고 경험해보시면서 결정해보셔요 🔥

2024-04-27 02:47 UTC, sihyung92 commented on src/main/java/roomescape/service/ReservationService.java
> +    }
엄밀히 말하면 "실패"가 아니라고 보는 개념이에요. 
삭제를 요청했으니 삭제를 수행했고, 없는 리소스니까 실은 아무것도 삭제 안 됐지만 "삭제를 하긴 했잖아" (???)라고 주장하는거죠 ㅋㅋ (200)

근데 기능의 요구사항이 "실제로 리소스가 없는 경우 '그런거 없습니다'라는 오류메시지를 노출해주세요." 라고 한다면 기존 코드처럼 둘수도 있고요 ㅎ

2024-04-27 02:51 UTC, sihyung92 approved these changes
안녕하세요 리니! 리뷰어 웨지입니다.
리뷰 반영이 잘 되어있고, 요구사항을 만족하셔서 머지합니다!
레벨 2 첫 미션 수고하셨습니다 👍

2024-04-27 02:51 UTC, sihyung92 commented on README.md
> +### 시간 추가
API 명세를 잘 만들어주셔서 참 좋아요. 나중에 프론트랑 협업하게 되면 이 문서가 중요한 역할을 하게 될거에요 ㅎ

2024-04-27 02:51 UTC, sihyung92 commented on src/main/java/roomescape/controller/ReservationTimeController.java
> +    @ResponseBody
`@RestController` 키워드에 대해 찾아보셔요 :)

2024-04-27 02:51 UTC, merged