[4 - 9단계 - 방탈출 예약 관리] 릴리(최윤서) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #136
Opened 2024-04-23 13:25 UTC by lilychoibb

안녕하세요 아서 🤗
리뷰 해주셔서 감사합니다 :)

우선, 1 - 3 단계에 남겼던 [질문](https://github.com/woowacourse/spring-roomescape-admin/pull/82#discussion_r1573189448) 참고 부탁드립니다

스프링에 대한 학습을 처음 해보며 미션을 진행하다보니 아직은 질문이 없습니다!
코드가 조금 지저분하거나 불필요해보이는 부분이 있을 수 있지만 최선을 다했습니다(😅😇)

개선해볼만한 부분 리뷰 남겨주시면 열심히 공부하며 질문이 생길 때 추가로 남겨보겠습니다
감사합니다

2024-04-24 12:59 UTC, Hyunta requested changes
안녕하세요 릴리,
두번째 미션도 잘 진행해주셨네요👍🏻
몇가지 커멘트 남겼는데 확인 부탁드립니다.
이해가지 않거나 궁금한점이 있으면 DM 주시거나 커멘트 남겨주세요!

2024-04-24 12:59 UTC, Hyunta commented on src/main/java/roomescape/dao/ReservationDAO.java
> +    }
Spring4.3부터 생성자 주입을 할 경우 `@Autowired` 를 생략해도 되는데요. 
<img width="1020" alt="image" src="https://github.com/woowacourse/spring-roomescape-admin/assets/75936123/6fac73dc-0c8c-4a8b-8f12-65535005816c">
[자료](https://docs.spring.io/spring-framework/reference/core/beans/annotation-config/autowired.html)

어떤것을 더 선호하시나요?

2024-04-24 12:59 UTC, Hyunta commented on src/main/java/roomescape/dao/ReservationDAO.java
> +    }
SimpleJdbcInsert를 사용해서 더 쉽게 사용해볼 수도 있을 것 같아요
https://hyeon9mak.github.io/easy-insert-with-simplejdbcinsert/

2024-04-24 12:59 UTC, Hyunta commented on src/main/java/roomescape/dao/ReservationTimeDAO.java
> +    }
클래스 이름에서 이미 도메인을 노출하고 있어서 생략해도 괜찮지 않을까요?

```suggestion
    public List<ReservationTime> findAll() {
        return jdbcTemplate.query("SELECT * FROM reservation_time", rowMapper);
    }
```

2024-04-24 12:59 UTC, Hyunta commented on src/main/java/roomescape/dao/ReservationTimeDAO.java
> +public class ReservationTimeDAO {
애노테이션은 Repository인데 클래스 이름은 DAO로 지어주셨네요.
혹시 이유를 알 수 있을까요?

2024-04-24 12:59 UTC, Hyunta commented on src/main/java/roomescape/dto/ReservationCreateRequestDto.java
> +public record ReservationCreateRequestDto(String name, String date, long timeId) {
[제안]
저는 개인적으로 Request라는 표현을 dto의 suffix로 사용해서 Dto는 쓰지 않습니다.
클래스 이름이 길어지는 게 싫어서 그러는데 생략해도 괜찮지 않을까요?

2024-04-25 02:30 UTC, lilychoibb commented on src/main/java/roomescape/controller/ReservationController.java
>      public ResponseEntity<Void> delete(@PathVariable long id) {
래퍼타입으로 받을 경우에 예외를 반환한 이유가 좀 더 명확해지는군요!
id 가 0L 로 들어오는 경우는 없다 라고 가정했었는데 생각해보니 아예 못 들어오진 않을 것 같네요
다양한 경우를 생각해서 처리하는게 좋을 것 같아요 :)
래퍼타입으로 감싸서 받아오도록 수정하겠습니다

2024-04-25 04:58 UTC, lilychoibb commented on src/main/java/roomescape/dao/ReservationDAO.java
> +    }
넵 생략해도 된다는 내용을 보긴 했었는데, 스프링 빈을 주입한다는 개념을 명시적으로 나타내면 학습을 하는데 있어서 도움이 될 것 같아 일부러 생략하지 않았습니다! :) 
그런데 생략을 하는 게 더 깔끔해서 스프링에 좀 더 익숙해지면 생략해보고 싶습니다 🙂

2024-04-25 05:23 UTC, lilychoibb commented on src/main/java/roomescape/dao/ReservationTimeDAO.java
> +    }
insert 와 delete 는 생략했는데 findAll 만 붙이고 있었네요 😅
감사합니다!

2024-04-25 07:24 UTC, lilychoibb commented on src/main/java/roomescape/dao/ReservationTimeDAO.java
> +public class ReservationTimeDAO {
`@Repository` 애노테이션은 `@Component` 의 specific 한 케이스로 Data access layer 에 사용합니다. 여기서 Data access layer 는 Repository 와 DAO 로 나눌 수 있는데요.
DAO 는 하나의 테이블에 대한 저수준 CRUD 의 책임을 가지고, Repository 는 Repository 에서 제공하는 하나의 오퍼레이션이 DAO의 여러 오퍼레이션에 매핑되는 것이 일반적이며 객체 컬렉션의 집합 처리에 관한 책임을 가지고 있습니다.
따라서 `@Repository` 애노테이션의 사용과 DAO 라고 정의한 클래스가 타당하다고 생각이 듭니다.
현재 ReservationTimeDAO 클래스가 객체 컬렉션의 집합 처리에 관한 책임을 가지고 있다고 생각이 되진 않습니다.
아서는 어떻게 생각하시나요? 현재의 ReservationTimeDAO 가 Repository 라고 생각하신다면 그 이유도 궁금합니다! 🙂

2024-04-25 07:26 UTC, lilychoibb commented on src/main/java/roomescape/dto/ReservationCreateRequestDto.java
> +public record ReservationCreateRequestDto(String name, String date, long timeId) {
오 생략해도 괜찮을 것 같네요 👍

> Request라는 표현을 dto의 suffix로 사용 

이 설명이 와닿는 것 같아요
감사합니다!

2024-04-26 15:42 UTC, Hyunta requested changes
안녕하세요 릴리,
피드백 반영 잘 해주셨네요👍🏻
남겨주신 질문에 의견 남겼는데 확인 부탁드립니다ㅎㅎ
확인해보시고 재요청주세요!

2024-04-27 08:47 UTC, lilychoibb commented on src/main/java/roomescape/dao/ReservationTimeDAO.java
> +public class ReservationTimeDAO {
앗 .. 쿼리를 두 테이블을 했네요 😅 왜 알아차리지 못했을까요 !!

> DAO 클래스 안에서 도메인 객체로 변환하는 작업과 여러 테이블을 조회해서 필요한 데이터를 불러오는 작업을 하고 있습니다.
아래 주장에 조금 어긋난 부분이 아닐까요?
DAO 는 하나의 테이블에 대한 저수준 CRUD 의 책임을 가지고, Repository 는 Repository 에서 제공하는 하나의 오퍼레이션이 DAO의 여러 오퍼레이션에 매핑되는 것이 일반적이며

어긋난 거 맞는 것 같습니다 🤦🏻‍♀️
그래도 아서 덕분에 앞으로 dao 와 repository 는 좀 더 잘 구분해서 사용할 수 있을 것 같아요 ㅎㅎ
Repository 로 수정해야겠네요!
감사합니다 :)

2024-04-27 08:57 UTC, lilychoibb commented on src/main/java/roomescape/dao/ReservationTimeDAO.java
> +public class ReservationTimeDAO {
> ReservationTimeDAO는 DAO로 충족하는 것 같습니다. 그런데 DAO와 Repository를 엄격하게 분리하는 것은 유지보수에 비용이 많이 들 것으로 예상됩니다. 그런 의미에서 조금 더 포괄적으로 관리할 수 있는 Repository를 선택하는건 어떨까요?

ReservationRepository 와 ReservationTimeDAO 로 분리하는 것이 유지보수에 비용이 든다는 말씀이 맞을까요?
저도 내부 구조는 똑같은데 repository 와 dao 로 분리하는 것은 추후에 혼동이 될 수 있다는 면에서 동의합니다!
제가 이해한 뜻과 맞는 지 확인하고 싶어서 한번 더 여쭤봅니다 🙂 !

2024-04-27 13:22 UTC, Hyunta commented on src/main/java/roomescape/dao/ReservationTimeDAO.java
> +public class ReservationTimeDAO {
네 릴리가 이해하신 뜻과 제가 전달하려는 의도가 맞습니다!

2024-04-27 13:26 UTC, Hyunta approved these changes
안녕하세요 릴리,
스프링을 처음 사용해보셨다고 하셔서 사소한 질문들을 많이 드렸는데 피드백을 주고받으면서 근거를 계속 쌓아가시는 모습이 인상적이었습니다.
앞으로도 고민을 많이 해보시면서 레벨 2 남은 미션들을 통해 많이 성장하시길 바랍니다!

2024-04-27 13:26 UTC, merged