[4 - 9단계 방탈출 예약 관리] 도비(김도엽) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #146
Opened 2024-04-24 08:39 UTC by Dobby-Kim

안녕하세요 파랑!
이번 미션은 Spring을 처음 접하였기에 학습을 진행하면서 학습한 내용을 적용해보는 것에 중점에 두고 진행해보았습니다!

모르는 것이 나타날 때 마다 하나하나 공식 문서와 공식 블로그를 참고하며 코드 작성을 진행하였더니 조금 시간이 걸렸네요..ㅎㅎ

##  관심을 두고 미션을 진행한 부분

- 미션 목표에 명시되어있는 바, 우선은 해피 케이스만을 고려하여 기능 구현에 우선 순위를 두고 미션을 진행해보았습니다.
- 기본적인 Spring 어노테이션 익히는 것을 신경써서 진행했습니다.
- Layered Architecture를 학습하게 되면서 각 계층이 가져야하는 책임과 역할에 대한 고민에 집중하였습니다.

## 궁금한 점

### 1. 하나의 `Service`는 하나의 `Repository`를 가져야 하나요?
1. `ReservationTime` 클래스가 DB Table을 따로 가지게 되면서 이를 다루는 레포지토리 계층을 만들었습니다.
2. 그리고, 요구사항에 따라 `Reservation` 객체는 client의 요청에서 ReservationTime Data를 직접 가지고 있는 것이 아닌, ReservationTime을 가르키는 `time_id`를 통해 간접적으로 데이터를 지니고 있게 되었습니다.
3. 이렇게 되면서 시간데이터를 가지는 예약 정보를 반환하기 위해 `reservation` table에서 reservation id, name, date, time_id를 가져온 후, time_id를 이용하여 `reservation_time` table을 조회하게 됐습니다.
4. `ReservationRepository`에서 `reservation` table과 `reservation_time` table, 2개의 테이블에 대한 접근을 하는 보다 각각의 레포지토리에서 각 테이블에 접근하는 것을 유지하고자 했습니다.
5. 그래서 `ReservationService` 클래스에서 2개의 레포지토리를 가지고 있게 했고, 먼저 `reservation` table을 조회한 후, 가져온 reservation의 time_id를 통해 `reservation_time` table을 조회하여 예약 시간 데이터를 가져오게 하였습니다.

이렇게 했을 때 제가 생각한 장단점에 대해서 말씀드리겠습니다!
#### 장점:
1. 각 레포지토리가 각 model에 관련된 하나의 테이블만을 다루면, 코드의 구조가 간단해지고 각 레포지토리의 책임이 명확해지지 않을까?
2. 재사용성: 각 테이블에 특화된 레포지토리를 사용하면 해당 데이터 모델에 대한 작업을 재사용하기 쉬워지지 않을까?
3. 유지보수: 각 테이블을 독립적으로 다루는 레포지토리는 유지보수가 용이하며, 데이터 모델이 변경될 때 해당 레포지토리만 수정하면 됩니다.

#### 단점:
1. 여러 테이블에 대한 작업을 여러 레포지토리에서 처리하면, 데이터베이스 연결과 트랜잭션 관리 효율성에 문제가 발생할 수도 있지 않을까?
2. `Service` 계층이 2개의 레포지토리를 가지게 된다면 해당 레포지토리 코드의 수정이 있을 때 `Service` 계층의 코드가 변경되어야할 수도 있지 않을까?

였습니다!
이 부분에 대한 파랑의 인사이트를 얻고 싶습니다 :)

리뷰 잘부탁드리겠습니다! :>

2024-04-25 11:29 UTC, summerlunaa requested changes
도비 안녕하세요~

남겨주신 질문에 대한 답변과 함께 리뷰 남겼습니다. 확인해주시고 더 궁금하거나 이해되지 않는 부분은 편하게 DM 주세요! 테스트도 잘 챙겨주시구요ㅎㅎ 파이팅 💪

2024-04-25 11:29 UTC, summerlunaa commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    public Reservation createReservation(Reservation reservation) {
[SimpleJdbcInsert](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/core/simple/SimpleJdbcInsert.html)를 사용하면 조금 더 쉽게 데이터를 삽입할 수 있습니다.

2024-04-25 11:29 UTC, summerlunaa commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    private final RowMapper<Reservation> reservationRowMapper = (resultSet, rowNum) ->
상수로 선언해도 좋겠네요.

2024-04-25 11:29 UTC, summerlunaa commented on src/main/java/roomescape/service/ReservationService.java
> +    private ReservationInfo generateReservationInfo(final Reservation reservation) {
메서드 순서를 확인해주세요~

2024-04-25 11:29 UTC, summerlunaa commented on src/main/java/roomescape/service/ReservationService.java
> +    private ReservationInfo generateReservationInfo(final Reservation reservation) {
> 요구사항에 따라 Reservation 객체는 client의 요청에서 ReservationTime Data를 직접 가지고 있는 것이 아닌, ReservationTime을 가르키는 time_id를 통해 간접적으로 데이터를 지니고 있게 되었습니다.
> 이렇게 되면서 시간데이터를 가지는 예약 정보를 반환하기 위해 reservation table에서 reservation id, name, date, time_id를 가져온 후, time_id를 이용하여 reservation_time table을 조회하게 됐습니다.
> ReservationRepository에서 reservation table과 reservation_time table, 2개의 테이블에 대한 접근을 하는 보다 각각의 레포지토리에서 각 테이블에 접근하는 것을 유지하고자 했습니다.

하나의 레포지토리는 하나의 테이블에만 접근해야 하나요? 이렇게 하면 데이터를 조회할 때 join을 통해 한 번의 쿼리로 가져올 수 있는 데이터도 모두 개별 쿼리를 사용해서 조회한 후, 합치는 과정이 필요한데 요 부분까지 고려해보셨는지 궁금합니다!

2024-04-25 11:29 UTC, summerlunaa commented on src/main/java/roomescape/service/ReservationService.java
> +    private final ReservationTimeRepository reservationTimeRepository;
> 하나의 Service는 하나의 Repository를 가져야 하나요?

하나의 API에서 하나의 테이블만 CRUD 하면 참 쉬울텐데 현실은 그렇지가 않죠 🥲 지금처럼 작은 서비스도 예약을 조회하기 위해 예약 시간 테이블의 데이터를 가져와야 합니다. 결국은 서로 다른 두 가지 테이블의 데이터를 어딘가에서는 합쳐서 가져와야 하는 거죠.

합치는 곳이 지금 도비가 구현한 것처럼 서비스가 될 수도 있구요, 레포지토리에서 join을 통해 미리 합쳐서 들고올 수도 있겠죠. 아니면 뭐 컨트롤러가 될 수도 있겠구요. 도메인이 복잡해질 수록 지금 하고 있는 이런 고민이 많이 드실 거예요!

그래서 하나의 Service는 하나의 Repository를 가져야 하나요?라고 물으면 저는 아니라고 생각합니다. 어디에선가는 데이터를 합쳐줘야 하니까요. 그렇다고 모든 Repository를 다 가져다 쓸 수도 없겠죠. 어렵겠지만 도메인들 간의 경계를 잘 설정해야 한다고 생각해요. 연관성이 깊은 도메인들을 묶어 사용하는 거죠. 회원 관련 도메인, 예약 관련 도메인.. 등으로요. 예약 관련 서비스에서는 예약 관련 레포지토리를 자유롭게 사용하지만, 회원 관련 레포지토리는 접근하지 않는다. 이런 식으로 기준을 설정해서 사용하면 좋지 않을까 생각합니다.

그런 의미에서 현재 예약과 예약 시간은 연관도가 굉장히 높은 테이블이기 때문에 join할 수 있으면 join을 통해 한 번에 가져와도 괜찮을 것 같아요.

2024-04-25 11:29 UTC, summerlunaa commented on src/main/resources/application.properties
> +spring.sql.init.mode=always
요 설정은 왜 추가해주셨나요?

2024-04-25 11:29 UTC, summerlunaa commented on src/test/java/roomescape/MissionStepTest.java
> +    void reservationControllerTest_ShouldAssertFalse_WhenChecked() {
무엇을 위한 테스트인가요?

2024-04-25 11:29 UTC, summerlunaa commented on src/test/java/roomescape/MissionStepTest.java
repository와 service에 대한 테스트가 전혀 없네요. 테스트도 잘 챙겨주세요~

2024-04-29 05:54 UTC, Dobby-Kim commented on src/main/java/roomescape/controller/ReservationController.java
> +        return ResponseEntity.created(URI.create("/reservations/" + newReservationInfo.id())).build();
4, 5, 6 단계에서 제공된 테스트 코드를 먼저 이용하여서 코드를 작성했었습니다. 
ResponseEntity 클래스를 컨트롤러에 사용하면서 상태 코드를 세부적으로 조정을 하였는데, 이 점을 이용하고자 201, 204로 바꾸어서 작성을 진행했었습니다 :>

다만 API 명세에 따라 코드를 다시 200을 주도록 수정하겠습니다!

2024-04-29 07:32 UTC, Dobby-Kim commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    private final RowMapper<Reservation> reservationRowMapper = (resultSet, rowNum) ->
넵 적용해봤습니다!
RowMapper 사용시에 계속 새로 생성되기에 상수로 선언하는 것이 좋을 것 같다고 이해했는데 혹시 맞을까요?!

2024-04-29 07:38 UTC, Dobby-Kim commented on src/main/java/roomescape/service/ReservationService.java
> +    private ReservationInfo generateReservationInfo(final Reservation reservation) {
리팩터링을 통해 해당 메서드를 삭제해서 제거했는데, 혹시 어떤 순서 때문에 리뷰 남겨주셨나요?


```java
public class ClassName {
    // private static final
    // 상수
    // 클래스 변수
    // 인스턴스 변수
    // 생성자
    // 팩토리 메서드
    // 일반 메서드 (호출 순서 지키기)
    // getter, setter
    // equals, hashCode, toString
}
```

순으로 작성하고 있었습니다..!!

2024-04-29 07:40 UTC, Dobby-Kim commented on src/main/java/roomescape/service/ReservationService.java
> +    private ReservationInfo generateReservationInfo(final Reservation reservation) {
네 해당 부분까지 고려하여 작성했었습니다!! 다만, 그 전에는 뭔가 근거 없이 '하나의 레포지토리에서는 하나의 테이블에만  접근하게 하면 좋겠다.' 라고 막연하게 생각했었던 것 같습니다..!! 파랑께서 남겨주신 리뷰를 읽어보고 리팩토링을 적용하였습니다.ㅎㅎ

아마 제가 기존에 작성한 방식대로 코드를 사용한다면, DB에 대한 불필요한 접근이 많아 질 것 같아서 한 번에 JOIN을 통해 데이터를 가져오도록 수정하였습니다!

2024-04-29 07:44 UTC, Dobby-Kim commented on src/main/resources/application.properties
> +spring.sql.init.mode=always
설정에 대해 찾아보며 따라하다가 추가하였습니다!
H2 DB의 특성 상, 어플리케이션이 시작될 때마다 새로운 DB가생성되는 것을 고려하면 필요없는 설정이었다고 이제 알게되었습니다. ㅎ.ㅎ

2024-04-29 07:46 UTC, Dobby-Kim commented on src/test/java/roomescape/MissionStepTest.java
> +    void reservationControllerTest_ShouldAssertFalse_WhenChecked() {
9단계에서  주어진 테스트입니다!
앞 단계에서 작성된 코드는 controller가 레포지토리를 가지고 있었는데, 계층 분리 요구 사항이 추가되면서 기존에 존재하였던 레포지토리 컴포넌트가 해당 controller에서 사라졌는지 확인하는 테스트로 알고 있습니다 😄

2024-04-29 07:49 UTC, Dobby-Kim commented on src/test/java/roomescape/MissionStepTest.java
네 맞습니다..ㅜㅜ 분명 테스트를 분리의 필요성을 느끼고 있었습니다.
하지만 이 부분에 대해서는 아직 제가 각 계층 단위에서 어떤 테스트를 진행해야하는지에 대해 인사이트가 부족하다고 생각해서 학습을 진행한 후에 다음 미션부터 분리하여 적용해보도록 하겠습니다..!!

2024-04-29 08:05 UTC, Dobby-Kim commented
안녕하세요 파랑!
이번 미션에 관련된 내용 뿐만 아니라 여러 방면으로 학습을 병행하며 리팩터링을 진행하다보니 리뷰가 늦었습니다!!

말씀해주신 부분들 고려하여 리팩터링 진행해보았습니다!

이번 리팩터링을 진행하면서 고민한 부분은 다음과 같습니다.

## 고민이 되던 부분
### 1. 가장 큰 변화 DTO 분리
- Reservation과 ReservationTime이 Request- DB- Response 형식이 같아서 Request가 레포지토리 단까지 데이터를 가지고 내려오게 되었습니다.
- 그리고 Response 또한 그 형식이 같아 `Reservation`과 `ReservationTime`이 그대로 직렬화되어 입력되었고, 그대로 역직렬화되어 반환 되었습니다!
- Layered Architecture로 설계된 현재 코드에서 계층간 정보 전달이 하나의 객체로 이루어지는 것이 계층을 나눈 것 이유와 상충하는 것 같아 DTO 클래스를 생성하였습니다.
- DTO가 `Request`, `Response` 클래스의 필드 구성이 같게 되어 `이건 코드 중복이 아닌가?`라고 생각이 들었습니다.
- 하지만 필요한 코드를 작성했을 뿐이고, 그 코드가 단순히 중복된다고 해서 `코드 중복`으로 취급하지 않아야겠다 라고 생각했습니다!
- 하지만 지금 작성한 코드가 과연 YAGNI 원칙에 어긋아니 않는 걸까? 라는 물음에 확신이 없어서 파랑의 인사이트를 구하고 싶습니다!

2024-04-29 15:18 UTC, summerlunaa commented on src/test/java/roomescape/MissionStepTest.java
넵 테스트는 천천히 공부해보시죠~

2024-04-29 15:48 UTC, summerlunaa requested changes
도비 안녕하세요~

리뷰와 함께 남겨주신 질문에도 답변 드렸습니다. 내일부터 새로운 미션 시작인 만큼 다음 리뷰 요청은 빠르게 해주시면 바로 머지하겠습니다. 너무 고민하지 마시고 얼른 끝내는 걸 목표로 하시죠 :) 마지막까지 힘내봅시다 💪

2024-04-29 15:48 UTC, summerlunaa commented on src/main/java/roomescape/service/ReservationService.java
> +    private ReservationInfo generateReservationInfo(final Reservation reservation) {
오호 `findAllReservations`에서만 해당 메서드가 사용되는 걸로 봤었네요ㅎㅎ 넘어가주셔도 될 것 같습니다!

2024-04-29 15:48 UTC, summerlunaa commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    private final RowMapper<Reservation> reservationRowMapper = (resultSet, rowNum) ->
넵 ReservationRepository가 여러번 생성되더라도 Mapper는 변하지 않는 값이니 상수로 두고 사용해도 괜찮아보여요. 물론 ReservationRepository는 싱글톤이지만요 ^-^

2024-04-29 15:48 UTC, summerlunaa commented on src/main/java/roomescape/controller/ReservationController.java
> +    private ReservationDto toDto(final ReservationRequest reservationRequest) {
서비츠 계층에서 사용하는 DTO를 분리하셨네요!

> DTO가 Request, Response 클래스의 필드 구성이 같게 되어 이건 코드 중복이 아닌가?라고 생각이 들었습니다. 하지만 필요한 코드를 작성했을 뿐이고, 그 코드가 단순히 중복된다고 해서 코드 중복으로 취급하지 않아야겠다 라고 생각했습니다!

진짜 중복과 가짜 중복에 대해 고민해보셨네요. 좋습니다! 저도 서비스용 DTO와 controller용 DTO가 진짜 중복이라고 생각하진 않습니다. 다만 서비스용 DTO를 생성했을 때 잃는 것과 얻는 것을 잘 생각해서 도입하면 더 좋지 않을까 싶어요. `계층간 정보 전달이 하나의 객체로 이루어지는 것`에서 어떤 문제점을 느꼈나요? 서비스용 DTO를 추가해서 잃게 된 점들, 예를 들면 DTO 변환과 DTO 클래스 관리에 사용되는 비용에 대해서는 어떻게 생각하시나요? 

개인적으로는 지금 서비스 DTO를 도입한 건 너무 이르다고 생각해요. 마치 레벨1 자동차 미션에 DTO를 도입하는 느낌입니다. Controller 코드만 봐도 변환 로직 때문에 코드가 많이 복잡해졌네요. 🤔

2024-04-29 15:48 UTC, summerlunaa commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    private static final RowMapper<ReservationDto> reservationRowMapper = (resultSet, rowNum) ->
상수는 순서를 맨 위로 올리고 대문자 스네이크케이스로 변경해볼까요?

2024-04-29 15:48 UTC, summerlunaa commented on src/main/java/roomescape/repository/ReservationRepository.java
> +                + " ON r.time_id = t.id";
텍스트 블록(`"""`)을 사용하면 훨씬 깔끔할 것 같아요

2024-04-29 15:48 UTC, summerlunaa commented on src/main/java/roomescape/service/ReservationService.java
> +
```suggestion
```

2024-04-29 15:48 UTC, summerlunaa commented on src/test/java/roomescape/MissionStepTest.java
> +    private final RowMapper<ReservationRequest> reservationDtoMapper = (resultSet, rowNum) ->
사용하지 않는 필드네요

2024-04-29 15:48 UTC, summerlunaa commented on src/main/resources/static/js/time.js
> +        if (response.status === 201) return response;
여기도 바뀌어야 하지 않을까요~

2024-05-01 07:28 UTC, Dobby-Kim commented
> 진짜 중복과 가짜 중복에 대해 고민해보셨네요. 좋습니다! 저도 서비스용 DTO와 controller용 DTO가 진짜 중복이라고 생각하진 않습니다. 다만 서비스용 DTO를 생성했을 때 잃는 것과 얻는 것을 잘 생각해서 도입하면 더 좋지 않을까 싶어요. 계층간 정보 전달이 하나의 객체로 이루어지는 것에서 어떤 문제점을 느꼈나요? 서비스용 DTO를 추가해서 잃게 된 점들, 예를 들면 DTO 변환과 DTO 클래스 관리에 사용되는 비용에 대해서는 어떻게 생각하시나요?

> 개인적으로는 지금 서비스 DTO를 도입한 건 너무 이르다고 생각해요. 마치 레벨1 자동차 미션에 DTO를 도입하는 느낌입니다. Controller 코드만 봐도 변환 로직 때문에 코드가 많이 복잡해졌네요. 🤔


음 1,2,3단계를 끝내고, 4~9단계를 진행하면서 API 명세가 기존 예약 내용에 예약 시간이 포함된 필드를 body에 포함되도록 변경되었습니다.

이 변경점이 반영되면서 기존에 Request, Response의 역할을 하던 Reservation 객체 하나가 변경이 되었고, 이 변경으로 인해 모든 계층의 코드가 변경되는 것을 경험하였습니다! 그래서 `아 이래서 계층간 데이터 전송 객체를 두고 분리를 해야된다고 하는구나!`라고 느꼈습니다!

미션을 진행할 당시에는 현제 2번째 미션의 내용을 몰랐지만, 2 번째 미션을 진행 중인 지금, 또 다시 API 명세와 여러가지 요구사항이 바뀌면서 Request, Response 형식이 달라졌습니다. 그러면서 또 한 번 그 필요성을 느꼈습니다!

물론 첫 번째 미션할 때로 돌아가서 생각한다면, 파랑께서 말씀해주신대로 DTO 클래스 관리에 필요한 코드가 많이 추가되면서 그 유지보수 비용이 늘었다고 느꼈습니다..!! 이 역시 필요에 의해 DTO가 생성되었다고 생각이 들이 않아 파랑께서 해주신 말씀이 와닿았습니다ㅎㅎ

---

이번 요청이 마지막 요청이 될 것 같은데, 지난 체스미션, 이번 미션까지 여러가지 배울 수 있는 좋은 시간이었던 것 같습니다! 
제가 미흡한 점이 많아서 답답하셨을 수도 있지만 꼼꼼히 리뷰 봐주셔서 감사했습니다!! 👍🏻 👍🏻

2024-05-01 13:21 UTC, summerlunaa approved these changes
도비 안녕하세요~

수정 사항은 없지만 이전에 얘기한대로 바로 머지하겠습니다. 첫 미션 마무리 축하드립니다 👏 남은 레벨 2 미션들도 잘 헤쳐나가시길 바랍니다. 즐거운 리뷰였습니다~~ 😄

2024-05-01 13:21 UTC, merged