[4 - 9단계 - 방탈출 예약 관리] 도라(추서연) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #148
Opened 2024-04-24 13:47 UTC by ChooSeoyeon

2024-04-24 18:15 UTC, ChooSeoyeon commented on README.md
> +ReservationMemoryDao 가 저장소로 바라보고 있는 List<Reservation>가 Dao의 데이터 저장소로 손색없다는 뜻이다.
지난 스텝에서 마지막에 남겨주신 커멘트에 대해 답변 달아두었습니다!
https://github.com/woowacourse/spring-roomescape-admin/pull/63#discussion_r1571963465

`List<Reservation>`을 데이터저장소로 바라보는 건 가능하지만, 굳이 바라볼 필요가 없었단 걸 깨달았단 내용입니다!

2024-04-25 09:24 UTC, jamie9504 requested changes
안녕하세요, 도라 😄 리뷰어 제이미입니다.

간단한 코멘트들만 남겨두었으니 확인해주세요!

오늘도 좋은 하루 보내세요~ 😉

2024-04-25 09:24 UTC, jamie9504 commented on src/main/java/roomescape/dao/ReservationDaoImpl.java
> +public class ReservationDaoImpl implements ReservationDao {
Interface를 분리했을 때는 어떠한 장점이 있을까요?

2024-04-25 10:51 UTC, ChooSeoyeon commented on src/main/resources/schema.sql
> +CREATE TABLE reservation_time
api 엔드포인트인 `/times `에 맞춰 TimeController, TimeService와 같이 이름 붙이다보니 도메인도 자연스레 Time이라 이름 붙이게 되었었습니다. 다만, 테이블명에 맞춰 reservatonTime으로 이름 붙이는 게 `예약 가능한 시간`이라는 역할을 더 잘 드러내는 거 같아 수정하겠습니다!

2024-04-26 07:59 UTC, ChooSeoyeon commented on src/main/java/roomescape/service/ReservationService.java
> +                .orElseThrow();
현재는 별도의 예외 핸들러를 두고 있지 않아, 500 예외가 발생합니다. 다만, 서비스 클래스 단위테스트 중 예외를 검증하고 싶을 수도 있기에 예외를 던지도록 수정해두었습니다!

[refactor: 예외 메시지 추가](https://github.com/woowacourse/spring-roomescape-admin/pull/148/commits/27da51b34ee7ec7df286c5dc0eacbe7d9dacac2b)

2024-04-26 08:00 UTC, ChooSeoyeon commented on src/main/java/roomescape/dao/TimeDaoImpl.java
> +        time.setId(id);
짐작하기 어려울 거 같습니다. 따라서 save 메서드가 생성한 객체를 반환하도록 수정해주었습니다!

2024-04-26 08:50 UTC, ChooSeoyeon commented on src/main/java/roomescape/dao/ReservationDaoImpl.java
> +public class ReservationDaoImpl implements ReservationDao {
원래 코드는 interface 분리의 장점을 가져가지 못하는 거 같아 아래와 같이 수정해주었습니다.
[refactor: repository와 dao 패키지 분리](https://github.com/woowacourse/spring-roomescape-admin/pull/148/commits/1eb811deee2ff0ca234b30712eb58409d305c509)

가장 크게 바뀐 점은 인터페이스는 domain 패키지에 들어가고, 구현체는 dao 패키지에 들어갔단 점입니다.
그 과정 속에 인터페이스는 repository로 이름을 바꿔줬습니다.

이를 통해 얻을 수 있는 장점으론 service가 dao 구현체를 아예 모르게 해줄 수 있단 점이 있습니다.
기존엔 service가 domain과 dao 패키지를 모두 살펴봤지만,
현재는 servicer가 domain 패키지만 알고, 구현체가 들어있는 dao 패키지는 모릅니다.
이를 통해 구현체를 숨길 수 있습니다.

2024-04-26 11:24 UTC, ChooSeoyeon commented on src/main/java/roomescape/service/ReservationService.java
> +    private final TimeDao timeDao;
ReservationService가 ReservationTimeDao를 아는 건 
Controller -> Serivce -> Dao 순에서 하위 계층을 참조하고 있기에 순환참조의 위험이 없습니다.
그러나 중복 코드가 생길 수 있습니다.

반면, ReservationService가 TimeService를 아는 건 순환참조의 위험이 존재합니다.
그러나 순환참조가 생기지 않는 걸 경계한다면 너무 경계할 필요는 없습니다.
오히려 중복 코드를 제거한단 관점에서 효율적일 수 있습니다.

둘 중 뭐가 옳다 하는 정답은 없고, 상황마다 팀마다 다르게 선택할 거 같습니다.
만일 ResevationService가 사용해야 하는 TimeService의 메서드가 단순히 dao 접근만 담당하는 게 아니라 그 외의 비즈니스 로직을 실행한다면 TimeService를 사용해 중복 코드를 줄일 거 같습니다.

2024-04-26 11:25 UTC, ChooSeoyeon commented on src/main/java/roomescape/dao/ReservationDaoImpl.java
> +public class ReservationDaoImpl implements ReservationDao {
도메인 패키지에 repository 인터페이스를 넣어준 이유는 repository를 도메인 객체의 컬렉션을 관리하는 개념으로 보았기 때문입니다.

2024-04-26 15:17 UTC, jamie9504 requested changes
안녕하세요, 도라 😄 리뷰어 제이미입니다.

간략한 코멘트만 조금 남겨두었어요.

다음 리뷰 요청 때는 이슈 없다면 Approve & Merge 예정입니다.
즐거운 주말 보내세요 😉

2024-04-26 15:17 UTC, jamie9504 commented on src/main/java/roomescape/dao/ReservationDaoImpl.java
> +public class ReservationDaoImpl implements ReservationDao {
구현체를 숨겼을 때는 어떠한 장점이 있을까요? 😃 
이 장점이 인터페이스를 분리하는 비용보다 큰 이익이라고 생각하시나요 작은 이익이라고 생각하시나요?

2024-04-26 15:17 UTC, jamie9504 commented on src/main/java/roomescape/service/ReservationService.java
> +                .orElseThrow();
👍 
API 요청 자체에 대한 예외 처리에 대한 요구 조건은 없었지만,
예외를 던질 때는 예외 메시지나 어떤 예외를 던질지 고려해야 하는 것이 아닌지 해서 적어두었었습니다.

2024-04-26 15:17 UTC, jamie9504 commented on src/main/resources/schema.sql
> +CREATE TABLE reservation_time
URL과 연관관계에 대한 고민들을 하게 되는군요!

해당 Times는 reservations와 항상 함께 움직이도록 설계되었을지 고민해볼까요?
RESTFUL API의 URL에 대해서도 알아봐도 좋겠네요.

2024-04-28 06:39 UTC, ChooSeoyeon commented on src/main/java/roomescape/dao/ReservationDaoImpl.java
> +public class ReservationDaoImpl implements ReservationDao {
지금과 같은 계층 구조에서 구현체를 숨기는 장점이 두드라집니다.
web / service(application+domain) / domain / database
크게 위의 계층 별로 패키지를 분리해뒀습니다.

인터페이스를 분리하지 않는다면, service는 domain과 database에 대해 모두 알아야 합니다.
인터페이스를 분리한다면, service는 domain만 알면 됩니다.

결국 web과 application service를 한 모듈로, domain service와 domain을 한 모듈로, database를 한 모듈로 바라볼 수 있습니다.
모듈 별로 사람을 나눠 개발하더라도 각 개발자들이 처음에 정한 인터페이스를 기반으로 독립적으로 개발할 수 있습니다.
작업의 효율성이 올라가는 것이지요.

인터페이스를 분리함으로써 관리 포인트가 늘어난단 단점이 생길 수 있지만, 프로그램을 모듈 별로 나눠 개발할 수 있단 장점이 그 단점을 커버해줄 수 있다 생각합니다. 지금과 같은 페어프로그래밍 상황에도 새 페어가 database 계층에 대한 이해가 부족한 상태에서도 service와 domain 계층만 살펴보고 비즈니스 로직을 이해할 수 있을 것입니다.

(추신. service의 경우 현재 application과 domain을 나눠 작업할만한 기능이 없어 나누지 않았습니다. 만일 web계층에서 외부 API를 사용한다던가 해서 web계층의 dto와 service 계층의 dto를 나눠 관리해야 할 포인트가 생긴다면 나눌 거 같습니다)

2024-04-29 02:03 UTC, jamie9504 approved these changes
안녕하세요, 도라 😄 리뷰어 제이미입니다.

특별한 부분은 보이지 않아 이만 Approve & Merge 진행합니다!
간략한 코멘트는 달아두었습니다.

2레벨 첫 미션 고생 많으셨고, 남은 미션도 즐겁게 해나가시길 바랍니다. 😉

2024-04-29 02:03 UTC, jamie9504 commented on src/main/resources/schema.sql
> +CREATE TABLE reservation_time
결국 도메인을 파악하고, 해당 도메인을 어떻게 정의하는지에 따라
내부 변수명이나, 데이터베이스명, API URL 등을 설계할 수 있는 부분이니 초반에 잘 정의하고 정리해나가는 것이 좋습니다 😉

2024-04-29 02:04 UTC, merged