[1 - 3단계 방탈출 예약 관리] 켬미(김경미) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #16
Opened 2024-04-16 11:51 UTC by kyum-q

안녕하세요 스티치! 이번에 리뷰를 받게된 6기 BE 켬미라고 합니다 😊
이번 미션은 스프링의 시작이라 그런지 예제 문제를 풀면서 페어와 함께 하다보니 생각보다 수월하게 진행했던 것 같아요!

그리고 이번에는 리뷰어에게 제가 웹 개발을 해봤는지, 해봤다면 스프링을 사용해봤는지 여부를 말해달라 해서 간단하게 말해보겠습니다 !

저는 `웹 개발 경험이 있나요?` 라는 질문에 답변으로는 `예. 웹 애플리케이션을 만들었지만 로컬에서만 서버를 띄워봤습니다.` 라고 답할 수 있을 것 같아요 ! 😊 근데 일반적인 웹 애플리케이션이 아니라, IoT 장치의 소프트웨어 연결을 웹으로 구현했었습니다 ! ([프로젝트](https://github.com/HINAPIA/CoMirror))

다음은 바로 이어지는 질문인 `스프링 프레임워크을 사용했나요?`라는 질문에 답변으로는 `아니요`라고 답할 것 같아요 ! ㅎㅎ

그래서 저는 웹에 대해서 조금은 안다고 할 수 있지만, 스프링에 대한 학습 경험은 대학교 때 수업으로 1학기 동안 배웠던 것이 전부입니다 ! 그것마저 1년 전이어서 거의 스프링을 모른다고 생각해주시면 감사할 것 같아요 ! 😊

그래서 이번에 스티치와 이야기하면서 스프링에 대해 배우면서 성장해가고 싶네요 ! 
많은 피드백과 생각할 거리를 주시면 열심히 생각해보도록 하겠습니다 😁

2024-04-17 07:41 UTC, lxxjn0 requested changes
안녕하세요, 켬미. 이번에 리뷰를 맡게 된 스티치입니다 :)

스프링부트 애플리케이션을 처음 만드는 만큼 설레기도 하면서 한편으론 새롭고 어렵기도 할 것 같아요. 이번 미션 진행하면서 하나씩 알아가다보면 분명 재미를 느끼실 수 있을겁니다 :)

첫 미션은 그리 어렵지 않아서 켬미가 작성한 코드에 대해서는 딱히 피드백을 드릴 만한 부분이 보이질 않았습니다. 그래도 시간적인 여유가 있는 만큼 스프링부트의 몇 가지 부분에 대해서 한번 같이 고민해보면 좋을 내용들을 남겨봤어요. 한번 참고하셔서 공부하시고 답변 남겨주세요 😄

2024-04-18 04:34 UTC, kyum-q commented on src/main/java/roomescape/controller/RoomEscapeController.java
> +@Controller
미션을 하기 전에 학습테스트(uri에 따라서 view를 보야줘야하는 미션)를 하다가 페어의 코드는 되고 제 코드는 안되는 부분이 있었어요! 왜 그럴까 확인하니 저는 `@RestController`로 하고 페어는 `@Controller`로 했더라고요 !
그 때 간단하게 찾아보긴했었는데 그 때 깨달은 점은 단순히 `view를 띄어주는 역할을 할 때는 @Controller를 사용`한다. @RestController는 @Controller와 @ResponseBody를 합친거다` 정도만 정리하고 넘어갔었습니다 !

그치만 스티치의 조언을 보고 조금 더 자세하게 찾아봤습니다 !
다음 내용이 제가 정리한 `@Controller`와 `@RestController`의 차이입니다. 혹시 잘못된 정보나 제가 놓친 정보가 있다면 편하게 말해주세요 !

 ---


### @Controller
: View를 반환하기 위해 사용 (Model 객체를 만들고 올바른 뷰를 선택하는 일을 담당)

![](https://i.imgur.com/uYbBokh.png)


그래서 가장 일반적인 Controller의 메서드 역할은 띄어주고 싶은 viewName을 반환하는 것이다.


ex) uri가 `localhost:8080/start` 일 경우, `start.html`을 띄워줘야 함

1. client가`localhost:8080/start` 로 웹 서비스에 요청을 보낸다
2. Dispatcher Servlet이 해당 uri를 처리할 대상을 찾는다.
3. HandlerAdapter을 통해 요청을 Controller에 위임한다.
4. **Controller는 `/start` uri를 담당하는 메서드를 실행한다. 
   -> 해당 메서드는 viewname으로 `start`를 반환한다.**
5. Dispatcher Servlet은 viewResolver를 통해 viewname에 해당하는 vieiw를 찾아 사용자에게 반환한다.

### Controller가 Data를 반환하고 싶으면?

>HTTP Response Body에 데이터를 담는 것은 RESTful 웹 서비스에 대한 응답에 매우 유용합니다.
>
>RESTful 웹서비스 : 요청-응답 서비스와 다르게 프로그램과 상호작용하자 않고, 일반적으로 데이터와 상호작용하는 웹 서비스

#### 1. @ResponseBody

: Controller가 반환하는 것이 viewName이 아니라 Data(Json) 형태임을 알려준다. (RESTful 웹 서비스에서 사용되는 특수 컨트롤러)

![](https://i.imgur.com/UBFCI0e.png)

-> 컨트롤러는 요청을 처리한 후에 **객체를 반환**한다.
-> 객체는 Json으로 Serialize 되어 사용자에게 반환된다.

#### 2. @RestController 
 
: @Controller에 @ResponseBody가 추가된 것 →  Json 형태로 객체 데이터를 반환


![](https://i.imgur.com/uE4lTUT.png)

(@Controller에 @ResponseBody가 추가된 경우도 동일하게 동작)

-> 컨트롤러는 요청을 처리한 후에 **객체를 반환**한다.
-> 객체는 Json으로 Serialize 되어 사용자에게 반환된다.

#### 두 방식 다 왜 ResponseEntity 객체로 감쌌을까?

: 반환할 때, HttpStatus를 설정하기 위해서.
(그냥 객체로 반환해도 되지만 그랬을 경우는 HttpStatus를 설정할 수 없다)

> HttpStatus - 201, 204, 404, ...

2024-04-18 04:36 UTC, kyum-q commented on src/main/java/roomescape/controller/RoomEscapeController.java
> +@Controller
그리고 찾으면서 깨달은 점은 ! view를 반환하는 메서드들과 객체를 반환하는 메서드들을 구분해서 다른 Controller로 만드는 경우가 분리도 편리하고 가독성도 좋다는 내용을 알게 되었습니다 ! (저도 생각해보니 그런 것 같아요 !) 그래서 해당 컨트롤러를 분리하려고 합니다 !

좋은 질문 감사합니다 😁

2024-04-18 04:41 UTC, kyum-q commented on src/main/java/roomescape/controller/RoomEscapeController.java
> +@Controller
수정하다가 한가지 궁금한 점이 생겼어요 스티지 !

Controller를 구분하려고 보니 다음과 같은 코드가 있었습니다.
```
   @GetMapping("/reservations")
    public ResponseEntity<List<Reservation>> readReservations() {
        return ResponseEntity.ok(reservations);
    }
```

해당 코드는 `ResponseEntity 객체를 반환하는 것`으로 `@RestController`의 역할이라고 생각합니다 !
근데 이전 코드에서는 `@Controller`로 되어있는 클래스의 메서드이고 `@ResponseBody`가 설정되지도 않았는데 왜 에러가 안나는 것인가요?
내부적으로 처리를 해주는건가요? 🤔

2024-04-18 05:25 UTC, kyum-q commented on src/main/java/roomescape/controller/RoomEscapeController.java
> +    }
스티치가 질문한 부분은 [위에 두 메서드 vs 마지막 메서드]가 맞을까요?
 
질문을 보고는 가장 처음 드는 생각은 `위에 두개에 공통점이 있나?` 였어요 ! 왜 두개를 묶어서 물어봤을까?  그리고 두번째 바로 든 생각은 `아래는 뭔가 위에 애들이랑 다른게 있나?` 였습니다 !

그래서 고민해본 제가 생각하는 위에 두 개의 공통점은 'Mapping이 `/reservation`이고 uri로 정보를 더 받지 않는다' 입니다
그리고 마지막 메서드의 차이점은 'uri로 정보를 더 받는다. 그것을 `@PathVariable`로 받아냈다.' 입니다.

그외에 차이점은 모르겠네요 🤔

2024-04-18 05:26 UTC, kyum-q commented on src/main/java/roomescape/controller/RoomEscapeController.java
> +    }
아 혹시 위에 
```java
    @GetMapping("/admin")
    public String openAdminPage() {
        return "/admin/index";
    }

    @GetMapping("/admin/reservation")
    public String openReservationPage() {
        return "/admin/reservation-legacy";
    }
```
이 두 개 메서드와의 차이점을 물어보신건가요?!

그렇다면 차이점은 viewname을 반환하는지 객체를 반환하는지에 차이점이 있는 것 같습니다 !
그래서 해당 부분을 위에 말했듯이 두개의 컨트롤러로 분리하였습니다 😁

2024-04-18 05:31 UTC, kyum-q commented on src/main/java/roomescape/controller/RoomEscapeController.java
> +        return ResponseEntity.ok(reservations);
사실 코드를 작성할 때는 예제코드가 그렇길래 그렇게 했습니다 !
하지만 위에 스티치의 질문을 보고 Controller에 대해 찾아보다가 갑자기 궁금해서 더 찾아보니 ResponseEntity를 사용하는 이유는 HttpsStatus를 지정하기 위해서였습니다. 이렇게했을 경우, 테스트 코드를 작성할 때도 메서드가 어떻게 처리되었는지까지 확인할 수 있을 것 같아서 더 좋다고 생각합니다. 그래서 원래 객체만 반환했던 코드도 ResponseEntity로 감싸도록 수정하였습니다 !

**왜 ResponseEntity 객체로 감쌌을까?**
: 반환할 때, HttpStatus를 설정하기 위해서.
(그냥 객체로 반환해도 되지만 그랬을 경우는 HttpStatus를 설정할 수 없다)

> HttpStatus - 201, 204, 404, ...

2024-04-18 05:33 UTC, kyum-q commented on src/main/java/roomescape/controller/RoomEscapeController.java
> +    @ResponseBody
`@ResponseBody`의 역할은 위에 스티치 질문에 말했듯이 view를 반환하는 `@Controller`가 데이터를 반환하고 싶을 때 사용해야하는 annotation입니다. 😊

2024-04-18 06:32 UTC, kyum-q commented on src/main/java/roomescape/controller/RoomEscapeController.java
> +    private AtomicLong index = new AtomicLong(1);
`AtomicLong`을 선택한 이유는 index 번호를 `getAndIncrement()` 메서드를 통해 다음 번호를 쉽게 알아낼 수 있어서였습니다.

그런데 명확한 이유는 없어서 좀 더 찾아봤습니다.
먼저 결론적으로는 동시성 문제를 해결하고 성능저하도 되지 않기 위해서는 AtomicLong을 사용하는 것이 더 좋은 것 같습니다. ! 

---

### Long 으로 id 증가

Long 타입으로 index 값을 설정하고, 필요할 때마다 long 값을 증가하는 방식은 무엇이 있을까?
바로 `index++;` 를 사용하면 된다.

해당 코드는 싱글 스레드에서는 문제가 되지 않는다.
하지만 여러 스레드가 `index++;` 이 있는 메서드를 동시에 사용하게 된다면 코드의 결과 값이 이상해진다.

Why? 동시접근을 생각하지 않은 간단한 증감 연산 때문에 
`index++` 가 하는 일은 3가지이다. 
1. 값을 얻는다
2. 얻은 값을 증가시킨다.
3. 증가시킨 값으로 값을 변경한다.

그러면 우리가 흔히 아는 동시성 문제가 발생한다.

그럼 long을 쓰면서 해결 방법은 하나다 -> `synchronized` 키워드를 사용한다.

```java
public synchronized void increseIndex() {
	index++;
}
```

동시성 문제는 해결된다 But 다른 문제가 발생한다.
 -> lock으로 인해 접근하려던 스레드가 멈춰 성능 저하가 된다.


### Atomic Operations

: 성능저하가 안되면서 동시성 문제를 해결할 수 있다.

어떡해? -> 데이터 무결성을 보장하기  위해 CAS 연산 사용

> CAS 연산은  M의 값을 B로 원자적(atomically)으로 M의 값이 기존 A의 값과 일치하는 경우에만 업데이트합니다. 만약 그렇지 않은 경우에는 아무런 변경도 일어나지 않습니다.
> 두 경우 모두, M의 기존 값이 return 됩니다

synchronized를 이용한 lock을 이용하는 경우와 달리 다른 스레드는 해당 값이 업데이트되는 동안에도 일시 중단되지 않는다. 
대신에 다른 스레드들은 해당 값을 업데이트하지 못했다는 것을 알게 됩니다. 
이렇게 되면 해당 값을 업데이트하는 스레드를 제외한 다른 스레드들은 추가로 다른 작업을 진행할 수 있으며 스레드 간의 콘텍스트 스위치도 일어나지 않습니다.

2024-04-18 07:59 UTC, kyum-q commented
안녕하세요 스티치 !
리뷰를 통해 공부하다보니 잠시였지만 많은 것을 알게 된 것 같아요 ! 
그리고 하다보니 한 가지 작은 궁금한 점이 있어서 댓글 남겼습니다. 😊
 https://github.com/woowacourse/spring-roomescape-admin/pull/16#discussion_r1570001312

2024-04-19 06:57 UTC, lxxjn0 commented on src/main/java/roomescape/controller/RoomEscapeController.java
> +@Controller
완전 꼼꼼하게 학습하시고 추가로 학습한 내용까지 잘 정리해주셨네요 👍🏼

2024-04-19 07:04 UTC, lxxjn0 commented on src/main/java/roomescape/controller/RoomEscapeController.java
> +    }
제가 헛갈리게 리뷰를 달았네요 ㅠㅠ 켬미가 두 번째로 달아주신 코멘트에 대한 질문이었습니다!! 저의 의도를 잘 파악해주시고 수정해주셨네요 👍🏼

2024-04-19 07:04 UTC, lxxjn0 commented on src/main/java/roomescape/controller/RoomEscapeController.java
> +    private AtomicLong index = new AtomicLong(1);
꼼꼼한 학습 및 정리 👍🏼

2024-04-19 07:07 UTC, lxxjn0 approved these changes
피드백 반영하시느라 수고하셨습니다 :)

추가로 제가 공부해보면 좋을 만한 부분들에 대해 엄청 꼼꼼히 학습하시고 정리해주셔서 저도 읽어보면서 한번 더 공부가 되었네요 👍🏼 이전에 남긴 리뷰에 대한 코멘트도 남겨두었고 간단한 피드백 남겼는데 큰 부분은 아니여서 다음 단계 진행하시면서 확인해보시면 될 것 같습니다 :) 수고하셨습니다

2024-04-19 07:07 UTC, lxxjn0 commented on src/main/java/roomescape/controller/LoadPageController.java
> +    }
공통된 URL 하위의 요청 메서드를 관리할 때는 `@RequestMapping` 어노테이션을 사용하면 조금 더 간결하게 작성할 수도 있습니다! 한번 찾아보면 좋을 것 같습니다 :)

2024-04-19 07:07 UTC, lxxjn0 commented on src/main/java/roomescape/controller/ReservationController.java
> +    @ResponseBody
`@RestController` 어노테이션이 설정되어 있는 클래스 하위에는 따로 해당 어노테이션을 붙이지 않아도 됩니다 :)

2024-04-19 07:08 UTC, merged