[4 - 9단계 - 방탈출 예약 관리] 땡이(정지호) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #162
Opened 2024-04-25 08:09 UTC by J-I-H-O

2024-04-26 05:44 UTC, syoun602 requested changes
안녕하세요 땡이~

전체적으로 잘 구현해주셨습니다 👍
코멘트 몇 개 남겨두었으니 반영후 재요청 주세요!
반영 중 질문이 있다면 언제든 DM 주셔도 됩니다 😊

2024-04-26 05:44 UTC, syoun602 commented on README.md
> +- `/admin/time` : 예약 시간 관리 페이지
기능 구현사항은 따로 정리된게 없을까요~?

2024-04-26 05:44 UTC, syoun602 commented on src/main/java/roomescape/controller/ReservationController.java
> +    }
스프링은 어떤 주입 방식을 제공하는지, 그 중에 생성자 주입 방식의 장점이 무엇인지 알려주세요 😊

2024-04-26 05:44 UTC, syoun602 commented on src/main/java/roomescape/controller/ReservationController.java
> +        return ResponseEntity.noContent().build();
엇 이전에 200, 404로 나누어두신걸 삭제하신 이유가 궁금합니다~

> 존재하지 않는 예약의 id에 대한 요청임을 명확히 나타내기 위해 404 Not Found를 응답으로 내려주었습니다!
조금 더 찾아보니 삭제할 리소스가 존재하지 않는 경우에 대해서는 크게 200 OK와 404 Not Found 로 의견이 갈리는 것 같았습니다.

또한, 전에 코멘트를 남겨주신 것에 대해 답변을 안드렸더라구요 😭 지금이라도 코멘트 달아보자면 이 부분은 확실히 명확한 해답이 없는 부분이라 저도 팀에 맞춰서 하는 것 같아요. 다만 개인적인으로 "서버의 입장만" 생각했을 때는 404가 맞다고 생각합니다.
하지만 서비스의 경우 프론트와 같이 일을 할 때 혼동을 줄 수 있기 때문에 추후 팀프로젝트를 할때 함께 조율해보면 좋은 경험이 될 것 같아요 😊

2024-04-26 05:44 UTC, syoun602 commented on src/main/java/roomescape/domain/reservation/ReservationRepository.java
> +public interface ReservationRepository {
인터페이스 분리가 꼭 필요한 상황인가요? 왜 분리하셨을까요?

2024-04-26 05:44 UTC, syoun602 commented on src/main/java/roomescape/domain/time/Time.java
> +    // TODO: DTO 분리
주석은 제거하는 방향으로 변경해주세요~

2024-04-26 05:44 UTC, syoun602 commented on src/main/java/roomescape/dto/reservation/ReservationRequest.java
> +public final class ReservationRequest {
final 클래스를 여기에만 적용하신 이유가 있으신가요~?

2024-04-26 05:44 UTC, syoun602 commented on src/main/java/roomescape/dto/reservation/ReservationRequest.java
> +    @Override
dto에 대한 eq&hc를 진행할 일이 있나요??

2024-04-26 05:44 UTC, syoun602 commented on src/main/java/roomescape/domain/time/Time.java
> +public class Time {
ReservationTime으로 조금 더 의미있는 이름을 부여해보면 어떨까요?

2024-04-26 05:44 UTC, syoun602 commented on src/main/java/roomescape/dto/time/TimeRequest.java
> +public record TimeRequest(LocalTime startAt) {
이번엔 여기만 record 네요 👀
전체적인 프로젝트 포맷을 선정해서 적용해볼까요?

2024-04-26 05:44 UTC, syoun602 commented on src/main/java/roomescape/repository/ReservationRepositoryImpl.java
> +public class ReservationRepositoryImpl implements roomescape.domain.reservation.ReservationRepository {
```suggestion
public class ReservationRepositoryImpl implements ReservationRepository {
```

2024-04-26 05:44 UTC, syoun602 commented on src/main/java/roomescape/repository/ReservationRepositoryImpl.java
> +@Primary
@primary는 어떤 의도로 작성하셨을까요?

2024-04-26 05:44 UTC, syoun602 commented on src/main/java/roomescape/repository/ReservationRepositoryImpl.java
> +        };
여기도 time과 같이 row mapper를 분리하는건 어떨까요~?

2024-04-26 05:44 UTC, syoun602 commented on src/main/java/roomescape/repository/TimeRepository.java
> +@Repository
현재 클래스를 repository라 생각하신 이유가 궁금합니다. repository와 dao는 어떤 차이가 있나요?

2024-04-26 05:44 UTC, syoun602 commented on src/main/java/roomescape/service/ReservationTimeService.java
> +                .map(reservation -> ReservationResponse.from(reservation))
```suggestion
                .map(ReservationResponse::from)
```

2024-04-26 05:44 UTC, syoun602 commented on src/main/java/roomescape/service/ReservationTimeService.java
> +        Time time = timeRepository.findById(timeId);
```suggestion
        Time time = timeRepository.findById(reservationRequest.timeId());
```
개인적으로 이정도 변수는 넣어주는 편인데, 이건 땡이의 스타일에 따라 수정할지 말지 경정해주세요!

2024-04-26 05:44 UTC, syoun602 commented on src/main/java/roomescape/service/ReservationTimeService.java
> +        Reservation responseReservation = reservationRepository.create(requestReservation);
도메인을 먼저 생성하고 잘 저장해주셨네요 👍
다만 request, response를 붙이기보다는 reservation, savedReservation으로 나눠보는건 어떨까요?

2024-04-26 05:44 UTC, syoun602 commented on src/main/java/roomescape/service/ReservationTimeService.java
> +                .map(time -> TimeResponse.from(time))
```suggestion
                .map(TimeResponse::from)
```

2024-04-26 05:44 UTC, syoun602 commented on src/main/java/roomescape/service/ReservationTimeService.java
> +public class ReservationTimeService {
하나의 서비스에서 모든 동작을 하고 있는데 아직은 비즈니스 로직을 포함하지 않아서 덜 복잡한 것 같지만,
추후에 서비스가 커진다면 너무 많은 역할을 맞고 있을 것 같아요.

예약과 시간에 대한 동작을 두 서비스로 분리해보는건 어떤가요?

2024-04-27 03:46 UTC, J-I-H-O commented on src/main/java/roomescape/service/ReservationTimeService.java
> +        Reservation responseReservation = reservationRepository.create(requestReservation);
해당 변수명이 request, response DTO와 유사해서 혼동이 있을 수 있겠네요!
비슷하게 작성한 부분 포함 수정 완료했습니다 👍

2024-04-27 03:50 UTC, J-I-H-O commented on src/main/java/roomescape/service/ReservationTimeService.java
> +        Time time = timeRepository.findById(timeId);
단순히 getter를 호출해주는 정도는 변수로 분리하지 않아도 괜찮을 것 같습니다 👍

2024-04-27 03:56 UTC, J-I-H-O commented on src/main/java/roomescape/dto/reservation/ReservationRequest.java
> +public final class ReservationRequest {
record를 적용하던 과정에서 실제로 어떤 코드가 작성되는지 보려고 intelij 기능을 이용해 class로 되돌려 보았습니다.
다시 record로 돌려놓는걸 잊고 코드가 그대로 남아있었네요 😅

2024-04-27 04:01 UTC, J-I-H-O commented on src/main/java/roomescape/dto/reservation/ReservationRequest.java
> +    @Override
> record를 적용하던 과정에서 실제로 어떤 코드가 작성되는지 보려고 intelij 기능을 이용해 class로 되돌려 보았습니다.
다시 record로 돌려놓는걸 잊고 코드가 그대로 남아있었네요 😅

마찬가지의 상황 입니다 😥 전체적으로 수정하겠습니다!

2024-04-27 04:46 UTC, J-I-H-O commented on src/main/java/roomescape/dto/time/TimeRequest.java
> +public record TimeRequest(LocalTime startAt) {
전체적으로 DTO를 record로 통일했습니다!
record 사용한 근거는 boilerplate 코드를 제거하고 더 간결하게 표현하기 위함입니다.

2024-04-27 07:33 UTC, J-I-H-O commented on src/main/java/roomescape/controller/ReservationController.java
> +        return ResponseEntity.noContent().build();
이전에 관련 내용을 조사해보았을 때, 2xx 상태 코드를 내려주는 쪽의 의견이 조금 더 설득력 있다고 생각했습니다.

특히 `삭제 대상이 실제로 삭제된 것과 처음부터 존재하지 않는 상태인 것은 결국 같은 결과이므로 모두 삭제 요청이 성공한 것으로 볼 수 있다` 는 주장이 와닿았습니다.

정답이 없는 주제인 만큼 팀원들과 충분한 논의를 통해 설득력 있는 쪽을 받아들이는게 좋다고 생각합니다. 그런 의미에서 404를 내려주는 쪽에 더 좋은 의견이 있다면 다시 생각이 바뀔 수도 있을 것 같습니다.

주관이 없어 보일 수도 있겠지만, 일단은 제 생각에 더 타당해 보이는 쪽을 수용하며 저만의 주관을 키워나가고자 합니다 😏

2024-04-27 08:26 UTC, J-I-H-O commented on src/main/java/roomescape/repository/ReservationRepositoryImpl.java
> +        };
기존 방식에서는 요청이 들어올 때마다 RowMapper를 생성하겠네요 🤯

상수 분리는 가독성과 코드 중복을 제거하기 위함이라고만 생각했는데, 매번 객체를 생성하지 않고 재사용하기 위해서도 사용할 수 있겠군요...!!

2024-04-27 13:30 UTC, J-I-H-O commented on src/main/java/roomescape/repository/ReservationRepositoryImpl.java
> +        };
기존 방식에서는 요청이 들어올 때마다 RowMapper를 생성하겠네요🤯

상수 분리는 가독성과 코드 중복을 제거하기 위함이라고 생각했는데, 매번 객체를 생성하지 않고 재사용하기 위해서도 사용할 수 있겠네요..!!

2024-04-27 13:43 UTC, J-I-H-O commented on src/main/java/roomescape/domain/reservation/ReservationRepository.java
> +public interface ReservationRepository {
미션을 진행하며 Collection을 사용해 데이터를 저장하던 기존 방식에서 H2에 저장하는 방식으로의 전환이 필요했습니다.
이때 각각의 방식을 구현한 `InMemoryReservationRepository` 와 `H2ReservationRepository` 두 가지의 클래스가 생기게 되었습니다. 

(PR을 보낸 시점에는 `InMemoryReservationRepository` 는 사용하지 않는 상태라 파일을 지우고 `H2ReservationRepository` 의 이름을 `ReservationRepositoryImpl` 로 변경 했습니다.)

이 과정을 겪으며 유연하게 구현 로직을 갈아끼울 수 있는 방법에 대해 고민하게 되었고, 구현체에 직접적으로 의존하지 않도록 인터페이스를 분리 해두었습니다.

하지만 지금은 인터페이스 별로 하나의 구현체만을 가지고있기 때문에 과한 설계가 아닌가 생각이 듭니다. 추후에 또다른 구현체가 필요한 상황이 오더라도 인터페이스 또한 수정되어야 할 가능성이 높은 것 같습니다.
일단 과감히 삭제하고, 추후에 필요할 때 다시 부활시키는 것으로 해야겠습니다 😆

2024-04-27 14:09 UTC, J-I-H-O commented on src/main/java/roomescape/repository/ReservationRepositoryImpl.java
> +@Primary
불필요한 코드가 삽입되어 있네요 😥

미션을 진행하면서 `ReservationRepository` 인터페이스의 구현체 두 개가 생기게 되었습니다.
의존성을 주입할 때 해당 구현체를 주입하겠다는 것을 명시하기 위해 `@Primary` 어노테이션을 붙여주었습니다.

PR을 보낼 때에는 하나의 구현체만 남겨두었고, 결정적으로 현재는 인터페이스를 제거했기 때문에 더이상 `@Primary` 어노테이션이 불필요한 상황입니다.

제거 완료했습니다 👍

2024-04-27 14:32 UTC, J-I-H-O commented on src/main/java/roomescape/service/ReservationTimeService.java
> +public class ReservationTimeService {
말씀 주신대로 `ReservationTimeService` 는 크게 복잡하지 않습니다.
때문에 분리의 필요성을 느끼지 못했습니다!

저는 필요성이 느껴질 때 분리하는게 좋다고 생각합니다.
미리 분리해두면 실제로 필요한 것에 비해 과한 설계가 들어가기도 하고, 완성되지 않은 코드를 리팩토링 했을 때 오히려 변경해야 할 지점이 많아지는 느낌이 들기도 했습니다.

따라서 지금으로써는 분리해야만 하는 상황을 마주했을 때 두 개의 서비스로 분리할 것 같습니다! 😏

2024-04-27 14:52 UTC, J-I-H-O commented on src/main/java/roomescape/domain/time/Time.java
> +public class Time {
한 번 적용해보았는데요, 전체적으로 Reservation 이라는 표현이 너무 많아져 가독성이 떨어지는 것 같았습니다 🤔

미션에서 제공하는 API 스펙에서도 time 이라는 표현을 사용하는걸 고려해 보았을 때, 이 부분은 추후에 예약 시간이 아닌 다른 개념의 시간 (방탈출 오픈 및 마감 시간 등)이 추가되었을 때 고려해봐도 좋을 것 같았습니다!

2024-04-27 15:32 UTC, J-I-H-O commented
안녕하세요 썬! 😎

남겨주신 리뷰에 코멘트 달아두었어요!
고민해볼만한 포인트를 자세히 짚어주셔서 관련된 부분에 대해 생각해볼 수 있는, 의미 있는 시간이 되었습니다 😊

이번 리뷰에는 저 나름대로의 주관을 가지고 임해보려 노력했습니다!
하지만 정성껏 남겨주신 코멘트를 무시하는 것 처럼 느껴질까봐 한편으로는 걱정되기도 하네요 😥
리뷰어 입장에서 리뷰이가 어떤 자세로 임하는 것이 바람직하다고 느껴지는지 궁금합니다.

그럼 잘 부탁드리겠습니다! 감사합니다!

2024-04-28 15:08 UTC, syoun602 requested changes
안녕하세요 땡이~

주말인데도 불구하고 열심히 리뷰 적용해주신거 확인했습니다 👍
몇 가지 더 남겨보았는데, 확인하시고 재요청 주세요 😊

2024-04-28 15:08 UTC, syoun602 commented on src/test/java/roomescape/repository/ReservationRepositoryTest.java
> +        assertThat(reservations.size()).isEqualTo(1);
create를 테스트하고 있는데, findAll까지 호출되어야 할까요 👀
현재는 id를 직접 넣어서 생성하고 있는데, jdbcTemplate를 활용해보면 어떨까요?

2024-04-28 15:08 UTC, syoun602 commented on src/main/java/roomescape/domain/time/Time.java
> +public class Time {
직접 적용해보고 롤백했다니 좋은 방향으로 학습 중이시네요 💯
저도 개발에서 주관이 가장 중요하다고 생각합니다.
말씀하신대로 지금처럼 온전히 납득이 된다면 적용하시면 됩니다 😊

2024-04-29 03:22 UTC, J-I-H-O commented on src/main/java/roomescape/service/ReservationTimeService.java
> +public class ReservationTimeService {
`ReservationTimeService` 를 `ReservationService` 와 `TimeService` 로 분리했습니다!

기존의 `ReservationTimeService` 는 예약과 시간 관리의 책임을 모두 가지고 있었기 때문에 단일 책임 원칙을 위반할 것 같습니다.
이렇게 되면 예약과 시간, 각각의 변경 사항이 하나의 `ReservationTimeService` 에 영향을 미치겠네요.

클래스가 복잡하지 않더라도 정말 하나의 역할만 수행하고 있는지 먼저 생각해보는 습관을 들이는게 좋겠습니다 😊

2024-04-29 06:14 UTC, J-I-H-O commented on src/test/java/roomescape/repository/ReservationRepositoryTest.java
> +        assertThat(reservations.size()).isEqualTo(1);
**1. create를 테스트할 때 findAll을 호출하는 문제**

`findAll` 을 호출하는 경우 DB에서 reservation 테이블의 전체 row를 조회하고, 조회 결과를 자바 객체로 매핑하는 과정까지 수행해야 합니다!

현재 테스트에서는 `등록된 예약의 수` 만을 필요로 합니다.
따라서 전체 테이블을 조회하기 보단, JdbcTemplate을 사용해서 count 쿼리를 날리는 편이 효율적일 것 같습니다.

또 `create` 를 테스트함에 있어 또 다른 테스트 대상인 `findAll` 을 사용하는 것이 테스트를 불안정하게 만들 수 있다는 생각이 들었습니다. 
`create` 테스트가 실패할 때 `create()` 가 잘못 작성된 것인지, `findAll` 의 구현이 잘못된 것인지 모호해지기 때문입니다.
다만 이 경우에는 `findAll` 이 충분히 검증된 상태라면 괜찮을 것 같습니다 😊

2024-04-29 06:28 UTC, J-I-H-O commented on src/test/java/roomescape/repository/ReservationRepositoryTest.java
> +        assertThat(reservations.size()).isEqualTo(1);
**2. id를 직접 넣어 객체를 생성하는 문제**

기존에는 id를 직접 하드코딩 해서 객체를 생성하는 방식을 사용하고 있었습니다. 
하지만 이 경우 DB에서 제공하는 auto increment의 이점을 누릴 수 없게 됩니다.

만약 테스트가 변경되어 DB에 이미 해당 (하드 코딩된) id를 가지는 예약이 존재하는 상태가 된다면, 테스트가 정상적으로 수행되지 않을 것으로 예상됩니다.

따라서 먼저 id 값이 없는 Reservation을 DB에 저장해 id를 얻어내고, 
id를 갖는 완전한 Reservation 객체를 테스트에서 사용하도록 변경했습니다.

2024-04-29 06:29 UTC, J-I-H-O commented on src/test/java/roomescape/repository/ReservationRepositoryTest.java
> +        assertThat(reservations.size()).isEqualTo(1);
추가로 delete 메서드를 테스트하는 코드에서 삭제 대상의 id를 하드코딩했던 부분을 getter를 사용하도록 변경했습니다. 

```java
reservationRepository.delete(1L);  // 변경 전
```
```java
reservationRepository.delete(saved.getId());  // 변경 후
```

따라서 실제로 존재하는 reservation 만을 삭제할 수 있도록 변경했습니다.

의도하신 대로 리뷰가 반영되었는지 확인 부탁드리겠습니다!

2024-04-29 07:45 UTC, J-I-H-O commented on src/main/java/roomescape/service/ReservationTimeService.java
>  @Service
스프링에서는 컴포넌트 스캔 과정에서 `@Component` 어노테이션이 붙어있는 클래스를 빈으로 등록합니다.

이 때 `@Controller`, `@Service`, `@Repository`, `@Configuration` 어노테이션 내부에는 `@Component` 가 붙어있어 이들도 스프링 빈으로 등록됩니다.

이들은 각각 아래와 같은 특징을 가집니다.

- **`@Controller`**
    - 해당 클래스가 스프링 MVC에서 controller 역할을 수행함을 알려줍니다.
- **`@Service`**
    - 해당 클래스가 비즈니스 로직을 처리하는 클래스임을 개발자로 하여금 명시적으로 알 수 있도록 해줍니다.
    - 그 외의 특별한 처리는 해주지 않습니다.
- **`@Repository`**
    - 해당 클래스가 데이터 액세스 계층임을 알려줍니다.
    - 또한 데이터 계층의 예외를 한 단계 추상화하여 스프링의 `DataAccessExeption` 의 서브 클래스로  자동으로 변환시켜줍니다.
    - 이로 인해 DB마다 다른 예외가 발생해도 서비스 단에 영향을 끼치지 않게 됩니다.
- **`@Configuration`**
    - 해당 클래스가 스프링의 설정 정보임을 알려줍니다.

2024-04-30 08:56 UTC, syoun602 approved these changes
안녕하세요 땡이!

예약 관리 미션 수고 많으셨습니다 👏👏
좋은 방향으로 학습 중인 것 같네요 💯
이번 미션은 이만 머지하겠습니다! 다음 사용자 예약 미션도 그럼 화이팅하세요 💪

2024-04-30 08:56 UTC, syoun602 commented on src/test/java/roomescape/repository/ReservationRepositoryTest.java
> +        assertThat(reservations.size()).isEqualTo(1);
jdbcTestUtils는 저도 처음봐서 조금 살펴봤는데, count 쿼리를 생성해서 날려주는군요.
이전의 테스트보다는 훨씬 좋은 방향인 것 같습니다 💯 delete 부분도 👍👍

심화) 테스트 환경의 디비가 (보통은 안그러겠지만) 데이터가 수백~수천만건 있다면 
count 쿼리가 결국 전체를 데이터를 확인해야해서 테스트 실행 성능에 문제가 있을 수 있을 것 같아요. 
지금 당장 고민해볼건 아니고 미션과 테스트를 계속 진행해보면서 땡이만의 테스트 전략을 수립해나가봅시다 👍

2024-04-30 08:56 UTC, syoun602 commented on src/main/java/roomescape/service/ReservationTimeService.java
>  @Service
넵 잘 알고 계시네요 👍👍
이미 학습하고 아셨을 수도 있지만, 만약 관습적으로 사용하셨다면 한번씩 의문을 가지고 
확인해보는 습관을 들이면 더 좋은 학습이 될 것 같아서 여쭤봤습니다 😊

2024-04-30 08:56 UTC, merged