[10단계 - 방탈출 예약 관리] 명오 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #173
Opened 2024-04-26 07:58 UTC by HyungHoKim00

안녕하세요 호돌! 10단계를 마치고 돌아왔습니다.

이번에 생긴 문제 중 하나는 Test 실행 시 consoleRunner에서 입력을 무한대로 받는 현상이였습니다.

다른 크루의 리뷰를 참고하여 `@Profile`를 사용해 해결했는데, 호돌이 선호하는 방법이 있다면 알려주시면 감사하겠습니다.

이번 과정에서 FakeDao들을 DB와 분리했는데요, Dao가 하나의 DB를 사용하는 것이 아닌 ForeignKey의 영향을 받고 있다면 불가피한 현상이라고 생각했습니다.

또다시 잘부탁드립니다!

2024-04-27 02:47 UTC, kimhodol requested changes
안녕하세요 명오 :)

10단계도 멋지게 구현해주셨네요.

코멘트 확인 부탁드릴게요!

2024-04-27 02:47 UTC, kimhodol commented on src/main/java/roomescape/console/Command.java
> +                .get();
의견) NPE가 날 수 있을 것 같아요.

2024-04-27 02:47 UTC, kimhodol commented on src/main/java/roomescape/console/ConsoleController.java
> +        }
의견) 인덴트를 1 이하로 지켜주세요.

2024-04-27 02:47 UTC, kimhodol commented on src/main/java/roomescape/console/ConsoleController.java
> +            System.out.println(e.getMessage());
의견) 예외 메세지도 OutputView를 통해 출력해주는 것은 어떨까요?

2024-04-27 02:47 UTC, kimhodol commented on src/main/java/roomescape/console/ConsoleRunner.java
> +@Profile("!test")
의견) ConsoleRunner은 !test 프로파일보다는 console 프로파일일때 실행되는게 더 자연스러울 것 같아요.

2024-04-27 02:47 UTC, kimhodol commented on src/main/java/roomescape/console/InputView.java
> +        throw new IllegalArgumentException();
의견) 사용자가 읽기 쉬운 메세지를 작성해주면 좋을 것 같습니다.

2024-04-27 02:47 UTC, kimhodol commented on src/main/java/roomescape/console/InputView.java
> +        String[] split = input.split(",");
의견) 의미 있는 문자열은 상수화해주세요!

2024-04-27 02:47 UTC, kimhodol commented on src/main/java/roomescape/console/fake/FakeReservationDb.java
> +public class FakeReservationDb {
의견) 사소하긴한데, Fake보다는 InMemoryReservationDb가 어떨까요?

2024-04-27 02:47 UTC, kimhodol commented on src/main/java/roomescape/console/fake/FakeReservationDb.java
> +                .filter(entry -> entry.getValue().getTime().getId() == timeId)
의견) Reservation이 직접 hasSameTimeId를 가지고 있으면 더 좋을 것 같아요.

2024-04-28 05:20 UTC, HyungHoKim00 commented on src/main/java/roomescape/console/Command.java
> +                .get();
콘솔에서 실행한다는 것을 "나 자신 혹은 사용법을 아는 개발자만 사용할거야" 라는 생각으로 엄격하게 만들지 않았던 것 같습니다.
이 또한 레벨 1에서 열심히 지켰던 것들을 위반했던 것 같네요.
에러 발생을 줄이도록 수정했습니다!

2024-04-28 05:28 UTC, HyungHoKim00 commented on src/main/java/roomescape/console/InputView.java
> +        String[] split = input.split(",");
이 부분에 대해선 1단계에서도 많은 고민을 했었는데요, 제가 선호하는 방식은 상수화하지 않는 방향이였습니다. 그 이유는 아래와 같습니다.
1. 요청 메시지를 수정하고 싶을 때, 요청 메서드를 찾아가는 것이 더 빠를 것이라고 생각했습니다. 요청 메서드에서 상수를 다시 눌러서 수정하러가는 것보다 덜 번거로울것이라고 생각했습니다.
2. 상수화에서 얻는 이점 중 하나는 같은 메시지를 동시에 수정하는 것인데, 한번만 쓰이는 경우 그 이점이 사라진다고 느꼈습니다.
3. 1번과 같은 맥락인데, 메서드에서 어떤 문구를 출력하는지 확인하는 것이 빠릅니다.
호돌은 이러한 문자열을 상수화 할 때 어떤 이점이 있다고 생각하는 지 궁금합니다!

2024-04-28 05:30 UTC, HyungHoKim00 commented on src/main/java/roomescape/console/fake/FakeReservationDb.java
> +public class FakeReservationDb {
저도 그러한 네이밍이 더 마음에 드네요! 수정했습니다.

2024-04-28 06:30 UTC, HyungHoKim00 commented
안녕하세요 호돌!

리뷰를 받고 나니, 콘솔 구현을 "웹 구현에서 분리를 잘했는지 확인하는 과정"이라고 생각하여 스스로의 코드에 엄격하지 못했었다는 생각이 드네요 ㅜㅜ 반성중입니다.

콘솔 실행을 분리해봤는데, 호돌의 말씀이 이 방식이 맞는지 확신은 들지 않습니다. (SpringBootApplication 어노테이션을 제거하고, 아예 콘솔 실행시에는 독립적으로 분리)
SpringBootApplication에 ComponentScan이 원래 붙어있는데, 또 붙여서 필터를 사용하는 방식 이외의 방법이 있는지도 궁금합니다.

또다시 잘 부탁드립니다!

2024-04-29 05:10 UTC, kimhodol requested changes
안녕하세요 명오 :)

피드백 반영 잘 해주셨네요!

10단계도 마무리해도 될 것 같은데, 수정하고 싶으신 부분 있으면 마저 정리하시고 리뷰 요청주시면 머지하도록 하겠습니다!

2024-04-29 05:10 UTC, kimhodol commented on src/main/java/roomescape/RoomescapeApplication.java
> +))
의견) Console 관련된 객체들이 스프링 컴포넌트로 등록되어있지는 않으니 요거는 없어도 될 것 같아요! 스프링 컴포넌트로 등록되어있을 때 불필요한 것들을 필터하기 위해 가이드를 드린거였습니다 :)

2024-04-29 05:10 UTC, kimhodol commented on src/main/java/roomescape/domain/Reservation.java
> +        return time.getId() == timeId;
의견) 요것도 time.hasSameId로 가도 될것 같네요!

2024-04-29 05:56 UTC, HyungHoKim00 commented
안녕하세요 호돌~

2주간 저의 코드를 리뷰해주셔서 감사합니다. 덕분에 많은 것을 배워서 좋았습니다!
특히, 질문을 많이 해주셔서 "어떤 방식을 왜 사용하는지"에 대한 생각이 깊어진 것 같습니다.

수고하셨습니다!

2024-04-29 05:57 UTC, kimhodol approved these changes
안녕하세요 명오 :)

10단계까지 정말 수고 많으셨어요.

다음 미션도 화이팅입니다!

2024-04-29 05:57 UTC, merged