[1 - 3단계 - 방탈출 예약 관리] 폭포(이성주)) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #20
Opened 2024-04-16 13:35 UTC by BurningFalls

안녕하세요, 제이! 폭포입니다. 체스 미션에 이어 또 뵙게 돼서 기쁩니다. 😄 

1 - 3단계 방탈출 예약 관리 구현 완료하여 PR 보냅니다.

리뷰 부탁드립니다. 감사합니다.

## 웹 개발 경험

* `flask` 서버 프레임워크를 사용하여 로컬에서 돌아가는 간단한 웹 애플리케이션을 구현해본 적 있습니다.
* `spring`은 경험이 없습니다.

2024-04-17 01:48 UTC, JunHoPark93 requested changes
안녕하세요 폭포~
또 만났네요! 첫 미션 구현 잘해주셨습니다.
생각할것들 위주로 몇가지 코멘트 남겼는데 확인해보시고 답글 남겨주세요~

2024-04-17 01:48 UTC, JunHoPark93 commented on src/main/java/roomescape/controller/ReservationController.java
> +public class ReservationController {
controller를 잘 만들어보셨네요 👍🏼

학습플랫폼내 API에 대한 문서 읽어보셨나요? API가 뭔지 정리해서 코멘트 남겨주시면 좋을거같아요.

2024-04-17 01:48 UTC, JunHoPark93 commented on src/main/java/roomescape/controller/ReservationController.java
> +    @GetMapping("")
중괄호를 빼면 어떻게 될까요?

2024-04-17 01:48 UTC, JunHoPark93 commented on src/main/java/roomescape/controller/dto/ReservationDto.java
> +    }
필요없지 않을까요? 🤔

2024-04-17 01:48 UTC, JunHoPark93 commented on src/test/java/roomescape/MissionStepTest.java
> +    void 이단계() {
테스트 이름도 명시적으로 작성부탁드려요~

2024-04-17 01:48 UTC, JunHoPark93 commented on src/main/java/roomescape/controller/ReservationController.java
> +    public Reservation createReservation(@RequestBody ReservationDto reservationDto) {
작성주신 애노테이션들은 어떤 역할을 하게 될까요? 3가지에 대해 역할을 정리해서 코멘트 남겨주시면 좋을거같아요.

2024-04-17 01:48 UTC, JunHoPark93 commented on src/main/java/roomescape/controller/ReservationController.java
> +    public ResponseEntity<Void> deleteReservationById(@PathVariable("id") long id) {
리소스를 삭제해보셨네요 👍🏼 

응답내용이 없도록 구현해주셨는데, 현재 http 응답코드는 어떻게 내려가게될까요?

2024-04-17 01:48 UTC, JunHoPark93 commented on src/main/java/roomescape/controller/AdminController.java
> +        return "admin/index.html";
로컬환경에서 잘 구동되는것 확인했습니다 👍🏼

폭포가 생각하는 로컬환경이란 무엇일까요?

2024-04-17 06:52 UTC, BurningFalls commented on src/main/java/roomescape/controller/ReservationController.java
> +public class ReservationController {
API에 대해 직접 정리해본 내용은 다음과 같습니다. 

API는 Application Programming Interface의 약자로, 복잡한 프로그래밍 기능을 간단한 방식으로 실행할 수 있게 해주는 도구이다. 이 인터페이스를 통해 개발자는 소프트웨어 내부의 복잡한 구현을 알 필요 없이 미리 정의된 방식으로 쉽게 사용할 수 있다. 이는 유저 인터페이스(UI)가 사용자를 위해 복잡한 기능을 간단하게 제공하는 것과 비슷하지만, API는 대상이 개발자이다.

프론트엔드 개발자와 백엔드 개발자는 API 명세서를 공유함으로써 효율적으로 협력한다. 백엔드 개발자는 기능을 구현하고 데이터를 어떻게 전달할지를 명세한다. 프론트엔드 개발자는 이 명세를 바탕으로 사용자 인터페이스를 구현한다. 여기서는 주로 JSON 형태의 데이터가 교환된다.

RESTful API는 웹 표준규약인 HTTP를 기반으로 작동하며, 리소스의 상태에 따라 GET(조회), POST(생성), PUT(변경), DELETE(삭제) 네 가지 주요 메서드를 사용한다. 이 메서드들은 웹 애플리케이션에서 자원을 효율적으로 관리하도록 설계되었다.

2024-04-17 06:57 UTC, BurningFalls commented on src/main/java/roomescape/controller/ReservationController.java
> +    @GetMapping("")
혹시 큰따옴표를 말씀하시는 걸까요?

`@GetMapping()`와 같이 괄호 안에 아무런 값도 넣지 않으면, 빈 문자열과 동일하게 작동한다는 사실을 새롭게 알게 되었고 이에 맞게 수정했습니다.

2024-04-17 07:33 UTC, BurningFalls commented on src/main/java/roomescape/controller/dto/ReservationDto.java
> +    }
데이터 전달 목적만을 가진 `ReservationDto`를 record로 변경했습니다.

2024-04-17 07:47 UTC, BurningFalls commented on src/test/java/roomescape/MissionStepTest.java
> +    void 이단계() {
테스트를 LMS에 나온대로 작성하였으나, 더 개선할 방법이 있다면 명세에 굳이 얽매일 필요가 없다는 지난 조언이 떠올랐습니다. 따라서 테스트 메서드를 적절하게 분리해서 이름을 명시적으로 바꾸었습니다.

2024-04-17 10:48 UTC, BurningFalls commented on src/main/java/roomescape/controller/ReservationController.java
> +    public Reservation createReservation(@RequestBody ReservationDto reservationDto) {
각각의 annotation에 대해 직접 정리해본 내용은 다음과 같습니다.

* Spring Framework는 컨트롤러 내의 메서드가 처리할 HTTP request의 종류를 명시적으로 선언할 수 있는 편리한 annotation을 제공한다. 이러한 annotation들은 `@RequestMapping`의 특수한 형태로 각각 다른 HTTP 메서드(GET, POST, PUT, DELETE)에 대응되어 사용된다. (`@GetMapping`, `@PostMapping`, `@PutMapping`, `DeleteMapping`)

* `@RequestBody` annotation은 HTTP request body를 자바 객체로 변환하여, 컨트롤러 메서드의 파라미터로 전달하는 데 사용된다. 이 annnotation은 주로 POST나 PUT 요청을 처리할 때 사용된다.

* `@ResponseBody` annotation은 컨트롤러 메서드의 반환값을 HTTP response body로 직접 전송할 때 사용된다. `@ResponseBody`를 메서드에 적용하면, 해당 메서드의 반환값은 View를 거치지 않고 HTTP response body에 직접 쓰여진다.

2024-04-17 10:59 UTC, BurningFalls commented on src/main/java/roomescape/controller/ReservationController.java
> +    public ResponseEntity<Void> deleteReservationById(@PathVariable("id") long id) {
삭제한 `reservation`을 확인하고자 `DELETE`의 response body에 삭제한 `reservation`의 정보를 담는 경우에는 `@ResponseBody` annotation이 필요해집니다.

그러나 LMS의 API 명세에 따르면 예약 취소 API의 response 형태는 다음과 같아야 합니다.

```
HTTP/1.1 200
```

따라서 해당 객체를 찾은 경우 `HTTP/1.1 200 OK`를 반환하고, 객체를 찾지 못해 예외가 발생하면 `HTTP/1.1 500 Internal Server Error`를 반환하도록 구현했습니다.

2024-04-17 11:07 UTC, BurningFalls commented on src/main/java/roomescape/controller/AdminController.java
> +        return "admin/index.html";
저는 하나의 컴퓨터에서 클라이언트와 서버의 역할을 동시에 수행할 수 있는 환경을 로컬환경이라고 생각하고 있습니다.

특정 클라우드 서비스를 사용해서 서로 다른 컴퓨터에 존재하는 클라이언트와 서버가 네트워크를 통해 통신하게 되면, 로컬환경에 반대되는 원격 환경이라고 생각합니다.

2024-04-17 11:15 UTC, BurningFalls commented
안녕하세요, 제이! 빠른 리뷰 감사합니다.

제가 스프링 관련 기본 개념이 아직 많이 부족하다는 사실을 눈치채시고, 자세히는 모르는 무심코 지나쳤던 부분들을 한 번 더 짚어주셨네요 ㅎㅎ. 질문을 던져주신 덕분에 이에 대해서 더 분석할 수 있는 좋은 기회를 가질 수 있었습니다. 감사합니다! 🙇

2024-04-18 06:14 UTC, BurningFalls commented on src/main/java/roomescape/controller/ReservationController.java
> +    public ResponseEntity<Void> deleteReservationById(@PathVariable("id") long id) {
좀더 조사하고 생각해보니, DELETE API를 구현한 method도 `@ResponseBody` annotation을 사용한다면, `@RestController` annotation으로 한 번에 묶을 수 있다는 생각이 들었습니다.

따라서 `deleteReservationById` 메서드가 void를 리턴하도록 수정했습니다.

2024-04-18 06:52 UTC, BurningFalls commented
안녕하세요, 제이! 빠른 리뷰 감사합니다.

제가 스프링 관련 기본 개념이 아직 많이 부족하다는 사실을 눈치채시고, 자세히는 모르는 무심코 지나쳤던 부분들을 한 번 더 짚어주셨네요 ㅎㅎ. 질문을 던져주신 덕분에 이에 대해서 더 분석할 수 있는 좋은 기회를 가질 수 있었습니다. 감사합니다! 🙇

2024-04-18 11:40 UTC, JunHoPark93 commented on src/main/java/roomescape/controller/AdminController.java
> +        return "admin/index.html";
넵 좀더 구체적으로 저희입장에서는 구현한 서버 프로그램을 각자 컴퓨터에서 실행할 때 해당 서버에 접속하기 위해 사용하는 호스트 이름이라고도 볼 수 있습니다.

2024-04-18 11:41 UTC, JunHoPark93 commented on src/main/java/roomescape/controller/ReservationController.java
> +    public ResponseEntity<Void> deleteReservationById(@PathVariable("id") long id) {
다른 여러가지 응답코드들도있으니 여력이 되시면 하나씩 살펴보시면 좋을거같아요.

2024-04-18 11:42 UTC, merged