[1 - 3단계 - 방탈출 예약 관리] 카피(김상혁) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #30
Opened 2024-04-17 05:18 UTC by tkdgur0906

안녕하세요 미르!
저는 카피입니다!

피드백 받으면서 궁금한 것이 생기면 열심히 질문드리겠습니다!

## 이전의 웹 개발 경험
- 스프링을 통한 프로젝트 개발 경험이 있습니다.
- AWS를 통해 배포해본 적이 있습니다.

2024-04-17 13:21 UTC, ddu0422 requested changes
안녕하세요 카피! 미르입니다 :)
방탈출 예약 관리 미션 구현하느라 고생 많으셨습니다!
몇 가지 코멘트 남겼으니 확인 부탁드립니다
궁금한 점이 있으면 언제든지 코멘트 남겨주시거나 DM주세요 😄 

먼저 요청하셨는데 제가 알림을 놓쳤네요 ㅜㅡㅜ
늦게 리뷰드려 죄송합니다 🙏🏻 
다음부턴 알림을 꼼꼼히 확인하도록 하겠습니다.

2024-04-17 13:21 UTC, ddu0422 commented on src/main/java/roomescape/ReservationController.java
> +    public ResponseEntity<List<Reservation>> getReservations() {
ResponseEntity의 응답값에는 어떤 내용이 있을까요?

2024-04-17 13:21 UTC, ddu0422 commented on src/main/java/roomescape/ReservationController.java
> +    public ResponseEntity<List<Reservation>> getReservations() {
ResponseEntity가 아닌 객체를 반환하면 어떻게 될까요?

2024-04-17 13:21 UTC, ddu0422 commented on src/main/java/roomescape/ReservationController.java
> +                .orElseThrow(RuntimeException::new);
예외가 나는 경우 어떤 에러가 나는지 확인하기 어렵지 않을까요?

2024-04-17 13:21 UTC, ddu0422 commented on src/main/java/roomescape/ReservationController.java
> +    public ResponseEntity<Reservation> addReservation(@RequestBody Reservation reservation) {
RequestBody와 ModelAttribute는 어떤 차이가 있을까요?

2024-04-17 13:21 UTC, ddu0422 commented on src/test/java/roomescape/MissionStepTest.java
> +        params.put("time", "15:40");
HashMap을 생성하며 초기화할 수는 없을까요?

2024-04-17 13:21 UTC, ddu0422 commented on src/main/java/roomescape/ReservationController.java
> +                .filter(reservation -> reservation.getId().equals(id))
객체에게 물어보는건 어떨까요?

2024-04-17 13:21 UTC, ddu0422 commented on src/main/java/roomescape/Reservation.java
> +    }
현재 toEntity와 생성자는 어떤 차이가 있는걸까요?

2024-04-17 13:21 UTC, ddu0422 commented on src/main/java/roomescape/Reservation.java
> +    private final Long id;
long, int, Integer 등이 아닌 id를 Long으로 선언하신 이유가 있을까요?

2024-04-18 01:59 UTC, tkdgur0906 commented on src/main/java/roomescape/ReservationController.java
> +    public ResponseEntity<List<Reservation>> getReservations() {
ResponseEntity의 내부 코드를 살펴보았습니다.

ResponseEntity는 HttpEntity를 상속받아 header와 body의 정보를 저장할 수 있고, 상태코드도 저장할 수 있는 것을 확인했습니다!

ResponseEntity를 생성할 때 header와 body의 값은 선택이지만 status의 값은 필수적으로 설정해줘야 하는 것도 볼 수 있었습니다!

2024-04-18 02:33 UTC, tkdgur0906 commented on src/main/java/roomescape/ReservationController.java
> +    public ResponseEntity<List<Reservation>> getReservations() {
ResponseEnitty를 사용하지 않고 List<Reservation> 객체의 값을 body로 보내기 위해서는 ResponseBody가 필요합니다.
ResponseBody가 없다면 해당 api가 500에러가 발생하는 것을 확인하였습니다!

이에 대해서 궁금한 점이 있습니다.
1. ResponseEntity를 사용하여 반환
- ResponseEntity를 생성할 때 header, body, status를 쉽게 설정 가능
 
2. ResponseBody 사용하여 List<Reservation> 반환
- ResponseStatus를 사용하여 상태코드 추가
- header를 직접 추가하는 것이 ResponseEntity에 비해 복잡

두가지 방법을 비교해봤을 때 이렇게 정리해볼 수 있었습니다!
혹시 미르는 컨트롤러의 반환값을 ResponseEntity로 하는 것과 List<Reservation>로 반환하는 것 중 어느 방법을 지양하시는지, 상황에 따라 다른지 궁금합니다!

2024-04-18 04:02 UTC, tkdgur0906 commented on src/main/java/roomescape/ReservationController.java
> +    public ResponseEntity<Reservation> addReservation(@RequestBody Reservation reservation) {
RequestBody는 Json 형태의 http body 데이터를 객체로 변환시킵니다.

ModelAttribute는 form 형태의 htttp body 데이터와 요청 파라미터를 객체에 바인딩합니다!

2024-04-18 04:05 UTC, tkdgur0906 commented on src/main/java/roomescape/ReservationController.java
> +                .orElseThrow(RuntimeException::new);
예외 종류를 IllegalArgumentException으로 수정하고 예외 메시지도 명확히 추가했습니다!

2024-04-18 04:10 UTC, tkdgur0906 commented on src/test/java/roomescape/MissionStepTest.java
> +        params.put("time", "15:40");
Map.of를 사용하여 생성하면서 초기화하도록 수정했습니다!

2024-04-18 04:15 UTC, tkdgur0906 commented on src/main/java/roomescape/ReservationController.java
> +                .filter(reservation -> reservation.getId().equals(id))
Reservation에 isSameReservation이라는 메서드를 만들어 객체에게 물어보는 방식으로 변경하였습니다!

2024-04-18 04:59 UTC, tkdgur0906 commented on src/main/java/roomescape/Reservation.java
> +    private final Long id;
우선 원시값이 아닌 객체로 선언한 이유는 null을 허용하기 위함입니다.
사용자 요청이 들어올 때 id값은 제외하고 들어와 RequestBody에서 객체로 변환될 때 id가 null으로 채워지기 때문에 객체 타입을 사용하였습니다.

Integer 대신 Long을 사용한 이유는 범위가 넓기 때문입니다. Reservation의 개수가 많아질 수 있기 때문에 좀 더 안정적인 Long을 사용하였습니다!

2024-04-18 06:40 UTC, tkdgur0906 commented on src/main/java/roomescape/Reservation.java
> +    }
우선 toEntity로 생성하는 것과 생성자로 생성하는 것에는 큰 차이가 없는 것 같습니다.
toEntity 대신 생성자를 통해서도 동일하게 생성할 수 있기 때문입니다.

현재는 도메인이 가지고 있는 toEntity를 삭제하고 dto를 도입하였습니다.
따로 코멘트 남기겠습니다!

2024-04-18 07:00 UTC, tkdgur0906 commented
Controller에서 사용자로 부터 받는 request와 내보내는 response를 dto로 변경하였습니다.
dto를 통해 원하는 정보만 보여줄 수 있고, 요청을 받을 때 id가 null로 저장되지 않게 하기 위해 dto를 사용했습니다.

## 궁금한점
### 1. dto와 entity간의 변환 로직의 위치
하지만 여기서 고민한 부분은 dto와 entity간의 변환 로직의 위치 입니다.
생각해본 방안은 다음과 같습니다.
1. dto(request) -> entity : request dto내부 변환 메서드
    entity -> dto(request) : entity 내부 변환 메서드

2. dto(request) -> entity :  controller에서 dto의 getter를 사용해 entity를 new로 생성
    entity -> dto(request) : controller에서 entity의 getter를 사용해 dto를 new로 생성

3. dto(request) -> entity :  request dto내부 변환 메서드
    entity -> dto(request) :  request dto 내부 변환 메서드

여기서 3번 방안을 선택하였습니다.
이유는 컨트롤러와 entity가 변환 로직을 알게하고 싶지 않았기 때문입니다.
해당 방식에 대해 어떻게 생각하시는지 미르의 의견이 궁금합니다!

### 2. List 형식으로 Json 반환하는 것
예전에 봤던 글 중에서 List 자체를 Json으로 반환하게 되면 확장성이 좋지 않아 껍데기 역할을 하는 클래스로 감싸 반환하는 것이 좋다라는 내용을 본 적이 있습니다.
미르도 실제로 리스트를 반환하는 경우 감싸 반환하시는지 궁금합니다!

2024-04-18 12:36 UTC, ddu0422 approved these changes
안녕하세요 카피! 미르입니다 :)
구현 잘 해주셔서 이만 머지해도 될 것 같아요.
추가 코멘트는 다음 미션 진행하시면서 확인해주시면 감사하겠습니다 😄 

다음 미션도 화이팅입니다!

2024-04-18 12:36 UTC, ddu0422 commented on src/main/java/roomescape/controller/ReservationController.java
> +    @DeleteMapping("/reservations/{id}")
HTTP의 Delete는 어떤 특성을 지닐까요?

2024-04-18 12:36 UTC, ddu0422 commented on src/main/java/roomescape/dto/ReservationResponse.java
> +    }
> 1. dto와 entity간의 변환 로직의 위치

역질문) 
- 왜 컨트롤러와 entity가 변환 로직을 알면 안되는걸까요?
- dto는 어떤 내용과 가장 연관이 있을까요?
- domain 객체가 변경하면 어떤 내용까지 변경해야할까요?

2024-04-18 12:36 UTC, ddu0422 commented on src/test/java/roomescape/MissionStepTest.java
> +        params.put("time", "15:40");
```java
Map<String, String> maps = new HashMap<>() {{
    put("name", "브라운");
    put("date", "2023-08-05");
    put("time", "15:40");
}};
```
위 방식도 있으니 참고해주세요~

2024-04-18 12:36 UTC, ddu0422 commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
DEFINED_PORT는 무엇일까요?
서버 실행 -> 테스트 코드를 실행하면 어떤 결과가 나올까요?

2024-04-18 12:36 UTC, ddu0422 commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)
선택) `@DirtiesContext`를 사용한 이유가 있을까요?

2024-04-18 12:36 UTC, merged

2024-04-23 08:13 UTC, tkdgur0906 commented on src/main/java/roomescape/controller/ReservationController.java
> +    @DeleteMapping("/reservations/{id}")
저장된 리소스를 삭제할 때 사용하는 http method 입니다.
Delete는 여러번 호출해도 항상 서버에 데이터가 없는 상태를 유지하므로 멱등성을 보장한다고 볼 수 있습니다.
성공 시  200, 202, 204 상태코드를 주로 반환합니다!

2024-04-23 08:34 UTC, tkdgur0906 commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
DEFINED_PORT를 설정하면 테스트를 실행할 때 8080 포트로 실행이 됩니다.
만약 이미 서버가 실행중이어서 8080 포트를 사용중이라면 테스트 코드는 실패합니다!

2024-04-23 08:38 UTC, tkdgur0906 commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)
각 테스트마다 독립적으로 수행할 수 있도록 하기 위해 사용한다고 알고있습니다.
예제 코드에 있어서 그대로 사용했습니다.

하지만 @DirtiesContext를 사용하면 테스트가 상당히 무거워지기 때문에 추후에 테스트에 대해 공부할 때 리팩토링 하는 방법을 학습해보려고 합니다!

2024-04-23 09:04 UTC, tkdgur0906 commented on src/main/java/roomescape/dto/ReservationResponse.java
> +    }
> 왜 컨트롤러와 entity가 변환 로직을 알면 안되는걸까요?

컨트롤러나 entity에 변환 로직을 두면 dto의 변경이 일어났을 경우 컨트롤러와 entity에 접근해 수정해야합니다.
따라서 변경이 미치는 범위를 dto로 한정하는 것이 좋을 것이라 생각했습니다!

> dto는 어떤 내용과 가장 연관이 있을까요?

dto는 클라이언트와 데이터 전달을 할 때의 형식에 관련이 있다고 생각합니다.

>domain 객체가 변경하면 어떤 내용까지 변경해야할까요?

마찬가지로 api명세가 변경되게 된다면 domain 객체의 코드를 수정해야 합니다