[1 - 3단계 - 방탈출 예약 관리] 제리(김민정) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #38
Opened 2024-04-17 05:37 UTC by mzeong

2024-04-17 09:15 UTC, andole98 requested changes
안녕하세요 리뷰어 안돌입니다.

레벨1에서 배운것을 잊지 않고 잘 활용해 주셨네요 :+1: 훌륭합니다.

몇가지 코멘트 남겼습니다. 살펴봐주세요~

2024-04-17 09:15 UTC, andole98 commented on src/main/java/roomescape/controller/AdminController.java
> +public class AdminController {
이 객체는 어떤 역할을 하나요? 이름과 역할이 잘 어울리나요?

`/admin/**` 과 `/reservations` 두가지 종류가 있는것 같아요.

2024-04-17 09:15 UTC, andole98 commented on src/main/java/roomescape/controller/AdminController.java
> +    @GetMapping("admin")
맨 앞에 "/" 가 있는게 좋을것 같아요. `/admin`

2024-04-17 09:15 UTC, andole98 commented on src/main/java/roomescape/controller/AdminController.java
> +        model.addAttribute("reservations", adminService.getAllReservations());
35번 라인이 필요한가요? 없으면 어떻게 되나요?

2024-04-17 09:15 UTC, andole98 commented on src/main/java/roomescape/controller/AdminController.java
> +    }
방금 등록했는데 다시 찾아야 하는게 조금 어색한것 같아요.

`adminService.addReservation()` 의 결과로 id를 알려준다면 다시 찾을 필요가 없을것 같아요.

2024-04-17 09:15 UTC, andole98 commented on src/main/java/roomescape/controller/AdminController.java
> +    public ResponseEntity<Void> cancel(@PathVariable("id") Long id){
```suggestion
    public ResponseEntity<Void> cancel(@PathVariable long id) {
```

`@PathVariable`은 parameter이름과 같다면 굳이 name을 넣어주지 않아도 됩니다.

Long / long의 차이는 무엇인가요? 여기서는 무엇을 사용하는게 좋을까요?

2024-04-17 09:15 UTC, andole98 commented on src/main/java/roomescape/controller/AdminController.java
> +        return ResponseEntity.ok().build();
여기에만 `ResponseEntity`가 사용된 이유가 궁금해요

2024-04-17 09:15 UTC, andole98 commented on src/main/java/roomescape/domain/Reservation.java
> +    private final Long id;
Long / long

2024-04-17 09:15 UTC, andole98 commented on src/main/java/roomescape/domain/Reservation.java
> +    public Reservation(Long id, ReservationDto reservationDto) {
domain이 dto를 아는게 좋을까요?

2024-04-17 09:15 UTC, andole98 commented on src/main/java/roomescape/domain/Reservations.java
> +public class Reservations {
일급컬렉션을 사용하셨네요. 배운걸 잊지 않으신것 같아요 :+1:

2024-04-18 06:08 UTC, mzeong commented on src/main/java/roomescape/controller/AdminController.java
> +        model.addAttribute("reservations", adminService.getAllReservations());
없더라도 무방한 코드입니다!

2단계를 구현할 때 reservation-legacy.html 파일에 아래의 코드를 추가하고 model을 사용했습니다

```
<tr th:each="reservation : ${reservations}">
  <td th:text="${reservation.id}"></td>
  <td th:text="${reservation.name}"></td>
  <td th:text="${reservation.date}"></td>
  <td th:text="${reservation.time}"></td>
</tr>
```

그러나 이후 reservation-legacy.html 파일을 수정할 필요가 없음을 깨닫고 지우는 과정에서 해당 라인을 누락했습니다

2024-04-18 08:29 UTC, mzeong commented on src/main/java/roomescape/controller/AdminController.java
> +        return ResponseEntity.ok().build();
큰 의도 없이 ResponseEntity와 ResponseBody를 혼용해서 사용하였어요 😓
반환값을 void로 두어도 테스트를 만족할 수 있기 때문에 코드를 수정하였습니다

2024-04-18 08:43 UTC, mzeong commented on src/main/java/roomescape/domain/Reservation.java
> +    private final Long id;
이 부분은 둘 중에 어떤 것을 사용해야 할지 고민이 돼요 

현재처럼 AtomicLong을 이용해서 id를 지정하는 상황에서는 nullable이어야 할 이유가 없다고 생각하는데
추후 DB를 적용하면 특정 시점에 객체의 id가 존재하지 않는 상황이 생길 수도 있나 싶어 Long으로 유지했습니다

2024-04-18 09:01 UTC, mzeong commented on README.md
> +### 예약 목록 조회 API
API 명세를 작성해두는 게 개발할 때 편해서 작성했습니다. 다른 개발자가 확인하기에도 편할 것 같았어요

2024-04-18 09:25 UTC, andole98 commented on README.md
> +### 예약 목록 조회 API
뭔가 잘못되었다는 얘기는 전혀 아니에요. 

제리가 느낀 필요함을 많은 개발자가 동시에 느끼고 있어요. 관련한 기술 / 도구들이 많이 있고 현재도 진화하고 있어요.

아마 레벨2에서 관련 도구들을 알게 될 텐데 지금의 느낌이 도움이 되면 좋겠네요.

2024-04-18 09:26 UTC, andole98 commented on src/main/java/roomescape/controller/AdminController.java
> +        model.addAttribute("reservations", adminService.getAllReservations());
model을 다룰줄 아시는군요. 좋아요.

2024-04-18 09:26 UTC, andole98 commented on src/main/java/roomescape/domain/Reservation.java
> +    private final Long id;
DB와 관련한 내용은 미션 어디에도 찾을수 없네요

2024-04-18 11:14 UTC, mzeong commented on src/main/java/roomescape/domain/Reservation.java
> +    private final Long id;
안돌이 정확한 지적을 해주셨네요 😂

2024-04-18 11:39 UTC, andole98 approved these changes
잘 구성해주셨네요. 다음 스텝 진행해주세요~

2024-04-18 11:39 UTC, andole98 commented on src/main/java/roomescape/controller/ReservationController.java
> +    @GetMapping()
어노테이션에 아무 인자도 없다면 괄호를 생략합니다.
```suggestion
    @GetMapping
```

2024-04-18 11:39 UTC, merged