[1, 2, 3 단계 - 방탈출 예약 관리] 미아(이종미) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #4
Opened 2024-04-16 08:56 UTC by jongmee

안녕하세요 수달! Level 2 첫 미션 잘 부탁드립니다 🙇🏻‍♀️ 

### 웹 개발 경험
- 웹 어플리케이션의 Restful 서버를 만들고 배포해 본 경험이 2회 있습니다. (Thymeleaf를 활용한 프로젝트 경험은 없습니다.)
- 미션에서 활용할 Springboot, Java, JPA, H2를 사용해본 적 있습니다.
- Springboot 공부 및 프로젝트를 시작한 지는 1년이 조금 넘었습니다.

2024-04-17 11:45 UTC, her0807 requested changes
안녕하세요 미아! 

리뷰어 수달입니다 ㅎㅎ
빠르게 구현해주셔서 놀랐어요~ 
커밋 시간을 보니 어제 2시부터 10시 까지 내리 했던데 
열정이 대단합니다. 

미아는 스프링에 대해서 구현 경험이 있다고 하셨는데요!
그래서 적절한 annotation 을 사용해서 spring 으로 view 를 적절히 반환하도록 요구사항이 충족된 것 같아요. 아주 잘하셨습니다.

그런데 레벨 1 때 저희가 연습했던 도메인 객체에 대해서 직접 요구사항을 도출해보고 검증하고, 단위테스트를 해보았던 것들이 코드에서 잘 보이지 않더라고요 ㅠㅠ

물론 요구사항에 적혀있지 않아서 그럴수도 있지만, 저희는 점진적으로 더 나음을 도모해야하니까요! 레벨 1 때 것들도 함께 챙겨나가볼까요?

2024-04-17 11:45 UTC, her0807 commented on README.md
> +  - [ ] 추가
추가, 삭제도 url 을 명시해볼까요? 🙂

2024-04-17 11:45 UTC, her0807 commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    public void deleteById(Long id) {
마이는 repository 는 어떤 책임을 가지고 있다고 생각하나요?

현재 deleteById 에서는

reservation 이 존재하는지 확인하고, 처음찾은 객체를 반환하여 지우는 동작이 연결되어 있는데요. 

존재하지 않으면 예외를 날리는 것은 respository 를 호출하기전에 이미 검증이 되어 있어야한다고 생각해요. repository 는 정말 저장소의 역할처럼 데이터에 관한 작업만 이뤄지고요! 

미아는 어떻게 생각하시나요?

2024-04-17 11:45 UTC, her0807 commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    private final List<Reservation> reservations = new ArrayList<>();
리아! 조금 더 재밌게 데이터 저장 자료형을 고민해보면 어떨까요?😁

List 로 데이터를 저장하게 되면 발생할 수 있는 문제점은 아래와 같아요.

1. 데이터를 조회 할 경우 O(n) 시간 복잡도를 가진다. 
2. 중복된 데이터가 들어갈 수 있다.

2024-04-17 11:45 UTC, her0807 commented on src/test/java/roomescape/MissionStepTest.java
>          RestAssured.given().log().all()
RestAssured 란 무엇이고, 어떻게 사용하는지 아시나요?
테스트 해보신 소감도 궁금해요 😁

2024-04-17 11:45 UTC, her0807 commented on src/main/java/roomescape/domain/Reservation.java
> +public class Reservation {
이전 레벨 1 때 요구사항을 직접 도출해보셨던 경험을 떠올려볼까요?
예약을 할 경우 굉장히 많은 것을 예외처리해야한다고 생각해요.

방탈출을 예약했는데, 예약자명이 올바르지 않다? -? 예약자를 판별하기 어려움.
예약 시간이나 날짜가 들어오지 않았다 -> 올바른 서비스를 제공하기 힘듦
같은 시간에 똑같은 예약이 중복으로 들어왔다 -> 방탈출 같은 경우 한 타임에 서비스할 수 있는 팀 수가 정해져 있기 때문에 중복이 허용된다면 실제로는 5팀 서비스가 가능한데 4팀, 3팀만 서비스를 하게 되는 경우가 있을 수 있음.

예를 들면 아래와 같이 검증을 해볼 수 있을 것 같아요.
1. 예약 이름에 대한 검증 ( 숫자로만 이뤄지거나 일반적인 이름이 아닐경우 예외)
2. 날짜나 시간이 들어오지 않은 경우에 대한 검증
3. 현재 날짜 기준 이전 날짜를 요청한 경우 검증
4. 모든 데이터가 전부 들어왔는지 검증

그래서 개발자가 직접 예외에 대한 처리를 고민하고 적용해주면 비지니스가 더 탄탄해질거예요.
한번 해볼까요?

2024-04-17 11:45 UTC, her0807 commented on src/main/java/roomescape/domain/Reservation.java
> +    public ReservationResponse toDto() {
Dto 는 데이터를 뷰에 뿌려주기 위한 객체인데요. 

domain 이 dto 를 직접 만들어서 반환해주면 뷰의 변경에 따라 도메인에도 변경 영향도가 
전파되어요. 개선해볼까요?

2024-04-17 11:45 UTC, her0807 commented on src/main/java/roomescape/domain/Reservation.java
> +        return this.id.equals(id);
메세지를 보내서 검증하는것 잘하셨습니다. 👍🏻
그런데 테스트가 있나요?

2024-04-17 11:45 UTC, her0807 commented on src/main/java/roomescape/controller/AdminController.java
> +        return "/admin/index";
오~ 미아 타임리프를 통해서 view 를 적절히 반환하도록 잘 구현해주셨네요 👍🏻

그렇다면 원리를 알고 계신지 궁금한데요!
타임 리프에서 static/  하위에 있는 html 파일을 찾아오는 원리가 어떻게 될까요?
.html 이라고 붙이지 않아도 되는 이유는 무엇일까요?

2024-04-17 11:45 UTC, her0807 commented on src/main/java/roomescape/controller/AdminController.java
> +public class AdminController {
Controller 에서 repository 를 바로 의존하고 있는데요, 

그러다보니 도메인에서 DTO 를 만드는 형태로 간결함에 초점을 두고 개발해주신 것 같아요!! 

가독성 좋고 읽기 깔끔하지만, 도메인에 뷰의 변경에 따른 전파가 가기 때문에

service layer 를 두어 검증과 계층 별 의존성 분리 역할을 주면 어떨까요? 😁

2024-04-17 11:45 UTC, her0807 commented on src/main/java/roomescape/controller/AdminController.java
> +    private final AtomicLong index = new AtomicLong(1);
AtomicLong 이 repository 에 id 값을 채워주는 것 같은데요 ~ 
Controller 에서 주입해주는 것이 적절한지 고민해볼까요?

현재는 controller 가 늘어나면 일관된 index 를 보장하기 힘든 형태인 것 같아요.

2024-04-18 05:51 UTC, jongmee commented on README.md
> +  - [ ] 추가
API 요청과 응답에 대한 명세를 추가하였습니다!

2024-04-18 05:55 UTC, jongmee commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    public void deleteById(Long id) {
layered architecture에서 repository는 데이터를 저장하고 불러오는 역할을 하기 때문에 수달이 제시해주신 것처럼 `입력 값 검증`에 대한 역할은 없다고 생각합니다! 현재 단계만 집중하다 보니 계층의 역할에 집중하지 못했네요 🥲

따라서 `Optional<Reservation>`을 반환하는 `findById` 메소드를 만들어 상위 계층에서 이를 검증하도록 변경하였습니다!

2024-04-18 05:58 UTC, jongmee commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    private final List<Reservation> reservations = new ArrayList<>();
두 문제점을 해결할 수 있는 자료구조는 `HashMap`일 것 같습니다 ☺️ 여기에 더해, `index`에 `AtomicLong`을 사용해주는 것처럼 데이터 저장 자료형 역시 Thread-safe한 `ConcurrentHashMap`으로 변경하였습니다.

(Reservation에서 `equals`와 `hashCode`를 재정의해 동일한 id의 예약은 동등성, 동일성 비교가 보장되도록 하였습니다.)

2024-04-18 06:01 UTC, jongmee commented on src/main/java/roomescape/domain/Reservation.java
> +    public ReservationResponse toDto() {
처음에는 `getter`를 최대한 덜 써보고자 해당 메소드를 추가했는데, 말씀해주신 분명한 단점이 존재하는군요..! 해당 메소드를 ReservationResponse의 정적 팩토리 메소드로 대체하였습니다. 고민해보니 응답과 뷰를 위한 `getter`는 불가피한 것 같네요 🥲

2024-04-18 06:05 UTC, jongmee commented on src/main/java/roomescape/domain/Reservation.java
> +        return this.id.equals(id);
해당 메소드는 더이상 필요치 않아서 삭제했지만, Reservation에 필드 검증 로직을 추가하면서 단위 테스트를 작성하였습니다. 테스트 커버리지를 좀 더 신경쓰겠습니다 ! 🥲

2024-04-18 06:09 UTC, jongmee commented on src/main/java/roomescape/controller/AdminController.java
> +    @GetMapping("/reservations")
어드민 페이지(뷰)를 반환하는 요청은 AdminController가, 응답을 반환하는 요청은 ReservationController가 담당하도록 controller를 분리해보았습니다!

2024-04-18 06:14 UTC, jongmee commented on src/main/java/roomescape/controller/AdminController.java
> +    private final AtomicLong index = new AtomicLong(1);
index를 ReservationRepository에서 저장하고, 증가하도록 변경하였습니다. Reservation을 저장하는 Repository에서 관리하므로 일관성을 유지할 수 있기 때문입니다. (라고 생각합니다!)

2024-04-18 06:43 UTC, jongmee commented on src/main/java/roomescape/controller/AdminController.java
> +public class AdminController {
기능 요구 사항을 만족하는 간결한 프로그램을 생각하며 구현하다 보니 전체적으로 도메인이 뷰의 변경에 영향을 받는 구조가 되었네요 🥲 

Service layer를 추가하여 계층 분리를 하고, 검증(예약 id 검증)을 service layer에서 하도록 변경하였습니다. 우선 Presentation 계층인 controller만 dto를 사용하도록 하여 service에서는 dto를 생성하거나, dto에서 entity를 변환하는 로직 등은 존재하지 않도록 구현하였는데, 수달은 이에 대해 어떻게 생각하시나요? 

저는 DTO의 역할이 아래와 같다고 생각합니다. (DTO를 controller에서만 사용한 이유)
1. 뷰의 변경에 도메인이 영향을 받지 않고, 도메인 자체를 뷰에 노출시키지 않는다.
2. 현재 DTO(ReservationResponse, ReservationSaveRequest)는 요청과 응답에서 데이터를 전달하고, 컨트롤러의 역할에서 필요하다.

이것저것 레퍼런스를 찾아보니 의견이 나뉘는 것 같은데(controller에서만 사용한다, controller와 service에서 모두 사용한다) 수달은 현재 현업에서 어떤 의견을 가지고 사용하고 계신지 궁금합니다!

2024-04-18 08:26 UTC, jongmee commented on src/test/java/roomescape/MissionStepTest.java
>          RestAssured.given().log().all()
RestAssured는 Restful API를 테스트하는 라이브러리로, E2E 테스트를 진행할 때 사용하는 것으로 알고 있습니다! given, when, then에 맞추어 빌드해서 테스트를 진행합니다. 현재 테스트에서는 `@SpringBootTest`로 스프링 컨테이너를 올리고`@DirtiesContext`로 매 테스트 전에 ApplicationContext를 초기화(testing framework’s cache에서 제거)하고 있습니다 :)

API 통합 테스트에서 사용하기 편리한 것 같습니다 👍 현재 단계에서는 예외 처리까지 하고 있지 않지만, 다양한 상태 코드 응답에 대해서 테스트하기 편리할 것 같습니다. Postman과 같은 툴로 일일히 테스트하는 것보다 훨씬 편하네요 ㅎㅎ

2024-04-18 12:29 UTC, jongmee commented
안녕하세요 수달! 리뷰에 코멘트 및 질문 남겨놓았습니다 :) 

+ 추가로, 리팩토링 및 추가 검증을 구현하면서 최대한 단위 테스트를 진행하려고 하였습니다!

2024-04-19 00:28 UTC, her0807 commented on src/main/java/roomescape/controller/AdminController.java
> +public class AdminController {
좋은 고민이네요! 

저는 dto는 controller에서 dto -> domain 으로 변환하여 의존성을 끊어서 사용하고 있어요. 
이유는 미아가 말씀해주신 영역도 있고, service layer 가 여러 곳에서 재사용될 여지가 큰데, dto 의 형태가 일정하지 않으니
재사용성에도 좋지 않고, 뷰 변경에 대한 영향도 전파되기 때문이에요!

그러나 재사용성이 적고, 뷰와 도메인이 항상 핏하게 떨어질 경우 혹은 개발 초기 단계에 빠르게 치고 나가야하는 경우에서는 
 controller와 service 모두 혼용해서 사용하기도 하는 것 같아요. 

transfer 한다는 것은 여러 고민들이 수반되어야하기 때문인데요. (어느곳에서 어떤 형태로 변환해줄것인지 등등 또 얼마나 잘게 나눌 것인가에 대한 고민도요!)

다만,service 에서 controller 로 응답값을 반환할 때는 domain -> reseponse dto 로 꼭 변환해주는 편이에요. 
controller 는 model 과 view 사이에 중개자 역할을 하는 것인데 도메인을 반환하게되면 
controller 영역에서 의도치 않게 도메인에 상태를 변경할 수도 있기 때문인데요! JPA 를 써보셨다고 하셔서 첨언드리면
JPA 의 장점 중 하나인 Dirty Checking 이 일어나서 의도치 않게 변경점이 DB 까지 이어지기도 하고요!

2024-04-19 00:38 UTC, her0807 approved these changes
안녕하세요 미아! ㅎㅎ

워밍업 제대로 된 것 같은데요? 🎉
질문주신 내용과 간단한 코멘트들 남겼습니다 :)
해당 코멘트들은 다음 단계 진행하면서 함께 반영해주시면 좋을 것 같아요👍🏻

2024-04-19 00:38 UTC, her0807 commented on src/main/java/roomescape/controller/ReservationController.java
> +@RestController
👍🏻

2024-04-19 00:38 UTC, her0807 commented on src/main/java/roomescape/controller/ReservationController.java
> +        var reservation = request.toReservation();
dto, -> domain 변환할 때 `toModel` 이라는 메서드명을 자주 사용하는 것 같아요 🙂

- https://stackoverflow.com/questions/63679542/generic-mapper-function-in-mapstruct

2024-04-19 00:38 UTC, her0807 commented on src/main/java/roomescape/controller/ReservationController.java
> +@RequestMapping("/reservations")
공통된 url 를 묶어두셨군요 👍🏻 잘하셨습니다

2024-04-19 00:38 UTC, her0807 commented on src/main/java/roomescape/domain/Reservation.java
> +public class Reservation {
아주 꼼꼼하게 잘 작성하신 것 같아요!

2024-04-19 00:38 UTC, her0807 commented on src/main/java/roomescape/service/ReservationService.java
> +        }
검증 로직을 따로 추출해볼까요?

2024-04-19 00:38 UTC, her0807 commented on src/main/java/roomescape/service/ReservationService.java
> +    public void deleteReservation(Long id) {
👍🏻

2024-04-19 00:38 UTC, her0807 commented on src/main/resources/application.properties
> +server.servlet.encoding.force=true
오 해당 속성들은 어떤 이유로 추가하셨나요?

2024-04-19 00:38 UTC, her0807 commented on src/test/java/roomescape/domain/ReservationTest.java
> +        Reservation reservation = new Reservation(USER_MIA, MIA_RESERVATION_DATE, MIA_RESERVATION_TIME);
테스트를 위해 반복 생성되는 객체들은 Test Fixture 로 추출해도 좋을 것 같아요!

2024-04-19 00:38 UTC, her0807 commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +    @DisplayName("동일한 시간대에 최대 4팀이 예약할 수 있다. 초과되면 예외가 발생한다.")
귀여운 요구사항을 적용시켰군요 고마워요 🤩

2024-04-19 00:39 UTC, merged

2024-04-19 05:19 UTC, jongmee commented on src/main/java/roomescape/service/ReservationService.java
> +        }
`private` 메소드로 추출하였습니다 :)

2024-04-19 05:27 UTC, jongmee commented on src/test/java/roomescape/domain/ReservationTest.java
> +        Reservation reservation = new Reservation(USER_MIA, MIA_RESERVATION_DATE, MIA_RESERVATION_TIME);
그렇네요! Reservation 객체도 TestFixture로 추출하였습니다.

2024-04-19 05:44 UTC, jongmee commented on src/main/resources/application.properties
> +server.servlet.encoding.force=true
<img width="1029" alt="스크린샷 2024-04-19 오후 2 35 49" src="https://github.com/woowacourse/spring-roomescape-admin/assets/101439796/20b8aca0-80ed-4af2-abfe-d4eb35d9786a">

처음에 MockMvc로 컨트롤러 슬라이싱 테스트를 할 때 json의 String을 검증했는데 한글 인코딩 때문에 제대로 검증이 되지 않아 해당 설정을 추가했습니다! 하지만 아래처럼 jsonPath로 변경하니(단순 문자열 체크를 하지 않으니) 인코딩 문제가 발생하지 않아 더 이상 해당 설정은 필요 없습니다..!
```
.andExpect(jsonPath("$[0].name").value(USER_MIA))
```

삭제해야 했는데 빠뜨렸네요 🥲 삭제하였습니다!