[1 - 3단계 - 방탈출 예약 관리] 재즈(함석명) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #46
Opened 2024-04-17 06:06 UTC by seokmyungham

안돌 안녕하세요~ 😎
레벨 2의 첫 번째 미션을 리뷰 받게된 재즈라고 합니다 🤗

이전에 김영한님 강의 로드맵을 통해 스프링과 MVC, JPA를 학습한 후 프로젝트를 배포해 본 경험이 있습니다.
그런데 지식의 빈틈이 너무 많은 것 같고, 이번 미션을 통해 많이많이 배우고 싶습니다!! 👨‍👦

코드 봐주셔서 감사드리고
리뷰 기다리고 있겠습니다. 🙇‍♀️

2024-04-17 07:57 UTC, andole98 requested changes
안녕하세요 리뷰어 안돌입니다.

가볍게 요구사항을 잘 만족했네요~

몇가지 코멘트 남겼습니다. 살펴봐주세요.

2024-04-17 07:57 UTC, andole98 commented on src/main/java/roomescape/controller/ReservationApiController.java
> +        return new ResponseEntity<>(reservationResponseDtos, HttpStatus.OK);
채널에서도 적었지만, `ResponseEntity`를 사용한 이유가 있을까요?

아래 코드는 어떤가요?

```java
public List<ReservationResponseDto> getReservations() {
  return reservations;
}
```

2024-04-17 07:57 UTC, andole98 commented on src/main/java/roomescape/controller/ReservationApiController.java
> +@Controller
`@RestController` 대신 `@Controller` 를 사용한 이유가 궁금해요

2024-04-17 07:57 UTC, andole98 commented on src/main/java/roomescape/controller/ReservationApiController.java
> +    public ResponseEntity<Void> deleteReservation(@PathVariable Long id) {
```suggestion
    public ResponseEntity<Void> deleteReservation(@PathVariable long id) {
```

Long 과 long은 무슨 차이가 있을까요?

2024-04-17 07:57 UTC, andole98 commented on src/main/java/roomescape/dto/ReservationRequestDto.java
> +    public ReservationEntity toEntity() {
좋네요~ :+1:

2024-04-17 07:57 UTC, andole98 commented on src/main/java/roomescape/dto/ReservationResponseDto.java
> +    private final Long id;
Long / long ? 어떤걸 사용하는게 좋을까요?

2024-04-17 07:57 UTC, andole98 commented on src/main/java/roomescape/RoomEscapeApplication.java
> +public class RoomEscapeApplication {
camel case를 신경써주셨군요. `RoomEscape`도 괜찮은것 같아요.

패키지명을 참고했을때, `roomescape`는 "방" 을 "탈출" 하는게 아니라 "방탈출", 복합명사로 취급하는것 같아요. 그렇다면 `Roomescape` 가 잘못된건 아닌것 같아요.

만약 인텔리제이가 오타니까 고치라고 한다면, save dictionary 로 노란줄을 지울수 있을거에요.

2024-04-17 07:57 UTC, andole98 commented on src/main/java/roomescape/controller/RoomEscapeController.java
> +public class RoomEscapeController {
이 객체는 어떤 역할을 하나요? "방탈출" 을 제어하나요?

2024-04-17 08:12 UTC, andole98 commented
`@DirtiesContext`에 대해

너무나도 바람직한 생각이에요. 💯 💯 💯 

현업에서 테스트좀 만든다 싶으면 몇천~몇만 개 test suite가 있어요. 모두 `@SpringBootTest` `@DirtiesContext` `@MockBean` 붙어있다면 끔찍하네요. (실제로 있는 일)

매우매우매우 바람직해요. 이 키워드로 알아가다 보면 스프링에서 테스트를 어떻게 지원하고 있는지, 왜 스프링이 인기가 많은지 등을 알수 있을거에요.

2024-04-17 12:33 UTC, seokmyungham commented on src/main/java/roomescape/controller/ReservationApiController.java
> +        return new ResponseEntity<>(reservationResponseDtos, HttpStatus.OK);
`ResponseEntity`를 사용하는 이점은 HTTP 메시지 내용에 따라 유연하게 응답을 처리할 수 있기 때문이에요.

현재 그 이점을 활용할 수 없고, 스프링api 성공 상태 코드 응답 기본 값이 200이라면 굳이 사용할 필요가 없어 보이네요.

수정하겠습니다 👍

2024-04-17 12:46 UTC, seokmyungham commented on src/main/java/roomescape/controller/ReservationApiController.java
> +@Controller
기존에는 `ResponseEntity`로 모두 응답을 반환하다보니 "직관적으로 명시해준다"라는 목적 말고는 `@ResponseBody`, `@RestController`를 사용할 필요가 없다고 느꼈던 것 같아요. 그래서 `@Controller`를 사용하게 되었습니다.

그런데 바로 위 리뷰에서 말한대로 `ResponseEntity`를 목적에 맞게 사용한다면
어떤 메서드는 `ResponseEntity`로 응답을 하지 않아 `@ResponseBody` 어노테이션을 사용하는 상황이 발생하게 되네요.

개인적으로 일관성이 떨어지고 코드가 직관적이지 못하다는 느낌이 들었습니다.
api 응답만을 관리하는 컨트롤러를 사용한다면 `@RestController`를 사용하는게 옳은 것 같습니다.

2024-04-17 13:06 UTC, seokmyungham commented on src/main/java/roomescape/RoomEscapeApplication.java
> +public class RoomEscapeApplication {
비문인 것 같으면서도 패키지 이름 때문에 수정하기 참 애매하다 느꼈는데
해주신 말씀이 맞는 것 같아요. 의견 감사합니다 😄

2024-04-17 15:28 UTC, seokmyungham commented on src/main/java/roomescape/controller/ReservationApiController.java
> +    public ResponseEntity<Void> deleteReservation(@PathVariable Long id) {
음.. id에 long vs Long 양쪽 케이스를 모두 고려해 본다면

primitive type long은 `null`을 허용안하고 기본 값이 0이라, id 값이 0이어서 0인건지 null이어서 0인건지 구분이 될지 의문이 들고
wrapper class Long은 `null`을 허용하니 null이면 id 값이 없다는 것을 구분할 수 있지 않나 생각이 드네요.

id 말고 일반적인 데이터로 접근해보면, 설계에 따라 달라지겠지만 테이블에 데이터가 없는 칼럼은 보통 null 일 것 같은데
Long과 long을 섞어 쓰지만 않으면 괜찮지 않나 생각하고 있습니다.

2024-04-17 15:44 UTC, seokmyungham commented on src/main/java/roomescape/controller/ReservationApiController.java
> +    public ResponseEntity<Void> deleteReservation(@PathVariable Long id) {
음.. id에 long vs Long 양쪽 케이스를 모두 고려해 본다면

primitive type long은 null을 허용안하고 기본 값이 0이라, id 값이 0이어서 0인건지 null이어서 0인건지 구분이 될지 의문이 들고
wrapper class Long은 null을 허용하니 null이면 id 값이 없다는 것을 구분할 수 있지 않나 생각이 드네요.

id 말고 일반적인 데이터로 접근해봤을 때, 
설계에 따라 달라지겠지만 테이블에 데이터가 없는 칼럼은 보통 null이 자연스럽다고 인식할 것 같은데,
long 때문에 0이 들어가게 되면 많이 어색하지 않을까 생각이듭니다.

2024-04-17 16:23 UTC, seokmyungham commented on src/main/java/roomescape/controller/RoomEscapeController.java
> +public class RoomEscapeController {
앗 어떤 의미로 말씀하신 건지 이해했습니다 😅
어드민 관련 웹페이지를 반환하므로 `AdminController`로 수정했습니다.

2024-04-18 02:26 UTC, andole98 commented on src/main/java/roomescape/controller/ReservationApiController.java
> +@Controller
객체이름, 역할기준으로도 생각해볼수 있어요.

어드민 리소스는 html로 서빙하고, Controller

예약 리소스는 api로 서빙한다고 볼수도 있죠 RestController

2024-04-18 02:28 UTC, andole98 commented on src/main/java/roomescape/controller/ReservationApiController.java
> +    public ResponseEntity<Void> deleteReservation(@PathVariable Long id) {
http request에 pathVariable id에 null을 허용하고 싶은 의도가 있는건가요?

2024-04-18 02:28 UTC, andole98 commented on src/main/java/roomescape/controller/ReservationApiController.java
> +    public ResponseEntity<Void> deleteReservation(@PathVariable Long id) {
"테이블"이란 용어는 무엇인가요? 혹시 디비 테이블인가요? 프로젝트 어디에도 디비 관련을 찾을수 없는것 같아요

2024-04-18 02:29 UTC, andole98 commented on src/main/java/roomescape/dto/ReservationResponseDto.java
> +    private final Long id;
`ResponseDto`에서 id는 null이 될수 있나요?

2024-04-18 02:33 UTC, andole98 approved these changes
잘 구현해 주셨네요~ 다음 스텝을 진행해주세요.

코멘트에 답글을 추가했어요. 다음 스텝 진행하기 전에 살펴봐주세요.

2024-04-18 02:33 UTC, merged