[1 - 3단계 - 방탈출 예약 관리] 위브(김기범) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #47
Opened 2024-04-17 06:11 UTC by jimi567

안녕하세요. 미르~
이번 미션의 리뷰이  위브라고 합니다. 
이번 미션 페어는 아톰과 진행했습니다. 아톰이 기존에 spring 경험이 있어서 많이 배우면서 미션을 진행한 것 같습니다.

기존 웹 개발 경험

웹 개발 경험은 없습니다.
프레임워크는 장고, 스프링 정도를 사용해 봤습니다만,
장고는 학교 수업에서 배웠던 수준이고, 스프링은 강의 1년 전에 잠깐 봤던 게 전부입니다.
그래서 생소한 부분을 최대한 학습하며, 미션을 진행했습니다.
아직 공부하는 입장이라 모르는 것이 많아서, 피드백을 받는 과정에서 궁금한 점이 생기면 그때 여쭤볼 것 같습니다.

이번 미션 리뷰 잘 부탁드립니다.!

2024-04-17 10:00 UTC, ddu0422 requested changes
안녕하세요 위브! 미르입니다 :)
방탈출 예약 관리 미션 구현하느라 고생 많으셨습니다!
몇 가지 코멘트 남겼으니 확인 부탁드립니다 🙏🏻 
궁금한 점이 있으면 언제든지 코멘트 남겨주시거나 DM주세요 :)

2024-04-17 10:00 UTC, ddu0422 commented on src/main/java/roomescape/ReservationController.java
> +                .filter(it -> Objects.equals(it.getId(), id))
객체에게 물어보는건 어떨까요?

2024-04-17 10:00 UTC, ddu0422 commented on src/main/java/roomescape/domain/Reservation.java
> +    @JsonFormat(pattern = "HH:mm")
JsonFormat의 사용 목적이 무엇인가요?

2024-04-17 10:00 UTC, ddu0422 commented on src/test/java/roomescape/MissionStepTest.java
> +                .body("size()", is(0));
테스트 코드를 독립적으로 구성하면 어떨까요?
+) 테스트 코드를 독립적으로 작성해야하는 이유는 무엇일까요?

2024-04-17 10:00 UTC, ddu0422 commented on src/main/java/roomescape/ReservationController.java
> +        return ResponseEntity.ok(newReservation);
ResponseEntity는 어떤 내용을 담고 있을까요?

2024-04-17 10:00 UTC, ddu0422 commented on src/main/java/roomescape/ReservationController.java
> +@RestController
RestController 사용 👍🏻

2024-04-17 10:00 UTC, ddu0422 commented on src/main/java/roomescape/AdminController.java
> +package roomescape;
Domain도 별도의 패키지로 옮긴 것처럼 Controller도 별도의 패키지로 이동하는건 어떨까요?

2024-04-17 10:00 UTC, ddu0422 commented on src/main/java/roomescape/CreateReservationRequest.java
> +public record CreateReservationRequest(LocalDate date, String name, LocalTime time) {
Requset 👍🏻

2024-04-17 10:00 UTC, ddu0422 commented on src/main/java/roomescape/ReservationController.java
> +    private final AtomicLong id = new AtomicLong(0);
AtomicLong을 사용하신 특별한 이유가 있을까요?

2024-04-17 10:00 UTC, ddu0422 commented on src/main/java/roomescape/ReservationController.java
> +                .orElseThrow(RuntimeException::new);
에러가 발생하는 경우 어떤 내용인지 알기 어렵지 않을까요?

2024-04-18 03:51 UTC, jimi567 commented on src/main/java/roomescape/ReservationController.java
> +        return ResponseEntity.ok(newReservation);
Http 응답에 관한 내용을 담고 있다고 알고 있습니다.
요구사항의 api명세에 보면 상태 코드에 관한 내용도 포함되어 있어서, ResponseEntity를 사용했습니다.!

2024-04-18 03:53 UTC, jimi567 commented on src/main/java/roomescape/ReservationController.java
> +                .orElseThrow(RuntimeException::new);
구체적인 에러메세지를 작성하도록 해봤습니다.

2024-04-18 04:09 UTC, jimi567 commented on src/main/java/roomescape/ReservationController.java
> +    private final AtomicLong id = new AtomicLong(0);
현재 미션에서는 단일 스레드라서  동시성 문제를 고려할 필요가 없어서, 굳이 사용할 필요는 없지만 
 create 작업을 할 때, id를 증가시키는 작업에서 incrementAndGet() 메소드를 활용하기 위함입니다.
그냥 Long 클래스를 사용하고 증가연산자를 사용해도 되지만, 메소드로 이름을 붙여줄 수 있다는 점에서 이점이 느껴져서 사용했습니다.
Atomic타입은 동기화를 해주지만 CAS 방식이라서 일반적은 동기화보다는 리소스가 덜 든다고 생각해서 사용했지만 역시 지우는게 좋을까요??

2024-04-18 04:10 UTC, jimi567 commented on src/main/java/roomescape/ReservationController.java
> +                .filter(it -> Objects.equals(it.getId(), id))
reservation 클래스에 기능을 추가해서, 객체가 스스로 판단하도록 리팩터링 해봤습니다.!

2024-04-18 04:48 UTC, jimi567 commented on src/main/java/roomescape/domain/Reservation.java
> +    @JsonFormat(pattern = "HH:mm")
날짜 및 시간 표현 방식을 지정해주고, 타임존 설정 등을 하기 위해 사용하는 애노테이션이라고 알고 있습니다.

지금 코드에서 reservation 클래스에서 시간을 저장하는 타입이 LocalTime입니다,
Jackson에서 localtime을 Json으로 직렬화 했을 때,   ISO-8601형식으로 직렬화를 하기 때문에 요구사항에서 원하는 형식과 상이해서 사용하게 되었습니다.

2024-04-18 04:51 UTC, jimi567 commented on src/test/java/roomescape/MissionStepTest.java
> +                .body("size()", is(0));
해당 테스트 코드를 통과 하도록 구현하는 것이 이번 미션의 요구사항 중 일부라서, 그대로 사용했던 것 같습니다.
테스트 명을 변경하기 보다 Displayname을 통해 해당 단계의 테스트가 어떤 테스트인지를 좀 더 명확하게 해봤습니다

2024-04-18 05:09 UTC, jimi567 commented
안녕하세요. 미르 리뷰 감사합니다.
아무래도 웹 개발이 처음이다 보니 제가 리뷰 피드백을 적용하는 과정에서 잘못 이해하거나, 의도 파악을 잘못하는 경우도 있을 것 같아요.! 그런 부분 가감 없이 강하게 말씀해주시면 좋을 것 같습니다.. 미르의 소중한 시간을 뺏는 만큼 많은 것을 배우고 싶습니다.
이번 리뷰도 잘 부탁드립니다.

2024-04-18 05:10 UTC, jimi567 commented
안녕하세요. 미르 리뷰 감사합니다.
아무래도 웹 개발이 처음이다 보니 제가 리뷰 피드백을 적용하는 과정에서 잘못 이해하거나, 의도 파악을 잘못하는 경우도 있을 것 같아요.! 그런 부분 가감 없이 강하게 말씀해주시면 좋을 것 같습니다.. 미르의 소중한 시간을 뺏는 만큼 많은 것을 배우고 싶습니다.
이번 리뷰도 잘 부탁드립니다.

2024-04-18 11:23 UTC, ddu0422 approved these changes
안녕하세요 위브! 미르입니다 :)

꼼꼼하게 학습해주셨네요 💯 💯 
구현 잘 해주셔서 이만 머지하겠습니다.

나머지 코멘트는 다음 미션 진행하며 살펴보시면 어떨까합니다!
다음 미션도 화이팅입니다~

2024-04-18 11:23 UTC, ddu0422 commented on src/main/java/roomescape/controller/ReservationController.java
> +    public ResponseEntity<Reservation> reserve(@RequestBody CreateReservationRequest request) {
RequestBody와 ModelAttribute의 차이는 무엇일까요?

2024-04-18 11:23 UTC, ddu0422 commented on src/main/java/roomescape/controller/ReservationController.java
> +    @DeleteMapping("/{id}")
Http 멱등성이란 무엇일까요?
멱등성 이외에 Delete Method는 어떤 특징을 가지고 있을까요?

2024-04-18 11:23 UTC, ddu0422 commented on src/main/java/roomescape/domain/Reservation.java
> +    @JsonFormat(pattern = "HH:mm")
> 요구사항에서 원하는 형식과 상이해서 사용

`날짜와 시간을 분리`해서 나타내야하기 때문에 사용했다고 이해하면 될까요?

보통 Domain에서는 날짜와 시간을 분리하지는 않습니다.
위 사항을 적용한다면, Domain에서는 날짜와 시간을 합쳐야합니다.
그렇다면, View에 반환할 때는 Domain의 내용을 변경해서 반환해야하지 않을까요?

요약) View와 Domain의 의존성이 강하다.

2024-04-18 11:23 UTC, merged

2024-04-18 11:24 UTC, ddu0422 commented on src/main/java/roomescape/ReservationController.java
> +    private final AtomicLong id = new AtomicLong(0);
우선 이대로 놔둬도 괜찮을 것 같습니다.
큰 영향이 있는 내용이 아니라서요.

2024-04-18 11:24 UTC, ddu0422 commented on src/main/java/roomescape/ReservationController.java
> +        return ResponseEntity.ok(newReservation);
ResponseEntity가 아닌 다른 방식으로 표현할 수 있는 방법은 없을까요?

2024-04-18 11:35 UTC, jimi567 commented on src/main/java/roomescape/ReservationController.java
> +        return ResponseEntity.ok(newReservation);
@ResponseBody (또는, @RestController)와 @ResponseStatus를 함께 사용한다면 표현할 수 있다고 생각합니다.!
예를 들어, 요구 사항이 "Post작업에 대해 201 상태 코드를 응답하라" 바뀐다면 @ResponseStatus(HttpStatus.CREATED) 등을 사용하여 표현할 수 있다고 생각합니다.
아직 ResponseEntity가 익숙치 않아서 그런지 개인적으로는 @ResponseStatus 이걸 사용하는게 좀 더 직관적이라고 생각이 드네요 ㅎㅎ

2024-04-19 07:48 UTC, jimi567 commented on src/main/java/roomescape/domain/Reservation.java
> +    @JsonFormat(pattern = "HH:mm")
시간 출력이 분 단위까지 나와야하는데,
LOCALTIME을 직렬화 하게 되면, 초 단위까지 나와서 포맷팅 해주었습니다.

> 날짜와 시간을 분리

이런 근거로 사용한 것은 아니지만. 

> 그렇다면, View에 반환할 때는 Domain의 내용을 변경해서 반환해야하지 않을까요?

이는 여전히 같은 상황인 것 같습니다. 이럴 경우는 어찌해야 될지 감이 안집히긴 하네요
당장 생각나는 것은 응답용 dto를 추가하고, dto에서 포맷팅 해주는게 어떨까?라는 생각이 들긴하네요