[1 - 3단계 - 방탈출 예약 관리] 땡이(정지호) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #53
Opened 2024-04-17 06:50 UTC by J-I-H-O

안녕하세요 썬! 땡이 입니다. 😊

**이전 웹 개발 경험**
- 약 1년 전에 스프링 관련 강의를 보며 학습을 했으나, 너무 띄엄띄엄 보기도 했고 시간이 많이 흘러 모두 잊어버렸습니다 ㅎㅎ;;;
- 웹 프로젝트에 참여해본 경험은 있지만, 스프링을 공부한지 얼마 되지 않아 간단한 CRUD 정도만 담당했습니다.
- 기반 지식이 많이 부족해서 **'어떤 점을 더 고민해볼 수 있을까' 도 알지 못하는 상태**입니다.

그럼 이번 미션 잘 부탁드리겠습니다! 😊😊😊😊😊

2024-04-18 12:00 UTC, syoun602 requested changes
안녕하세요 땡이~ 방탈출 미션 리뷰어를 맡게된 썬입니다 ☀️

전반적으로 잘 구현해주셨습니다 👍
간단한 코멘트 몇 개 남겨두었으니 확인 후 재요청주세요 !
하시다가 코멘트에 대해 궁금한 점이 있다면 언제든 DM 주셔도 됩니다 😊

2024-04-19 07:28 UTC, J-I-H-O commented on src/test/java/roomescape/ReservationControllerTest.java
> +        PARAMS.put("time", "17:00");
수정했습니다! 👍

2024-04-19 07:32 UTC, J-I-H-O commented on src/main/java/roomescape/controller/ReservationController.java
> +                .toList());
수정했습니다! 👍

2024-04-20 06:45 UTC, J-I-H-O commented on src/main/java/roomescape/dto/ReservationResponse.java
> +    }
모든 필드를 갖는 생성자를 만들어주고, 정적 팩토리 메서드에서 값을 넣어주도록 변경했습니다! 😊

2024-04-20 11:39 UTC, J-I-H-O commented on src/main/java/roomescape/controller/ReservationController.java
> +@RestController
`@Controller` 는 view를 위한 컨트롤러를 개발할 때 사용되고, 
`@RestController` 는 REST API용 컨트롤러를 개발할 때 사용되는 것으로 알고 있습니다!

`@RestController` 는 `@Controller` 와 `@ResponseBody` 가 결합된 어노테이션입니다. 클래스 레벨에 `@ResponseBody` 를 붙여준 것과 같으므로 각각의 메서드에 `@ResponseBody` 를 붙여줄 필요가 없게 됩니다.

이때 `@ResponseBody` 어노테이션은 메서드가 리턴한 값(단순 문자열, 객체 등)을 HttpMessageConverter를 통해 자동으로 직렬화하여 HTTP 응답 body에 넣어줄 수 있도록 합니다.

2024-04-20 12:05 UTC, J-I-H-O commented on src/main/java/roomescape/dto/ReservationResponse.java
> +public class ReservationResponse {
**Request DTO**

먼저 미션에서 제공한 API 명세를 살펴보면, Request의 경우 id 값을 포함하고 있지 않습니다. 도메인은 id 값을 가지고 있어야 하기 때문에 Request와 도메인에 차이가 있었습니다.
따라서 요청을 받을 때 사용되는 DTO를 따로 분리했습니다.

**Response DTO**

`Reservation` 도메인과 `ReservationResponse` DTO가 가지는 필드는 같습니다. 하지만 API 명세에서 시간 표현 형식으로 ‘HH:mm:ss’ 가 아닌 ‘HH:mm’을 요구했기 때문에 응답 형식을 맞춰줄 필요가 있었습니다.

처음에는 따로 DTO를 분리하지 않고, `Reservation` 의 time 필드에 `@JsonFormat` 을 붙여줌으로써 이를 해결했습니다.
하지만 응답 형식을 맞추기 위한 코드가 도메인에 있는 것이므로 도메인이 view에 의존한다고 생각했고, 요구사항이 변경되면 도메인 코드를 수정해야 하는 경우가 생길 것이라고 판단했습니다.

따라서 응답을 위한 DTO를 따로 분리했습니다!

2024-04-20 15:28 UTC, J-I-H-O commented on src/test/java/roomescape/AdminControllerTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
같은 port를 사용하기 때문에 애플리케이션이 실행중일 때 테스트를 실행할 수 없었습니다 😥
테스트에서 RANDOM_PORT를 사용하도록 변경해보았습니다!

2024-04-21 00:29 UTC, J-I-H-O commented on src/main/java/roomescape/controller/ReservationController.java
> +        return ResponseEntity.notFound().build();
존재하지 않는 예약의 id에 대한 요청임을 명확히 나타내기 위해 404 Not Found를 응답으로 내려주었습니다! 
조금 더 찾아보니 삭제할 리소스가 존재하지 않는 경우에 대해서는 크게 200 OK와 404 Not Found 로 의견이 갈리는 것 같았습니다.

- **200 OK를 옹호하는 입장**
    - 결과적으로 생각해보았을 때, 실제로 존재하는 대상이 삭제된 것과 처음부터 존재하지 않는 상태인 것은 같은 결과임.
    따라서 모두 삭제 요청이 성공한 것으로 볼 수 있음
    - 404를 사용하게 되면 다양한 해석의 여지가 있어 혼동을 줄 수 있음.
    잘못된 경로로 요청을 보낸 것인지, 올바른 경로로 요청을 보냈으나 단순히 삭제할 리소스가 존재하지 않는 것인지 파악하기 어려움
- **404 Not Found를 옹호하는 입장**
    - 실제로 삭제 요청이 성공했는지 서버 측에서 명확하게 알릴 수 있음

이번 미션에서는 잘 모르는 상태로 404를 내려주었지만, 의견이 분분하게 갈리는 만큼 저는 속해있는 조직의 결정을 따라갈 것 같습니다.
썬은 어떤 상태 코드를 응답하는게 더 적합하다고 생각하시는지 궁급합니다!

2024-04-21 00:57 UTC, J-I-H-O commented on src/main/java/roomescape/controller/ReservationController.java
> +    public ResponseEntity<List<ReservationResponse>> readReservations() {
예약 삭제 메서드와 다른 메서드간 통일성을 위해 사용했습니다!

`ResponseEntity` 는 body 뿐만 아니라 status 및 header를 유연하게 설정할 수 있어, 프로그램에서 특정 조건에 따라 상태 코드를 변경하기 용이하다고 알고있습니다.

예약 삭제 메서드에서는 조건에 따라 다른 상태 코드를 내려주기 위해 `ResponseEntity` 를 사용하고 있습니다.

```java
@DeleteMapping("/{id}")
public ResponseEntity<Void> deleteReservation(@PathVariable Long id) {
    boolean isDeleted = reservations.removeIf(reservation -> reservation.getId().equals(id));

    if (isDeleted) {
        return ResponseEntity.ok().build();
    }
    return ResponseEntity.notFound().build();
}
```

이때 전반적인 통일성을 위해 다른 메서드에서도 `ResponseEntity` 를 사용하여 응답을 내려주도록 했습니다.

혹시 `ResponseEntity` 를 사용했을 때 발생할 수 있는 문제점이 있는지, 
그리고 `ResponseEntity` 와 `@ResponseBody` 중 어떤 방식을 사용하는 것을 권장하시는지 궁금합니다! 😊

2024-04-21 01:09 UTC, J-I-H-O commented
안녕하세요 썬! 꼼꼼한 리뷰 감사드립니다 😊
관련 내용 조사한 뒤에 코멘트도 남겨두었는데, 미흡한 내용이 많을 것 같아요...!! 
잘못된 부분이 있다면 교정 부탁 드릴게요..!
다시 한 번 감사드립니다 😊

2024-04-22 04:04 UTC, syoun602 approved these changes
안녕하세요 땡이!

이전에도 크게 변경할 부분이 없었는데, 리뷰 반영도 잘해주셔서
이번 단계는 이만 머지하겠습니다!
다음 단계에서 더 많은 얘기 나누어보아요 😊

2024-04-22 04:04 UTC, merged