[1 - 3단계 - 방탈출 예약 관리] 호기(조호연) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #58
Opened 2024-04-17 07:06 UTC by hoyeonyy

안녕하세요 미르! 호기입니다! 👋👋👋
오랜만에 코드를 치려니까 어색하면서도 좋네요..ㅎㅎ

## 스프링 경험
학교 졸업 프로젝트로 스프링을 경험해보긴 했지만 사실 처음이라봐도 무방합니다..
스프링에 대해 아무것도 모르고 구글링해서 코드 붙여넣은게 전부였어요..😂

## 고민했던 내용
### 시나리오를 위한 다이나믹 테스트
`Reservation`에 대한 테스트를 작성하던 중 예약 생성, 예약 취소에 대한 테스트에서 페어와 고민을 많이 했습니다.
작은 단위의 테스트를 해야했지만 삭제의 경우 생성된 예약이 있어야 테스트를 할 수 있었습니다.
테스트 순서를 지정해야하나..? 라는 생각을 했고 그러던 와중 다이나믹 테스트라는 것을 발견했습니다.
다이나믹 테스트를 사용하여 생성 후 삭제 라는 시나리오를 만들었습니다.
이러한 경우에 다이나믹 테스트를 사용하는 게 맞는지 궁금합니다!

미르에게 리뷰받으며 스프링을 깊게 이해해보고 싶습니다!
감사합니다!

2024-04-17 12:52 UTC, ddu0422 requested changes
안녕하세요 호기! 미르입니다 :)
방탈출 예약 관리 미션 잘 구현해주셨네요!
간단한 코멘트 남겼으니 확인 부탁드립니다~
궁금한 점이 있으시면 언제든지 DM주시거나 코멘트 남겨주세요!

2024-04-17 12:52 UTC, ddu0422 commented on src/main/java/roomescape/reservation/ReservationController.java
> +    @ResponseBody
ResponseBody는 어떤 역할을 할까요?

2024-04-17 12:52 UTC, ddu0422 commented on src/main/java/roomescape/reservation/ReservationController.java
> +        return ResponseEntity.ok(responseReservations);
ResponseEntity의 응답값은 무엇일까요?

2024-04-17 15:38 UTC, hoyeonyy commented on src/main/java/roomescape/reservation/ReservationController.java
> +    @ResponseBody
`ResponseBody`는 자바 객체를 http 바디의 json으로 자동 변환하여 보내주는 것으로 알고 있습니다!

2024-04-17 15:39 UTC, hoyeonyy commented on src/main/java/roomescape/reservation/ReservationController.java
> +    @ResponseBody
`@RestController` 를 사용하면 `@ResponseBody`를 생략할 수 있을 것 같습니다!

2024-04-17 15:43 UTC, hoyeonyy commented on src/main/java/roomescape/reservation/ReservationController.java
> +    }
미르가 밑에 주신 리뷰와 이어지는 것 같습니다..!

저도 `RestContoller`를 사용하려 했지만 페이지를 요청하는 것이 있어 망설여졌습니다..
하지만 페이지와 api 요청을 분리하게 된다면 망설임 없이 `RestContoller`를 사용할 수 있을 것 같습니다!

이 과정에서 궁금한 것이 생겼는데요..!
만약 페이지와 api요청을 분리하지 않은 현재같은 상황에서도 `RestController`를 붙여도 상관이 없을까요?!
저에게는 `ResponseBody`를 사용하지 않아도 되는 요청들이 있음에도 `RestController`를 사용하는 것이 조금 이상했습니다😂

2024-04-17 16:00 UTC, hoyeonyy commented on src/main/java/roomescape/reservation/ReservationController.java
> +                .filter(reservation -> reservation.getId().equals(id))
스프링에 들어왔더니 레벨 1때 배운 내용을 다 까먹은 것 처럼 코드를 짰네요..😂

수정해서 리뷰요청 하겠습니다!

2024-04-18 02:05 UTC, hoyeonyy commented on src/test/java/roomescape/reservation/ReservationControllerTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
아니요..🥲 사실 주어진 테스트를 의심 없이 사용한 것 같아요!

미르가 말을 해주시고 찾아봤습니다!
`DEFINED_PORT` 를 사용 했을 때는 프로그램을 실행 시킨 후 테스트를 돌리면 같은 포트를 사용하기 때문에 실행이 안되더라구요!
그래서 `RANDOM_PORT` 를 사용해 서로 다른 포트를 사용하도록 바꿨습니다!

하지만 `RANDOM_PORT`를 사용해 다른 포트에서 테스트를 실행시키더라도 `RestAssured` 에서 api를 8080으로 날리는 것 같아요..!
그래서 @LocalServerPort를 사용해서 RestAssured 가 api를 현재 테스트 서버의 포트로 날리도록 바꾸었습니다..!
혹시 제가 이해한게 맞을까요..?!

2024-04-18 02:05 UTC, hoyeonyy commented on src/test/java/roomescape/reservation/ReservationControllerTest.java
> +        params.put("time", "15:40");
Map.of 를 사용해서 초기화 시켜보겠습니다!
(ㅇ..이게 맞을까요..?!)

2024-04-18 02:19 UTC, hoyeonyy commented on src/test/java/roomescape/reservation/ReservationControllerTest.java
> +    @TestFactory
다이나믹 테스트의 장점은 시나리오를 테스트할 수 있다는 장점이 있는 것 같습니다!
하나의 단위테스트 말고도 전체적인 흐름을 만들어 테스트 할 수 있다는 것이 장점인 것 같습니다.

반면 다이나믹 테스트로만 테스트를 작성 한다고 한다면 경우의 수가 너무 많아진다는 점..?

현재 제가 느끼기로는 일반적인 단위 테스트와 다이나믹 테스트는 사용하는 경우가 다른 것 같습니다!
단위 테스트는 객체의 행동 하나하나를 테스트 한다면 다이나믹 테스트는 컨트롤러같은 흐름에 대해 테스트 한다..? 라고 생각합니다!

2024-04-18 02:22 UTC, hoyeonyy commented on src/main/java/roomescape/admin/AdminController.java
> +    }
1. 클라이언트가 "/" 주소를 요청한다
2. 서버에서 redirect가 있는 것을 확인한다.
3. 302 상태 코드와 함께 "/admin" 주소를 같이 보내준다.
4. 클라이언트는 302 를 확인하고 같이 온 "/admin" 주소를 요청한다.

정도로 알고 있습니다!

2024-04-18 10:47 UTC, ddu0422 approved these changes
안녕하세요 호기! 미르입니다 :)
전반적으로 구현 잘 해주셔서 이만 머지하겠습니다.
코멘트 남긴 부분은 다음 미션을 진행하며 참고하시면 될 것 같습니다!

2024-04-18 10:47 UTC, ddu0422 commented on src/main/java/roomescape/reservation/ReservationController.java
> +        return ResponseEntity.ok(responseReservations);
네~ 맞습니다 :)

2024-04-18 10:47 UTC, ddu0422 commented on src/test/java/roomescape/reservation/ReservationControllerTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
👍🏻 👍🏻

2024-04-18 10:47 UTC, ddu0422 commented on src/test/java/roomescape/reservation/ReservationControllerTest.java
> +        params.put("time", "15:40");
Map.of도 좋은 방향이라고 생각합니다~

```java
new HashSet() {{
    put("name", "브라운"),
    put("date", "2023-08-05"),
    put("time", "15:40")
}}
```

위 방식도 있으니 참고해주세요~

2024-04-18 10:47 UTC, merged

2024-04-18 15:35 UTC, hoyeonyy commented on src/main/java/roomescape/reservation/ReservationController.java
> +    }
한번 테스트 해봤는데 "admin/reservation-legacy" 이것이 문자열로 바디에 들어가는 것 같습니다.

페이지 랜더링이 안되고 json으로 바뀌네요..! 주의해야할 것 같습니다!

2024-04-18 15:40 UTC, hoyeonyy commented on src/main/java/roomescape/reservation/ReservationApiController.java
> +    @ResponseBody
> 만약, ResponseBody가 필요한 상황이 많아진다면 어떻게 될까요?
이런 경우 중복이 많아지기 때문에 미르가 말씀해주신대로 `page`를 따로 분리하고 `RestController`를 사용하는 게 맞지 않을까..? 생각이 듭니다!

> 혹은 ResponseEntity를 사용하지 않는 상황이라면 어떤 결과를 반환할까요?
미르의 질문이 `ResponseEntity`를 사용하지 않는 상황에 어떤 값을 반환해야 되는지 물어보시는 건가요?!
만약 이게 맞다면 객체 자체를 반환할 것 같습니다!
객체자체를 반환 하더라도 `ResponseBody` 어노테이션이 직렬화를 하여 Json으로 변환해주기 때문입니다!

이 과정에서 그럼 왜 굳이 `ResponseEntity`를 사용해야할까? 라는 의문이 들었습니다.
이유를 찾던 와중 가장 설득이 되는 내용은 `ResponseEntity`는 헤더를 직접 만들어 넣어줄 수 있기 때문에 `ResponseEntity`를 사용한다고 생각했습니다.
이러한 이유에서 `ResponseEntity`를 사용하는 것이 맞을까요??

2024-04-18 15:41 UTC, hoyeonyy commented on src/main/java/roomescape/reservation/Reservation.java
> +        return false;
다음 번 리뷰 요청을 드릴 때
`return this.id == id;` 이처럼 코드를 수정하고 테스트 케이스를 추가해서 요청 하겠습니다!