[1 - 3단계 방탈출 예약 관리] 제제(장진우) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #66
Opened 2024-04-17 07:56 UTC by JINU-CHANG

안녕하세요 러너덕! 제제라고 합니다 🙂

### 스프링 경험
스프링으로 2-3번 프로젝트를 진행한 적은 있지만 개념을 깊게 공부하지는 못했습니다.

## 고민했던 부분

미션을 진행하며 고민했던 부분과 나름대로 저의 결론을 남겨두었는데 좀 더 좋은 피드백과 조언을 얻을 수 있지 않을까하여 질문합니다 ☺️

### ResponseEntity vs. ResponseBody

1. 차이점과 사용이유에 대한 고민

둘 다 자바 객체를 JSON으로 변환한 후 HTTP 응답을 보내기 위해 사용합니다. 둘 중의 어느 것을 사용해도 큰 문제없이 동작했고 공식문서에서도 둘이 비슷한 기능을 하고 있다고 작성되어있는 것을 확인했습니다. 그렇다면 어떤 것을 사용하는 게 더 큰 장점이 있을지 고민하게 되는데요, ResponseEntity가 HTTP 옵션에 대해 좀 더 유연하기 때문에 ResponseEntity를 사용하자고 결론내렸습니다. 검색해 봤을 때 추가적인 장점을 발견하기 어려웠는데 해당 장점만 존재하는 것이 맞을까요?

2. 추가고민

다음 고민들은 아직 결론을 내리지 못해서 질문해도 괜찮은지 모르겠지만 조언해주실 부분이 있을까하여 남겨두었습니다!

- ResponeEntity로 대체된다면 ResponseBody가 필요한 곳이 있을까?
- @RestController 어노테이션은 @Controller + @ResponseBody를 위해 사용되는데 @Controller + ResponseEntity를 사용하면 해당 어노테이션은 사용하지 않아도 되지 않는지 그럼에도 대부분의 프로젝트에서 사용하는 것은 어떤 이유가 있는걸까?

### ReservationResponses 일급 컬렉션

아래의 중복 코드를 없애기 위해 ReservationResponses라는 일급 컬렉션을 사용하고자 했습니다.
(해당 커밋 > 77592dbc9bb5c7c4e475accb184475715293be02)

```java
List<ReservationResponse> reservationResponses = reservations.getReservations()
                .stream()
                .map(ReservationResponse::fromEntity).toList();
```

하지만 2가지 문제점이 존재했습니다.

1. 테스트 코드 변경

기존의 코드는 List<ReservationResponse>의 사이즈를 비교하기 때문에 테스트가 통과합니다. 

```java
RestAssured.given().log().all()
                .when().get("/reservations")
                .then().log().all()
                .statusCode(200)
                .body("size()", is(0));
```
하지만 ReservationResponses로 한 번 더 감싸면 파싱하는 코드가 필요하기 때문에 해당 테스트 코드를 사용할 수 없었습니다.

2. API 명세서

애초에 명세서에서 List값을 반환합니다.

![image](https://github.com/woowacourse/spring-roomescape-admin/assets/98975580/a7d9a30f-df12-42c0-969f-5721c17d111a)

이런 2가지 문제점때문에 결국 처음의 코드로 돌아오게 되었는데요, 레벨1에서는 일급 컬렉션의 사용을 강조해오기도 했고 지금 저의 코드에서도 필요성이 보인다고 생각했는데 사용하지 말아야하는것인지 궁금합니다..!

2024-04-17 14:56 UTC, Deocksoo requested changes
안녕하세요 제제, 러너덕입니다.
코드 깔끔하게 잘 작성해주셨네요 👍 
생각해보시면 좋을 만한 부분에 코멘트 남겨두었으니, 확인 한 번 부탁드려요.

> ResponseEntity vs. ResponseBody

ResponseEntity를 왜 사용하는지 고민해보셨군요 :) 
두 가지 질문을 주셨는데, Server Side Rendering과 Client Side Rendering 두 가지 방식을 비교해보시면서 질문에 대한 답을 정리해보셔도 좋겠네요. @RestController는 언제 사용하나요? @RestController를 사용하면 뷰가 어디에서 그려질까요?

> ReservationResponses 일급 컬렉션

일급컬렉션이 무엇이고, 언제 필요한지 한번 다시 생각해보시면 좋을것같아요.
레벨1에서는 일급 컬렉션의 사용을 많이들 강조하셨다면, 어떤 상황에서 사용할 것을 강조하셨나요?
제제는 일급컬렉션을 어떤 상황에서 사용하시나요?
이 질문에 대한 답변은 코멘트에서 계속 이어나가도 좋겠어요.

2024-04-17 14:56 UTC, Deocksoo commented on src/main/java/roomescape/controller/ReservationController.java
> +    @GetMapping("/reservations")
이 API는 어디에 필요한 API인가요?
이 API 위의 두 API와는 어떤 차이가 있고, 왜 필요한가요?

2024-04-17 14:56 UTC, Deocksoo commented on src/main/java/roomescape/domain/Reservations.java
> +public class Reservations {
이 일급컬렉션의 역할은 무엇인가요?
왜 필요한가요?

2024-04-18 16:30 UTC, JINU-CHANG commented on src/main/java/roomescape/domain/Reservations.java
> +public class Reservations {
일급 컬렉션이 무엇이고 언제 사용하는지부터 다시 생각해보았는데요, 일급 컬렉션은 컬렉션 외에 다른 멤버변수가 존재하지 않는 상태를 뜻합니다. 또한 상태와 행위를 관리하여 비즈니스에 종속적인 자료구조를 만들기 위해 사용한다고 알고 있습니다.

Reservations을 일급 컬렉션으로 만든 이유는 `List<Reservation> reservations` 컬렉션에 대한 행위(메서드)를 하나의 클래스 내부에서 관리해주기 위해서였습니다. 반면 질문에 남겼던 ReservationResponses는 List<ReservationResponse>를 감싸는 클래스일뿐 별다른 역할이 없었습니다. 그래서 굳이 일급 컬렉션으로 뺄 필요가 없겠다고 생각했습니다.

질문에 답하면서 일급 컬렉션에 대해 더 고민해볼 수 있었던 것 같습니다 🙂👍

2024-04-19 01:36 UTC, JINU-CHANG commented on src/main/java/roomescape/controller/ReservationController.java
> +    @GetMapping("/reservations")
위의 코멘트까지 함께 답변하면, 기본적으로 Controller와 RestController의 차이는 Controller는 뷰 이름을 반환하고 RestController는 json데이터를 반환한다고 알고 있었습니다. 저의 고민은 Controller로 대체할 수 있음에도 RestController가 등장하게 된 이유가 있지 않을까에서였는데요, 여러 글을 찾아봤지만 대부분 `@RestController includes the @Controller and @ResponseBody annotations, and as a result, simplifies the controller implementation`라고 설명하고 있었습니다. 큰 이유없이 `간단하게 사용할 수 있다` 정도의 설명이었습니다.

그러면 RestController는 json데이터를 처리하는 것이 목적인데 `@Controller + @ResponseBody로 사용하면 굳이 거치지 않아도 될 View에 대한 처리를 한다. 결국 필요없는 과정을 생략하기 위해 어노테이션을 차이있게 사용하는건가`라는 고민을 하게 되었는데요, 크루들과 이야기한 결과 그렇지는 않았다는 결론이 났습니다. RestController은 Controller와 동일하게 동작했고 차이가 있다면 ResponseBody때문에 발생하는 것이었습니다 🥲

아직 이해가 완벽하지는 않지만 미션을 진행해야하기 때문에 알고있는한에서 결론을 내렸습니다. view에 대한 처리를 할 것이냐 json데이터를 전달할 것이라는 목적을 확실하게 전달해주기 위해 어노테이션을 차이있게 사용할 수 있습니다. 그 이유만으로도 충분히 RestController 어노테이션의 필요성을 설명할 수 있을 것 같았습니다. CSR, SSR에 대해서도 말씀해주셨는데요, CSR 방식에서는 RestController, SSR방식에서는 Controller를 사용할 수 있을 것 같습니다. 보통 프로젝트에서는 CSR 방식을 사용했으나 이번에는 뷰까지 처리해야하므로 두 어노테이션을 사용해야 했고 원래는 하나의 ReservationController에서 처리하던 것을 ReservationController 와 ReservationPageController로 분리했습니다.

2024-04-19 15:45 UTC, Deocksoo commented on src/main/java/roomescape/controller/ReservationController.java
> +    @GetMapping("/reservations")
많이 고민해보신 것 같네요👍 
충분히 고민해보신 것 같아서, 생각해보실 만한 관점을 하나 더 제안드릴게요.

과거에는 서버의 클라이언트가 웹 브라우저밖에 없었던 시절이 있었죠. 그 때는 인터넷 브라우저를 열고 사용하는 사용자들만 웹 서버의 클라이언트였어요.
그런데 점점 웹이 널리 사용되고, 웹에서 하는 기능들이 많아지면서 백엔드라고 부르는 서버쪽 구조가 점점 더 복잡해지기 시작했어요. HTTP 프로토콜도 점점 더 많은 곳에 쓰이기 시작했죠. 예전에는 웹 브라우저만 서버의 클라이언트였지만, 이제는  클라이언트가 더 이상 웹 브라우저에만 국한되지 않고 데스크톱 앱, 모바일 앱, 심지어는 서버도 다른 서버의 클라이언트가 되는 경우가 생기기 시작했죠.

이러한 웹의 발전 과정을 고려할 때, @RestController가 왜 필요하게 되었을지 한 번 연결해서 생각해 보시면 이해하시는 데에 도움이 되지 않을까 싶네요 :)

2024-04-19 16:15 UTC, Deocksoo commented on src/main/java/roomescape/domain/Reservations.java
> +public class Reservations {
잘 정리해주셨네요 👍 
말씀해주신 관점에서 보면, 위 일급컬렉션은 List의 기능을 약간 wrapping 하거나, delegate하는 정도의 역할 말고는 특별한 행위라고 할 만한 것이 아직 없는것같아요.
불필요한 일급컬렉션인것 같은데, 제거하고 나중에 필요하면 만드는 것은 어떤가요?

2024-04-19 16:23 UTC, Deocksoo approved these changes
안녕하세요 제제
변경할 만한 코드가 많지 않아 미션 머지해요.
코멘트 몇 군데 남겨두었으니, 확인 한 번 부탁드려요.
[이 코멘트](https://github.com/woowacourse/spring-roomescape-admin/pull/66#discussion_r1572573210)와 관련해서는 머지 후에 다음 미션 진행하시면서 한번 고민해보시면 좋겠네요.

2024-04-19 16:24 UTC, merged