[1 - 3단계 방탈출 예약 관리] 켈리(양성욱) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #71
Opened 2024-04-17 08:27 UTC by kelly6bf

안녕하세요 오리! 리뷰이로 만나뵙게된 켈리입니다! 잘 부탁 드려요!!

🧑‍💻 # 스프링 경험
레벨2 이전 스프링의 기본 개념 학습과 간단한 프로젝트(프론트와 함께)를 진행해본 경험이 있습니다.

🙇 # 리뷰어님께 전하고 싶은 내용
## 테스트 코드 분리
미션에서 기본으로 제공된 테스트는 큰 단위로 묶여있기에 단위별로 테스트를 분리하고싶었습니다. 하지만 조회/삭제를 검증하기위한 테스트용 데이터를 미리 삽입할 적당한 방법을 찾지못해 우선은 저장/삭제/조회 메서드를 하나의 단위로 묶었습니다. 예전 Mock을 활용해 Controller Test를 수행한 경험이 있어 이번에도 Mock을 활용해볼까 생각은 했지만 이번 미션에서 도입하기에는 너무 과하다는 생각이 들어 우선 기능 검증에 의의룰 두었습니다.

## ControllerAdvice 도입
방탈출 예약 저장시 요청으로 들어온 예약자 이름을 검증하는 로직을 작성하였습니다. 이 때 유효하지 않은 예약자 이름이 입력되면 예외 API를 반환하도록 ControllerAdvice를 도입했는데 막상 작성해보니 이번 미션에서는 너무 과한 기능이지 않을까 고민이 들었습니다. 그래도 코드 자체는 복잡하지 않아 우선 도입하였습니다.

리뷰 잘 부탁드리겠습니다! 감사합니다!

2024-04-17 13:19 UTC, jinyoungchoi95 requested changes
안녕하세요 켈리 😄

방탈출 예약 관리 미션의 리뷰어를 맡은 오리입니다.

첫미션 잘 구현해주셨네요. 몇가지 코멘트 남겨두었으니 확인부탁드려요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-04-17 13:19 UTC, jinyoungchoi95 commented on src/main/java/roomescape/entity/ReservationEntity.java
> +public class ReservationEntity {
단순히 domain객체로 두면 되는 것 아닌가요? `Reservation`은 어떤 의미에서의 entity로 정의되고 있는걸까요? 현재 미션에서 학습에 필요한 내용인지 고민해보셨으면 좋겠습니다.

2024-04-17 13:19 UTC, jinyoungchoi95 commented on src/main/java/roomescape/entity/ReservationEntity.java
> +    }
현재 정적 팩토리 메소드는 생성자와 다를바가 없어보여요. 이름도 결국 of라는 관습적인 이름은 생성자의 의미와 다르지 않구요. 정적 팩토리 메소드를 사용해야하는 이유가 있을까요?

2024-04-17 13:19 UTC, jinyoungchoi95 commented on src/main/java/roomescape/entity/ReservationEntity.java
> +    }
1레벨때와 마찬가지로 비즈니스 로직에는 모두 테스트를 추가해주세요.

2024-04-17 13:19 UTC, jinyoungchoi95 commented on src/main/java/roomescape/repository/ReservationRepository.java
> +public interface ReservationRepository {
미리 잘 구현해주셨네요 👍

2024-04-17 13:19 UTC, jinyoungchoi95 commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    void deleteById(final Long reservationId);
인터페이스의 파라미터에 final이 필요한가요?

2024-04-17 13:19 UTC, jinyoungchoi95 commented on src/main/java/roomescape/repository/MemoryReservationRepository.java
> +public class MemoryReservationRepository implements ReservationRepository {
잘 구현해주신 memory repository도 테스트가 필요해보이네요.

2024-04-17 13:19 UTC, jinyoungchoi95 commented on src/main/java/roomescape/dto/SaveReservationRequest.java
> +    public ReservationEntity toEntity() {
`toReservation`으로 사용되는 것 같은데 `toEntity`를 사용하여야할까요?

2024-04-17 13:19 UTC, jinyoungchoi95 commented on src/main/java/roomescape/controller/AdminWebController.java
> +public class AdminWebController {
view용 controller로 잘 분리해주셨네요.

2024-04-17 13:19 UTC, jinyoungchoi95 commented on src/main/java/roomescape/dto/ReservationDto.java
> +public record ReservationDto(Long id, String name, LocalDate date, LocalTime time) {
`SaveReservationRequest`와 마찬가지로 해당 클래스의 네임은 `ReservationResponse`가 더 적절하지 않을까요?

2024-04-18 04:31 UTC, kelly6bf commented on src/main/java/roomescape/entity/ReservationEntity.java
> +public class ReservationEntity {
동의합니다! 아무래도 다음 단계의 DB접근을 의식하다보니 나온 결과인거같아요. 이번 미션에서는 필요없는 내용이라 생각됩니다. 변경해보겠습니다!

2024-04-18 04:36 UTC, kelly6bf commented on src/main/java/roomescape/entity/ReservationEntity.java
> +    }
현재 상황에서는 불필요할거 같습니다. `id`값을 받지 않았을때 자동으로 `0L`으로 초기화하는 로직이 포함되서 이런 형태는 정적 팩토리 메소드를 사용하는게 좋지않을까..? 싶은 막연한 생각에 사용을 한 거 같습니다.

코멘트르 읽고 정적 팩토리 메소드를 사용했을때 장점을 찾아보았습니다.
1. 호출될 때 마다 인스턴스를 새로 생성하지 않아도 된다. (싱글톤으로 활용 가능)
2. 반환 타입의 하위 타입 객체를 반환할 수 있다.

지금 상황에서는 위 장점들을 가질 상황이 아니기에 불필요하다는 생각이 듭니다. 수정해보겠습니다.

2024-04-18 04:38 UTC, kelly6bf commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    void deleteById(final Long reservationId);
실수로 추가해버렸습니다.. 👀 수정하겠습니다!

2024-04-18 04:38 UTC, kelly6bf commented on src/main/java/roomescape/repository/MemoryReservationRepository.java
> +public class MemoryReservationRepository implements ReservationRepository {
추가해보겠습니다!

2024-04-18 04:39 UTC, kelly6bf commented on src/main/java/roomescape/dto/SaveReservationRequest.java
> +    public ReservationEntity toEntity() {
현재 상황에서 `Entity`라는 개념을 사용하는게 적절하지 않으므로 `toReservation`으로 사용하는게 맞다고봅니다!

2024-04-18 04:40 UTC, kelly6bf commented on src/main/java/roomescape/dto/ReservationDto.java
> +    public static ReservationDto from(final ReservationEntity reservationEntity) {
동의합니다..! 테스트를 추가해보겠습니다!

2024-04-18 04:40 UTC, kelly6bf commented on src/main/java/roomescape/controller/AdminApiController.java
> +        return ResponseEntity.ok(reservations);
`200`을 응답한다는걸 명시적으로 표현하고 싶어 `ResponseEntity`를 사용했습니다! 하지만 이번 미션의 취지에서는 굳이 필요없다는 생각이 듭니다! 수정해보겠습니다!

2024-04-18 04:41 UTC, kelly6bf commented on src/main/java/roomescape/dto/ReservationDto.java
> +public record ReservationDto(Long id, String name, LocalDate date, LocalTime time) {
동의합니다! 기존 이름보다는 응답에 사용된다는 의미를 넣어주기에 해당 이름이 더 적절할거 같습니다! 수정해보겠습니다!

2024-04-18 04:42 UTC, kelly6bf commented on src/main/java/roomescape/controller/AdminApiController.java
> +    @GetMapping("/reservations")
`@RequestMapping`을 활용하면 앞의 중복되는 경로를 클래스레벨에 부여할 수 있습니다! 다만 개인적으로는 메서드 하나에 전체 경로를 기술하는걸 좋아해서(한눈에 해당 메서드 API의 경로를 파악) 이와 같이 작성했습니다...!

2024-04-18 04:45 UTC, kelly6bf commented on src/main/java/roomescape/controller/AdminApiController.java
> +        return new ResponseEntity<>(HttpStatus.OK);
처음에는 `Body`에 아무 데이터도 넣지 않으려면 생성자를 사용해야하는건가? 라는 생각에 위와같이 작성했는데 찾아보니 다음과 같이 빌더도 아무 데이터 없이 생성할 수 있군요...!

`return ResponseEntity.ok().build();`

다음부터는 좀 더 찾아보고 일관적으로 코드를 작성하겠습니다!

2024-04-18 08:11 UTC, jinyoungchoi95 commented on src/main/java/roomescape/dto/SaveReservationRequest.java
> +    public ReservationEntity toEntity() {
나중에라도 `Entity`의 개념을 db entity로 두고 계신다면 jpa entity를 고려하더라도 `toReservation`이 더 적절하지 않을까싶네요. 이 기능는 entity로 전환하는것이 목적이 아닌 `Reservation`으로 전환하는 것이 목적이니까요.

2024-04-18 08:12 UTC, jinyoungchoi95 commented on src/main/java/roomescape/controller/AdminApiController.java
> +    @GetMapping("/reservations")
보통은 하드코딩의 여지가 있어서 `@RequestMapping`에 중복된 path를 달아둔다는 것만 알아두시면 좋을 것 같네요.

2024-04-18 08:14 UTC, jinyoungchoi95 commented on src/main/java/roomescape/domain/Reservation.java
> +    }
1. 14번의 private 생성자가 굳이 필요한가요? 현재 구조상 생성자는 하나만 있어도 되지 않을까싶네요.
2. 0L은 의미가 있는 상수로 변경될 수 있을 것 같네요.

2024-04-18 08:15 UTC, jinyoungchoi95 commented on src/test/java/roomescape/dto/ReservationResponseTest.java
> +        assertThat(reservationResponse).isNotNull();
생성의 의미라면 null만 체크해도 되겠지만 정말 원하는 값으로 필드가 변경되었는지 각 필드값을 확인해야하지 않을까요?

2024-04-18 08:16 UTC, jinyoungchoi95 commented on src/main/java/roomescape/controller/AdminApiController.java
> +        return reservations;
```suggestion
        return reservationRepository.findAll()
                .stream()
                .map(ReservationResponse::from)
                .toList();
```
이어도 될 것으로 보이네요 :)

2024-04-18 08:17 UTC, jinyoungchoi95 commented on src/main/java/roomescape/exception/ReservationExceptionHandler.java
> +        return new ResponseEntity<>(e.getMessage(), HttpStatus.BAD_REQUEST);
```suggestion
        return ResponseEntity.badRequest().body(e.getMessage());
```
여기도 정의된 builder를 사용할 수 있겠네요.

2024-04-18 08:18 UTC, jinyoungchoi95 commented on src/test/java/roomescape/controller/AdminApiControllerTest.java
> +class AdminApiControllerTest {
👍

2024-04-18 08:19 UTC, jinyoungchoi95 commented on src/test/java/roomescape/controller/AdminApiControllerTest.java
> +    void deleteReservationTest() {
정보가 정말 삭제되었는지는 테스트하지 않아도 괜찮을까요?

2024-04-18 08:20 UTC, merged