[방탈출 예약 관리 4 - 9단계] 리건(이한길) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #76
Opened 2024-04-17 12:36 UTC by hangillee

안녕하세요, 영이! 😀

이번 단계는 1 ~ 3단계에 비해 다소 어려웠습니다.
특히, `JdbcTemplate`만으로 테이블 간 연관관계를 저장하는게 가장 어려웠던 것 같습니다.
지금 당장은 예약 객체 생성 과정에서 JSON으로 넘어온 `timeId`를 통해 예약 시간 객체를 조회하고
예약과 예약 시간을 매핑해주는 방식으로 구현했습니다. 이 방식보다 더 좋은 방법이 떠오르지 않습니다..

제가 구현한 방식이 괜찮은 방식인지, 계층화 리팩토링이 제대로 이루어진 것이 맞는지 궁금합니다!
이번 리뷰도 잘 부탁드립니다! 😄

2024-04-17 14:37 UTC, choijy1705 requested changes
리건 DB 적용도 빠르게 잘 해주셨네요👍
몇가지 코멘트 남겼으니 확인부탁드려요!

2024-04-17 14:37 UTC, choijy1705 commented on src/main/java/roomescape/controller/ReservationTimeController.java
> +        return ResponseEntity.ok().build();
noContent?

2024-04-17 14:37 UTC, choijy1705 commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    }
```suggestion
    public Long save(final Reservation reservation) {
        SqlParameterSource parameters = new MapSqlParameterSource()
                .addValue("name", reservation.getName())
                .addValue("date", reservation.getDate())
                .addValue("time_id", reservation.getTimeId());
        long id = jdbcInsert.executeAndReturnKey(parameters).longValue();
        return new Reservation(id, reservation.getName(), reservation.getDate(), reservation.getTimeId());
    }
```
저장후 id만 반환하기보다는 저장된 도메인을 반환하는게 어떨까요?

2024-04-17 14:37 UTC, choijy1705 commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    }
전체적인 흐름이 바뀔수있어서 참고만해주세요!

2024-04-17 14:37 UTC, choijy1705 commented on src/main/resources/static/js/reservation-legacy.js
> +    document.getElementById('add-button').addEventListener('click', addInputRow);
js, html 코드들은 보통 자바와 컨벤션이 다르기때문에 변경이 안되도록 신경써주시면 좋을것 같아요!
(리뷰 하는데도 변경사항을 파악하기 힘들어서요...🙏)

2024-04-17 14:37 UTC, choijy1705 commented on src/main/java/roomescape/dto/ReservationRequestDto.java
> +    private Long timeId;
이부분은 전혀 이상할게 없는것 같아요!👍
질문 주신 부분이 이부분 맞을까요??

2024-04-17 15:49 UTC, hangillee commented on src/main/java/roomescape/controller/ReservationTimeController.java
> +        return ResponseEntity.ok().build();
<img width="935" alt="time_delete" src="https://github.com/woowacourse/spring-roomescape-admin/assets/14046092/7d0baf76-1db5-4407-b36e-f7c0a4690404">

일단 미션 요구 사항을 따르는게 우선이라고 생각해서 `ok()`로 처리했습니다..

2024-04-17 15:50 UTC, hangillee commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    public void deleteById(final Long id) {
고쳐보겠습니다!

2024-04-17 15:57 UTC, hangillee commented on src/main/resources/static/js/reservation-legacy.js
> +    document.getElementById('add-button').addEventListener('click', addInputRow);
앗.. JS 컨벤션을 제대로 적용하지 않았네요.. 죄송합니다.. 😢

2024-04-18 06:00 UTC, hangillee commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    }
리팩토링을 진행하면서 이 부분을 다시 한번 고민해봤습니다.

만약 현재 로직에서 `id`를 반환하는 것이 아니라, 도메인을 반환하게 되면 `Reservation`의 필드인 `ReservationTime` 객체도 `timeId`로 찾아와야 하는 문제가 있습니다. 즉, `save` 메소드에서 저장과 조회 두 가지 일을 하게 될 가능성이 있어서 저는 `id`를 반환하고 Service 계층에서 `id`를 활용해 여러 비즈니스 로직을 수행하는 편이 더 낫다고 생각했습니다.

2024-04-18 06:08 UTC, hangillee commented
안녕하세요, 영이! 🙂

피드백 남겨주신 것 확인하고 리팩토링 했습니다!
JS, HTML 파일의 들여쓰기 컨벤션을 원래대로 수정했더니 또 수정 이력이 남았습니다.. 정말 죄송합니다..
해당 파일들은 들여쓰기를 제외하면 바뀐 것은 없습니다..

리뷰 잘 부탁드립니다! 🙇‍♂️

2024-04-18 15:53 UTC, choijy1705 requested changes
리건 빠르게 반영해주셨네요👍
추가 코멘트 남겼으니 
확인부탁드립니다!

2024-04-18 15:53 UTC, choijy1705 commented on src/main/resources/application.properties
> +spring.h2.console.enabled=true
yaml 파일로 관리해보는건 어떨까요?

2024-04-18 15:53 UTC, choijy1705 commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    }
lazy loading에 대해서도 나중에 쉽게 이해하실 수 있겠네요!

2024-04-18 15:53 UTC, choijy1705 commented on src/main/java/roomescape/dto/ReservationRequestDto.java
> +    private Long timeId;
create 메서드에서는 reservationTIme는 조회를 하고 있고 따로 생성은 하지 않는것 같은데요...🤔
변경 사항이 있던걸까요?

2024-04-18 15:53 UTC, choijy1705 commented on src/main/java/roomescape/service/ReservationService.java
> +        final ReservationTime reservationTime = reservationTimeRepository.findById(request.getTimeId());
reservationTIme이 null 인 경우는 어떻게 되나요?

2024-04-18 15:53 UTC, choijy1705 commented on src/main/resources/schema.sql
> +    time_id BIGINT,
timeId는 null일 수 있나요?

2024-04-18 15:53 UTC, choijy1705 commented on src/main/java/roomescape/service/ReservationTimeService.java
> +    }
시간을 지울때 해당 시간에 예약을 삭제해야한다는 요구사항이 있을까요?
시간에 해당하는 예약이 있다면 에러를 내는것이 더 바람직하지 않을까 싶어서요!!

2024-04-18 15:53 UTC, choijy1705 commented on src/main/java/roomescape/service/ReservationTimeService.java
> +        }
순회하면서 지우기 보다는 
`DELETE FROM reservation WHERE time_id = ?`
한번에 지우는게 어떨지요??🤔

2024-04-18 15:53 UTC, choijy1705 commented on src/main/java/roomescape/service/ReservationTimeService.java
> +    public void delete(final long id) {
reservation과 reservationTime을 다 지우는거라면 
트랜잭션도 고려해보면 좋지 않을까요??

2024-04-18 15:53 UTC, choijy1705 commented on src/main/java/roomescape/controller/ReservationTimeController.java
> +@RestController
requestMapping으로 /times를 묶으면 더 보기 좋을것 같네요!

2024-04-18 15:53 UTC, choijy1705 commented on src/main/java/roomescape/controller/ReservationController.java
>  @RestController
여기도 requestMapping!

2024-04-18 15:53 UTC, choijy1705 commented on src/main/java/roomescape/controller/ReservationController.java
> +    public ResponseEntity<ReservationResponseDto> create(@RequestBody final ReservationRequestDto request) {
request의 값들이 올바른지 체크할필요는 없을까요?

2024-04-18 15:53 UTC, choijy1705 commented on src/main/java/roomescape/service/ReservationService.java
> +        final ReservationTime reservationTime = reservationTimeRepository.findById(request.getTimeId());
request.getTimeId()도 null 일 수 있겠네요!
controller로 들어오는 requestDto를 검증하는 방법에 대해서도 고민해보면 좋을것 같습니다!

2024-04-19 01:55 UTC, hangillee commented on src/main/java/roomescape/service/ReservationService.java
> +        final ReservationTime reservationTime = reservationTimeRepository.findById(request.getTimeId());
가장 핵심이 될 예약 시간이 Null이 될 수 있는 위험이 있었네요.. 고쳐보겠습니다!

2024-04-19 01:56 UTC, hangillee commented on src/main/resources/schema.sql
> +    time_id BIGINT,
스키마에서부터 Null을 막을 수 있었네요! 고쳐보겠습니다!

2024-04-19 01:58 UTC, hangillee commented on src/main/java/roomescape/service/ReservationTimeService.java
> +        }
해당 쿼리를 날릴 `deleteAllByTimeId()` 메소드를 구현해보겠습니다!

2024-04-19 02:25 UTC, hangillee commented on src/main/java/roomescape/dto/ReservationRequestDto.java
> +    private Long timeId;
제가 혼동을 드린 것 같습니다..
ReservationTime을 조회하는 과정에서 Repository가 조회한 도메인 객체를 생성하고 반환하고 있습니다.
이 과정에서 문제가 될 만한 부분이 있는지 질문드리고 싶었습니다!

2024-04-19 04:11 UTC, hangillee commented on src/main/java/roomescape/service/ReservationTimeService.java
> +    }
크루들과 이 부분을 두고 치열하게 토론했습니다..

저도 영이의 생각처럼 삭제하려는 시간에 예약이 있을 경우 참조 무결성에 의해 예외가 발생하는 것이 더 낫지 않냐는 의견이었으나, 시간을 삭제하려는 동작 자체가 해당 시간으로 예약된 모든 예약 내역도 지우려는 의도가 있다는 의견이 주류라 이렇게 구현했습니다.

지금 당장의 요구 사항에도 없는 내용이어서 구현하는데 정말 많이 고민했지만, 영이의 의견을 들어보니 제 의견대로 다시 구현해보는 것이 좋을 것 같습니다.

2024-04-19 07:29 UTC, hangillee commented on src/main/java/roomescape/controller/ReservationController.java
> +    public ResponseEntity<ReservationResponseDto> create(@RequestBody final ReservationRequestDto request) {
검증 로직 추가했습니다!

2024-04-19 07:31 UTC, hangillee commented on src/main/java/roomescape/service/ReservationTimeService.java
> +    public void delete(final long id) {
`@Transactional` 어노테이션을 학습하고 추가해봤습니다!

2024-04-19 07:41 UTC, hangillee commented
안녕하세요, 영이! 😁
너무 자주 리뷰 요청 드리는 건 아닌지 조금 죄송스럽습니다..😅

코멘트에 대한 답변으로도 남겼지만, 저도 시간을 삭제할 때, 해당 시간으로 예약된 내역이 있다면 삭제되지 않는 쪽이 더 자연스럽다고 생각해서
시간 삭제 로직을 리팩토링 했습니다.

또한, 예외 처리에 대해서도 학습하다가 Spring Validation의 여러 어노테이션들에 대해 알게 되었는데, 다음 미션에서 예외 처리를 본격적으로 다루다 보니 일단은 해당 기능들을 사용하지 않았습니다. 지금 당장은 잘못된 요청 시(`RequestDto`들에 잘못된 값이 들어갔을 때), HTTP 상태 코드는 그냥 500을 반환하도록 했습니다.

p.s. `properties` 대신 `yml`을 사용할 것을 제안하신 이유로 높은 가독성과 중복되는 속성의 제거라는 장점 때문으로 이해했는데 잘 이해한 건지 궁금합니다!

2024-04-19 15:05 UTC, choijy1705 requested changes
리건 피드백 반영 잘해주셨습니다
간단한 추가 피드백 드렸습니다!

2024-04-20 04:46 UTC, hangillee commented on src/main/java/roomescape/service/ReservationService.java
> +        }
예외가 발생하는 부분이 repository가 맞겠네요! 리팩토링 해보겠습니다!

2024-04-20 04:46 UTC, hangillee commented on src/main/java/roomescape/controller/ReservationTimeController.java
> +        validateStartAtValue(request.getStartAt());
습관적으로 분리했던 것 같습니다! 고쳐보겠습니다!

2024-04-20 06:16 UTC, hangillee commented on src/main/java/roomescape/service/ReservationTimeService.java
> +        reservationTimeRepository.deleteById(id);
예외를 발생시키도록 처리했습니다!

2024-04-20 06:30 UTC, hangillee commented
안녕하세요, 영이! 🙂
남겨주신 피드백 덕분에 주생성자와 부생성자 개념에 대해서 학습하게 되었습니다.

예외 처리 과정에서 생긴 한 가지 궁금증이 있어 질문드립니다! 여러 데이터를 한번에 조회하는 쿼리에서 발생하는 `EmptyResultDataAccessException`을 빈 `List`를 반환하는 것으로 예외 처리해봤는데 괜찮은 방식인지 궁금합니다. 다른 예외를 던져야 하는지, 아무런 값이 없어도 조회는 성공해야 하는 것인지, 조금 헷갈립니다.

일단 저는 일반적으로 DB 콘솔에서 `SELECT` 쿼리를 날렸을 때, 아무런 값이 없으면 없는대로 비어있는 결과를 돌려주니 제가 예외를 처리한 방식이 괜찮다고 생각합니다. 영이는 주로 어느 방식을 사용하는지 궁금합니다!

2024-04-20 09:20 UTC, choijy1705 requested changes
리건 잘 반영해주셨네요👍👍
질문에 대한 답변과 마지막으로 추가 피드백이 있어서 
다시한번 반영 요청드려요!

2024-04-20 09:20 UTC, choijy1705 commented on src/main/java/roomescape/repository/ReservationRepository.java
> +        } catch (EmptyResultDataAccessException e) {
queryForObject와 다르게 query는 결과가 없다면 에러를 던질것 같지는 않아요
공식문서를 한번 찾아보시면 좋을것 같네요!
혹은 테스트코드를 한번 작성해보시는 것도 좋을것 같습니다

2024-04-20 09:20 UTC, choijy1705 commented on src/main/java/roomescape/repository/ReservationRepository.java
> +        } catch (EmptyResultDataAccessException e) {
list를 조회했을때 에러를 내는 경우는 거의 없을것 같습니다! 
웬만한 상황에서 게시물들을 조회한다고 했을때 비어있는 경우는 흔한 케이스일 것 같고요
이러한 이유에서도 query에서는 에러를 내려주지 않도록 설계되어있겠네요

view로 내려주는 과정에서 클라이언트의 요청에 따라 빈 리스트가 아닌 null로 내려주는 경우는 있을수 있을것 같지만 
이는 정해진 방법이 아닌 클라와의 소통을 통해서 정하면 되는 부분이라 생각합니다!

2024-04-20 09:20 UTC, choijy1705 commented on src/main/java/roomescape/service/ReservationTimeService.java
> +            throw new IllegalArgumentException("Reservation exists with this time");
에러 메세지도 왜 안되는지를 명확하게 표시해주는게 좋을것 같아요!
"이 시간에 예약이 존재합니다" 보다는 "예약이 존재하는 시간은 삭제할 수 없습니다"
지금은 간단한 로직이라서 클라이언트가 쉽게 이해할 수 있을수 있지만 조금만 복잡한 케이스라면 추상적인 메세지는 혼란을 줄 수 있을것 같습니다!

2024-04-20 11:30 UTC, hangillee commented on src/main/java/roomescape/repository/ReservationRepository.java
> +        } catch (EmptyResultDataAccessException e) {
`query`와 `queryForObject`의 차이를 제대로 알지 못하고 사용했네요.. 불필요한 예외 처리는 제거하겠습니다!

2024-04-20 11:47 UTC, hangillee commented on src/main/java/roomescape/service/ReservationTimeService.java
> +            throw new IllegalArgumentException("Reservation exists with this time");
개선해보겠습니다!

2024-04-20 11:48 UTC, hangillee commented
빠르게 피드백 반영했습니다!
리뷰 잘 부탁드려요!

2024-04-20 11:50 UTC, hangillee commented
피드백 반영했습니다!
리뷰 잘 부탁드려요!

2024-04-20 13:43 UTC, choijy1705 approved these changes
리건 피드백 잘반영해주셨습니다!
항상 빠르게 반영해주셔서 이번 미션이 빨리 마무리되는 느낌이네요!
더이상 피드백 드릴게 없는것 같습니다!
이번 미션은 여기서 머지하겠습니다👏

2024-04-20 13:43 UTC, choijy1705 commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    }
private 메서드는 public 메서드인 deletById 하단에 위치하는게 좋을것 같네요!

2024-04-20 13:43 UTC, choijy1705 commented on src/main/java/roomescape/repository/ReservationTimeRepository.java
> +    }
여기도요!

2024-04-20 13:43 UTC, merged