[4 - 9단계 방탈출 예약 관리] 백호(전호건) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #86
Opened 2024-04-18 06:17 UTC by Arachneee

안녕하세요 호돌! 백호입니다.

### 웹 개발 경험
Spring MVC를 사용하여 로컬에 게시판을 만들어본 경험이 있고 배포한 경험은 없습니다.

### 질문
#### 상황
예약이 존재하는 예약시간 삭제가 불가했습니다.

#### 원인
reservation 테이블과 reservation_time 테이블의 외래키 매핑때문이었습니다.

#### 해결
방법1: service 계층에서 Reservation를 전부 삭제한 후 ReservationTime을 삭제하기
장점: 어떤 데이터가 삭제되는지 비지니스로직에서 볼 수 있다.
단점: 매번 연관된 데이터를 삭제해줘야 한다.

방법2: DB의 cascade delete 옵션을 사용하여 연관된 db 삭제하기
장점: DB의 연관된 데이터를 한번에 삭제할 수 있다.
단점: 예상치 못한 데이터가 삭제될 수 있다.

이 두 방법중 어떤 방법을 사용하는 것이 좋은지 잘 모르겠습니다. 어떤 부분을 고려해야할까요?

2024-04-18 12:20 UTC, kimhodol requested changes
안녕하세요 백호 :)

엄청 빠르게 리뷰 요청 주셨네요, 대박!

코멘트 참고 부탁드릴게요~

2024-04-18 12:20 UTC, kimhodol commented on src/main/java/roomescape/controller/HomeController.java
> +    @GetMapping(value = {"/", "/static"})
질문) /static으로 들어갔을 때 redirect가 필요한 이유는 무엇인가요?

2024-04-18 12:20 UTC, kimhodol commented on src/main/java/roomescape/controller/ReservationController.java
> +        List<ReservationResponse> responses = reservationService.findAllReservationResponse();
질문) ReservationResponse를 만드는 역할은 뷰의 책임이라고 생각했는데요, 서비스에서 Response를 반환하게 하는 설계의도가 궁금합니다!

2024-04-18 12:20 UTC, kimhodol commented on src/main/java/roomescape/domain/Reservation.java
> +    }
질문) 기본 생성자는 왜 필요한가요?

2024-04-18 12:20 UTC, kimhodol commented on src/main/java/roomescape/dto/ReservationTimeRequest.java
> +
의견) 불필요한 공백줄 같아요.

2024-04-18 12:20 UTC, kimhodol commented on src/main/java/roomescape/repository/ReservationDao.java
> +                        + "left join reservation_time as t on a.time_id = t.id",
의견) multiline string을 쓰면 더 가독성이 좋아질 것 같네요! 그리고 SQL 쿼리문도 schema.sql 에서처럼 포맷팅이 되어있으면 더 좋을 것 같아요.

2024-04-18 12:20 UTC, kimhodol commented on src/main/java/roomescape/service/ReservationService.java
> +    }
의견) ReservationService가 너무 커진 느낌인데, ReservationTime 을 관리하는 서비스는 따로 가지고 있는게 어떨까요?

2024-04-19 01:33 UTC, Arachneee commented on src/main/java/roomescape/controller/AdminController.java
> +    @GetMapping("/time")
```
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="/admin/reservation">Reservation</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/time">Time</a>
      </li>
    </ul>
  </div>
```
js 파일의 경로가 /time으로 되어 있어 time으로 했습니다. /admin으로 통일하는 것이 더 일관성있어 보여 변경하겠습니다.

2024-04-19 02:31 UTC, Arachneee commented on src/main/java/roomescape/controller/HomeController.java
> +    @GetMapping(value = {"/", "/static"})
```
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/static">
    <img src="/image/admin-logo.png" alt="LOGO" style="height: 40px;">
  </a>
```
주어진 index.html에서 로고 클릭 경로가 /static으로 되어있어 /static도 admin으로 redirect 되게 하였습니다.

2024-04-19 04:29 UTC, Arachneee commented on src/main/java/roomescape/controller/ReservationController.java
> +        List<ReservationResponse> responses = reservationService.findAllReservationResponse();
엔티티를 컨트롤러에 노출시키지 않기 위함이었습니다. 하지만 ReservationResponse는 뷰의 책임이고 서비스가 반환하는 것은 서비스에 뷰에 의존적인 것 같습니다.

그래서 서비스용 Dto를 만들어 뷰의 의존성을 분리하겠습니다.

2024-04-19 04:37 UTC, Arachneee commented on src/main/java/roomescape/domain/Reservation.java
> +    }
Intellij 로 빌드할 경우 기본 생성자가 없으면 리플랙션을 사용하여 역직렬화를 하지 못하는 문제가 있습니다.
초기 test코드에 Reservation을 역직렬화 하는 코드가 있어 추가했었습니다.
```
List<Reservation> reservations = RestAssured.given().log().all()
            .when().get("/reservations")
            .then().log().all()
            .statusCode(200).extract()
            .jsonPath().getList(".", Reservation.class);
```
현재는 Dto를 사용하도록 변경하여 기본 생성자가 없어도 문제가 없지만 리플랙션 기능을 썻다 안썻다하는 상황에서 기본생성자가 있는 것이 좋지 않을까요?

2024-04-19 05:00 UTC, Arachneee commented on src/main/java/roomescape/repository/ReservationDao.java
> +                        + "left join reservation_time as t on a.time_id = t.id",
포맷팅은 SELECT 처럼 대문자로 쓰는 것이 도 좋다는 의견이 맞을까요?

2024-04-19 05:33 UTC, Arachneee commented on src/main/java/roomescape/service/ReservationService.java
> +    }
컨트롤러도 따로 있는 만큼 서비스도 분리하는 것이 유지보수에 좋겠군요.

2024-04-19 06:15 UTC, Arachneee commented
Service 객체를 분리했습니다. 
예약시간을 삭제하면 해당 시간의 예약을 전부 삭제하기 위해 ReservationTimeService에서 ReservationDao를 의존하도록 구현했습니다.
그런데 도메인객체 입장에서는 ReservationTime이 Reservation을 모르고 있는데 ReservationTimeService에서 Reservation을 삭제하는 것이 어색해보입니다.

호돌을 어떻게 생각하시나요?

2024-04-20 00:53 UTC, kimhodol commented on src/main/java/roomescape/controller/ReservationController.java
> +        List<ReservationResponse> responses = reservationService.findAllReservationResponse();
확실히 계층별로 역할이 분리가 되긴 했지만, 백호 말대로 현재 수준에서는 약간 과하다는 생각이 들긴하네요 ㅋㅋ

2024-04-20 01:01 UTC, kimhodol commented on src/main/java/roomescape/domain/Reservation.java
> +    }
흠, 제가 테스트 돌려볼때는 기본 생성자가 없어도 테스트가 성공하는 것 같긴한데 혹시 관련해서 좀 더 자세한 설명을 부탁드려도 될까요?

2024-04-20 01:06 UTC, kimhodol commented on src/main/java/roomescape/controller/HomeController.java
> +    @GetMapping(value = {"/", "/static"})
Git으로 봤을 때 주어진 index.html에서 원래 / 로 되어있던 경로가 /static으로 변경하신걸로 나오는데 확인 부탁드릴게요!

2024-04-20 01:09 UTC, kimhodol requested changes
안녕하세요 백호 :)

빠르게 피드백 반영해주셨네요!

코멘트 확인 부탁드릴게요!

2024-04-20 01:27 UTC, Arachneee commented on src/main/java/roomescape/controller/HomeController.java
> +    @GetMapping(value = {"/", "/static"})
제가 실수로 변경한것 같습니다. 수정했습니다!

2024-04-20 02:41 UTC, Arachneee commented on src/main/java/roomescape/domain/Reservation.java
> +    }
ReservationTimeSerializeTest 를 추가했습니다.
Gradle이 아닌 Intellij로 빌드할 경우 기본생성자가 없으면 jsonPath를 객체로 역직렬화 하지 못합니다.

기존의 테스트는 ReservationResponse로 수정하여 record 는 빌드조건 상관없이 역직렬화에 성공합니다.

Intellij로 빌드할 경우 class의 메타데이터에 누락된 정보가 있어 기본생성자가 존재하지 않으면 역직렬화할 객체를 생성하지 못하는 것으로 추측됩니다.

2024-04-20 04:49 UTC, Arachneee commented
질문1 : Long과 long을 구분하였는데 적절하게 구분되었을까요?
레벨1때는 long을 사용하여 null을 불가능하게 하였습니다. 그런데 엔티티의 id가 생기면서 null이 가능한 Long이 필요해졌습니다.
그래서 엔티티는 Long을 사용하였고 엔티티의 정보를 전달하는 dto도 Long을 사용했습니다.
반면에 PathVariable이나 dao에 요청하는 id는 long을 사용하여 null인 경우를 제거했습니다.
null이 들어올 가능성을 제거하기 위해 구분하였는데 통일성이 없어보이기도 합니다.
호돌은 어떻게 생각하시나요?

질문2: Spring을 어떻게 학습하는 것이 좋을까요?
현재는 Spring의 각종 어노테이션, 객체들을 어떻게 사용하고 어떤 일을 하는지 이해하며 공부하고 있습니다.
하지만 내부로직이 어떻게 돌아가는지 정확히 알지 못한 상태로 사용법만 공부하는 것 같습니다.
내부로직을 들어가면 너무 방대한 로직이 나와 어디까지 알아야 하는지 모르겠습니다.

저의 공부방법은 문제가 발생했을 때 해결하기 위해 공부하는 것입니다.
그런데 문제가 발생하지 않아 공부를 안해도 되는지 or 미리 공부해놔야 나중에 빨리 문제를 해결할 수 있을지 고민됩니다.


예외처리 로직도 추가해보겠습니다.

2024-04-20 06:38 UTC, kimhodol requested changes
안녕하세요 백호 :)

진도가 정말 빠르군요 ㅋㅋ

예외 처리까지 기능 완료하면 리뷰 요청 한 번 더 부탁드릴게요~

---

> 질문1 : Long과 long을 구분하였는데 적절하게 구분되었을까요?

[링크](https://stackoverflow.com/questions/67542278/should-i-use-primitive-or-object-for-entity-and-models-in-java/67542411#67542411)를 확인해보면 좋을 것 같아요.

개인적으로는 primitive long의 기본값이 0이라 nullable한 값을 사용할 때는 혼동이 있을 수 있어 잘 사용하지 않는 편인데요, loop 등을 사용할 때 오토박싱/언박싱 이슈 때문에 primitive long을 사용해서 성능 이슈가 생기지 않는 이상 항상 object Long을 사용하는 것으로 통일하는 편입니다. 제 말이 정답은 아닐 수 있어요.

> 질문2: Spring을 어떻게 학습하는 것이 좋을까요?

스프링을 깊게 공부하면 어디까지 할 수 있을까요? 저도 스프링을 아직 잘 모른다고 생각하는데 (ㅋㅋ) 개인적으로 우테코에서 + 현업 1년차까지 기준으로는 `문제가 발생했을 때 해결하기 위해 공부하는 것입니다.`를 기본 마인드로 공부를 했는데, 그래도 그 외적으로 도움이 되었던 공부 방법은 다음과 같았어요.

1. 스프링 부트를 사용하는 기본 서적 1권 이상 (저같은 경우는 크루들하고 [스프링5 프로그래밍 입문, 최범균]를 1회독,  하는 스터디를 진행)
2. [토비의 스프링 3.1 vol.1] 3회독 스터디 (매우 추천합니다! 특히 우테코에서 학습하는 것과 같이 궁합이 좋은 것 같아요)

이 정도로 진행하고, 취업 후에 스프링 프레임워크 공식 문서를 최대한 처음부터 끝까지 읽되, 최대한 XML 관련 코드는 안 보는 쪽으로 공부를 했었습니다. 다른 크루들은 인프런에서 백기선님이나 김영한님 강좌를 보는 사람들도 많았던 것 같네요.

도움이 되면 좋겠네요!

2024-04-21 10:16 UTC, Arachneee commented
안녕하세요~ 호돌!
백호입니다!

find, delete 예외를 추가했습니다.

그런데 예약을 찾지 못하는 예외의 상태코드를 뭘로 하는 것이 좋을까요?
저는 리소스를 찾지 못했다는 의미의 404 코드가 좋아보입니다. 
그런데 다른 사람의 주장은 404는 해당 URL을 처리할 핸들러가 없다는 의미로 Controller가 존재하지 않았을 때만 사용해야한다고 합니다.
호돌은 404, 200, 204 중 어떤 상태코드를 반환하는 것을 선호하시나요?

2024-04-22 00:27 UTC, kimhodol requested changes
안녕하세요 백호~

미션 마무리해도 될 것 같은데, 좀 더 고치시고 싶은 부분이 있을까봐 열어둘게요.

머지 필요하시면 리뷰 재요청 주세요!

2024-04-22 00:27 UTC, kimhodol commented on src/main/java/roomescape/controller/NotFoundExceptionHandler.java
> +}
IllegalArugmentException이 아닌 다른 예외들도 핸들링 할 수 있으면 좋겠네요! 예상치 못한 오류가 나면 "알 수 없는 오류가 발생했습니다" 등과 함께 500을 내려주는게 예시가 될 것 같아요.

2024-04-22 00:27 UTC, kimhodol commented on src/test/java/serialize/ReservationTimeSerializeTest.java
> +    void nonBasic() {
요거 환경 문제인지는 모르겠는데 저는 이 테스트도 여전히 실패로 뜨네요 ㅠㅠ gradle로 돌려도 intellij로 돌려도

2024-04-22 00:27 UTC, kimhodol commented on src/main/java/roomescape/service/ReservationService.java
> +@Transactional(readOnly = true)
의견) findAll에만 따로 이 어노테이션을 붙여주는 것이 더 명시적일 것 같아요.

2024-04-22 06:00 UTC, Arachneee commented on src/main/java/roomescape/service/ReservationService.java
> +@Transactional(readOnly = true)
해당 클래스 전체가 readOnly = true로 인식할 위험이 있겠군요. 수정했습니다!

2024-04-23 05:08 UTC, Arachneee commented on src/test/java/serialize/ReservationTimeSerializeTest.java
> +    void nonBasic() {
java compile 옵션에 -parameters를 추가하니까 Intellij로 빌드해도 기본생성자가 없어도 역직렬화를 할 수 있는 것으로 확인했습니다.
 
<img width="1001" alt="스크린샷 2024-04-23 오후 2 03 28" src="https://github.com/woowacourse/spring-roomescape-admin/assets/66822642/677552ab-fdb0-46f6-8f48-01904abb8bb8">

2024-04-23 06:47 UTC, Arachneee commented
안녕하세요 호돌~ 백호입니다!

예약 시간 삭제 기능을 변경했습니다. 
예약시간 삭제로 전체 예약을 삭제하는 것은 위험하다고 판단하여 예외로 처리하게 했습니다.

추가로 학습해 볼 만한 키워드가 있을까요?

2024-04-23 10:23 UTC, kimhodol commented on src/main/java/roomescape/service/ReservationService.java
> +@Transactional(readOnly = true)
요거는 클래스에 어노테이션 말고 각각 메소드에 붙여주시는 식으로 수정하면 더 좋을 것 같아요! 실수를 방지할 수 있습니다 ㅎㅎ

2024-04-23 10:24 UTC, kimhodol approved these changes
안녕하세요 백호 :)

이번 단계는 여기서 마무리해도 될 것 같아요.

머지할게요, 고생하셨습니다~

2024-04-23 10:24 UTC, merged

2024-04-23 12:35 UTC, Arachneee commented on src/main/java/roomescape/service/ReservationService.java
> +@Transactional(readOnly = true)
클래스 단위에 붙인것은 실수를 방지하기 위함이었습니다. readOnly 를 default로 하여 불필요한 락을 거는 실수를 막기 위함이었습니다. 메소드 단위로 붙이면 트랙젝션을 걸지 않는 실수를 할 수 있지 않을까요?