[4~9단계 - 방탈출 예약 관리] 커찬(이충안) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #91
Opened 2024-04-21 02:26 UTC by leegwichan

안녕하세요 피케이! 커찬입니다.

이전 단계가 빠르게 머지되고나서, 다음 단계들를 열심히 하다 보니 벌써 9단계까지 완료했네요.
이번에도 9단계까지의 요구사항에 걸맞는 복잡도를 유지하기 위해서 노력했습니다!
아래에는 코드를 작성하며 신경쓴 점을 위주로 정리했습니다! 리뷰 부탁드립니다!

## 이전 Spring 경험
- 6개월 동안 Java/Spring을 배우는 부트캠프를 수료한 적이 있습니다. (2022.02 ~ 2022.08)
  - 부트캠프 기간 중에 Spring을 이용하여 서비스를 배포해 본 경험이 있습니다.

## 신경 쓴 점

### '확장성을 고려하면서도, 복잡하지 않는 코드'

 이전 코드(1~3단계)는 최대한 간결한 코드를 가져가기 위해 노력했습니다. 그 기조를 이번 단계에서도 적용하려다 보니, 많은 고민이 있었던 것 같습니다. "간단한 구조가 정말 옳은가?", "간단한 구조가 현재 상황에서 불편할 일이 있을까?"에 대해 많이 생각해 본 시간이었습니다.
 일단 제가 생각한 결론은 "더 명확해진다면, 더 복잡해져도 괜찮다." 입니다. 그리고 복잡도가 증가할 때는 변경 포인트와 객체의 역할을 생각하면서 분리하는 것을 목표로 했습니다.

#### DTO 도입

 8단계 요구 사항 중 '예약 객체'와 '예약 시간 객체'를 분리하면서, 예약 생성 API의 입력 형식과 도메인 형식이 달라졌습니다. 그래서 `ReservationRequest` 객체를 DTO로 도입하여 사용했습니다. 그러고 나니, 예약 생성 API에서는 DTO를 사용하고, 예약 시간 생성 API에서는 도메인 객체를 사용하게 되었습니다. 그래서 코드 구조의 통일성이 떨어지는 것을 느꼈습니다.
 그래서 `ReservationTime`의 DTO가 필요 없을지라도, DTO를 도입함으로써 코드 구조의 명확성이 올라갈 것이라 생각했습니다. 그래서 `ReservationTimeRequest`를 도입했습니다. 추가로 Controller에서는 DTO로 요청받고 DTO로 응답하는 것이 더 통일성 있어 보여 `ReservationResponse`, `ReservationTimeResponse`까지 도입하여 사용했습니다. 

#### Service 계층의 도입

 지금 주어진 요구사항에서 굳이 Service를 도입할 필요는 없다고 생각합니다. Service의 역할들을 Controller와 Repository가 적절히 나누어서 담당해도, 지금의 코드에서는 각 객체들이 무겁지 않다고 생각했습니다. 하지만 9단계 요구사항 중 "각 레이어별 역할과 책임에 따라 클래스 분리"가 있어 Service 계층을 도입했습니다.

 Service 계층에서는 'DTO 객체, Domain 객체를 서로 바꾸는 역할', '삭제 시, 해당 예약이 있는지 확인하는 역할'을 주었습니다. 계층별로 역할을 분리하다 보니, 확실히 각 계층들이 더 명확해진 것을 느낄 수 있었습니다.

### 도메인 객체에서 `LocalDate`, `LocalTime` 도입
 저번에는 받은 값을 그대로 넘겨주기만 하면 되므로 시간 관리 객체를 도입하지 않았습니다. 이번에는 클라이언트의 요청에 대한 최소한의 유효성 검사는 필요하다고 생각해서 `LocalDate`, `LocalTime`을 도입했습니다. 그래서 String을 받아 `LocalDate`로 바꾸는 과정을 도메인에 두었습니다.

추후 DB에 저장하는 형식, Request 형식, Response 형식이 서로 달라진다면,  String을 `LocalDate`로 `LocalDate`를 String으로 바꾸는 역할을 도메인 객체 외부 (DTO, Repository)로 옮길 것 같습니다.

2024-04-22 23:21 UTC, pkeugine requested changes
안녕하세요 커찬!
리뷰하기까지 조금 시간이 걸려서 죄송해요.
막상 코드를 보니 리뷰를 남길 부분이 없어서 좀 당황했어요 😅 
리뷰 남길 부분이 없다는건 정말 깔끔하고 요구사항에 딱 맞게 구현했다는 의미죠.
정말 잘 만들어주셨어요 👍 

몇가지 생각해볼거리와 자잘한 변경사항 남겨봤어요.
한 번 확인해주시고, 질문이 있다면 언제든 DM 보내주시면 됩니다.
날씨도 좋은데 즐거운 한 주 보내보죠!!!!

2024-04-22 23:21 UTC, pkeugine commented on src/main/java/roomescape/domain/ReservationRepository.java
> +    private final JdbcTemplate jdbcTemplate;
JdbcTemplate 잘 사용해주셨네요. 👍 
여기서 조금 더 학습해보자면 `SimpleJdbcInsert` 와 `NamedParameterJdbcTemplate` 같은 것들도 있어요.
한 번 학습해보신 뒤, 커찬의 애플리케이션에 도입을 할 수 있을지 없을지 생각해봐도 좋을 것 같네요!

2024-04-22 23:21 UTC, pkeugine commented on src/main/java/roomescape/domain/ReservationService.java
> +    }
>  지금 주어진 요구사항에는 Service를 도입할 필요는 없다고 생각합니다

맞아요. 그런데 지금 미션이 제공하는 요구사항이 조금 이상해요.
아무래도 Spring 과 DB 연결 관련 학습에 초점이 맞춰져있다보니, 실제 애플리케이션이 받을만한 요구사항이 없어요.

예를 들어 겹치는 시간에 중복되는 예약이 들어온다면 예외를 던지는 기능이 빠져있죠.
<img width="1318" alt="Screenshot 2024-04-23 at 8 04 51 AM" src="https://github.com/woowacourse/spring-roomescape-admin/assets/48251668/82a01712-79de-42d6-9048-00bbe17c909b">

요구사항에 없으니 꼭 처리해줄 필요는 없지만 (재미삼아 해보셔도 괜찮구요)
실제 애플리케이션이었다면 지금의 상황에서도 저런 요구사항 때문에 Service 가 필요했을 것 같아요.

2024-04-22 23:21 UTC, pkeugine commented on src/main/java/roomescape/domain/ReservationTimeRepository.java
> +        jdbcTemplate.update(connection -> createPreparedStatementForUpdate(connection, reservationTime), keyHolder);
JdbcTemplate 에는 여러 update 메서드가 있는데요, 이 방식을 선택하신 이유가 궁금하네요!

2024-04-22 23:21 UTC, pkeugine commented on src/main/resources/static/js/reservation.js
> +        if (response.status !== 204) throw new Error('Delete failed');
👍 지난번에 리뷰로 남긴 부분 잘 반영해주셨습니다.

2024-04-22 23:21 UTC, pkeugine commented on src/test/java/roomescape/acceptance/ReservationAcceptanceTest.java
> +                "브라운", "2023-08-05", 1L);
```suggestion
        jdbcTemplate.update(
            "INSERT INTO reservation (name, date, time_id) VALUES (?, ?, ?)", 
            "브라운", "2023-08-05", 1L);
```
줄바꿈을 윗줄에도 해줘서 가독성을 높여볼 수 있을 것 같네요!

2024-04-22 23:21 UTC, pkeugine commented on src/test/java/roomescape/acceptance/ReservationAcceptanceTest.java
> +class ReservationAcceptanceTest {
조금은 어려운 주제일 수도 있어요.
AcceptanceTest 와 IntegratedTest 의 차이는 무엇일까요?
왜 우리는 이 테스트의 이름을 AcceptanceTest 라고 하는거죠?
우리는 브라운이 좋고, 그는 뛰어나신 분이지만
`Acceptance` 와 `Integrated` 의 차이를 한 번 조사해보고 `AcceptanceTest` 라는 이름을 사용하면 좋을 것 같아요.

(브라운 사랑해요)

2024-04-22 23:21 UTC, pkeugine commented on src/test/java/roomescape/acceptance/ReservationAcceptanceTest.java
> +    }
제가 알기론 현재 커찬의 애플리케이션에서는 delete 이 실패하는 경우도 존재하는데, 그것도 테스트해볼까요?

2024-04-24 04:26 UTC, leegwichan reviewed
안녕하세요 피케이! 커찬입니다.

주신 리뷰 반영해보고, 제 의견도 추가해보았습니다! 리뷰 부탁드립니다!

2024-04-24 04:26 UTC, leegwichan commented on src/main/java/roomescape/controller/dto/ReservationResponse.java
> +        String date,
저는 "JSON에서 String 값으로 받으니까, DTO도 String으로 관리하면 더 직관적이지 않을까?"라는 생각이 들었던 것 같습니다. 그리고 DB에 저장하는 형태, JSON으로 반환하는 형태도 동일하기 때문에 앞과 같은 구조를 가져갔습니다.

그런데 피케이의 `하나의 필드는 전체 애플리케이션에 걸쳐서 하나의 타입으로만 관리되면 좋겠다`는 정말 좋은 말이라 생각됩니다. 제 방식이 이것을 뛰어넘을 만한 장점은 없다고 느껴졌습니다. 그래서 피케이의 의견을 반영해서 수정해보았습니다!

2024-04-24 23:39 UTC, pkeugine commented on src/main/java/roomescape/domain/ReservationService.java
> +                .orElseThrow(() -> new IllegalStateException("해당 예약을 찾을 수 없습니다."));
우문(?)현답이네요 👍 
클라이언트에게 물어보는게 정말 중요하죠.
반대로 그 쪽에서 이렇게 말할 수도 있답니다 : 
`저희는 성공했을 때 200 만 내려주면 상관없어요.`

굳이 호출한 쪽에 '리소스 존재 유무'를 알려주는 것을 원치 않아서 숨기는 경우도 있어요.
그래서 한 번 남겨봤는데, 커찬이 남겨주신 이유도 좋고 저도 그렇게 할 것 같아요! 💯

2024-04-24 23:45 UTC, pkeugine commented on src/main/java/roomescape/domain/ReservationRepository.java
> +    public Optional<Reservation> findById(Long id) {
좋네요! 예외 처리 로직을 작성하기에도 더 편해지죠.
특히 find 는 조회 api 외에도 다른 곳에서 사용될 가능성도 높으니까요 :)

2024-04-24 23:47 UTC, pkeugine commented on src/main/java/roomescape/domain/ReservationRepository.java
> +    private final JdbcTemplate jdbcTemplate;
직접 사용해보고 판단하는 모습이 정말 멋있습니다.
`SimpleJdbcInsert` 도 잘 적용해주셨네요 👍

2024-04-24 23:51 UTC, pkeugine commented on src/test/java/roomescape/acceptance/ReservationAcceptanceTest.java
> +class ReservationAcceptanceTest {
👍 👍 👍 
왜 우리는 이걸 AcceptanceTest 라고 부르고 있는가...
제가 우테코 할 당시 이 의문을 항상 가지고 있었거든요.

잘 정리해주셨네요!!

2024-04-25 00:06 UTC, pkeugine commented on src/test/java/roomescape/acceptance/ReservationAcceptanceTest.java
> +    }
테스트를 만드는 김에 `@ExceptionHandler` 를 사용해서 controller 쪽 분기를 없애셨군요!

`@ControllerAdvice` 를 사용하지 않더라도 `@ExceptionHandler` 를 사용할 수 있어요.
그냥 그 핸들러를 사용하고 싶은 컨트롤러에 넣으면 그 api 에 한정되어 적용된답니다. :)
```java
@RestController
@RequestMapping("/reservations")
public class ReservationController {

    // ...

    @ExceptionHandler
    public ResponseEntity<ErrorResponse> exceptionHandler(IllegalStateException exception) {
        ErrorResponse response = new ErrorResponse(exception.getMessage());
        return ResponseEntity.badRequest().body(response);
    }
}
```

물론 controller 가 두 개이고, 두 개 다 공통된 예외처리 방식을 사용하고 있어서 어드바이스로 통일해도 괜찮긴해요.
`ErrorResponse` 까지 잘 만들어주셨네요.

여담으로 실제 서비스에서는 `@ControllerAdvice` 로 예외처리를 한다면 커스텀 예외처리 전략이 동반되어야한다고도 생각합니다.
테스트를 만들다보니 예외처리라는 주제까지 오게 되네요 ㅋㅋㅋ

2024-04-25 00:21 UTC, pkeugine requested changes
안녕하세요 커찬!
확실히 코드의 간결함에 신경을 많이 쓰시는 분이라 그런지
코드 읽기도 편하고 리뷰하기에도 좋네요 💯 💯 💯 

이번 단계는 여기서 머지해도 좋을 것 같네요.
하지만 아직 단계가 다 끝난 건 아니죠!
그리고 커찬도 남은 시간동안 궁금한게 더 생길 수도 있구요.

한 번 10단계까지 가볼까요 우리? 🚀

2024-04-25 00:21 UTC, pkeugine commented on src/test/java/roomescape/integratedtest/ReservationIntegratedTest.java
> +    }
테스트를 진행하기 위한 초기 데이터를 넣어주는 방식에는 외부 sql 파일을 실행하는 방법도 있죠.
커찬이 `truncate.sql` 을 만드신것처럼요.
truncate 는 sql 파일로, 그리고 초기 데이터 insert 는 테스트 메서드로 진행해주신 이유가 궁금해요.

2024-04-25 00:21 UTC, pkeugine commented on src/test/java/roomescape/integratedtest/ReservationIntegratedTest.java
> +@Sql(scripts = "/truncate.sql", executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
재미있는 주제 또 하나 가져와봤어요.
truncate 를 before test method 시점에 해주신 이유가 궁금합니다!
after test method 시점에 해줄 수도 있으니까요 🤔 
(바꾸자는 말은 아닙니다)

2024-04-26 00:48 UTC, leegwichan reviewed
안녕하세요 피케이! 커찬입니다.

10단계 들어가기 앞서 간단한 코멘트부터 남깁니다! 10단계 마치고 나서 리뷰 요청 드리겠습니다! (토요일 저녁까지는 마쳐보도록 할께요!)

2024-04-26 00:48 UTC, leegwichan commented on src/test/java/roomescape/integratedtest/ReservationIntegratedTest.java
> +@Sql(scripts = "/truncate.sql", executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
'테스트 실행하기 전, 특정 상태를 만들어 주는 것'에 초점을 맞추었습니다. 혹시나 테스트를 시작하기 전에 원치 않는 데이터가 있을지 모르니까요.

물론 테스트 이후에 초기화해주어도 문제 없다고 생각합니다. 저는 DB를 사용하는 테스트라면 각각의 테스트마다 특정 상태를 만드는 것에 집중해서 before test method를 사용했습니다.

2024-04-26 00:48 UTC, leegwichan commented on src/test/java/roomescape/acceptance/ReservationAcceptanceTest.java
> +    }
`ControllerAdvice`처럼 하나의 파일에서 관리해주려면, 확실히 커스텀 예외 처리를 해야겠군요...

지금은 그 정도로 많은 포인트에서 예외를 발생하지 않으니까 `ControllerAdvice`를 지우고 각 컨트롤러에 `@ExceptionHandler`를 넣어보도록 하겠습니다!

2024-04-28 09:10 UTC, pkeugine commented on src/test/java/roomescape/integratedtest/ReservationIntegratedTest.java
> +@Sql(scripts = "/truncate.sql", executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
좋네요 👍 
개발자들마다 before test method 에 할지, 아니면 after test method 에 할지에 대한 의견이 다 다른데요,
저도 커찬과 마찬가지로 테스트가 직접 truncate 를 한 뒤에 테스트를 진행해야 한다고 생각합니다.
외부 요소가 해주는 것에 기대지 않고 스스로 원하는 환경을 만드는 것이죠. :)

2024-04-28 09:54 UTC, pkeugine requested changes
안녕하세요 커찬!
이제 함께할 시간이 얼마 안 남았네요.
정말 잘 만들어주셔서 간단한 리뷰만 몇 개 남겨봤어요.
해당 코멘트 한 번 확인해주시고, 개인적으로 더 궁금한게 있다면 무엇이든 남겨주시면 확인해볼게요 :)

2024-04-28 09:54 UTC, pkeugine commented on README.md
> +    ```
커찬이 코멘트로 남겨주신 console 사용법 및 출력 예시를 readme 에 추가해주면 좋을 것 같습니다 :)

2024-04-28 09:54 UTC, pkeugine commented on src/main/java/roomescape/console/repository/MemoryReservationRepository.java
> +                .orElseThrow(() -> new IllegalStateException("해당 예약 시간이 존재하지 않습니다."));
아직 예외처리는 이번 미션의 범위는 아니지만, 이왕 10단계까지 와본김에 리뷰 남겨봐요.
repository 는 저장에만 신경쓰도록 하고, 예약 시간 존재 유무 검증은 service 에서 하도록 하는건 어떨까요?

2024-04-28 09:54 UTC, pkeugine commented on src/main/java/roomescape/console/view/ConsoleInputView.java
> +            1, DomainCommand.RESERVATION, 2, DomainCommand.RESERVATION_TIME, 3, DomainCommand.END_PROGRAM);
```suggestion
    private static final Map<Integer, DomainCommand> INT_TO_DOMAIN_COMMAND = Map.of(
        1, DomainCommand.RESERVATION,
        2, DomainCommand.RESERVATION_TIME,
        3, DomainCommand.END_PROGRAM);
```
intelliJ 가 어느정도 표시를 해주기는 하지만, 그래도 줄바꿈을 통해 map 의 key-value 묶음을 구분해봐도 좋을 것 같아요.
GitHub 에서 코드리뷰를 하는 사람에게도 이게 더 보기 편할테구요!

2024-04-28 09:54 UTC, pkeugine commented on src/main/java/roomescape/console/view/ConsoleInputView.java
> +    private static final Map<Integer, FunctionCommand> INT_TO_FUNCTION_COMMAND = Map.of(
```java
public enum FunctionCommand {
    FIND_ALL(1),
    CREATE(2),
    DELETE(3),
    ;

    private final int value;

    FunctionCommand(int value) {
        this.value = value;
    }

    // ...
```
이왕 enum 을 만든김에, enum 에 value 필드를 추가해서 관리해볼 수도 있지않을까요?
이렇게 하면 Map 을 꼭 만들어주지 않아도 될 것 같아요.

2024-04-28 09:54 UTC, pkeugine commented on src/main/java/roomescape/console/view/ConsoleInputView.java
> +        System.out.println("예약 시간 정보를 입력해주세요. (형식 : 시간");
```suggestion
        System.out.println("예약 시간 정보를 입력해주세요. (형식 : 시간)");
```
매의 눈 👀

2024-04-28 09:54 UTC, pkeugine commented on src/main/java/roomescape/console/view/ConsoleInputView.java
> +            throw new IllegalArgumentException("id 형식(양수)을 맞추어 입력해야 합니다.", exception);
음수를 입력했을 때 해당 예외가 터지지 않네요!

2024-04-28 11:35 UTC, leegwichan reviewed
안녕하세요 피케이! 커찬입니다.

심심해서 캠퍼스에 있는 김에, 주신 피드백을 빠르게 반영해보았습니다!
추가로 언급하실 점 있다면, 코멘트 부탁드립니다!

2024-04-28 11:35 UTC, leegwichan commented on README.md
> +    ```
넵! 피케이 의견 반영하여 출력 예시를 추가해 보았습니다!

2024-04-28 11:35 UTC, leegwichan commented on src/main/java/roomescape/console/view/ConsoleInputView.java
> +            throw new IllegalArgumentException("id 형식(양수)을 맞추어 입력해야 합니다.", exception);
앗... 그렇네요.. 음수일 때도 예외가 터지도록 반영해 보았습니다!

2024-04-28 11:35 UTC, leegwichan commented on src/main/java/roomescape/console/view/ConsoleInputView.java
> +    private static final Map<Integer, FunctionCommand> INT_TO_FUNCTION_COMMAND = Map.of(
처음에는 숫자와 커멘드 사이의 관계를 `ConsoleInputView`에서 관리해주려고 했습니다. 왜냐하면, 출력 문구를 사용할 때에 숫자와 커멘드 사이의 관계에 따라 바뀔 수 있으니까요. 그런데 Map을 사용한다 하더라고 변경 포인트가 두 군데라는 점은 변함이 없다는 것을 알았습니다.

그래서 이번에는 피케이의 의견에 따라 `FunctionCommand`에 숫자와 커멘드 사이의 관계를 관리하도록 했습니다. 비록 변경 포인트를 한 쪽으로 몰아넣을 수는 없었지만, 훨씬 깔끔한 코드를 사용할 수 있었습니다.

2024-04-28 11:35 UTC, leegwichan commented on src/main/java/roomescape/console/repository/MemoryReservationRepository.java
> +                .orElseThrow(() -> new IllegalStateException("해당 예약 시간이 존재하지 않습니다."));
넵! 이번에 반영해 보고, 다음 미션에서 자세히 학습해보도록 하겠습니다!

2024-04-28 11:52 UTC, pkeugine requested changes
안녕하세요 커찬!
저도 빠르게 반영하신 점 확인해보았습니다.
최종본_찐찐찐막.comment 느낌이네요!
한 번 확인 부탁드려요!

2024-04-28 11:52 UTC, pkeugine commented on src/main/java/roomescape/console/view/ConsoleInputView.java
> +    }
`tryToId` 라는 이름이 조금은 어색한 것 같아요.
approve 를 누르려는 순간 메서드 이름을 보고 `'id 를 하려고 한다' 는게 무슨 뜻이지?` 라는 생각을 했네요 😂 
`validatePositiveNumber` 또는 `convertToNumber` 등... 의 이름으로 지어주는건 어떨까요?

2024-04-29 03:32 UTC, leegwichan commented on src/main/java/roomescape/console/view/ConsoleInputView.java
> +    }
보통 try 문 안에 있는 행동(메서드)들을 try~ 라는 접두사를 사용했었는데요, 만능은 아닌 것 같네요;;

2024-04-29 11:13 UTC, pkeugine approved these changes
안녕하세요 커찬!
10단계까지 진행하느라 고생 많으셨어요.
이번 미션에서 간결함을 신경 많이 쓰셨는데, 확실히 코드가 정말 보기 편했어요.
남은 미션도 아마 이번처럼 잘 해내실 것 같네요.
파이팅입니다!! 💪 💪 💪

2024-04-29 11:13 UTC, merged