[4-6단계 - 방탈출 예약 관리] 제제(장진우) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #93
Opened 2024-04-21 07:09 UTC by JINU-CHANG

안녕하세요 러너덕! 제제입니다 🙂

DM 드렸던대로 4-6단계 먼저 제출합니다!

## @RestController 필요성 정리
https://github.com/woowacourse/spring-roomescape-admin/pull/66#pullrequestreview-2006244079

말씀해주신 것들을 토대로 웹 서비스의 발전 과정과 함께 필요성을 정리해보았습니다.

### 1세대 웹 서비스
웹 서버는 웹 브라우저인 클라이언트에게 정적인 HTML 페이지를 전송했습니다. 이 시기에는 정보 제공이 주 목적이었고, 사용자 상호작용이 크게 요구되지 않았습니다.

### 2세대 웹 서비스
웹 서비스가 발전하면서 동적인 요소가 필요해졌고, JavaScript가 등장했습니다. 이 단계에서 서버는 프론트엔드(HTML, JavaScript)와 백엔드(데이터베이스 및 비즈니스 로직)를 모두 처리했습니다. Controller 어노테이션이 등장(Spring 2.5 release)하게 된 시기가 이 시기가 아닐까 추측해보는데, 이 어노테이션을 통해 서버에서 모든 데이터를 처리하고 HTML 뷰를 반환할 수 있습니다.

### 3세대 웹 서비스
SPA(Single Page Application) 및 MPA(Multi-Page Application)와 같은 개념이 등장했습니다. 점차 SPA에서 사용하는 CSR 방식이 응답 속도를 향상시키기 위해 중요해졌습니다. 이로 인해 백엔드 서버에서는 HTML 대신 JSON 또는 XML과 같은 데이터 형식을 전송하는 일이 증가했습니다. 그러나 기존의 Controller 어노테이션은 주로 HTML 페이지를 반환하기 위해 사용되었기 때문에 JSON/XML 데이터를 전송하기 위해서는 @ResponseBody(Spring 3.0) 또는 ResponseEntity(Spring 3.0.2)와 함께 사용해야 했습니다.

### @RestController의 등장
이러한 과정에서 @Controller와 @ResponseBody를 함께 사용하는 것이 번거롭다는 인식이 있었습니다. 또한 목적이 다른 Controller 어노테이션을 사용하는 것이 올바르지 않다는 생각을 하게 되었습니다. 따라서 Spring 4.0에서는 이 두 기능을 결합한 @RestController가 도입되었습니다.

2024-04-22 13:56 UTC, Deocksoo requested changes
안녕하세요 제제,
RestController에 대해서 깊이 학습해보셨네요 👍 잘 정리해주셨어요. 
미션 관련해서 코멘트 몇 군데 남겨두었으니, 확인 한 번 부탁드려요.

ps. 코멘트와 더불어..
1. 지금 index 페이지에서 Reservation 버튼을 누르면 제대로 페이지 랜딩이 안되는것같아요.
의도한 동작일까요~?
2. 지난 리뷰때 제가 지나친 부분이 있네요.
Controller에서 @RequestMapping 사용과 관련된 내용인데, [이 코멘트](https://github.com/woowacourse/spring-roomescape-admin/pull/33#discussion_r1568312450) 한번 참고해보시면 좋겠어요.

2024-04-22 13:56 UTC, Deocksoo commented on src/main/java/roomescape/controller/ReservationController.java
> +        Long savedId = reservationDao.save(reservationCreateRequest);
dao에 controller에서 받은 request를 바로 넘겨주고 있군요.
의도하신 의존일까요?

2024-04-22 13:56 UTC, Deocksoo commented on src/main/java/roomescape/dto/request/ReservationCreateRequest.java
>  public record ReservationCreateRequest(String name, LocalDate date, LocalTime time) {
dto 패키지에 있는 Request와 Response를 이제 한번 고민해볼 시점이 왔네요.
이제 dto 패키지에 controller도, dao도 의존하는 형태가 되었어요.
dto 패키지의 위치를 보았을 때, 일종의 common 모듈처럼 layer 와 관계 없이 아무데서나 접근 가능한 패키지가 될 가능성이 생겼네요.
([멀티모듈 설계 이야기](https://techblog.woowahan.com/2637/) 의 common 모듈의 저주를 한 번 참고해보시면 좋겠어요.)
패키지 위치를 한번 다시 고려해보는 것은 어떤가요~?

2024-04-22 13:56 UTC, Deocksoo commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:database
설정을 properties 파일로 잘 분리해서 관리하고 계시네요 👍 
가독성을 고려하여 요새는 yaml 파일 형식으로 많이 관리하는데, 한번 도입해보는 것은 어떤가요?

2024-04-22 15:14 UTC, Deocksoo commented on src/test/java/roomescape/ReservationDaoTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)
@DirtiesContext를 사용하셨군요.
어떤 문제가 생길 수 있을까요?

2024-04-23 07:09 UTC, JINU-CHANG commented on src/main/java/roomescape/controller/ReservationController.java
> +        Long savedId = reservationDao.save(reservationCreateRequest);
제가 생각했을 때 dao로 dto를 넘겨줬을 때의 장점은 다음과 같았습니다.

- 도메인 객체에 대한 의존을 끊음으로써 도메인 객체를 보호할 수 있다. 
- 필요한 데이터만 dao로 넘겨줄 수 있다.

그런데 사실상 findAll 메서드에서 응답값으로 도메인 객체를 넘겨주고 있기 때문에 `도메인에 대한 의존을 끊음으로써 도메인 객체를 안전하게 할 수 있다.`는 모순된 말이었습니다. 그렇다면 `요청/응답시에 모두 dto로 넘겨줘야하나?`라고 고민했는데요, 아니라는 결론을 내렸습니다. 필요한 데이터가 달라질 때마다(RequestDto) 여러 find 메서드를 만드는 것은 효율적이지 않고 너무 많은 dto 객체를 생성해야 합니다.

도메인 객체를 사용하면 dto의 변경이 dao까지 미치지 않는다는 장점도 있습니다. 현재는 name, date, time으로 예약을 생성합니다. 이때 name, date만으로 예약을 생성할 수 있다고 변경된다고 가정해보겠습니다.

```java
// ReservationDao
public Long save(ReservationCreateRequest reservationCreateRequest) {
        String insertSQL = "insert into reservation (name, date, time) values (?, ?, ?)";
        KeyHolder keyHolder = new GeneratedKeyHolder();

        jdbcTemplate.update(connection -> {
            PreparedStatement preparedStatement = connection.prepareStatement(insertSQL, new String[]{"id"});
            preparedStatement.setString(1, reservationCreateRequest.name());
            preparedStatement.setDate(2, Date.valueOf(reservationCreateRequest.date()));
            preparedStatement.setTime(3, Time.valueOf(reservationCreateRequest.time()));
            return preparedStatement;
        }, keyHolder);

        return keyHolder.getKey().longValue();
    }
```
현재는 insertSQL, update 메서드 내부값이 전부 바뀌어야하는데요, 도메인 객체를 사용하면 dao코드상의 변경이 일어나지 않습니다.

2024-04-23 13:07 UTC, JINU-CHANG commented on src/main/java/roomescape/controller/ReservationController.java
> +        Long savedId = reservationDao.save(reservationCreateRequest);
dto를 의도해서 넘겨준 것이 맞습니다 :)  다음의 장점이 있을 거라고 생각했는데요,

- 도메인 객체를 dao로 넘겨주지 않아도 된다. 즉 도메인 객체를 보호할 수 있다.
- 필요한 데이터만 넘겨줄 수 있다. 그리고 컨트롤러로부터 넘겨받은 dto를 굳이 변경할 필요가 없다.

그런데 이런 장점들에 점차 의문이 생겼습니다. 현재 findAll이라는 조회 메서드는 반환값으로 도메인 객체를 넘겨주고 있습니다. 이후 서비스 계층이 생기면 다른 도메인 객체들과 상호작용해서 비즈니스 로직을 수행할 수 있기 때문에 넘겨주었는데요, 이로써 dao에서도 도메인 객체에 접근할 수 있게 되었네요.. ㅎㅎ 그렇다면 마찬가지로 다른 dao 메서드들도 통일성있게 도메인 객체를 요청/응답해야한다고 생각했습니다.

또한 필요한 데이터만 넘겨줄 수 있다고 했는데, 만약 Reservation(도메인 객체)을 저장하기 위해 필요한 데이터가 (name, date, time) 에서 (name, date)로 바뀐다면 dao 내부의 sql문과 매핑 로직이 변환되어야 할 것입니다. 하지만 controller에서 Reservation으로 변환해서 넘겨주면 앞의 것들이 더이상 바뀔 필요가 없을 것 같아요.

이렇게 생각했음에도 레이어간의 적합한 데이터를 옮겨주기 위해 dto를 다 따로 두는게 맞지않나 ..하는 생각을 하기도 했었는데요 현재 상황에서는 크지 않은 프로젝트에서 너무 많은 dto를 생성한다고 생각해서 만들지 않았습니다.

그리고 service 계층을 계층을 두지 않고 dao에서 바로 처리하는 이유는 service 계층이 필요할만큼 복잡한 비즈니스 로직이 없기 때문입니다. 뒤에 레이어드 아키텍처와 관련된 요구사항이 있으니 이때 적용해볼 수 있을 것 같아요! 😀

2024-04-23 13:07 UTC, JINU-CHANG commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:database
적용해보았습니다 👍

2024-04-24 05:48 UTC, JINU-CHANG commented on src/test/java/roomescape/ReservationDaoTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)
> @DirtiesContext indicates the associated test or class modifies the ApplicationContext. It tells the testing framework to close and recreate the context for later tests.

즉, `BEFORE_EACH_TEST_METHOD`를 사용하면 테스트 메서드를 실행하기 전에 **컨텍스트를 초기화**합니다. 이 과정에서 테이블이 초기화되면서 테스트간 격리가 가능해집니다. 하지만 모든 컨텍스트를 새로 띄워야하니 테스트 시간이 많이 걸릴 것입니다. 테스트가 무겁고 오래걸리면 자주 실행하지 않게 되니 문제일 수 있을 것 같아요.

LMS에 나와있어서 해당 어노테이션을 사용했는데요, 이런 문제점을 해결하고자 롤백 테스트가 가능한 `@Transactional` 사용도 고려해보았습니다. 하지만 사용을 지양하는 글도 많이보았고, 지금 단계에서 해당 부분까지 깊게 고민해봐야하는건지 고민이 되어서 LMS에 나온 방식을 따르기로 했었습니다.

2024-04-24 06:15 UTC, JINU-CHANG commented on src/main/java/roomescape/dto/request/ReservationCreateRequest.java
>  public record ReservationCreateRequest(String name, LocalDate date, LocalTime time) {
제공해주신 글을 여러번 읽어보았지만 이해하기 쉽지 않았습니다 😂
패키지의 위치를 어떻게 지정해야하는지 고민해보았는데요, 이전에는 패키지의 위치를 단순히 비슷한 클래스들을 묶는 용도로 사용하였습니다. 그 이상의 중요한 무언가가 있다고 생각은 했지만 관련해서 설명해주는 글을 찾기는 어려웠어요 ㅠㅠ
그래도 현재 패키지의 문제점이 있다면 dto가 controller 내부에서만 사용되고 있음에도 controller/domain/dao와 같은 선상에 있는 것은 문제라고 생각했습니다. 따라서 dto가 실제로 사용되는 위치인 controller 패키지 내부로 옮겨주었습니다 !

2024-04-24 06:31 UTC, JINU-CHANG commented
러너덕~ 좋은 고민거리들을 남겨주셔서 감사합니다 ㅎㅎ
여러 고민을 하느라 RC가 조금 늦어졌어요. 근데 그만큼 만족스러운 답변을 하지 못한 것 같기도 합니다 🥹 스프링으로 넘어오니 확실히 개념하나하나가 쉽지 않더라구요..!! 혼자 끙끙대기보다는 최대한 고민해본 것들을 적어서 보내는게 낫다고 생각했습니다. 부족한 부분이 있다면 말씀해주세요 감사합니다 🙇‍♀️

2024-04-24 06:34 UTC, JINU-CHANG commented on src/main/resources/templates/admin/index.html
> +        <a class="nav-link" href="/admin/reservation">Reservation</a>
> 지금 index 페이지에서 Reservation 버튼을 누르면 제대로 페이지 랜딩이 안되는것같아요.
의도한 동작일까요~?

확인못한 부분이네요..ㅎㅎ 고쳤습니다 !

2024-04-24 06:34 UTC, JINU-CHANG commented on src/main/java/roomescape/controller/ReservationPageController.java
> +    @GetMapping("/admin")
> 지난 리뷰때 제가 지나친 부분이 있네요.
Controller에서 @RequestMapping 사용과 관련된 내용인데, https://github.com/woowacourse/spring-roomescape-admin/pull/33#discussion_r1568312450 한번 참고해보시면 좋겠어요.

url 전체검색이 힘들다는 것은 생각해보지 못한 부분이었어요! 반영했습니다 🙂

2024-04-24 11:22 UTC, Deocksoo commented on src/main/java/roomescape/dto/request/ReservationCreateRequest.java
>  public record ReservationCreateRequest(String name, LocalDate date, LocalTime time) {
이 부분은 약간 리뷰가 과했을수도 있겠네요 :) 
패키지나 모듈의 위치가 어디에 있고, 객체를 어느 곳에 배치하느냐는 생각보다 무척 중요한 문제에요.
'이 객체를 다른곳에서 가져다 써도 되겠다, 안 되겠다'를 판단할 수 있는 기준이 될 수 있거든요.
모호한 위치에 있는 객체들은 자칫하면 여기저기서 가져다 쓰게 되고, 그러다보면 어느 순간부터는 그 복잡함을 감당하기 어려워지는 순간이 오기도 하죠.

이 부분에는 시간을 너무 오래 쓰지 않으셔도 괜찮고, 적당히 읽고 넘어가셔도 될것같아요.

2024-04-24 11:24 UTC, Deocksoo approved these changes
안녕하세요 제제, 
필요한 부분들을 충분히 깊게 고민하고 계시고, 적당한 속도로 보내고 계시는 것 같아요 👍 
다음 미션 계속 진행해주세요~

2024-04-24 11:29 UTC, merged