[4 - 9단계 방탈출 예약 관리] 우주(김성현) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #94
Opened 2024-04-21 08:23 UTC by tsulocalize

지난번에 남겨주신 코멘트 + 미션 추가 구현했습니다

이번에 고민했던 부분은 'dto <-> entity를 어떤 layer에서 변환하면 좋을까'였습니다.

저는 Service 계층의 재사용성 + dto 종류가 많아졌을 때 service 메서드 관리 등을 생각해봤을 때 Controller에서 변환하는 게 더 나은 것 같은 느낌인데 제이미는 어떻게 생각하시나요?

이번에도 잘 부탁드립니다!

2024-04-21 20:07 UTC, jamie9504 requested changes
안녕하세요, 우주 😄 리뷰어 제이미입니다!

간단한 코멘트들을 조금 남겨두었습니다.

이번 한 주도 화이팅입니다 💪

2024-04-21 20:07 UTC, jamie9504 commented on src/main/java/roomescape/dao/ReservationDao.java
> +    }
매번 생성해줘야할까요?

2024-04-21 20:07 UTC, jamie9504 commented on src/main/java/roomescape/dto/ReservationResponseDto.java
> +    private final ReservationTime time;
Reservation은 Dto로 내려주는데 ReservationTime은 Dto로 내려주지 않는 기준은 무엇인가요?

2024-04-21 20:07 UTC, jamie9504 commented on src/main/java/roomescape/service/ReservationService.java
> +@Service
Service, Dao를 분리했을 때 어떠한 장점이 있었나요?

2024-04-21 20:07 UTC, jamie9504 commented on src/main/resources/static/js/reservation-legacy.js
>    return input;
요구사항엔 없지만, index.html의 nav-link를 각각 만들어준 page Link로 바꿔준다면 쉽게 접근할 수 있겠죠!

2024-04-22 06:03 UTC, tsulocalize commented on src/main/java/roomescape/controller/AdminPageController.java
>  import org.springframework.web.bind.annotation.GetMapping;
문서 관리를 깜빡했네요;;
업데이트 했습니다!

2024-04-22 06:07 UTC, tsulocalize commented on src/main/java/roomescape/controller/AdminPageController.java
> +public class AdminPageController {
`/admin`이 중복되고 있었네요
수정했습니다!

2024-04-22 06:14 UTC, tsulocalize commented on src/main/java/roomescape/dto/ReservationResponseDto.java
> +    private final ReservationTime time;
반환 타입을 일관적으로 하는 게 더 좋아보이네요
Dto를 주도록 변경했습니다!

2024-04-22 06:17 UTC, tsulocalize commented on src/main/java/roomescape/service/ReservationService.java
> +@Service
현재 미션에서 분리했을 때 장점은 찾기 쉽지 않아보입니다.
다만 일반적으로 생각했을 때, service와 dao를 분리하면 비즈니스 로직과 DB 접근 책임을 분리할 수 있다는 점이 장점입니다.

2024-04-22 06:21 UTC, tsulocalize commented on src/main/resources/static/js/reservation-legacy.js
>    return input;
저도 처음 봤을 때 불편했는데 뭔가 쓰임새가 있겠지 하고 넘어갔는데요 ㅠ
Link 바꿔봤습니다!

2024-04-22 06:27 UTC, tsulocalize commented on src/main/java/roomescape/dao/ReservationDao.java
> +    }
이제와서 보니 매번 생성하고 있었네요...
클래스 변수로 바꿔줬습니다!

2024-04-22 07:55 UTC, tsulocalize commented on src/main/java/roomescape/dao/ReservationDao.java
> +public class ReservationDao {
`@Repository` 어노테이션은 `@Component`임을 알려주고, JdbcTemplate를 사용할 때 발생할 수 있는 Exception을 Spring에 미리 정의된 exception으로 다시 돌려주기 위해 사용했습니다.

Dao는 일반적으로 DB table과 1:1 매칭되는 특성을 고려해봤을 때, ReservationDao는 reservation_times TABLE을 가져와 사용하기 때문에 ~Repository라고 붙이는 게 좋을 것 같은데요.
그렇게 되면 한 클래스는 ~Repository, 다른 한 클래스는 ~Dao라고 명명되어 혼동을 주게 될 것 같아보이네요.
우선 둘 다 ~Repository로 통일되게 바꿔줬습니다!

2024-04-22 08:07 UTC, tsulocalize commented on src/main/java/roomescape/controller/ReservationApiController.java
> +        Reservation reservation = reservationService.createReservation(requestedReservation);
Controller에서 변경할 때 장점은 기존에 말씀드린대로일 것 같고, 그럼 Service에서 변경할 때 장점을 살펴봐야겠죠.
우선, Controller에 별도의 변환 과정이 없어지기 때문에 본래의 역할(요청/응답)에 더 충실할 수 있을 것 같습니다. 또한 비즈니스 로직과 관련된 Entity 객체가 Controller로 넘어갈 일이 없어지게 되겠죠.

결국 정답은 없고, 프로젝트/팀 마다 trade-off를 비교하며 결정해야 될 사항인 것 같네요!

2024-04-22 13:56 UTC, jamie9504 requested changes
안녕하세요, 우주 😄 리뷰어 제이미입니다.

간단한 코멘트만 남겼어요.

다음 리뷰 요청 때는 이슈 없다면, Approve & Merge 예정입니다.

2024-04-25 04:48 UTC, tsulocalize commented on src/main/java/roomescape/controller/ReservationApiController.java
> +    public ResponseEntity<ReservationResponseDto> postReservation(@RequestBody ReservationRequestDto reservationRequestDto) {
제가 이해한 게 맞는 지 모르겠네요:
JSON 값에 이상이 있을 경우 500 에러를 응답하고 있습니다.
하지만 잘못된 요청에 대해 400(Bad Request)가 올바른 응답이라는 생각이 들어 유효성 검증을 추가해봤습니다!

2024-04-25 05:09 UTC, tsulocalize commented on src/main/java/roomescape/controller/ReservationApiController.java
> +        Reservation reservation = reservationService.createReservation(requestedReservation);
양쪽의 단점은 서로의 장점을 얻을 수 없는 것이라고 생각합니다.
Controller : MVC 패턴의 controller로, model과 view 사이에서 유저의 input을 받아 적절한 작업을 수행합니다. 
Service: 비즈니스 로직을 Presentation Layer로부터 분리하고, 하나의 작업단위를 정의하고 캡슐화하여 트랜잭션 관리를 수행합니다.

2024-04-25 05:11 UTC, tsulocalize commented
추가로 10단계(콘솔 UI 구현)까지 해보았는데 실제로 콘솔에서 다룰 일이 있을까요?

2024-04-25 09:42 UTC, jamie9504 requested changes
안녕하세요, 우주 😄 리뷰어 제이미입니다.

추가 코멘트 간략하게 남겨두었습니다.

다음 리뷰 요청시엔 이슈가 없다면 Approve & Merge 예정입니다.

2024-04-25 09:42 UTC, jamie9504 commented on src/main/java/roomescape/console/RoomEscapeConsoleRunner.java
> +    public RoomEscapeConsoleRunner(ConsoleCommandMatcher consoleCommandMatcher, ConsoleInputScanner consoleInputScanner) {
예외가 발생했을 때 사용자에게 그대로 노출해도 될까요?

<img width="1075" alt="image" src="https://github.com/woowacourse/spring-roomescape-admin/assets/59511689/fb97e041-070a-4998-bdc1-f2ea8a3b725c">

2024-04-25 09:42 UTC, jamie9504 commented on src/main/java/roomescape/console/command/AddReservationCommand.java
> +    private final ReservationApiController reservationApiController;
해당 Controller는 Web에 의존성이 있던 것 같은데요 😃 

만약 Web쪽 dependency를 지운다고 하더라도, 콘솔은 동작할 수 있을까요?

2024-04-25 09:42 UTC, jamie9504 commented on src/main/java/roomescape/console/command/AddReservationCommand.java
> +        System.out.println("예약자 이름을 입력해주세요.");
해당 추가한 console은 뭔가 기존 방탈출을 이용해 구현하려한 것 같은데
1레벨 미션들을 생각했을 때, View를 나눈다던가는 할 필요가 없는걸까요?

2024-04-25 09:42 UTC, jamie9504 commented on src/main/java/roomescape/controller/ReservationApiController.java
> +        Reservation reservation = reservationService.createReservation(requestedReservation);
우주가 적어둔 계층이 담당하는 일을 보면

Service에서는 비즈니스 로직을 분리한다고 적으셨는데, Controller에서 변환을 하면 도메인에 접근할 수 있을 것 같긴 한데요!
그렇다면 비즈니스 로직을 분리했다고 봐도 되는 걸까요?

2024-04-28 07:15 UTC, tsulocalize commented on src/main/java/roomescape/console/RoomEscapeConsoleRunner.java
> +    public RoomEscapeConsoleRunner(ConsoleCommandMatcher consoleCommandMatcher, ConsoleInputScanner consoleInputScanner) {
예외 처리하도록 수정했습니다!

2024-04-28 07:45 UTC, tsulocalize commented on src/main/java/roomescape/console/command/AddReservationCommand.java
> +        System.out.println("예약자 이름을 입력해주세요.");
View를 나누어주었습니다!

2024-04-28 07:48 UTC, tsulocalize commented on src/main/java/roomescape/controller/ReservationApiController.java
> +        Reservation reservation = reservationService.createReservation(requestedReservation);
관점에 따라 Controller에서 변환할 때 접근할 수 있기 때문에 비즈니스 로직이 분리되지 않았다고 볼 수 있을 것 같습니다.
다만, 저는 Service 계층의 재사용성으로 얻는 장점이 훨씬 크다고 느껴 이 정도는 타협해도 괜찮다고 생각합니다!

2024-04-28 08:00 UTC, tsulocalize commented on src/main/java/roomescape/console/command/AddReservationCommand.java
> +    private final ReservationApiController reservationApiController;
Web dependency를 지운다는 뜻은 명확히 이해하기 힘들지만, `org.springframework.web`에 대한 의존성이 없더라도  `@Component` 어노테이션을 붙이면 콘솔은 동작할 수 있습니다.
저는 10단계 요구사항을 브라우저 외 추가 UI(콘솔)를 구현하라는 것으로 생각해 콘솔 명령이 Controller에 의존하도록 구현해봤습니다!

2024-04-29 04:18 UTC, jamie9504 requested changes
안녕하세요, 우주 😄 리뷰어 제이미입니다.

간단한 코멘트만 남겨두었으니 확인해주세요!

다음 리뷰 요청시에는 특이사항 없을시 Approve & Merge 예정입니다.

2024-04-29 04:18 UTC, jamie9504 commented on src/main/java/roomescape/console/ConsoleCommandMatcher.java
> +package roomescape.console;
package가 console로 나뉠 것이라면, 나머진 web으로 묶여있어야 할 것 같은데요.
console이 추가되면서 패키지를 나누는 기준이 여러 개가 섞인 느낌이네요.
패키지 기준에 일관성이 있으면 좋을 것 같아요!

전반적으로 console쪽 패키지를 정비해보는 것은 어떨까요?

2024-05-01 04:13 UTC, tsulocalize commented on src/main/java/roomescape/console/command/AddReservationCommand.java
> +    private final ReservationApiController reservationApiController;
스프링과 별개의 콘솔 어플리케이션으로 수정해보았습니다!

2024-05-01 04:19 UTC, tsulocalize commented on src/main/java/roomescape/console/ConsoleCommandMatcher.java
> +package roomescape.console;
패키지도 정비하다보니 consolerunner 라는, 일반적인 스프링 어플리케이션의 패키지 구조(controller, service, repository 등)를 따르지 않는 별도 패키지가 생겼습니다. 다른 사람이 코드를 처음 봤을 때 직관적으로 이해하기 힘들 수 있지만(그렇게 이해하기 힘든가? 싶지만요...), 추가적인 기능(이번 미션에서는 콘솔 UI 기능)을 위해서라면 일반적인 구조가 아닌 패키지도 있어도 된다고 생각했습니다!

2024-05-01 04:19 UTC, tsulocalize commented on src/main/java/roomescape/console/ConsoleCommandMatcher.java
> +package roomescape.console;
패키지도 정비하다보니 consolerunner 라는, 일반적인 스프링 어플리케이션의 패키지 구조(controller, service, repository 등)를 따르지 않는 별도 패키지가 생겼습니다. 다른 사람이 코드를 처음 봤을 때 직관적으로 이해하기 힘들 수 있지만(그렇게 이해하기 힘든가? 싶지만요...), 추가적인 기능(이번 미션에서는 콘솔 UI 기능)을 위해서라면 일반적인 구조가 아닌 패키지도 있어도 된다고 생각했습니다!

2024-05-01 12:41 UTC, jamie9504 requested changes
안녕하세요, 우주 😄 리뷰어 제이미입니다.

코멘트를 조금 남겨두었는데요. 이 부분 확인 및 수정 부탁드려요.

이후 리뷰 요청은 별도 코멘트 없이 Approve & Merge 예정입니다.
고생 많으셨어요 😉

2024-05-01 12:41 UTC, jamie9504 commented on src/main/java/roomescape/RoomEscapeConsoleApplication.java
> +
😄

2024-05-01 12:41 UTC, jamie9504 commented on src/main/java/roomescape/console/ConsoleCommandMatcher.java
> +package roomescape.console;
좋습니다. 👍 

직관적이고 이해하기 쉬운 패키지 구조에 대해서는 앞으로 미션과 팀 프로젝트를 하면서 우주만의 기준을 추가적으로 정립해봐도 좋을 것 같아요.
패키지 구조, 클래스/메서드/변수명은 저도 늘 어렵습니다 😃

2024-05-01 12:41 UTC, jamie9504 commented on src/main/java/roomescape/RoomEscapeConsoleApplication.java
> +    public static void main(String[] args) {
<img width="866" alt="image" src="https://github.com/woowacourse/spring-roomescape-admin/assets/59511689/9c094193-1b4d-495c-b8b7-acfd673c35d2">

예외가 생겼을 때 이와 같이 StackTrace를 노출하고 종료해버리면 안되겠죠?

2024-05-01 12:41 UTC, jamie9504 commented on src/main/java/roomescape/consolerunner/command/DeleteReservationCommand.java
> +    private static final String COMMAND_INPUT = "3";
얘랑 Time이랑 반대로 된 것 같네요 ?

2024-05-02 11:16 UTC, tsulocalize commented on src/main/java/roomescape/RoomEscapeConsoleApplication.java
> +    public static void main(String[] args) {
예외 처리하도록 수정했습니다!

2024-05-02 11:17 UTC, tsulocalize commented on src/main/java/roomescape/consolerunner/command/DeleteReservationCommand.java
> +    private static final String COMMAND_INPUT = "3";
앗... 값을 잘못 넣어줬네요.
수정해줬습니다!

2024-05-02 11:19 UTC, tsulocalize commented on src/main/java/roomescape/RoomEscapeConsoleApplication.java
> +
공백 제거했습니다;;

2024-05-03 07:34 UTC, jamie9504 approved these changes
안녕하세요, 우주 😄 리뷰어 제이미입니다.

2레벨 첫 미션 고생 많으셨어요!

이만 Approve & Merge 합니다!

2024-05-03 07:34 UTC, merged