[4 - 9단계 방탈출 예약 관리] 이상(이건상) 미션 제출합니다.
woowacourse/spring-roomescape-admin pull request #99
Opened 2024-04-21 15:11 UTC by kunsanglee

안녕하세요 스티치! 😃 주말 잘 보내셨나요?
저는 주말이 끝나기 전에 미션 기본 구현은 어찌 저찌 끝내서 검토 받아보고자 pr 보냅니다!

다른 크루들은 미션에 기본 제공한 테스트코드를 슬라이스 테스트로 바꾸는 것 같더라고요.
저는 아직까지 스프링 프레임워크에 익숙해지기와 기본 원리 공부하기 하는데도 여유가 별로 없는 것 같아서
테스트는 아직 건드리지 못했습니다 🥲

제가 작성한 코드의 레이어드 아키텍쳐는 이런 구성으로 되어있습니다.
```
└── roomescape
    ├── RoomescapeApplication.java
    ├── application
    │   ├── ReservationService.java
    │   └── ReservationTimeService.java
    ├── domain
    │   ├── H2ReservationRepository.java
    │   ├── InMemoryReservationRepository.java
    │   ├── Reservation.java
    │   ├── ReservationRepository.java
    │   ├── ReservationTime.java
    │   ├── ReservationTimeRepository.java
    │   └── strategy
    │       ├── CurrentDateStrategy.java
    │       └── ReservationDateStrategy.java
    ├── dto
    │   ├── ReservationRequest.java
    │   ├── ReservationResponse.java
    │   ├── ReservationTimeRequest.java
    │   └── ReservationTimeResponse.java
    └── presentation
        ├── AdminController.java
        ├── ReservationController.java
        └── ReservationTimeController.java
```
`presentation`패키지에 컨트롤러,
`application`패키지에 서비스,
`domain`패키지에 도메인과 리포지토리가 함께 있습니다.

처음에는 `controller`, `service`, `repository` 패키지로 이름짓고 레이어드 아키텍쳐를 구성했었습니다.
`Reservation` 객체 생성시 `LocalDate` 타입의 데이터를 검증하기 위해서 검증 조건을 추가하게 됐는데요,
`ReservationService` 객체에서 `Reservation` 객체를 생성할 때에는 날짜 데이터의 검증이 통과되면 생성하게 해야했고,
`ReservationRepository`에서 이미 저장된 데이터를 조회하여 객체로 생성시에는 이미 지난 날짜이기에 날짜 검증 조건을 수행하면 안되는 상황이 발생했습니다.

그래서 고민끝에 서비스 계층과 도메인 계층을 분리하여 서비스에서는 `Reservation` 객체 생성을 정적 팩토리 메서드로만 가능하도록 하고,
리포지토리는 `Reservation` 객체를 조회시 자유롭게 검증을 하지 않고 생성할 수 있게 하기 위해 도메인과 리포지토리를 같은 패키지에 두었습니다. 

`프레젠테이션` 계층에서는 사용자의 요청을 받아서 비즈니스 로직 계층으로 요청에 대한 처리를 위임하고, 
`비즈니스 로직` 계층에서 비즈니스 로직(현재 단계에서는 DTO -> 도메인 변환로직만 있지만요😅)을 수행하고, 
`데이터 엑세스` 계층에서 요청에 대한 로직을 수행하여 만들어진 도메인을 저장하거나,
저장된 도메인을 수정 또는 조회하여 다시 비즈니스 로직 계층으로 넘겨줍니다. 
그렇기 때문에 도메인 객체와 리포지토리를 같이 묶어두는 것이 적절하다고 생각했습니다.

그리고 컨트롤러에서 요청 객체를 생성하여 서비스로 넘기고, 서비스에서 DTO를 도메인으로 변환하고,
서비스에서 도메인을 다시 DTO로 변환하여 컨트롤러로 반환하도록 했습니다.

제가 이번 미션을 진행하면서 레이어드 아키텍쳐를 적절히 구성했는지 확신이 들지 않네요! 😅
이밖에도 테스트에 대한 공부거리를 주시면 또 열심히 공부해서 다시 pr 요청 하겠습니다!!!!! 😇

2024-04-23 02:14 UTC, lxxjn0 requested changes
이상, 미션 구현하시느라 수고 많으셨습니다! 제가 리뷰를 남기고 마무리를 해둔 줄 알았는데 Request Changes를 누르지 않아서 리뷰가 늦어졌네요 ㅠㅠ 죄송합니다.

작성하신 코드 잘 봤고 전체적으로 잘 작성해주신 것 같아요. 일단 간단한 부분들에 대해서 코멘트 남겼습니다. 그 중에서 트랜잭션을 어떤 상황과 어떤 단위에서 쓰는 것이 적절할까와 레이어 분리에 대한 코멘트를 위주로 한번 고민해보고 수정해보면 좋을 것 같아요 :)

2024-04-23 02:14 UTC, lxxjn0 commented on src/main/java/roomescape/domain/Reservation.java
> +        }
해당 유효성 검증은 개발 요구사항에는 존재하지 않는 것 같은데 이상 개인적으로 추가한 유효성 검증일까요? 해당 검증을 유지하기 위해서 생성된 코드들이 오히려 어색함을 가져오는 것 같아요.

2024-04-23 02:14 UTC, lxxjn0 commented on src/main/java/roomescape/domain/Reservation.java
> +    public static Reservation of(String name, LocalDate date, ReservationTime time, ReservationDateStrategy strategy) {
유효성 검증을 위한 전략을 외부에서 주입해서 도메인 객체를 생성하는 방향이 어색하게 느껴집니다. 그렇다면 해당 도메인은 결국 DateStrategy가 없이는 아예 생성을 할 수 없는 객체가 되어버리는데, 이는 사실상 내부에서 Strategy를 가지고 생성하는 강결합 구조와 큰 차이가 없다고 느껴져요. 이상은 어떻게 생각하나요? 그리고 전략을 주입받아서 유효성을 도메인 내부에서 검증하고 있는 방식이 과연 도메인의 유효성 검증으로 볼 수 있을까요?

2024-04-23 02:14 UTC, lxxjn0 commented on src/main/java/roomescape/domain/H2ReservationRepository.java
> +public class H2ReservationRepository implements ReservationRepository {
해당 클래스를 도메인 레이어에 둔 이유는 단지 생성자를 사용하기 위함일까요? 이 클래스는 DB 라이브러리와 강한 의존을 가지고 있는 클래스로 보입니다. 도메인 레이어에 두기에는 성격이 조금 달라보이는데 이동시킨다면 어떤 레이어에 위치시키면 좋을까요?

2024-04-23 06:30 UTC, kunsanglee commented on src/main/resources/application.yml
`.properties`는 평면적으로 속성을 나열하기 때문에 중복이 발생하기도 하고 가독성이 좋지 않습니다.
반면에 `.yml`는 디렉토리처럼 계층적인 구조로 속성을 작성할 수 있기 때문에 가독성이 좋습니다.
그래서 yml 파일로 변경하여 작성했습니다 😊

2024-04-23 07:26 UTC, kunsanglee commented on src/main/java/roomescape/domain/Reservation.java
> +        }
맞습니다 제가 개인적으로 추가한 유효성 검증이에요 🥲 유효성 검증 자체가 잘못된 것은 아니라고 생각합니다!

처음에는 예약 날짜 속성에 대한 검증 자체가 비즈니스 로직이라고 생각해서 응집도 측면에서  `Reservation` 객체가 가지는게 맞다고 생각했었습니다.

어떻게든 `Reservation` 객체 내부에서 검증하려 했기 때문에 예약 객체를 최초 생성하는 시점과, 이미 저장되어있던 예약 객체를 꺼내는 과정에서 생성하는 시점에서 검증 로직을 수행할지 말지를 결정지으려 했기 때문에 어색한 코드가 됐던 것 같습니다.

그런데 다시 생각해보니 `Reservation` 객체 내부에서 현재 시점을 기준으로 과거인지 판단하는 검증 로직을 가지고있는 것이 잘못됐다고 생각이 들었습니다. 

사실 예약이라는 것 자체는 기본적으로 어느 날짜를 기준으로도 생성 가능하기 때문에 예약 객체 자체에서 검증하기보다, 예약 추가 요청을 하는 시점(요청 객체로 변환되어 생성될 때)인 `ReservationRequest` DTO에서 요청 값을 검증하는 것이 적절하다고 생각이 정리됐습니다. 이렇게 DTO에서 값을 검증하면 도메인 레이어 이후에서는 검증 로직을 거치지 않고 객체를 생성할 수 있게 되고, `Repository` 구현체들이 들어갈 `infrastructure` 레이어에서 저장된 데이터를 조회할 때 문제가 발생하지 않는다고 생각합니다. 

결론적으로 전략 패턴을 사용하여 도메인 내부에서 검증하던 로직을 제거하고 `ReservationRequest` DTO에서 예약 추가 요청시 받은 값을 검증하는 방식으로 코드를 개선하고자 합니다.😇

2024-04-23 07:28 UTC, kunsanglee commented on src/main/java/roomescape/domain/Reservation.java
> +    public static Reservation of(String name, LocalDate date, ReservationTime time, ReservationDateStrategy strategy) {
객체간 책임 파악을 잘 못해서 위와 같은 어색한 코드를 작성한 것 같습니다.
바로 위 코멘트에 답변한 대로 개선하려고 합니다! 🥹

2024-04-23 07:32 UTC, kunsanglee commented on src/main/java/roomescape/domain/H2ReservationRepository.java
> +public class H2ReservationRepository implements ReservationRepository {
`Reservation` 객체를 `Repository` 구현체에서 검증 로직이 포함되지 않은 생성자를 자유롭게 사용하게 하려고 같은 패키지에 놨었습니다. 책임 파악을 잘못하여 어색한 방법으로 해결하려다 발생한 좋지 못한 패키지 구성이었네요 😭 

앞서 검증 문제를 해결하면서 repository 구현체들의 패키지를 `infrastructure` 패키지에 위치시키려고 합니다.

2024-04-23 13:49 UTC, kunsanglee commented on src/main/java/roomescape/application/ReservationService.java
> +@Transactional
`@Transactional` 애너테이션은 클래스 레벨에 선언 할 경우 `public` 메서드에 대한 프록시를 생성하여 작동합니다.
`@Transactional`은 데이터를 CRUD 하는 경우에 데이터 일관성과 무결성을 위해 필수적으로 트랜잭션 관리를 해줘야 합니다.
또 여러 작업을 하나의 트랜잭션으로 묶어서 작업의 원자성(Atomicity)를 보장하고자 할 때 사용합니다.
마지막으로는 읽기만 하는 작업인 경우 `@Transactional(readOnly = true)` 옵션을 사용하여 데이터베이스 락과 관련한 오버헤드를 줄여 트랜잭션을 최적화 할 수 있습니다.

반대로 단순 입력 값을 검증하거나 메모리 내에서 계산하는 등, 데이터베이스와 상호작용하지 않는 메서드에는 `@Transactional`을 사용할 필요가 없습니다.🙂🙂

2024-04-24 07:43 UTC, lxxjn0 commented on src/main/java/roomescape/application/ReservationService.java
> +@Transactional
이상이 정리해준대로 여러 작업을 하나의 트랜잭션으로 묶어서 원자성을 보장하고자 하기 위해서 `@Transactional` 어노테이션을 사용합니다. 그렇다면 해당 서비스의 메서드 중에서 DB를 접근하는 메서드가 하나만 있거나 또는 여러 메서드가 있더라도 원자성을 보장해줄 필요가 없다면 해당 어노테이션이 꼭 필요할까요?

2024-04-24 07:46 UTC, lxxjn0 commented on src/main/java/roomescape/domain/Reservation.java
> +        }
> 예약 추가 요청을 하는 시점에 서비스 레이어에서 검증하는 것이 적절한 것 같아요

맞습니다! 사실 Reservation이란 도메인은 결국 사용자가 작성한 예약이라는 도메인을 관리하기 위한 객체입니다. 이 도메인에서 예약 날짜에 이러한 비즈니스 로직은 필요가 없습니다. 

그러나 예약 추가라는 비즈니스 행위에 대해서는 다를 수 있어요. 외부 사용자가 임의나 강제적으로 예약을 추가하거나 이미 지나간 예약을 추가하려는 올바르지 않은 행위를 시도할 수 있습니다. 이렇게 API를 통해 오는 `예약 생성`이라는 비즈니스에서는 생성 요청 시간이 현재의 시간보다 이전이면 안된다는 비즈니스 로직을 넣을 수 있습니다. 이러한 검증은 도메인 객체가 아닌 요청 객체에서 진행할 수도 있고 또는 서비스 레이어의 객체에서 진행할 수도 있어요.

기존의 코드는 도메인의 요구사항이 아닌 내용을 추가하려다보니 어색함이 발생한 것 같습니다. 제가 위에 말씀드린 방향으로 한번 고민해보고 적용해보면서 기존의 코드와 어떠한 다른 점들이 있는지도 한번 살펴보면 좋을 것 같아요 👍🏼

2024-04-24 07:59 UTC, lxxjn0 requested changes
피드백 반영하시느라 수고하셨습니다! 기존의 코드보다 훨씬 더 명확해지고 깔끔해진 것 같아요! 이전 코멘트에 대해서도 피드백 남겨두었는데 한번 확인해보시고 미션 마무리해도 될 것 같습니다 👍🏼

2024-04-24 07:59 UTC, lxxjn0 commented on src/main/java/roomescape/application/ReservationService.java
> +    private final ReservationTimeRepository reservationTimes;
기존에 필드명에서 바꾸신 이유가 따로 있을까요? 상관없는 부분이긴 한데 보통은 Repository라는 이름을 사용해서 한번 질문드려봅니다 :)

2024-04-24 07:59 UTC, lxxjn0 commented on src/main/java/roomescape/dto/ReservationRequest.java
> +    public Reservation from(ReservationTime reservationTime) {
보통 `from`과 같은 이름은 정적 팩토리 메서드에서 주로 사용합니다. 현재는 Request 객체에서 도메인 객체를 생성하는 메서드이니 단순히 `from`이라는 이름으로는 행위를 추측하기 어려울 것 같아요. `toReservation`과 같이 명확한 이름을 사용해보는 것은 어떨까요?

2024-04-24 07:59 UTC, lxxjn0 commented on src/main/java/roomescape/domain/ReservationTimeRepository.java
> +public interface ReservationTimeRepository {
도메인에 해당하는 명세만 인터페이스로 추출해 남겨두고 구현체는 적절한 레이어로 옮겨두었네요 👍🏼

2024-04-24 11:42 UTC, kunsanglee commented on src/main/java/roomescape/application/ReservationService.java
> +    private final ReservationTimeRepository reservationTimes;
`Repository`와 `DAO`의 차이점에 대해서 읽은 후에 `Repository`는 도메인 객체들을 관리하는 저장소를 추상화 한 개념이라는 것을 알게됐습니다. `Repository`는 영속성 계층과 연관이 있을 수도 있지만, 일급 컬렉션처럼 인메모리 저장소일 수도 있습니다. 결론적으로 객체를 관리하는 저장소의 의미이기 때문에 일급 컬렉션처럼 변수명을 사용해도 어색함이 없다는 것을 배워서 한 번 적용해봤습니다. 😂 

저도 일급 컬렉션과 같은 복수형으로 변수명을 지은 적은 처음이라서 다음부터는 관례처럼 사용하는 `~Repository` 네이밍을 사용하려고 합니다!

2024-04-28 14:25 UTC, kunsanglee commented on src/main/java/roomescape/domain/Reservation.java
> +        }
클라이언트가 예약 추가 요청을 하는 시점에 요청 객체를 바탕으로 `ReservationService` 클래스에서 예약 날짜에 대한 검증 로직을 수행하도록 했습니다.😇 

스티치가 말씀해주신대로 요청 객체에서도 검증할 수 있겠지만, 해당 비즈니스 로직을 어디서 수행하는게 좋을까 고민해보니 다른 개발자가 해당 로직을 찾아야할 때 `ReservationService`에서 찾을 가능성이 더 높다고 생각하기 때문에 검증 로직 수행 위치를 서비스 레이어로 결정했습니다. 

`LocalDate`를 바탕으로 테스트할 때 정식 명칭인지는 모르겠으나, `타임머신 테스트`라는 시점에 대한 검증의 어려움을 해결하기 위해 `ReservationService`에서 `Clock` 객체를 상태로 가지고 외부에서 주입받도록 하여 테스트시 테스트 시점을 결정할 수 있도록 mocking하는 코드를 추가했습니다.

2024-04-29 14:00 UTC, lxxjn0 commented on src/main/java/roomescape/application/ReservationService.java
> +    private final ReservationTimeRepository reservationTimes;
해당 변수명을 사용해서 문제가 될 건 없습니다! 궁금해서 질문드려봤어요 :)

2024-04-29 14:01 UTC, lxxjn0 commented on src/main/java/roomescape/dto/ReservationRequest.java
> +    public Reservation from(ReservationTime reservationTime) {
저는 toReservation과 같이 명확한 이름을 사용합니다. 지금은 Request가 하나 뿐이지만 나중엔 한 도메인에 대해서 여러 요청 객체가 있을 수도 있고, 생각보다 도메인의 이름이 명확히 드러나지 않는 객체에서 도메인 객체를 만들 시점도 있을 수 있습니다. 그래서 저는 명확한 이름을 사용하는 것이 더 좋다고 생각해요 :)

2024-04-29 14:03 UTC, lxxjn0 approved these changes
이상, 미션 진행하시느라 수고하셨습니다 👍🏼 이번 미션은 여기서 마무리해도 될 것 같아요!! 이전 리뷰에 대한 코멘트도 남겨두었으니 한번 확인해주세요.

추가로 모킹의 경우 외부 라이브러리에 대한 의존을 끊거나 테스트 환경을 만들기 위해서 너무 많은 의존성이 필요할 경우에 주로 사용하곤 합니다. 지금의 코드에서는 모킹을 사용하지 않고도 충분히 테스트가 가능한 로직이니 한번 참고해서 다음 미션 진행하실 때 적용해보시면 좋을 것 같습니다 👍🏼

2024-04-29 14:03 UTC, merged